### ISSUE TITLE
Write "Open Source" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#100]
The lesson plan should live at [`open-source/open-source.md`](https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by Karla-Isabel-Sandoval** [comment]
Closes with https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md
