### ISSUE TITLE
Write "Entrepreneurship" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#102]
The lesson plan should live at https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/entrepreneurship.md. You can base it on [this completed slideshow](https://docs.google.com/presentation/d/1fRYImBTR0ZWGSQfDJ7ctz57OdvmU6kFewoMfTt3lL3I/edit?usp=sharing).  If your idea for the slideshow is totally different than this, please copy it and create your own.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by imskr** [comment]
I want to work on this!
