### ISSUE TITLE
Fix week 6 grader guide links

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1028]
The links to the assignments in the week 6 grader's guide are broken, probably because they have been renamed. Please fix them!

https://github.com/Techtonica/curriculum/blob/master/assessment-objectives/6.md

**Comment by harshanarisetty** [comment]
I can work on this

**Comment by yagosansz** [comment]
Hello,
Is this issue still up for grabs? I would like to work on it!

**Comment by alodahl** [comment]
Hi @yagosansz , @harshanarisetty has already taken it.  But please pick up another easy issue in the to-do list [here](https://github.com/Techtonica/curriculum/projects) if you have time!

**Comment by alodahl** [comment]
hi @harshanarisetty, how is this issue going?  If I don't hear from you , maybe @yagosansz can pick it up.
