### ISSUE TITLE
Write "Roles in Tech" lesson plan

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#103]
The lesson plan should live at [`roles-in-tech/roles-in-tech.md`](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/roles-in-tech.md). It should at least discuss sales engineers, technical support, and customer success engineers.

Acceptance Criteria:
- [x] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
Complete with https://github.com/Techtonica/curriculum/commit/5abdda02c0f3e776a85e4de0e0df658cddea16d4
