### ISSUE TITLE
Write "Popular Tools" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#104]
The lesson plan should live at [`popular-tools/popular-tools.md`](https://github.com/Techtonica/curriculum/tree/master/popular-tools/popular-tools.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by alodahl** [comment]
no need to overwhelm them - tools they need for job placement can be addressed during "prep week"
