### ISSUE TITLE
Write "SEO" topic outline.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#105]
The topic outline lives at [SEO/SEO.md](https://github.com/Techtonica/curriculum/blob/master/SEO/SEO.md).

Acceptance Criteria:

- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

**Comment by kristalane** [comment]
Duplicate to issue #85
