### ISSUE TITLE
Add Techtonica to GHC volunteerism list

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1057]
Add Techtonica’s curriculum project to this list, with an excerpt from our website Techtonica.org or this project’s readme. 

https://docs.google.com/document/d/11fmV6GacqmbPhU1X892R3jBGfy7xoMr_1kYbc4j_FZs/mobilebasic

Reply via the comments when complete. You can submit a simple typo fix with this issue tagged to acheive your Hacktoberfest PR if you are participating.

**Comment by cedarfall** [comment]
I would like to take this issue.

In the document, should I put your name?
Also, the city should be San Francisco right?

**Comment by alodahl** [comment]
Yes!  You can use my name.  Thanks @cedarfall !

**Comment by cedarfall** [comment]
https://docs.google.com/document/d/11fmV6GacqmbPhU1X892R3jBGfy7xoMr_1kYbc4j_FZs/edit

Is this okay?

P.S. In the last column, there are two asterisks above your name indicating that you don't mind leading the project.

**Comment by alodahl** [comment]
Yes, perfect 🙌
