### ISSUE TITLE
Fix Data Science Roles contents tables so they don't contain actual content

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1065]
https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/data-science.md

- [ ] ###Objectives and Specific Things To Teach sections should contain the objectives of the outline and the things the outline teaches, **not** what an apprentice will learn if they spend years becoming a Data Science engineer.  Move the present material into the lesson somewhere, and replace ###Objectives and Specific Things To Teach with relevant lists that summarize the outline itself, near the beginning of the outline, similar to a table of contents. See our [template](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md) for more details about the purposes if each section.

- [ ] Check the links in ###Guided Practice and ###Independent Practice.  If the links are not free, or if the link doesn't obviously lead to the said resource without some investigation, please replace with a relevant link that values the apprentices' time by taking them straight to the resource so they can get started.

**Comment by eaquin1** [comment]
I would like to work on this! :)
