### ISSUE TITLE
Add example links and explanations to Roles in Tech:  Technical Writing

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1067]
Add the following links and explanations, reworded if necessary, to appropriate sections in our [Roles In Tech: Technical Writing outline](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/technical-writing.md).

_________________
Here are some technical writing examples.
Process discussions: https://www.prismnet.com/~hcexres/textbook/proc.html
API documentation: https://nordicapis.com/5-examples-of-excellent-api-documentation/
Walkthrough documentation, perhaps the most overall useful for people who are technically capable but unfamiliar. https://medium.com/product-labs/how-to-write-a-useful-scenario-walkthrough-f48bf40b1b69 
...and here's a good high-level overview of the kinds of documentation technical writers typically get involved with:

https://clickhelp.com/clickhelp-technical-writing-blog/types-of-technical-documentation/

In addition to the above, my team edits a lot of external blogposts too. You can see are work here, polishing other people's articles:

https://engineering.indeedblog.com/blog/
https://medium.com/indeed-engineering

....and occasionally getting to write our own. : ) 

https://medium.com/indeed-engineering/the-evolving-language-of-data-science-89830c5aa0c7

**Comment by carmelag** [comment]
Hi! @alodahl I would like to help here. 
So what is needed to solve this issue, is to add in _technical-writing.md_ file those links along with a good explanation, is it correct?

**Comment by carmelag** [comment]
Hi @alodahl , I have just created the PR related to this issue.
I added the links that were directly related to tech writing but I didn't add the last 3 links (indeed ones). They seem to be less specific than the others.
If it's needed I will add them, but it would be helpful if someone could add more details to better understand what kind of description/headline we could put for them. Thanks
