### ISSUE TITLE
Create lesson on "Solving coding challenges"

### ISSUE THREAD

**Issue by lalpert** [Techtonica/curriculum#1080]
Create a lesson on "Solving coding challenges". It should give apprentices a framework for approaching coding challenges that they can use in morning coding challenges and interviews. Could be combined with whiteboarding (https://github.com/Techtonica/curriculum/blob/master/interviewing/whiteboarding.md). 

Could link to or build off resources including:
- https://simpleprogrammer.com/solving-problems-breaking-it-down/
- https://www.codementor.io/npostolovski/9-essential-tips-on-how-to-tackle-a-coding-challenge-argfuyqz9
- https://medium.com/swlh/how-to-solve-any-code-challenge-or-algorithm-c66e0bed9dc9
- https://hackernoon.com/how-to-approach-any-coding-problem-9230f3ad6f9
- https://www.freecodecamp.org/news/how-to-think-like-a-programmer-lessons-in-problem-solving-d1d8bf1de7d2/

(Evaluate these resources to find which ones are most helpful)

**Comment by dpenny** [comment]
Hey- would love to work on this! Should I assume that coding challenges will have an IDE they can test with?

**Comment by alodahl** [comment]
Hi @dpenny , they can practice directly on the site provided above, but during the Apprenticeship Program they will mainly be working in repl.it. Would you still like to pick this up?

**Comment by dpenny** [comment]
yes will do! I have different testing strategies for whiteboard vs having IDE, so was wondering which to include. thanks!

**Comment by alodahl** [comment]
Awesome! Also, let us know if you have anything to add to the whiteboarding outline 😊

**Comment by dpenny** [comment]
hey- should this have sections for both short Qs (ie morning assignments, phone screens), and for longer take homes?

**Comment by alodahl** [comment]
Hi @dpenny, sorry for the delay.  We are giving them practice take-home challenges in the final few weeks of the curriculum [here (#s 8, 9, 10)](https://github.com/Techtonica/curriculum#career-development--final-project).  

If you think 'take-home challenges' will be a single short section, go ahead and include it, and link to this section while mentioning they will learn more about these later.  If it will be good-sized outline on its own, it should probably just be its own outline combined with the article in #8 of the above link.

**Comment by alodahl** [comment]
Hi @dpenny, the new cohort could use this ASAP.  is this close to being ready?

**Comment by dpenny** [comment]
Hey so sorry for the delay. Is end of week ok?

**Comment by alodahl** [comment]
Sure, thank you 😊

**Comment by dpenny** [comment]
PR here @alodahl 
https://github.com/Techtonica/curriculum/pull/1129

**Comment by alodahl** [comment]
Create a function that takes two integers and displays the largest one. 
Example:

largestInt(11, 22) → 22 
largestInt(22, 44) → 44

* Hints: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Relational_operators

**Comment by alodahl** [comment]
Hi Danielle, here is an example code challenge. Thanks for the PR!
