### ISSUE TITLE
 Update Jasmine lesson

### ISSUE THREAD

**Issue by lalpert** [Techtonica/curriculum#1081]
Improvements to be made to Jasmine lesson (https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/jasmine-testing.md):

- Make this lesson only teach Jasmine, not Chai and Mocha as well. Move Chai and Mocha material into a different lesson called "Testing with Chai and Mocha".

- Add more specific practice problems that encourage the learner to explore different Jasmine functions (such as toBe,(), toEqual(), toBeLessThan(), toBeDefined(), toContain(), etc)

**Comment by brookeangel** [comment]
Hi, @lalpert - if no one is working on this issue yet, I'd love to help out with it!

**Comment by lalpert** [comment]
@brookeangel please do!

**Comment by brookeangel** [comment]
Wonderful! Just wanted to check - does this issue also involve updating a slideshow or presentation? The current slideshow link takes me to an "Advanced Command Line" presentation.

**Comment by alodahl** [comment]
Great question!! Yes, plz edit ... It should be this one: https://docs.google.com/presentation/d/1jMkVbUkZS40z7kAoC1mPIt8RwfF8-GRL8oeee25UzYw

**Comment by alodahl** [comment]
Be aware of this one too:https://docs.google.com/presentation/d/1viDJyLHXVs-VioUEatvWHDZeOCCmPxZNPHzH0C393rg

**Comment by brookeangel** [comment]
Thank you! 🎉 

Also, I saw that the process for tackling issues is to add myself as an assignee & move this to in progress, but wanted to give a heads up that I don't have permission to do those things

**Comment by brookeangel** [comment]
This PR is ready for feedback ➡️ https://github.com/Techtonica/curriculum/pull/1109

(Not quite sure who to assign it to. In any case, thanks for taking a look!)

**Comment by alodahl** [comment]
To edit the slides, please request permission from the owner... in this case, it isn't me.

I'll take a look at the PR 😄

**Comment by brookeangel** [comment]
Thanks you! 😄Will go ahead and request permission

**Comment by brookeangel** [comment]
Hey @alodahl - thanks so much for the review! 🎉 

No rush, just an update on my status: requested permission on the slideshow, but I haven't received it yet. Not quite sure who owns.

**Comment by alodahl** [comment]
A new cohort starts Monday, so they may be a bit busy!  I’ll see about making some new slideshows that you can work on, and we’ll include the links once they’re done.

**Comment by MichelleGlauser** [comment]
I added Brooke on Friday. :)

**Comment by brookeangel** [comment]
Thanks! :) I'll work on this in the upcoming week!

**Comment by brookeangel** [comment]
Here's the PR that splits the slideshows & updates the links: https://github.com/Techtonica/curriculum/pull/1131
