### ISSUE TITLE
Create "Intro to Backend Development" lesson

### ISSUE THREAD

**Issue by lalpert** [Techtonica/curriculum#1082]
This lesson will be in the roadmap before the apprentices learn APIs, Express, SQL, and other backend concepts. It should give an overview of what backend development is, giving a good foundation for the apprentices to understand future lessons.

Some possible resources to include:
- https://learntocodewith.me/posts/backend-development/
- https://simpleprogrammer.com/what-is-back-end-development/
- https://www.coursereport.com/blog/front-end-development-vs-back-end-development-where-to-start

**Comment by jmcgeeney** [comment]
I'm going to hammer out a rough draft of this today, assuming it hasn't been worked on yet.

**Comment by jmcgeeney** [comment]
Here's a PR for my first pass. Still working on it, but any feedback would be appreciated!
https://github.com/Techtonica/curriculum/pull/1106
