### ISSUE TITLE
Create lesson on ORMs

### ISSUE THREAD

**Issue by lalpert** [Techtonica/curriculum#1083]
Create a lesson introducing apprentices to ORMs. 
Teach:
- Overall what an ORM is and why it's useful
- Use an ORM that can be used with Postgres/Express
- Have apprentices compare and contrast the same code using an ORM and raw SQL

This lesson will be added to the curriculum after the apprentices learn Postgres and Express.

May have a little overlap with this Mongoose lesson that comes later https://github.com/Techtonica/curriculum/blob/35e6a464a2cca16995c64b53aec204e08b18ca9f/databases/mongoose.md

A challenge exercise could be using JS to create some of their own ORM functions like filter() and select()

Another challenge could be picking a second JS ORM and comparing it to the first one they learned.

**Comment by vegetabill** [comment]
Given the number of other issues open on the curriculum, I'm going to downgrade this from Priority but if someone wants to add more context and advocate for it being more important, please do!

**Comment by vegetabill** [comment]
This feels like an elective and/or wish list request. I'm closing it for now since no one has picked it up.

**Comment by alodahl** [comment]
I wouldn’t close things just cuz no one has picked it up! It’s up to you whether ORMs are an elective.
