### ISSUE TITLE
Create "React 2" lesson

### ISSUE THREAD

**Issue by lalpert** [Techtonica/curriculum#1084]
We want to create a React 2 lesson that will be added after React 1 (https://github.com/Techtonica/curriculum/blob/master/react-js/react.md). 

It should teach how to add more advanced features to React projects, including:
- Making ajax calls from React
- Styling React components
- Anything else the apprentices will need to know to create a real React app

Possible tutorial for apprentices to do: https://scrimba.com/g/glearnreact

**Comment by HenriqueFadoni** [comment]
Hello Lalpert, I would love to help. Could you go more in-depth about the Third Item? Because I don't know what React 1 lesson has. Should I include Hooks? Life cycles? Redux?

**Comment by alodahl** [comment]
https://github.com/Techtonica/curriculum/issues/965

**Comment by lalpert** [comment]
Hi @HenriqueFadoni, glad you're interested in helping! Here's the current React 1 lesson: https://github.com/Techtonica/curriculum/blob/master/react-js/react.md. I don't know exactly what the React 1 lesson covers so it would be great if you could go through that lesson and see what it covers and what's missing.

As Alina linked to, we would like to teach React hooks and functional components. I think that content could either replace the current "React 1" or be added as an additional lesson. I'm not a React expert so I'd like to hear input from current React engineers on how to structure the React lessons and what are the key things to include.

**Comment by vegetabill** [comment]
Closing. Replaced by sub-tasks: 
- #1160 
- #965
- #1161
