### ISSUE TITLE
Add Concurrently somewhere.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1094]
The current participants learned about this and found it extremely helpful: https://www.npmjs.com/package/concurrently Let's figure out where it can be added.

**Comment by vegetabill** [comment]
Not 100% of the use cases they used it for but seems like `tmux` would be better to learn in the long run.

**Comment by vegetabill** [comment]
Expired. If you like this idea and want to work on it, please reopen!
