### ISSUE TITLE
Keyboard Shortcuts - Zoom bug: keyboard breaks in Chrome

### ISSUE THREAD

**Issue by IngridGdesigns** [Techtonica/curriculum#1097]
<img width="755" alt="Screen Shot 2019-12-03 at 2 33 07 PM" src="https://user-images.githubusercontent.com/16828218/70095736-5ddc6480-15da-11ea-81bc-da203e14367e.png">

Zoom at 110%, 90%, 80% in chrome. Did not find the bug in Firefox.

**Comment by vegetabill** [comment]
@IngridGdesigns I think this issue belongs in a different project: https://github.com/Techtonica/keyboard-shortcuts-practice

**Comment by vegetabill** [comment]
I would move it myself but I don't think I have access to do so

**Comment by alodahl** [comment]
I’m not sure there is a way to move an issue to a different repo... anyway I just copied and pasted it. Thanks!
