### ISSUE TITLE
Proofread & format LinkedIn outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1098]
##Task:

Proofread & format the markdown in this [LinkedIn outline](https://github.com/Techtonica/curriculum/blob/master/professionalism/LinkedIn.md). You can start by addressing the comments from [this review](https://github.com/Techtonica/curriculum/pull/1043).

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by vegetabill** [comment]
@alodahl I can take a look at this unless someone else did.

**Comment by alodahl** [comment]
Thanks Bill, it’s yours!

**Comment by jmcgeeney** [comment]
Just submitted a PR for some of these: https://github.com/Techtonica/curriculum/pull/1105
It's my first PR, so please let me know if I got everything wildly wrong :)

**Comment by jmcgeeney** [comment]
Oh shoot, just realized this has another assignee. @vegetabill, maybe take a look at my PR if you haven't started yet?

**Comment by vegetabill** [comment]
@jmcgeeney I have not started & I'm happy to take look at your PR.

Thanks so much for contributing!

**Comment by vegetabill** [comment]
@alodahl I did a quick pass of the PR if you can take it from here as I'll be on holiday.
