### ISSUE TITLE
Find the new urls of these 2 outlines and replace the links

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1099]
## Task: 

Fix these two links in our [ReadMe](Event Search System with Javascript
Event Search System with Javascript - Part 2) by finding their new names and replacing the urls.

- Event Search System with Javascript
- Event Search System with Javascript - Part 2

### Hints:  
- the new names have something to do with "eventonica".
- the old names are below, which you can likely look up in the project history:
[✖] https://github.com/Techtonica/curriculum/blob/master/javascript/event-recommender.md → Status: 404
[✖] https://github.com/Techtonica/curriculum/blob/master/javascript/event-recommender-part2.md → Status: 404

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by thisLinda** [comment]
Alina, these are the new URLs. I can't figure out how to replace the links in the README which is maddening. Would you give me a hint?

https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part1-objects.md

https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part2-testing.md

**Comment by lemon-yellow** [comment]
Hi @thisLinda,

If you go to the https://github.com/Techtonica/curriculum/blob/master/README.md and click the "Raw" button, you can see the raw markdown text. The format of a markdown url is `[display name](url)`. Hope this helps!

**Comment by alodahl** [comment]
Hi @thisLinda , what part of it is confusing?

Also, since @lalpert has been changing the structure of this project, could you please:
- replace event-recommender.md with https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part1-objects.md
- instead of replacing #44 (part-2), remove it, and add this *after* the jasmine outline link? https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part2-testing.md
- go ahead and change the link titles to the titles of the new outlines, or something that you think makes sense.
- replace the "#18 Eventonica Project" link with 
this:https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-intro.md
and call it "Eventonica Project Intro"
![image](https://user-images.githubusercontent.com/29131689/71551781-0ac0bc00-29a4-11ea-9108-f9ae7b2ab94a.png)

**Comment by thisLinda** [comment]
@alodahl I was having a major brain cramp and fortunately that passed.

@lemon-yellow Raw files are new to me. I'll check it out, thank you.

**Comment by thisLinda** [comment]
Alina I just merged the branch...missed this step 11 days ago.

**Comment by vegetabill** [comment]
@thisLinda sorry for the confusion around this issue. I'm a new staff member and I'm just getting the hang of all the in-flight issues. We've actually changed the main README quite a bit and so I'm just going to close this issue for now. If you'd be willing to pick something up from the [project board](https://github.com/Techtonica/curriculum/projects/2) we'd appreciate any work you could contribute. The available items on the left are in priority order.

Cheers

**Comment by thisLinda** [comment]
@vegetabill I am interested in picking up a beginner or easy issue. I've checked in with the repo multiple times recently and see a lot of people helping out and such issues are always assigned--how wonderful for Techtonica! I'll keep trying :)
