### ISSUE TITLE
[Feature Request] Convert google doc lessons to markdown

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1103]
Some parts of the intro curriculum link to Google docs. Is this intentional to keep them private? If not I think we should convert them to markdown and put them into this repo.

Examples I've seen:
* tech tips and tricks
* expectations

I'm happy to volunteer to do that but wanted to check if there is context I am missing for why they are in that format.

**Comment by alodahl** [comment]
@MichelleGlauser, can you remind us why you wanted to avoid md images in our project?

**Comment by vegetabill** [comment]
@alodahl I probably wasn't clear above. The content is currently in a Google doc, but it's mostly/entirely textual. My only concern is about the content itself. Perhaps it's confidential and shouldn't be in the repo. Even then we could move it into a private repo in the org, rather than use Google.

**Comment by vegetabill** [comment]
Example link to [Expectations G Doc](https://github.com/Techtonica/curriculum/blame/99278367a6ab40b4e3849b789923a2bbcd29b2e9/professionalism/professionalism.md#L15)

**Comment by MichelleGlauser** [comment]
For official docs that are more about participation in the program and not curriculum/technical topics (like the program guidelines), I'd like to make sure we keep those in a Google Doc as we have non-technical people who edit those and we often need to share them as PDFs.

**Comment by vegetabill** [comment]
Ahh that makes sense! Closing
