### ISSUE TITLE
Revise `Check for Understanding` questions of for Data Visualization, list other fixes needed

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1110]
1. Revise the Check for Understanding section of our [Data Visualization Outline](https://github.com/Techtonica/curriculum/blob/master/data-visualization/data-visualization.md) based on this comment: https://github.com/Techtonica/curriculum/pull/1107#issuecomment-568230598
For more details on what we're looking for in a Check for Understanding section, see the directions in #700.

1. Implement any small things mentioned in the following comment: https://github.com/Techtonica/curriculum/issues/1086#issuecomment-567664466 
  If there are fixes mentioned that seem a bit larger, leave a comment here on #1110 and we will make some more issues.

**Comment by vegetabill** [comment]
This is elective so bumping out of the TODO project

**Comment by Kundan28** [comment]
Is this issue be worked under `GSSoC20` ? @alodahl @vegetabill

**Comment by pa7ri** [comment]
I'm a gssoc participant and I'm interested in working on this issue, if possible :smiley:

**Comment by Kundan28** [comment]
@pa7ri No you could start working on this issue.

**Comment by Kundan28** [comment]
@pa7ri  You only have 9 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by pa7ri** [comment]
I've completed part 1, but the second one is taking me longer than expected. BTW, I've tried to push my changes into a branch but it says : `ERROR: Permission to Techtonica/curriculum.git denied to pa7ri.` any help with this?

**Comment by alodahl** [comment]
@pa7ri : 

1. enter `git log` in your terminal, and write down the commit(s) hashes from this issue from oldest to newest.  you only have to write down the first 7 digits.  So for example, if you had this:
![image](https://user-images.githubusercontent.com/29131689/76713008-e4750780-66da-11ea-80ca-222870607599.png)

If you only want the last two, you would write in a note to yourself:
- 00eb81b
- d7dfa51

2. Fork the repo  
![image](https://user-images.githubusercontent.com/29131689/76712972-8f38f600-66da-11ea-84b5-6ff1ff3a5af2.png)

3. git clone that forked repo

4. cd into that forked repo.

5 enter `git cherry-pick <oldest hash you wrote down>`,
6 enter `git cherry-pick <next-oldest hash you wrote down>`, etc, until you've done them all.  
7. push up and make a pull request.  the changes you want should be there.  Let us know if this doesnt work.

**Comment by pa7ri** [comment]
It worked! _(I was trying to push directly to this repo instead of fork it)_ Thank you very much @alodahl and @Kundan28
