### ISSUE TITLE
Update titles and urls in 2 links

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1111]
Update titles and urls in 2 links here:
https://github.com/Techtonica/curriculum/blob/master/objectives/6.md

The files have been renamed to be Eventonica Part 1 and Part 2.  Something similar was done for the same links in #1099.
https://github.com/Techtonica/curriculum/blob/master/objectives/6.md

Related to #1099

**Comment by viditkumar** [comment]
Hi @alodahl 
Could you please let me know, what are the updated titles and urls?

I would like to work on this issue.

**Comment by alodahl** [comment]
Thanks @viditkumar !

https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part1-objects.md

https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part2-testing.md
