### ISSUE TITLE
replace bash lesson with zsh

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1113]
Use existing bash outline as a pattern to create a new outline for using zsh instead. It could be really minor, but personally not knowing zsh, I'm not sure of the scope.

**Note these files were recently moved into the `dev-tools` folder**

### Check and Revise the Following Lessons
- https://github.com/Techtonica/curriculum/blob/master/dev-tools/command-line-interface.md
- https://github.com/Techtonica/curriculum/blob/master/dev-tools/dot-profile.md
- https://github.com/Techtonica/curriculum/blob/master/dev-tools/command-line-advanced.md

Consider including https://github.com/robbyrussell/oh-my-zsh as an optional resource.

**Comment by vegetabill** [comment]
We want to use this for next cohort, H2-2020, but I would still keep as a priority because we should not be teaching bash anymore.

**Comment by vegetabill** [comment]
I would also include [oh-my-zsh](https://ohmyz.sh/) as an additional material.

**Comment by Kundan28** [comment]
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by vegetabill** [comment]
@adriculous how has it been going working on this? We'll need this lesson for the next cohort since zsh is now the default. If you have any questions let me know.

Do you have a target date to complete a draft pull request for these changes? Could you create it by April 1st?
