### ISSUE TITLE
Change every "Javascript" to "JavaScript"

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1114]

**Comment by MichelleGlauser** [comment]
Fixed with commit https://github.com/Techtonica/curriculum/commit/00bed5682617285024bd78e2c1467ee466f926b2

**Comment by vegetabill** [comment]
![](https://d3qdvvkm3r2z1i.cloudfront.net/media/catalog/product/cache/1/image/1800x/6b9ffbf72458f4fd2d3cb995d92e8889/g/r/grammarpo_thumb_2.png)
