### ISSUE TITLE
Replace 3 Codecademy Pro links with something free

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1115]
I audited them, and most are fine.  Here is a list of the links that need replacing:
- [ ] https://www.codecademy.com/courses/asynchronous-javascript/lessons/promises/exercises/understanding-promises in curriculum/javascript/javascript-9.md
- [ ] https://www.codecademy.com/learn/learn-the-command-line in curriculum/command-line/command-line-interface.md
- [ ] https://www.codecademy.com/learn/learn-jquery in curriculum/jquery/jquery.md
- [ ] https://www.codecademy.com/learn/learn-sass in sass/sass.md (low priority)

@alodahl

**Comment by alodahl** [comment]
I replaced the one in git-version-control.md.

**Comment by alodahl** [comment]
I'm combing through them, and most are fine.  Here is a list of the links that need replacing:
- [ ] https://www.codecademy.com/courses/asynchronous-javascript/lessons/promises/exercises/understanding-promises in curriculum/javascript/javascript-9.md

**Comment by habeeba-naaz** [comment]
Hello...I want to work on this issue.I am gssoc20 participant.

**Comment by habeeba-naaz** [comment]
Can you please assign to me this issue if possible.?

**Comment by abhinashgiri** [comment]
I want to contribute on this issue. May I with your permission, please?

**Comment by SimranMakhija7** [comment]
I want to contribute to this issue as a part of GSSOC 20. Could the issue be assigned to me, please?

**Comment by soulhunter10737** [comment]
I want to contribute to this issue as a part of GSSOC 20. Can you please assign me this issue?

**Comment by daya2940** [comment]
I want to contribute to this issue as a part of gssoc20.can you please assign this to me

**Comment by prangya244** [comment]
i want to work on this issue.

**Comment by soulhunter10737** [comment]
I would like to take the issue, can you assign me this?

**Comment by vegetabill** [comment]
@SimranMakhija7 

Thanks for volunteering to help Techtonica improve its curriculum! I have assigned you to this issue.

Please follow the [contribution instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) in additional to any instructions from GSSoC.

### Questions?
- If you have any question about this issue and what contributions are being asked for, reply on this issue. 
- **If you have questions about Git, Pull Requests, GitHub, or the contest itself**, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.

**Comment by Kundan28** [comment]
@atrip10  You only have 4 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Kundan28** [comment]
@SimranMakhija7 You only have 5 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Kundan28** [comment]
@SimranMakhija7 I we don't get any response from your side in few days then we would assign someone else to this PR.

**Comment by alodahl** [comment]
@abhinashgiri would you like this one?

**Comment by abhinashgiri** [comment]
yes

**Comment by Kundan28** [comment]
@abhinashgiri Now you could start working on this issue.

**Comment by abhinashgiri** [comment]
where is the jquery folder, I can't find the 3rd link

**Comment by Kundan28** [comment]
> where is the jquery folder, I can't find the 3rd link @Kundan28 @alodahl

It's been moved to `web/jquery.md`
