### ISSUE TITLE
Set up a tool to check our curriculum for dead links

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1117]
This might work: https://github.com/tcort/markdown-link-check

**Comment by MichelleGlauser** [comment]
@gsong Maybe you can take this?

**Comment by gsong** [comment]
Couple other possible tools:

* https://github.com/remarkjs/remark-validate-links
* https://github.com/davidtheclark/remark-lint-no-dead-urls

**Comment by alodahl** [comment]
Is this related to #1059 ?

**Comment by gsong** [comment]
@alodahl Yup, the two issues are related.

**Comment by gsong** [comment]
Closed via #1120

**Comment by alodahl** [comment]
@gsong we’re you able to do the actual scanning and find any dead links?
