### ISSUE TITLE
Replace growth mindset quiz

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1118]
The growth mindset quiz currently linked to is not working: https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md

Find another free quiz that measures growth mindset and fix this link

**Comment by pa7ri** [comment]
I would like to contribute solving this issue if everyone is agree

**Comment by abhinashgiri** [comment]
I want to contribute to this issue. May I, please?

**Comment by Srashtimittal** [comment]
I ama gssoc 2020 participant. I would like to contribute.

**Comment by Aakansha99** [comment]
I would also like to contribute to the issue as a part of GSSoC'20, could you please assign it to me

**Comment by abhinashgiri** [comment]
Please assign me to this issue. I also commented very early, so, please.

**Comment by vegetabill** [comment]
@pa7ri 

I have assigned you this issue. Follow the instructions in [CONTRIBUTING](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md)

**Comment by pa7ri** [comment]
hi @MichelleGlauser & @vegetabill, I've just checked every link inside : [https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md](https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md) they are all working.

In case the issue refers to `Growth Mindset Self-Assessment` I suggest using : [16-personalities](https://www.16personalities.com/free-personality-test) (but the current link is working).

If I misunderstood something, please let me know.

**Comment by alodahl** [comment]
@MichelleGlauser @vegetabill I agree with @pa7ri that all of the links work in the outline.  With one exception, actually: Learning to Learn (video walkthrough of slides) (https://drive.google.com/open?id=1R7cp0huJu5kiIIfDsraFbtmGbINHb2Xe) is blocking anyone without permissions, which seems like a problem that only you two could solve.

I am closing this issue and labelling it `wontfix`.

**Comment by MichelleGlauser** [comment]
Changed the view settings on the "Learning to Learn" video. It might be outdated, though.

**Comment by alodahl** [comment]
it worked! thanks @MichelleGlauser 👍🏼
