### ISSUE TITLE
Standardize on prettier for formatting of our markdown

### ISSUE THREAD

**Issue by gsong** [Techtonica/curriculum#1121]
Rather than bike shedding formatting suggestions, just let a tool do the work. I suggest using [prettier](https://prettier.io).

* [ ] Add prettier to the project
* [ ] Format everything using prettier
* [ ] Add pre-commit hook to ensure changes conform to prettier

**Comment by vegetabill** [comment]
+100 to just going with something premade.

Can someone provide a comparison of prettier to eslint+Airbnb settings? I don't really have a strong opinion but just wanted some context.

**Comment by gsong** [comment]
@vegetabill Well, considering most of this repo are markdown files, eslint won't do anything for you. 😉

**Comment by huonggiangbui** [comment]
Hi, I am GSSoC participant. Can I take this issue?

**Comment by ravireddy07** [comment]
I would like to work on this, please assign this to me @vegetabill  @Kundan28

**Comment by Kundan28** [comment]
@huonggiangbui @ravireddy07 This issue is not labelled with gssoc20 label so you can't work on this.

**Comment by alodahl** [comment]
@ravireddy07 would you like this issue?

**Comment by ravireddy07** [comment]
@alodahl  yes. Can i work on this..??

**Comment by Kundan28** [comment]
@ravireddy07 You are assigned to this task, now you could start working on this issue.

**Comment by ravireddy07** [comment]
@Kundan28  @alodahl  Standardized all Markdown using Prettier. And i also mentioned settings used like tab spaces, single quotes, etc. Please once review it. 
PR: #1285
