### ISSUE TITLE
Link in a resource: "System Design Primer" to appropriate existing lesson

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1132]
This might be an excellent resource to add to our curriculum: https://github.com/joinhandshake/system-design-primer#study-guide

Help us figure out where it belongs and include the link in a PR!

**Comment by abhinashgiri** [comment]
Please assign me this one.I'm a GSSoC participant.

**Comment by vegetabill** [comment]
@MichelleGlauser what makes you think we need this in the curriculum? Amazon does not ask System Design questions until Engineer Level 2, which is minimum 4 years experience. Maybe I'm not thinking of the right type of "system design" or maybe other companies differ.

**Comment by alodahl** [comment]
Maybe as an interview supplemental material?
