### ISSUE TITLE
Add Twilio HTTP headers article to the Web Security lesson

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1133]
"HTTP Headers for the Responsible Developer" is a great resource we should share in an applicable topic: https://www.twilio.com/blog/a-http-headers-for-the-responsible-developer

Target file to add: https://github.com/Techtonica/curriculum/blob/master/security/web-security.md

**Comment by vegetabill** [comment]
Target: https://github.com/Techtonica/curriculum/blob/master/security/web-security.md

**Comment by Tahanima** [comment]
Hello,
I am a GSSoC20 participant and I want to work on this issue.

**Comment by habeeba-naaz** [comment]
I gssoc20 participant...I am interested to work on this...if possible please assign?

**Comment by CipherGirl** [comment]
Hello, I'm GSSoC 20 participant. I would like to work in this issue. If it's available can you please assign to me?

**Comment by vegetabill** [comment]
I am assigning this to @Tahanima 

Thanks for volunteering to help Techtonica improve its curriculum!

Please follow the [contribution instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) in additional to any instructions from GSSoC.

Please reply to confirm you are still interested in this issue and will be actively working on it within 48 hours. You do not have to finish the work in that time, but we just want to make sure others have a chance to pick it up if you are working on other issues. 


### Questions?
- If you have any question about this issue and what contributions are being asked for, reply on this issue. 
- **If you have questions about Git, Pull Requests, GitHub, or the contest itself**, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.

**Comment by Tahanima** [comment]
Thank You @vegetabill for assigning me to this issue. Yes, I am still interested in this issue.

**Comment by vegetabill** [comment]
Closing this. I added it to the scoresheet.
