### ISSUE TITLE
[Epic] merge sparse folders with goal of having less total number of folders

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1135]
The large block of folder names is intimidating and doesn't give a clue to the structure. While we do have links in the top-level README, I think having either numerical prefixes to the folders or using subfolders would make it easier to navigate and understand the curriculum sequence.

Has this been thought of before?

**Comment by MichelleGlauser** [comment]
The order/structure was originally reflected in the README, but because we change the order now and then, the README just became a general index and the roadmap is where the order is reflected. If we add numbers to the folders, we'd have to change all of the folders and all of the links whenever we change the order of topics.

**Comment by alodahl** [comment]
Ive been trying to keep the readme In order, as I’ve been directing people to follow the curriculum there if they like, as it’s open-Source. I’d love to fix it if it’s behind.

**Comment by alodahl** [comment]
Rearranging the folders might be a Pandora’s box.

**Comment by vegetabill** [comment]
Agree could be a maintenance headache. I'll try to see if I can think of something cheaper that would help with organization. 

Closing for now

**Comment by vegetabill** [comment]
Reopening. I think merging some of the folders would help unless there is a reason they are like that. There are a lot of folders with only one child.

**Comment by alodahl** [comment]
Im ok with that as long as in-project and roadmap links get fixed accordingly.

**Comment by vegetabill** [comment]
This seems good enough for now.
