### ISSUE TITLE
Incorporate material from slide deck into SEO lesson

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1149]
Add any useful material from [SEO slide deck](https://www.dropbox.com/s/r6e63bqrwc58ou6/Pub%20Network%20SEO%20101%202018.compressed.pdf?dl=0) into:

[seo/seo.md](https://github.com/Techtonica/curriculum/blob/master/seo/seo.md)

**Comment by vegetabill** [comment]
SEO might be on the chopping block so deprioritizing this.

**Comment by alodahl** [comment]
@vegetabill really?  why wouldn't SEO be a priority, esp since its a relatively short lesson?
