### ISSUE TITLE
Create "Feedback, Giving" markdown lesson based on existing slides

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1151]
The former SEAM, me, created a slideshow for an in-person workshop:

https://vegetabill.github.io/techtonica-deck/#1

We should convert this into a new lesson md file (and Google slideshow from the official template) and add to the `career` folder.

Template & instructions for new lessons: https://github.com/Techtonica/curriculum/tree/main/_templates#instructions

**Comment by vegetabill** [comment]
Added slideshow earlier

**Comment by alodahl** [comment]
@vegetabill you've been assigned this whole time... did you mean to  open this to a volunteer?  If not, please add yourself again.
