### ISSUE TITLE
Add content to existing lessons on "Mental ergonomics"

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1153]
Important practices for any corporate worker to learn. Include some basic tips about taking breaks, not eating lunch at your desk, finding a work confidant to vent to, etc. This lesson can mostly be links to external reading along with your own personal slant of what has worked for you.

### Possible Topics
* Taking breaks when stuck 
* Routine of taking a break _before_ your mind is diminished
* Knowing when your mind is at peak: doing your best work then
* Meditation apps and/or yoga
* Stress management
* Therapy (in-person, app-based)

## Lesson Template
Please use our [template README](https://github.com/Techtonica/curriculum/tree/master/_templates) and for the specific format our [lesson outline template](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md) 

### Possible Sources
* https://www.helpguide.org/articles/mental-health/emotional-intelligence-eq.htm
*

**Comment by atrip10** [comment]
I would like to work on this issue.

**Comment by alodahl** [comment]
Sure @atrip10 , just be aware that this new lesson will be paired with the existing [Ergonomics](https://github.com/Techtonica/curriculum/blob/master/ergonomics/ergonomics.md) outline - no need to repeat these things, but feel free to refer to it.

**Comment by alodahl** [comment]
I would also include the new file in the ergonomics folder.  Do you agree, @vegetabill ?

**Comment by vegetabill** [comment]
@atrip10 are you part of GSSOC20? If so this issue is not part of that so please find another. I'm unassigning for now.

**Comment by alodahl** [comment]
@reetika-gupta

**Comment by alodahl** [comment]
Hi @reetika-gupta any word on this issue? Do you have any questions?

**Comment by alodahl** [comment]
If we don't hear from you in a few days, we will assume you are no longer working on this issue. Please let us know.

**Comment by vegetabill** [comment]
Will review and split out into:

- https://github.com/Techtonica/curriculum/blob/master/onboarding/ergonomics.md
- https://github.com/Techtonica/curriculum/blob/master/onboarding/tech-industry-tips.md

**Comment by vegetabill** [comment]
Added concrete items to those docs. Closing as complete.
