### ISSUE TITLE
Add homebrew to Advanced Command Line

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1155]
As part of intro to command line, we should add instructions about installing Homebrew. Currently it is not mentioned until [Mongo installation](https://github.com/Techtonica/curriculum/blame/d6733508fae785be87fc25ed75bba9612e31912c/databases/mongo-db.md#L43).

Edit [Advanced Command Line](https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-advanced.md) lesson 
- include instructions to install Homebrew itself
- explain what it's for, e.g. "the app store for CLI."
- for the exercise, have them install an optional utility, e.g. `tree` or `wget`

We should edit some existing instructions to use Homebrew
* [installing git](https://github.com/Techtonica/curriculum/blame/master/git-version-control/git-version-control.md#L88)
* [installing nvm/node](https://github.com/Techtonica/curriculum/blame/master/node-js/node-lab-exercise-part-1.md#L46)

**Comment by Kundan28** [comment]
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by pa7ri** [comment]
Interested! I'm a GSSoc2020 participant

**Comment by Kundan28** [comment]
@pa7ri You are already assigned to other issue, so once it's merged you will be assigned to other issue.

**Comment by alodahl** [comment]
@pa7ri would you like to take this issue?

**Comment by pa7ri** [comment]
Yes @alodahl :smile: that would be awesome!

**Comment by Kundan28** [comment]
@pa7ri You could now work on this issue.

**Comment by vegetabill** [comment]
Thanks @pa7ri
