### ISSUE TITLE
Add "Living in Open Workspaces" lesson during on-boarding sequence

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1157]
Working in open workspaces can be a problematic balance. It lets folks collaborate easily but this also means folks can interrupt focus easily. Psychological stress of having random people walking by and team members able to see your screen all day is real.

Document techniques, videos, and reading around this topic to help apprentices adjust to this style early in the program.

Create a new folder: `/workplace` and add this lesson. It might be a good folder home for ergonomics, stress, etc.

Copy / paste this template to structure your outline: https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md

### Examples
* Respect headphones as an indicator of busyness
* Find a quiet corner if you want to focus
* Intentionally spend some amount of time without headphones on so others can approach you
* Send "slack warnings" if you are going to come interrupt someone to reduce surprise

**Comment by vegetabill** [comment]
Freakonomics Podcast [Yes, the Open Office Is Terrible — But It Doesn’t Have to Be (Ep. 358)](http://freakonomics.com/podcast/open-offices/?utm_source=Sketchplanations&utm_campaign=2a3a3fb5ae-EMAIL_CAMPAIGN_2019_12_29_02_06_COPY_01&utm_medium=email&utm_term=0_a5a82e1a38-2a3a3fb5ae-131591865)

**Comment by huonggiangbui** [comment]
Hi. Is this issue about documentation?

**Comment by alodahl** [comment]
Yes @huonggiangbui , you will be documenting resources about the topics mentioned based in a template.

**Comment by Kundan28** [comment]
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by ishaan2908** [comment]
I want to work on this issue. Can you assign it to me? @alodahl @vegetabill

**Comment by Kundan28** [comment]
@ishaan2908 Now you could start working on it.

**Comment by Kundan28** [comment]
Removed as per request made by @ishaan2908

**Comment by kichloo** [comment]
@alodahl @Kundan28 Can I work on this issue?

**Comment by Kundan28** [comment]
> @alodahl @Kundan28 Can I work on this issue?

Yes, you can.

**Comment by kichloo** [comment]
I created a folder Workspace, now can anyone give a template to be followed and explain about it.

**Comment by kichloo** [comment]
> I created a folder Workspace, now can anyone give a template to be followed and explain about it.

@Kundan28 @alodahl Anyone?

**Comment by Kundan28** [comment]
> > I created a folder Workspace, now can anyone give a template to be followed and explain about it.
> 
> @Kundan28 @alodahl Anyone?

You could find the templates under `https://github.com/Techtonica/curriculum/tree/master/_templates` directory.

**Comment by kichloo** [comment]
> You could find the templates under https://github.com/Techtonica/curriculum/tree/master/_templates director

The template is definitely good for software development, but it will have to be restructured in /workspace folder. So, can I restructure it(removing some parts and modifying the titles)?

**Comment by Kundan28** [comment]
> > You could find the templates under https://github.com/Techtonica/curriculum/tree/master/_templates director
> 
> The template is definitely good for software development, but it will have to be restructured in `workspace` folder. So, can I restructure it(removing some parts and modifying the titles)?

Yeah, you can.
