### ISSUE TITLE
Review Eventonica Part 5 Express

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1158]
[Eventonica - Part 5 - Express Backend](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part5-express-backend.md) is marked with TODOs to revise and test. 

Please follow up on them, remove and resolve all TODOs.

**Comment by lemon-yellow** [comment]
I can take a look at this! I worked on reviewing parts 1-4 so I already have the inputs ready.

**Comment by lemon-yellow** [comment]
@vegetabill - Can we consider this issue closed?

**Comment by vegetabill** [comment]
Yup! Thanks @lemon-yellow
