### ISSUE TITLE
Create "Eventonica Part 6 - Postgres"

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1159]
[Eventonica Part 6 Postgres](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part6-postgres.md) is just a placeholder. Please complete it.

It covers adding Postgres support to the existing Eventonica Express app.

### Context
- [Eventonica Intro](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-intro.md)

**Comment by lemon-yellow** [comment]
I can work on this! How much experience with Postgres will the cohort have by the time they get to this lesson?

**Comment by vegetabill** [comment]
Addressed by #1178 - thanks @lemon-yellow !!!!!
