### ISSUE TITLE
Create React Styling lesson outline

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1160]
add short lesson into the [react folder](https://github.com/Techtonica/curriculum/tree/master/react-js)
[template markdown](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md)

### Things to Cover
* inline styles and CSS
* integrating bootstrap
* styling in JS frameworks
* create slideshow for visual learners

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue as part of GSSOC 20

**Comment by alodahl** [comment]
great @ashishnagpal2498 !  Please fill out this form if you haven't already, and you can get started:
https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

**Comment by alodahl** [comment]
are you ok with this @vegetabill or is this not for gssoc?

**Comment by ashishnagpal2498** [comment]
hi @alodahl , I have started working on this issue. I wanted to know that if there any template for slides ? If yes , kindly share that. Thank you

**Comment by ashishnagpal2498** [comment]
Completed , Kindly review the PR.

**Comment by alodahl** [comment]
Please make your powerpoint slideshow into a google slides doc and transfer ownership to techtonicaorg@gmal.com.
