### ISSUE TITLE
Create redux lesson outline

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1161]
Fill in intro to redux:
[redux/redux.md](https://github.com/Techtonica/curriculum/blob/master/redux/redux.md)

There are lots of good tutorials that exist so feel free to link in external resources

**Comment by gsong** [comment]
The community at large is moving away from redux, and none of the cohort projects I’ve seen have required using it. Wondering if it’s worth introducing this complexity when they already have so much to deal with.
