### ISSUE TITLE
Review "Intro to Web Security" lesson

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1163]
According to some previous cohorts, the intro to web security lesson needs some revisions and expansion. Please review it and improve it as you see fit.

[Web Security](https://github.com/Techtonica/curriculum/blob/master/security/web-security.md)

Please add an activity link for practice hacking, e.g. https://www.hackthissite.org/

**Comment by huonggiangbui** [comment]
I am a GSSoC Participant. Can I take this issue?

**Comment by alodahl** [comment]
Hi @huonggiangbui , please fill this form out and then you can start! https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

**Comment by huonggiangbui** [comment]
@alodahl I filled out this form few days ago. Do I have to fill it out again?

**Comment by vegetabill** [comment]
Haven't heard back on this so I'm opening it up as unassigned.

**Comment by vegetabill** [comment]
I scanned it and the lesson looks adequate. Closing as no-op
