### ISSUE TITLE
Expand/improve the DevOps material

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1166]
Currently we have [/roles-in-tech/dev-ops.md](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/dev-ops.md)

But it could be refreshed and expanded. If there are specific exercises folks can do, we can also create a freestanding lesson under electives. I realize this is a bit vague so feel free to ping me on the comments below to discuss.

**Comment by sonali623** [comment]
@vegetabill could you please elaborate what the freestanding lesson means ?

**Comment by kichloo** [comment]
@vegetabill We can discuss and I can work on this issue.

**Comment by vegetabill** [comment]
This was a wishlist from Michelle. Closing.
