### ISSUE TITLE
Add lesson on BEM style CSS

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1175]
Add a small lesson on BEM CSS

- what it is
- why it's valuable, esp as it avoids specificity conflicts

Use the [Outline Template](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md)

**Comment by abhu-A-J** [comment]
@vegetabill  can I take this up?

**Comment by vegetabill** [comment]
@abhu-A-J absolutely! Go for it! If you have any questions let me know. Thanks for your help.

These are the [existing dedicated CSS lessons](https://github.com/Techtonica/curriculum/tree/master/css)

**Comment by abhu-A-J** [comment]
@vegetabill  this is addressed on the https://github.com/Techtonica/curriculum/pull/1181
