### ISSUE TITLE
[Draft] [Idea] create a hierarchical set of important topics to help future SEAMs and curriculum owners

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1185]
What topics should participants have a basic understanding of, a working definition, and how they fit into the tech ecosystem. This list does not need to include topics that are already called out in specific lessons.

This list will help the SEAM decide what lessons can be de-prioritized if we are only expecting a basic fluency with a concept, not interview-question-level knowledge of it.

**Comment by vegetabill** [comment]
## Starting list

- Bootstrap
- DNS
- Sockets / ports

**Comment by MichelleGlauser** [comment]
I would argue that they need a bit more than just a definition for Bootstrap and web accessibility.

**Comment by vegetabill** [comment]
@MichelleGlauser can you go into a little more detail? Are you expecting Bootstrap to be part of interview question, vs. actually knowing CSS?

For a11y, this seems important because it's related to inclusion so I think that's fine to emphasize more, but not for industry reasons.

**Comment by MichelleGlauser** [comment]
At the very least, people should understand what a CSS framework is, know that Bootstrap is a popular one, and have made changes d in code that uses one. 

Inclusion needs to be built into process, so ensuring people are aware of and utilizing @11y best practices will help with that and ensure people we're serious about that.

**Comment by alodahl** [comment]
At the risk of being repetitive, I think this is another situation where updating "objectives" and having a centralized objective list as a study guide would help apprentices remember what is really important (and in assessments) versus what is just associated.  If the objectives need to shift, we should change those, not make additional lists.

**Comment by vegetabill** [comment]
Actually going to close this in favor of a draft Google doc
