### ISSUE TITLE
Create Node HTTP.Server exercise without Express

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1187]
# Task:  Convert the driections below into a full project outline.  Include any clarifying statements that you think an absolute beginner might need. Use this template: https://github.com/Techtonica/curriculum/blob/master/_templates/project.md

## New Coding Assignment Guide
This challenge is to help participants learn how to build a simple web server in Node without any frameworks, using built-in `http.server`.

## Deliverables for Your PR
- a markdown file description of the assignment that participants will use to create the code (this should be put in `/projects/node-http-exercise.md`
- Testing files (see Postman below)
- Your own solutions JavaScript file that future assignment graders can use for comparison

## Challenge: Routes to Build 

These are the endpoints they need to create and the behavior they should exhibit. For each one, describe what needs to be created. Feel free to include example code snippets for the first few under a **Hints** section.

1. `/spin` should never close the socket
1. `/hangup` should immediate close with no response
1. `/head` should respond with 204 
1. `/hello` should respond with 200 and text body of "Hello"
1. `/echo?message=xyz` - should respond with 200 and the message as the body
1. `/error` - should respond with 500 
1. `/time.json` - should respond with 200, body with Content-Type of application/json and `{ "now": "Sat Feb 15 2020 14:29:20 GMT-0800" }` where it's the current time of the response
1. `/github` should respond with 302 that redirects to Techtonica GitHub page

## Testing
Create Postman tests that the reader can run themselves while doing this assignment to see if they got on track. (note: the first 2 cannot be tested with Postman).

Export these tests as a file as part of your Pull Request.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by vegetabill** [comment]
One interesting possibility I worked on with @lisaau was adding a custom 302 redirect to demonstrate how certain headers have agreed-upon meaning and will trigger behavior by clients like browsers.

**Comment by imrishabh18** [comment]
Hey, I would like to try this issue.

**Comment by Kundan28** [comment]
@imrishabh18 Now you could start working on this issue.

**Comment by imrishabh18** [comment]
@Kundan28 Hey, could you explain from where should i begin ?

**Comment by Kundan28** [comment]
@alodahl Could you please help @imrishabh18 with this.
As I too is not able to understand the `Challenge: Routes to Build` section.

**Comment by alodahl** [comment]
The goal here is to write a challenge outline for the apprentices: create their own API.  @vegetabill has listed what he wants in the challenge, and your task is to make this a clear set of directions for building the API with some hints.  You can use this template for the challenge directions : https://github.com/Techtonica/curriculum/blob/master/_templates/project.md

**Comment by alodahl** [comment]
Hi @imrishabh18 are you working on this? We haven't heard from you in a month.

**Comment by imrishabh18** [comment]
Nope, i am not.

**Comment by Kuljeet-123** [comment]
@Kundan28 Can I work on this issue??

**Comment by Kundan28** [comment]
> @Kundan28 Can I work on this issue??

You could nort working on this issue. I've assigned you to this issue.
Please have a look at this https://bit.ly/2wQxqLy and fill out the required forms before starting.

**Comment by Kuljeet-123** [comment]
@Kundan28 @alodahl Do I have to write how to create node http server exercise without express or just how to do that exercise ??  Can you please tell me.

**Comment by Kundan28** [comment]
> @Kundan28 @alodahl Do I have to write how to create node http server exercise without express or just how to do that exercise ?? Can you please tell me.

@vegetabill

**Comment by Kuljeet-123** [comment]
> @Kundan28 @alodahl Do I have to write how to create node http server exercise without express or just how to do that exercise ?? Can you please tell me.

@vegetabill  Can you please??

**Comment by alodahl** [comment]
@Kuljeet-123 sorry I missed this.  

Create a new markdown file showing apprentices how to create node http server, but don't use express in the lesson.

**Comment by sylvaindessureault** [comment]
Hi @alodahl!

I'm free and super interested in working on this issue!

**Comment by alodahl** [comment]
Thanks @sylvaindessureault! Please look at our [contributing file](https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md) and let us know if you have questions.

**Comment by sylvaindessureault** [comment]
Excellent. Already did steps 0 and 0.5.
Will start working on this tomorrow.
Thanks!

**Comment by sylvaindessureault** [comment]
Hi @alodahl !

I'm so sorry, I had a mishap on my account and had to recreate it. I'm still working on this issue. Let me know if you want me to continue or pass the bar to someone else since I unassigned myself above.

**Comment by sylvaindessureault** [comment]
Also, for this issue, is it OK if I work on a branch and make the PR from that branch? 

As for the `.js` solution file, do I simply attach the file to the PR?

**Comment by sylvaindessureault** [comment]
Thanks @alodahl! If you want you can reassign me, I should fulfill this within the week.
I will be waiting for @vegetabill to confirm about the `.js` file as well as the Postman test file.

I suggest a folder within `projects` like this:
`projects/node-http-exercise/node-http-exercise.md`
`projects/node-http-exercise/node-http-exercise-postman-collection.json`

And attach the `.js` file to the PR as suggested originally. However, would that stay available to the users if they look for it? I don't know to what extent you want the solution file to be available.

Thanks!

**Comment by sylvaindessureault** [comment]
Almost done. 1 more route remaining, then revise, then I'll make the PR. Probably tomorrow or latest on Friday.

**Comment by sylvaindessureault** [comment]
FYI, @alodahl, I have filled another contributing form with my new email address.

**Comment by sylvaindessureault** [comment]
Just an update to let you know that I'm on schedule. I need to make some tests and should be able to make the PR later on this afternoon.

**Comment by sylvaindessureault** [comment]
@alodahl and @vegetabill, created #1406 .

Let me know if you need any changes.

Have a great day!
