### ISSUE TITLE
[Epic] ES2015-ify code examples and lessons

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1194]
This epic needs to be split into smaller pieces. It could be a good one for GSSoC20

- `let`, and then secondarily `const` should replace `var` entirely
- normal `function` functions are fine to leave in
  - arrow functions can be introduced as part of FP concepts like `map`
- drop constructor functions / prototype examples and rely on just `class` syntax
- destructuring should be not be included until Advanced JS as an optional mini-lesson
- backtick strings should replace all concatenations
- `Promise` is already covered
- Data structures week already covers the new ones like Map & Set. Plain objects as Maps are still very common and acceptable
- require vs import isn't priority

**Comment by alodahl** [comment]
- I agree `var` should not be around - I can't remember if its purpose is ever explained.  What I do know is that `let` v `const` **is** explained in the JS object lesson already.  
- I think require vs import does deserve a quick mention in a backend lesson. I recall that it tripped me up a lot early on, until I read about the difference.
- I agree with the rest 💪🏽

**Comment by gsong** [comment]
Hmm, I'm not sure if destructuring should be optional, as it's vital to working with modern React.

Also, why secondarily `const`? There are many more use cases for `const` than `let` in modern JS practices.

**Comment by alodahl** [comment]
I added #1195 #1196 #1197 #1198 , which should cover the first bullet point.

@vegetabill i agree w @gsong about destructuring - it is necessary pretty quickly when in comes to importing modules. We dont have to get into multi-level destructuring or destructuring props, though - that could be optional.

@gsong, i dont think const is getting a back seat, don't worry.

**Comment by vegetabill** [comment]
+100 to `destructuring` and `require`. I think those would be great mini-lessons during the Advanced JS portion of the curriculum which we just finished, along with OOP (not really all that useful in JS but they need to know it for interviews), recursion, etc.

Added #1220 for destructuring and #1221 for require/import

**Comment by vegetabill** [comment]
@gsong thanks for the feedback. Just curious what your take is on let/const. IIRC the book that Kisha recommended, [Eloquent JavaScript](https://eloquentjavascript.net/) suggests only using const for primitives because otherwise it's not really all the helpful and then you'd basically never use let unless you're reassigning. At Goodreads we actually enforced const where you could use it. I've tended to not want to get that into the weeds on topics, but would love your take here for future reference and future SEAMs.

**Comment by vegetabill** [comment]
This seems good enough for now
