### ISSUE TITLE
ensure our slideshow code examples match their respective outlines

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1196]
_Blocked until completion of #1195_ 

Task:
Look at the pull request changes submitted for #1195. For the files that have been changed, take a look at its linked slideshow and ensure that any code examples match; the `const` and `let` declarations should look the same, along with anything else.  If there are differences, "request access" on the slideshow and/or message a project admin for permission to change the slideshow.

When finished, say so in a comment below. Make a pull request with a single typo fix of your choice and the phrase 'addresses #1196'.

**Comment by abhu-A-J** [comment]
@alodahl once issue #1195 is fixed, I would like to take this up. I have not worked with the presentation before for this platform, so looking to learn something new. 
**Note:** I want to undertake this as GSSoC participant.

**Comment by alodahl** [comment]
Thanks @abhu-A-J !  Please go into each file individually that was changed in #1195 and fix its linked slideshow accordingly if it shares code.

**Comment by abhu-A-J** [comment]
@alodahl Ma'am based on the changes made to files in issue #1195 , I have corrected the following slides:
Slide for JavaScript/JavaScript-7-oop.md : Changes were made in slides 12 and 17.
Slide for testing-and-tdd-mocha-testing.md: Change was made on slide 11.

OOP slide was open for edit , so I have made the changes.
Mocha Testing was in view only mode, So I have send the the link to technotica's gmail id addressing the same. 

You can verify the same and give me green signal so I can make a PR with a typo fix as you have suggested above. Thanks!

**Comment by alodahl** [comment]
@abhu-A-J please request edit permissions on the mocha slides rather than creating a new file.

**Comment by alodahl** [comment]
I emailed you permissions for the mocha slides.  The oop slides look great.  Are there any other files that need to be changed, or is the mocha one the last?

**Comment by abhu-A-J** [comment]
> @abhu-A-J please request edit permissions on the mocha slides rather than creating a new file.

Sure, I'll do the changes there.

**Comment by abhu-A-J** [comment]
> mailed you permissions for the moch

Based on #1195 the other attached slides were pretty correct. I had already raise PR for this, I'll edit the same as instructed.

**Comment by Kundan28** [comment]
@alodahl This issue could be closed now.
