### ISSUE TITLE
ensure our slideshow code examples no longer contain `var`

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1198]
Blocked until completion of #1197 

# Task: Ensure our slideshow code examples match their respective outlines.

Look at the pull request changes submitted for #1197. For the files that have been changed, take a look at its linked slideshow and ensure that any code examples match; the const and let declarations should look the same, and there should no longer be any `var` declarations. If there are differences, "request access" on the slideshow and/or message a project admin for permission to change the slideshow.

When finished, say so in a comment below. Make a pull request with a single typo fix of your choice and the phrase 'addresses #1198'.

**Comment by pandeykriti** [comment]
Is there any work left on this?

**Comment by satvikchachra** [comment]
I am a GSSoC participant. I would really like to contribute. Please assign me with this issue.

**Comment by vegetabill** [comment]
@pandeykriti since you asked this issue is OPEN which means it has no work on it. I am assigning you to work on it. If you changed your mind, just reply and I can remove you. Thanks for your help! 
Follow the [contributor instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md) as well.

**Comment by Kundan28** [comment]
@pandeykriti If you don't reply by tomorrow, the issue will be assigned to someone else.

**Comment by abhu-A-J** [comment]
@Kundan28 may I work on this issue?

**Comment by Kundan28** [comment]
> @Kundan28 may I work on this issue?

Yes, you can.

**Comment by abhu-A-J** [comment]
@alodahl Ma'am based on the changes made to files in issue #1197 , the following slides were corrected

#### Writing Reusable code:
- Slide 4
- Slide 6


#### AJAX
- Slide 10
- Slide 14

#### Testing and TDD
- Slide 13
- Slide 14

#### Refactoring
- Slide 16
- Slide 17
- Slide 17

#### JavaScript VI
- Slide 2
- Slide 6
- Slide 7
- Slide 8
- Slide 9
- Slide 10
- Slide 11
- Slide 12
- Slide 13
- Slide 14
- Slide 15
- Slide 17
- Slide 18
- Slide 19
- Slide 20

For some other slides the issues was resolved already via my previous PR #1260 
> Note: Do you also mind bumping the issue to medium since there were a lot of files I had to go through and check their slides??

**Comment by alodahl** [comment]
Hi @abhu-A-J , it would be much appreciated if you could include the slide links as well as their titles in your comment.
