### ISSUE TITLE
Add outline for code liniting + eslint instructions

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1201]
We want our participants to submit clean PR's and see what well-formatted code looks like. Once they learn syntax and formatting manually, we need a new lesson for how to set up and use a linter.

Create a new lesson outline (markdown only, no need for slides or recording) using our [TEMPLATE](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md).

### Topics to Cover
- Why automated linting?
- eslint setup and use
- suggestion to use popular default style guides, e.g. AirBNB
- Integration with vscode to automatically show linting violations for JavaScript

**Comment by guptavarun619** [comment]
Shall i give it a try. I've been using `es-lint` for quite sometime and can document somewhat begginer-friendly documentation for it.

**Comment by gsong** [comment]
Is there a reason beyond https://prettier.io/docs/en/integrating-with-linters.html#eslint?

**Comment by BhuwanChandra** [comment]
Hey @vegetabill ,  I am gssoc20 participant. I would like to work on this issue, will you assign it to me?

**Comment by vegetabill** [comment]
@gsong I don't understand that link. What tool is the one integrating with linters? Are you saying we don't need a lesson and can just link to that guide?

**Comment by vegetabill** [comment]
@guptavarun619 I've assigned you the issue

Follow the [CONTRIBUTING instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) along with any GSSoC instructions you were given.

**Comment by guptavarun619** [comment]
I've compiled a markdown `./linting/code-linting-eslint.md` with appropriate amount of instructions and resources for the topic. Here's the link to PR #1244
