### ISSUE TITLE
Improve guided practice of intro to databases

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1202]
The [relational DB](https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md) lesson is far too lengthy. It should introduce some basics, ensure the participant has installed and can successfully use Postgres, and leave the rest of it up to the other lessons, e.g. [SQL 1](https://github.com/Techtonica/curriculum/blob/master/databases/sql-1.md).

### Areas to Improve
- [ ] The guided practice is not really guided at all - guide the reader through the example actions with concrete suggestion.
- [ ] Replace hypothetical query examples of SELECT etc
  - [ ] Use an activity based around a test table instead with real examples
- [ ] Remove "under construction" note at the top that refers to this issue

Related to #1380

**Comment by meghaa105** [comment]
Can you assign this to me?

**Comment by Kundan28** [comment]
@vegetabill Could this be worked under GSSoC20 ?

**Comment by Kundan28** [comment]
@meghaa105 Sorry to say but this issue could not be worked under `GSSoC20`

**Comment by meghaa105** [comment]
I can work anyways

**Comment by Kundan28** [comment]
> I can work anyways

Are you a part of GSSoC20 ?

**Comment by shreyakapoor08** [comment]
I want to take up this issue

**Comment by Kundan28** [comment]
@shreyakapoor08 Sorry to say but this issue could not be worked under GSSoC20

**Comment by meghaa105** [comment]
Yes

**Comment by Kundan28** [comment]
Then how could you work ? @meghaa105

**Comment by alodahl** [comment]
@vegetabill are things being removed already in SQL1, or do they need to be moved over there?

**Comment by alodahl** [comment]
@meghaa105 are you still interested?

**Comment by pa7ri** [comment]
I'm a GSSoC participant (just solved a previous assigned issue) if anyone else is interested I would like to work on it

**Comment by meghaa105** [comment]
Yes

**Comment by Kundan28** [comment]
@meghaa105  I have assigned you this issue.

Please follow the [Contributor](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md) instructions and ask any questions here.

**Comment by alodahl** [comment]
Hi @meghaa105 , how is this issue going? Let us know if you have any questions.

**Comment by Kundan28** [comment]
@meghaa105 Are you still working on this, please reply as soon as possible. Otherwise someone else would be assigned to this issue.

**Comment by meghaa105** [comment]
Yes I am working on it, will update you in a day or two.

**Comment by Kundan28** [comment]
> Yes I am working on it, will update you in a day or two.

Sure.

**Comment by alodahl** [comment]
Hi @meghaa105 , feel free to continue working on this issue, but as it was assigned to you 6 weeks ago and there's no PR yet, I will make this available for someone else to try.  I will merge whoever's PR is ready first.

**Comment by alodahl** [comment]
Assigning to @iamdhruvsharma

**Comment by iamdhruvsharma** [comment]
Hi! 

Can you just update me on the things that I need to do because I believe some of the issues are already being handled. So, if you can tell me how exactly I can help that would be more efficient.

Thanks!

**Comment by alodahl** [comment]
@iamdhruvsharma ,  I don't think this issue is out of date.  I'm not sure what you mean.

**Comment by iamdhruvsharma** [comment]
Thanks for the response. 

Please tell me little bit more about this:

Basic column types - include examples and their equivalent in JavaScript
e.g. varchar is like String
remove Text
remove auto increment

**Comment by iamdhruvsharma** [comment]
Replace all the "Common mistakes" with just one: "Database can refer to the tables, the database server, or SQL. You'll just have to use context to know what someone means"

The above requirement is already completed I believe.

**Comment by alodahl** [comment]
I don't even see a common mistakes section... it may have been deleted completely in the last merge. Could you add it back with the "just one" part?  It should look like the "Common Mistakes & Misconceptions" section here: https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md#common-mistakes--misconceptions

**Comment by iamdhruvsharma** [comment]
Sure! Will definitely do.

**Comment by iamdhruvsharma** [comment]
Move the non-relational examples to an Optional Section covering other types of databases. What about this one??

Rest I am all clear and will do all the things very soon.

**Comment by alodahl** [comment]
If you find examples that aren't directly about relational databases, remove them, or group them all in a section clearly marked something like "Non-relational dbs to be aware of."

**Comment by iamdhruvsharma** [comment]
Got the idea!!! On it now. Will complete as soon as possible. Thanks for the clarification.

**Comment by alodahl** [comment]
Hi @iamdhruvsharma , any word on this one?

**Comment by iamdhruvsharma** [comment]
Hi there!! Hope you are perfectly safe in this difficult situation. Sorry of the delays, for last couple of weeks I was little with my University curriculum but I assure I will complete this task very soon. On it now.

**Comment by iamdhruvsharma** [comment]
Hello! Just made the pull request. Please have a look.

**Comment by vegetabill** [comment]
@alodahl I merged in the small fixes from that PR and now this description is accurate as to what remains. Unfortunately what remains is much more important for the apprentices 😢

**Comment by alodahl** [comment]
🚨
Leah Alpert  1 hour ago
i broke up the content into these 5 lessons that are in the roadmap now:
1. intro to db (optional if we don’t want a lesson this short, but introduces the concept of dbs) https://github.com/Techtonica/curriculum/blob/master/databases/database-intro.md 
2. data modeling 1 https://github.com/Techtonica/curriculum/blob/master/databases/data-modeling-1.md 
3. sql part 1 https://github.com/Techtonica/curriculum/blob/master/databases/sql-1.md 
4. data modeling 2 https://github.com/Techtonica/curriculum/blob/master/databases/data-modeling-2.md 
5. sql part 2 https://github.com/Techtonica/curriculum/blob/master/databases/sql-2.md
6. 
let me know if you want me to delete the old versions

**Comment by lemon-yellow** [comment]
Hi - I am available to work on this issue. To confirm, the lesson should give an overview of why databases are used, introduce relational databases, cover NoSQL very briefly, and walk through the 4 SQL statements using Postgres? Are there other topics that should be covered?

**Comment by lemon-yellow** [comment]
Hi- does this need to be worked on? Feel free to assign it to me.

**Comment by daaimah123** [comment]
Closing this issue as it was resolved by @alodahl ([see comment](https://github.com/Techtonica/curriculum/issues/1202#issuecomment-770132237))
