### ISSUE TITLE
Revise/reword Creating/Updating Data, Question No. 3

### ISSUE THREAD

**Issue by gabymoreno9** [Techtonica/curriculum#1203]
Under db-modeling-assignment.md, number 3 asks 

> **Update** the database to record that a user Heart'ed a specific photo

The word **update**  is confusing. Not sure what the question means by update.

**Comment by vegetabill** [comment]
Thanks for opening this, @gabymoreno9  .

Can you suggest a clearer wording? Is the confusion because it mentions an 'update' but you should actually use SQL `INSERT` ?

**Comment by alodahl** [comment]
@gabymoreno9 we'd love to fix this, but we need to know your answer first.
