### ISSUE TITLE
Remove SQLite from curriculum and replace with Postgres

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1204]
Originally, the curriculum included some activities that used SQLite. This only saved a small amount of installation time and just caused confusion. Since SQL is further along in the curriculum, the participants should be capable of setting it up so let's go all in on Postgres.

## Requirements
- Find all references to SQLite
- Change them to use Postgres tooling and syntax

We will continue to rely on the [existing install instructions](https://github.com/Techtonica/curriculum/blob/master/databases/installing-postgresql.md). You can ignore the docker debate below.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by vegetabill** [comment]
@alodahl is this something that was discussed and discarded before? Since the original curriculum used Mongo exclusively, not sure if this was really thought about in-depth.

**Comment by gsong** [comment]
@vegetabill As long as by setup you mean https://hub.docker.com/_/postgres 😉

**Comment by vegetabill** [comment]
😐

**Comment by gsong** [comment]
@vegetabill Not a fan of Docker? Any specific reasons why?

**Comment by vegetabill** [comment]
@gsong I like Docker just fine but we're trying to limit the moving parts here. Installing psql takes about 5 minutes using Homebrew so not sure how we would justify using Docker there unless we plan to Docker-ify the whole laptop environment. If you think that's worthwhile, I'd open a Epic to do that for future discussion. Having the laptops all set up the same way would be nice.

**Comment by gsong** [comment]
My personal opinion is that a Docker based environment is much more predictable than your typical developer's local environment.  PostgreSQL is definitely easy to install via Homebrew, but it introduces its own challenges compared to isolated Docker DB instances (e.g. you can completely isolate your test DB from your development DB, no need to worry about user names, roles, etc. for different projects).

I also think there's value in setting a development environment that's closer to how a modern development environment would be set up.

No right or wrong answer here, and you're closer to the ground. So ¯\_(ツ)_/¯.

**Comment by alodahl** [comment]
@vegetabill could we add this to gssoc?

**Comment by alodahl** [comment]
@vegetabill I'm having a hard time understanding your original question. I'm fine to go forward with this issue.

**Comment by alodahl** [comment]
@gsong as we have a limited time, containers won't make the short list I'm afraid.

**Comment by vegetabill** [comment]
@alodahl I was just asking if someone proposed this idea before and bad things happened. I doubt it so I'm moving this for our hackathon today and then gssoc.

**Comment by Tawishi** [comment]
I would like to work on this issue @vegetabill.

**Comment by Tawishi** [comment]
> Originally, the curriculum included some activities that used SQLite. This only saved a small amount of installation time and just caused confusion. Since SQL is further along in the curriculum, the participants should be capable of setting it up so let's go all in on Postgres.
> 
> ## Requirements
> * Find all references to SQLite
> * Change them to use Postgres tooling and syntax
> 
> We will continue to rely on the [existing install instructions](https://github.com/Techtonica/curriculum/blob/master/databases/installing-postgresql.md). You can ignore the docker debate below.

Does this mean even the SQL slides and all material related to SQL to changed to Postgres?

**Comment by Kundan28** [comment]
@Tawishi Are you still working on this issue ?
And I don't see any Pull Request started by your for this issue.

**Comment by Tawishi** [comment]
No @Kundan28 .😔

**Comment by Kundan28** [comment]
> No @Kundan28 .😔

So you want to continue working on this ? Or you want someone else to be assigned to this ?

**Comment by Tawishi** [comment]
> > No @Kundan28 .pensive
> 
> So you want to continue working on this ? Or you want someone else to be assigned to this ?

You may assign it to someone else.

**Comment by Kundan28** [comment]
@alodahl I would like to work on this issue.

**Comment by GazKris** [comment]
I would like to pick this up.

**Comment by alodahl** [comment]
Hi @GazKris how is this going?

**Comment by GazKris** [comment]
Good! I plan on submitting the PR today.

**Comment by GazKris** [comment]
Do you want all references of SQLite in all files changed to PostgreSQL, or just the references in the files linked in the [table of contents ](https://github.com/Techtonica/curriculum#table-of-contents)?

**Comment by vegetabill** [comment]
The intent was for all references so as many as you can do would be great!

If some of them are more complicated (assignments that have sqlite-specific steps that aren't trivial to migrate to postgres), we can create additional tickets for them. Just let me know which ones you're skipping.

**Comment by GazKris** [comment]
Oh ok! I misunderstood then. I will go through all the docs and hopefully finish that up this weekend. Thanks!

**Comment by GazKris** [comment]
Do you want to replace the SQLite browser with pgAdmin?

**Comment by vegetabill** [comment]
Last cohort Postico is what everyone used and I thought it was a good choice

**Comment by GazKris** [comment]
There are a lot of references to pgAdmin in the projects session. Do those need to be changed to Postico? 
If so, do you want me to change them while I'm here, or open another issue?

**Comment by vegetabill** [comment]
I don't think it's worth updating those.  Longer term, we could change them to just be generic to "your preferred Postgres client" but I think that should be a separate issue so just leave them as is for now.

Thanks for checking!

**Comment by vegetabill** [comment]
To summarize now that I'm in front of my computer, please replace any reference to a specific SQLite app with either Postico or a generic "Postgres client" (your choice!)

But you can leave existing pgadmin or anything else since that's valid.

**Comment by vegetabill** [comment]
Fixed by #1204
