### ISSUE TITLE
Reorganize career folder

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1205]
Recently we created a new `career` top-level folder.

Please move the following lessons under this folder and update all existing internal links to their new locations

### Desired Contents
If the item is a folder, move it as it is and make it a subfolder of `career`. If it's a file, move it into `career` and drop its folder.

#### Folders 
- `roles-in-tech`
- `interviewing`

#### Files
- `resume-writing/resume-writing.md` 
- `conflict-resolution/conflict-resolution.md`
- `professionalism/building-confidence.md`
- `professionalism/difficult-workplace-situations.md`
- `professionalism/LinkedIn.md` please rename to kebab case, `linked-in.md`
- `professionalism/professionalism.md`

**Comment by habeeba-naaz** [comment]
I am gssoc20 participant and interested in doing this work. please assign me this issue if possible?

**Comment by SaranshDawra** [comment]
Sir, I am a participant in GSSoC20 and want to work on this issue. Please assign me with this issue.

**Comment by alodahl** [comment]
@SaranshDawra , i’ll assign this to you. Would you please fill this form out for us before you start? https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

@habeeba-naaz I believe you already have an issue in progress.

**Comment by SaranshDawra** [comment]
@alodahl I have filled the above-mentioned form. May I start working on the issue.

**Comment by soulhunter10737** [comment]
Hello!, I am a participant of GSSOC'20 and i would really love to work on this issue, please assign me with this issue. Thank you!

**Comment by vngarg** [comment]
Hello, I'm GSSOC'20 participant. I would like to work on this issue. Assign this to me please.

**Comment by FrozenGirl-spd** [comment]
@alodahl I have filled out the form and i want to work on this issue. Can you please assign this to me?

**Comment by PriyaSaini26** [comment]
I am a participant of GSSOC'20 and I am interested in doing this project, could you please assign this task to me.

**Comment by soulhunter10737** [comment]
I would like to take this issue, please assign me this for GSSoC'20. I am new in this.

**Comment by SaranshDawra** [comment]
@alodahl I have started working on this issue.

**Comment by soulhunter10737** [comment]
I would like to take the issue, can you assign me this?

**Comment by vegetabill** [comment]
@SaranshDawra 

Thanks for volunteering to help Techtonica improve its curriculum! I have assigned you to this issue.

Please follow the [contribution instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) in additional to any instructions from GSSoC.

### Questions?
- If you have any question about this issue and what contributions are being asked for, reply on this issue. 
- **If you have questions about Git, Pull Requests, GitHub, or the contest itself**, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.
