### ISSUE TITLE
Implementation of repo for  training and job placement Guidance with study material for our students and guests.

### ISSUE THREAD

**Issue by biekymahato** [Techtonica/curriculum#1206]
**The placement session for any company generally has 3 – 4 rounds. The first round is the written test, consisting of quantitative aptitude, reasoning (logical ability), English (verbal ability) and computer science subjects (C, C++, Data Structures, Algorithms, DBMS, OS, Networks, etc.).
For some companies, you might also have a coding round, which is sometimes taken as a separate round and sometimes is clubbed with the written test.
Further rounds are interview rounds, the first two usually being the technical round and successive rounds being the HR round.**

**Overall, we want to expand our program to serve more students for their better placements and technical knowledge.
Together As the whole Gssoc's community We can work for making a good placement and training repo.**

**Comment by biekymahato** [comment]
As a part of Gssoc'20, I want to work on it.

**Comment by vegetabill** [comment]
@biekymahato I'm not 100% sure what you're proposing. This project is _a_ curriculum for what you're describing, albeit geared toward the tech culture of San Francisco, CA, USA, but probably much of it is universal. What exactly would you want to work on?

**Comment by biekymahato** [comment]
In this project, we are going to build a placement and training tutorial.
From this issue, we can make a project which helps the student to prepare themself for placements and to guide them in a specific way.
In this Project, we include all the things related to placement and training programs.

**Comment by vegetabill** [comment]
Continuing discussion in GSSoC20 slack.

https://gssoc20.slack.com/archives/CUCLEHDHN/p1582775903122500

**Comment by biekymahato** [comment]
@vegetabill  Can I change the topic?
