### ISSUE TITLE
Merge git and GitHub folder contents => git folder

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1207]
Please create a new top-level folder called `git` and fill it with the contents below. For any file you move, please search for all existing internal links to the file and update to its new location.

- Move all contents of [/git-version-control](https://github.com/Techtonica/curriculum/tree/master/git-version-control) into this new folder
- Move github-code-storage/github-storage.md
- Move github-collaboration/github-collaboration.md

**Comment by habeeba-naaz** [comment]
I am gssoc20 participant..Interested to do this work, please assign me to this if possible?

**Comment by Yashank18** [comment]
Sir,
I want to work on this issue and want to consider this under GSSoC'20. Please assign me the same. :)

**Comment by SimranMakhija7** [comment]
I want to contribute to this issue as a part of GSSOC 20. Could the issue be assigned to me please?

**Comment by FrozenGirl-spd** [comment]
Sir, I want to work on this issue.  @vegetabill  Can you please assign me?

**Comment by CipherGirl** [comment]
Hello, I'm GSSoC 20 participant. I'm very new to open source projects. Never have contributed to any projects before. I think I can do this. Can you please assign me?

**Comment by vegetabill** [comment]
@habeeba-naaz since you were first to comment, I have assigned you the issue. If you decided to work on something else, please reply.

For others, please choose a different issue. If another volunteer, or in this case four others, have already commented, do not leave another comment.

**Comment by vegetabill** [comment]
@habeeba-naaz please follow the [CONTRIBUTING instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) if you have not already.

**Comment by vegetabill** [comment]
@Yashank18 I have assigned you this issue. If you would like to work on it, please reply to confirm that you still want to work on this issue within 48 hours (just that you're interested; you don't have to complete the work in that time). After that, it will go to the next volunteer.

**Comment by Yashank18** [comment]
@vegetabill 
Thank you for assigning me. Yes, I will work on this sir.

**Comment by habeeba-naaz** [comment]
Sorry...I was unable to reply because It was night time for me...I didn’t check it...I am happy to take up this issue

**Comment by Kundan28** [comment]
@habeeba-naaz Sorry to say but the @Yashank18 has been assigned to this issue.

**Comment by alodahl** [comment]
Hi @Yashank18, you did some great work, but a few of the links are broken, but I couldn't test them until it was merged.

1. Anything with this incorrect link: https://github.com/Techtonica/curriculum/blob/master/projects/git/git-version-control.md

2. One image link in gitignore.md is incorrect.

Please link this issue and the old PR in your New PR.  Then we can close this issue.  Thanks!

**Comment by Yashank18** [comment]
@alodahl 
Sure. Will create a new pr with changes
