### ISSUE TITLE
Remove references to Mongo DB

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1208]
MongoDB used to be the primary database taught in our curriculum but we have since switched to PostgreSQL. But there are still a lot of references lying around to Mongo.

Find all references to `Mongo`, `MongoDB` and `Mongoose` and remove them / replace them to say Postgres (depending on the context of the sentence/paragraph).

_Note: We will be keeping the actual lessons on Mongo and Mongoose intact as electives._

**Comment by vegetabill** [comment]
This ticket can ignore the following files:

- /express-js/server-side-project.md
- /projects/kickball-signups-project.md
- /projects/mongo-assessment.md
- /databases/mongo-db.md
- /databases/mongoose.md

**Comment by mikenator5** [comment]
First time contributor, changed objectives/9.md to PostgresDB, wasn't sure if this needed to be changed cause it wasn't in the ignored files.

[9.md.tar.gz](https://github.com/Techtonica/curriculum/files/4263098/9.md.tar.gz)

**Comment by satvikchachra** [comment]
@vegetabill Could you please describe the issue in a more elaborate and file-specific way?
Which files of the curriculum need to be updated?

**Comment by vegetabill** [comment]
@satvikchachra  part of the work of this task is to find the usages. As this task was already commented on, please choose another

[See CONTRIBUTING for instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0)

**Comment by vegetabill** [comment]
@mikenator5 would you like to be assigned this issue? If so, follow the [instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0)

**Comment by prangya244** [comment]
I want to work on this issue as a part of GSSOC 2020.

**Comment by vegetabill** [comment]
@prangya244 I have assigned you this issue. Please follow the [CONTRIBUTING instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md)

**Comment by prangya244** [comment]
Thanks @vegetabill. I am working on it.
