### ISSUE TITLE
Revise templates and requirements for new lessons

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1211]
Based on Vrie's research and feedback from current and past participants, we should streamline the template to come up a format for concise, easy-to-use lessons. Preliminary feedback and my own experience has led me to the conclusion that many of existing lesson outlines are far too detailed, not skimmable, have too many links, too few visuals, etc. We also currently mandate to include slides and a slide recording, which makes the volunteer effort to create a new lesson quite high.

In the templates/README we should include a link to a "model lesson" that is highly rated by participants, the SEAM, and curriculum developers as being easy to read, effective in teaching, and easy to maintain.

**Comment by vegetabill** [comment]
Example feedback: the "Motivation" section now lists companies that use the tech (????) which isn't really a compelling reason for an apprentice to learn the topic (and become laughably out of date quickly). A possibly better template would say to connect this lesson to previous lessons and how it will come into play for later lessons: e.g. this is a building block for creating a full stack app and will be covered by assessment(s).

**Comment by meghaa105** [comment]
Can you please assign this issue to me?

**Comment by vegetabill** [comment]
This is the new template:

https://github.com/Techtonica/curriculum/blob/master/_templates/lesson-v2.md

Any changes can be a new issue
