### ISSUE TITLE
On www.techtonica.org's Team page have responsiveness issue

### ISSUE THREAD

**Issue by Yashank18** [Techtonica/curriculum#1212]
On the website, www.techtonica.org's team page is not responsive. Background color is missing and blue blocks are not completely covering up the background. Will like to work on this issue under GSSoC'20.
Please assign me the same. @alodahl @vegetabill 
![Screenshot (95)](https://user-images.githubusercontent.com/46098062/75539433-37469200-5a40-11ea-80d9-8fd8802392dc.png)

**Comment by vegetabill** [comment]
@Yashank18 thank you for reporting this issue. However, this repository is not for our website. 

It's also an open issue on that repo. If you want to work on that issue, I can credit it toward the GSSoc points: 

https://github.com/Techtonica/techtonica.org/issues/167
