### ISSUE TITLE
Issue with responsiveness (techtonica.org)

### ISSUE THREAD

**Issue by goyalmuskan** [Techtonica/curriculum#1213]
The Upcoming Events section is not responsive. I would like to work on the issue. (GSSoC'20)

![Screenshot (3)](https://user-images.githubusercontent.com/47412347/75539809-dcfa0100-5a40-11ea-9ca7-48d8251ef3cb.png)

@alodahl 
@vegetabill

**Comment by vegetabill** [comment]
This repo is not for the website. Please open this issue at https://github.com/Techtonica/techtonica.org/issues

Unfortunately it cannot be counted toward GSSoC since it's a different repo

**Comment by Srashtimittal** [comment]
I am a gssoc 2020 participant. I want to contribute in this issue.
