### ISSUE TITLE
Overlapping Image in "Openings" Section and bullets in "Volunteer" Section..

### ISSUE THREAD

**Issue by vngarg** [Techtonica/curriculum#1214]
![Screenshot from 2020-02-28 17-13-45](https://user-images.githubusercontent.com/49458871/75547014-f6567980-5a4f-11ea-8608-1146de36f872.png)
![Screenshot from 2020-02-28 17-15-05](https://user-images.githubusercontent.com/49458871/75547082-243bbe00-5a50-11ea-811d-0eaf6e58ad51.png)

I would love to work on these issues....
Assign these to me .

**Comment by vegetabill** [comment]
This repository is not for the website. If you'd like to open this issue in that project, open it there: https://github.com/Techtonica/techtonica.org/issues

Unfortunately, those issues cannot count toward the GSSoC content.
