### ISSUE TITLE
Create API testing activity

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1215]
## Related Issues

- #1216 - We should use `supertest` since we already have some materials/lessons on it (and Bill thinks it's pretty good)
- #1296 - Eventonica Epic

## Description

Once Eventonica Part 5 is done, having API tests is a great way to provide stability while working on migrating to a database-backed backend. Let's make an in-class pair activity guide for it!

In the H1-2020 cohort, I just linked them to a short blog: https://codeforgeek.com/unit-testing-nodejs-application-using-mocha/

### Requirements
- Please add this project activity in the `projects/eventonica` folder.
  - See [project template](https://github.com/Techtonica/curriculum/tree/main/_templates) in our templates folder
  - Code examples should match the [Eventonica Domain](https://github.com/Techtonica/curriculum/blob/main/projects/eventonica/README.md) domain
- Include tests for GET, POST
- Include sample code for a single test case that creates data, verifies it exists, deletes it, and verifies it's gone
- For the Application Under Test (AUT) you can use [Lisa's code](https://github.com/lisaau/techtonica-assignments/tree/c194870fecadf0627def4b035a857c7dd7c3f846/Eventonica-with-Express) but note that the feature set has changed since she wrote it, so a few of the API endpoints wouldn't match. To minimize future rework, focus on endpoints that wouldn't change, e.g.
  - GET user
  - POST user

### Preferred
- Instead of using Mocha (an elective framework), preferably use node Jasmine to run these tests
  - I couldn't find any existing blogs for this so you might have to try it out on your own
- For the request-making, preferably use supertest (see related issue above)
- As a challenge, linking to how to leverage package.json's "scripts" feature to run all the tests or  start their server would be helpful

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by vegetabill** [comment]
@lisaau would you share your most complex test case code snippet here please?

**Comment by lisaau** [comment]
Here's one I have to test POST: 

`describe("POST", function() {
    it("POST/user should add a user",function(done){
        let data = {userName: 'test', userID: 10};
        server
        .post('/user')
        .set('Content-type', "application/x-www-form-urlencoded")
        .send(data)
        .expect("Content-type",/text\/html/)
        .expect(200)
        .then( () => {
            server
            .get('/users')
            .end(function(err, res) {
                // check that user is added to the end of the array
                res.body[res.body.length - 1].userID.should.equal(data.userID); 
                done()
            })
        })
    });
});
`

**Comment by Nshah-02** [comment]
I would like to work on this issue.

**Comment by Kundan28** [comment]
@Nshah-02 You only have 8 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Nshah-02** [comment]
Sorry, sir
Due to some reasons, I was not able to connect to you regarding this issue.
But I can assure you that this will not happen again.
Regards,
Nidhi Shah

**Comment by Kundan28** [comment]
So are you working on this or if you want I could assign someone else to it.

**Comment by Nshah-02** [comment]
sir, I am working on it but I just need more time to learn it as it is a
new subject for me. But before the deadline, I would definitely complete it.

**Comment by Kundan28** [comment]
Okay, go for it.

**Comment by Nshah-02** [comment]
Thank you, sir

**Comment by Nshah-02** [comment]
sorry sir, Due to some personal reasons I cannot work on this issue anymore.

**Comment by Kundan28** [comment]
Okay, no problem.

**Comment by vegetabill** [comment]
Related to #1216

**Comment by lemon-yellow** [comment]
HI- I am available to work on this issue.

**Comment by lemon-yellow** [comment]
Hi- does this need to be worked on? Feel free to assign it to me.

**Comment by vegetabill** [comment]
@lemon-yellow awesome thanks for offering! I've assigned you. If you have any questions, feel free to ask here.

**Comment by lemon-yellow** [comment]
@vegetabill - I created a pull request. Let me know if you'd like any changes!

**Comment by vegetabill** [comment]
Implemented and merged in #1485
