### ISSUE TITLE
Create "mocking" lesson outline using existing material in integration testing

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1217]
Split from #1216, this issue concerns creating a new lesson about mocking specifically

## Lesson Objective / Motivation
- Participant should understand what mocking is and why it's useful.
- Create a unit test that leverages mocking using the Jasmine testing framework

## Steps
1. Familiarize yourself with the [mocking section](https://github.com/Techtonica/curriculum/blob/8acd5068d6bcbfb4f4c71ef598340bb324793764/testing-and-tdd/integration-testing.md#2-mocking-and-abstraction) of the existing integration testing lesson. That link is not of master since it may be deleted on master if someone already worked on #1216.
1. Start with a [Template Lesson Outline](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md)
1. Revise the content as you see fit. If you can find better external resources, please use them instead
1. Be concise, repeat important topics, use visuals, use lots of headings, bold text, etc to make the content skimmable. Participants will often not have time to read all the text fully

**Comment by samridhijain27** [comment]
I am interested in working on this issue .

**Comment by Kundan28** [comment]
@samridhijain27 Now you could start working on this issue.

**Comment by samridhijain27** [comment]
Sure, on it

**Comment by Kundan28** [comment]
@samridhijain27   You only have 5 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by alodahl** [comment]
@samridhijain27 is still working on this one; they responded on slack.

**Comment by Kundan28** [comment]
@samridhijain27 Requested to unassign her.

**Comment by kichloo** [comment]
Can I take this issue?

**Comment by Kundan28** [comment]
> Can I take this issue?

You PR is not yet merged.

**Comment by pa7ri** [comment]
hi @Kundan28, can I work in this issue?

**Comment by Kundan28** [comment]
> hi @Kundan28, can I work in this issue?

Yes, you can now start working on this issue.
