### ISSUE TITLE
Fix typo in eventonica-6 instructions

### ISSUE THREAD

**Issue by Zarina2311** [Techtonica/curriculum#1218]
https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part6-postgres.md

How to Submit
`In additional to the usual steps:` => In **addition** to

**Comment by vegetabill** [comment]
@Zarina2311 thanks for submitting this issue. When creating issues in the future, use a clearer title, see how I revised it. Thanks!

**Comment by CipherGirl** [comment]
As GSSoC 20 participant can I work on this?

**Comment by ishaan2908** [comment]
I want to work on this issue as a part of GSSOC 2020. Can you assign this to me? @vegetabill

**Comment by soulhunter10737** [comment]
@vegetabill Please assign me this issue .

**Comment by Tahanima** [comment]
Hello,
I am a GSSoC20 participant and I want to work on this issue. @vegetabill please assign me this issue if it is available.

**Comment by soulhunter10737** [comment]
@vegetabill I would like to take up this issue, can you please assign me?(gssoc20)

**Comment by vegetabill** [comment]
@CipherGirl I have assigned you this issue.

Please follow the instructions in [CONTRIBUTION](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md)

**Comment by CipherGirl** [comment]
#1259

**Comment by CipherGirl** [comment]
The pull request #1259 regarding this issue is been merged. This issue can be closed.
