### ISSUE TITLE
Simplify and modernize AJAX lesson

### ISSUE THREAD

**Issue by lizandry** [Techtonica/curriculum#1219]
https://github.com/Techtonica/curriculum/blob/master/ajax/ajax.md

This lesson was dropped from the roadmap, but reading it helped me understand more about how APIs work. Centering a different API request method (this lesson links to an article that also covers Fetch and async/await: https://dev.to/bjhaid_93/beginners-guide-to-fetching-data-with-ajax-fetch-api--asyncawait-3m1l) and getting it back into the roadmap might help the next cohort a lot!

**Comment by vegetabill** [comment]
Thanks @lizandry for submitting this issue! 

I originally cut that lesson from the roadmap because it was overly long with a lot of unnecessary background information. I'm going to rename your issue into one to just revise it and modernize it for next time.

**Comment by vegetabill** [comment]
- Remove example websites using AJAX (it would be hard to find a website _not_ using AJAX these days)
- Add a short paragraph with background on the name, concluding that it's not really relevant anymore, and is just a shorthand name for the technique in general. 
- Split the intro of "What does AJAX do?" as a new section called "Full Page Load vs AJAX" using the example of a traditional old-school form and an AJAX form
- Remove thread of execution section and replace with a reminder link to [JavaScript 9 - Callbacks and Promises](https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-9.md)

**Comment by abhu-A-J** [comment]
@vegetabill I'll like to work on this one under GSSoC.

**Comment by ashishnagpal2498** [comment]
Hi @lizandry @vegetabill , I would like to work on this issue as part of GSSOC 20 ?

**Comment by Kundan28** [comment]
@ashishnagpal2498 Now you could start working on this issue.

**Comment by alodahl** [comment]
I am unassigning this, as @ashishnagpal2498 is in the middle of another PR.

**Comment by ashishnagpal2498** [comment]
Hey , @alodahl , I have started working on this too. Kind off in the middle. So please don't unassign the issue. I will be completing both soon.

**Comment by alodahl** [comment]
sorry @ashishnagpal2498 , I'll put you back on

**Comment by Kundan28** [comment]
> I am unassigning this, as @ashishnagpal2498 is in the middle of another PR.

But when I assigned him, he was not assigned to any other issue.
