### ISSUE TITLE
Add mini-lesson on destructuring

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1220]
Destructuring is very helpful but a little magical to those new to JS.

**Prereqs:** JavaScript 7

Mini-Lesson - Projected Length 30min max

## Items to include
- What is destructuring
- why it is useful?
- Example: Destructuring an two element array into two named variables
  - `const [k, v] = keyValuePair`
- Example: destructuring items out of a nested object, e.g.
  - `const { id, name } = req.body.object`
- Code snippets showing those examples and the exact same logic written without using destructuring

### Items not to include
- Other more complex forms of destructuring beyond the examples above

### How to get started
Use the [Outline Template](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md) but as this is a "Mini-Lesson" feel free to not include all sections if they don't apply. Our draft [Style Guide](https://github.com/Techtonica/curriculum/blob/master/_templates/instructions.md#lesson-outline-style-tldr) might also be useful.

**Comment by Yashank18** [comment]
I would like to work on this issue under GSSoC'20. @vegetabill assign me with the same.

**Comment by Srashtimittal** [comment]
I am a gssoc 2020 participant. Please assign me this issue @vegetabill

**Comment by sonali623** [comment]
I would like to work on this issue as a part of GSSoC 2020 @vegetabill

**Comment by abhu-A-J** [comment]
@Kundan28 I would like to work on this issue. It's fairly straight forward.

**Comment by Kundan28** [comment]
@sonali623 @abhu-A-J Please find some other issue to work on, as the first one to ask would get would get assigned if he/she is not assigned to some other issue.

**Comment by Srashtimittal** [comment]
@Kundan28 and @vegetabill  Sir, please give the file link where I have to contribute on this issue.

**Comment by Kundan28** [comment]
@Srashtimittal Add that under `JavaScript` folder.

**Comment by Srashtimittal** [comment]
@Kundan28 Thanku sir.

**Comment by Kundan28** [comment]
@Srashtimittal  You only have 3 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Srashtimittal** [comment]
@Kundan28 Sorry Sir, I forgot to do this . I do this today only.

**Comment by Kundan28** [comment]
The new PR would not be accepted.
Open the old one and work on it.

**Comment by Srashtimittal** [comment]
@Kundan28 Ok sir

**Comment by Kundan28** [comment]
Closed with reference to #1272
