### ISSUE TITLE
Add mini-lesson on require & import 

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1221]
In Eloquent JavaScript, our unofficial paper textbook, there is a modules chapter but it wasn't great. Let's add a mini lesson on require and import that we will use in the Advanced JS portion of the curriculum.

**Prereqs:** JavaScript 7

## Items to include
- include the file in our project's /javascript/ directory
- Why there are both (_short_ historical context)
- when they can and cannot use import
  - vanilla node apps should use require asrequire will always work
  - using import requires a transformation pipeline (??? or is this even true? it seems true as of when I'm creating this issue)
- why neither works in the browser
  - unless you fake it with webpack or equivalent
- code examples
- As a mini-lesson avoid relying on links. Provide your own explanations and point of view and save the extra resources for additional detail.

Use the [Outline Template](https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md) but as this is a "Mini-Lesson" feel free to not include all sections if they don't apply. Our draft [Style Guide](https://github.com/Techtonica/curriculum/blob/master/_templates/instructions.md#lesson-outline-style-tldr) might also be useful.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by goyalmuskan** [comment]
I would like to work on this under GSSoC'20. Please assign me this issue. 
@vegetabill

**Comment by vegetabill** [comment]
@goyalmuskan 

Thanks for volunteering to help Techtonica improve its curriculum!

Please follow the [contribution instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) in additional to any instructions from GSSoC.

### Questions?
- If you have any question about this issue and what contributions are being asked for, reply on this issue. 
- **If you have questions about Git, Pull Requests, GitHub, or the contest itself**, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.

**Comment by Kundan28** [comment]
@goyalmuskan Are you still working on this ?
If we don't get your reply by tomorrow, I will assign someone else to this issue.

**Comment by goyalmuskan** [comment]
@Kundan28 Yes, I am.

**Comment by Kundan28** [comment]
Are you working on this ?

**Comment by goyalmuskan** [comment]
Yes, I had my exams earlier, now I am working on it.

**Comment by Kundan28** [comment]
How much time would it take ?

**Comment by Kundan28** [comment]
@goyalmuskan As per your message I've unassigned you from this issue.

**Comment by abhu-A-J** [comment]
@Kundan28 Can I take this??

**Comment by Kundan28** [comment]
> @Kundan28 Can I take this??

You are already assigned to issue 882

**Comment by abhu-A-J** [comment]
> 2

But people are working on two issues at a time as well?? It can be seen on the scorecard? So should I take easy level issue instead of medium for second one??

**Comment by Kundan28** [comment]
> But people are working on two issues at a time as well?? It can be seen on the scorecard? So should I take easy level issue instead of medium for second one??

The maximum limit is 2 issue but we are sticking to 1 issue at a time.

**Comment by abhu-A-J** [comment]
> > But people are working on two issues at a time as well?? It can be seen on the scorecard? So should I take easy level issue instead of medium for second one??
> 
> The maximum limit is 2 issue but we are sticking to 1 issue at a time.

Ah! I see . The it's okay!! I'll wait for it to get merged and the  work on it

**Comment by Kundan28** [comment]
> Ah! I see . The it's okay!! I'll wait for it to get merged and the work on it

Don't get dishearten, I'm just following the rules.

**Comment by kichloo** [comment]
@Kundan28 I can take up the issue.

**Comment by Kundan28** [comment]
> @Kundan28 I can take up the issue.

You are already assigned with one.

**Comment by kichloo** [comment]
@Kundan28 That issue is up for review now.

**Comment by Kundan28** [comment]
> @Kundan28 That issue is up for review now.

Yeah, I know that. But you will only be assigned with other issue after the PR is merged.

**Comment by abhishekgupta368** [comment]
Hey, I am new, Can I do it, please?

**Comment by Kundan28** [comment]
@abhishekgupta368 I've assigned you to this issue. Before starting please go through [this](https://bit.ly/2wQxqLy) link.

**Comment by abhishekgupta368** [comment]
thanks

**Comment by kichloo** [comment]
@Kundan28 Pl address the issue #1157

**Comment by annu12340** [comment]
Is this issue still open?
I am looking forward to contributing to it
Please assign it to me

**Comment by Kundan28** [comment]
> Is this issue still open?
> I am looking forward to contributing to it
> Please assign it to me

@abhishekgupta368 is already assigned to this issue. Please look for other one.
Here's the [link](https://github.com/Techtonica/curriculum/issues?q=is%3Aopen+is%3Aissue+label%3Agssoc20+no%3Aassignee) to see unassigned issues.

**Comment by alodahl** [comment]
I am making this issue available again to whoever asks first.  @annu12340  are you  still interested?

**Comment by sylvaindessureault** [comment]
Hi @vegetabill @alodahl! I'd love to work on this one next!

**Comment by vegetabill** [comment]
Sounds good! I've assigned you.

**Comment by sylvaindessureault** [comment]
Perfect, thanks! I will start working on this tomorrow!

**Comment by sylvaindessureault** [comment]
@vegetabill and @alodahl, I created the PR.

Have a great day!
