### ISSUE TITLE
Expand Postgres installation instructions

### ISSUE THREAD

**Issue by lisaau** [Techtonica/curriculum#1222]
https://github.com/Techtonica/curriculum/blob/master/projects/db-modeling-assignment.md

This was our first assignment where we started using Postgres. It would be helpful to have an additional topic outline/doc or link to a helpful tutorial to teach us how to use PG admin GUI tool (it isn't very intuitive. 

In the psql link, it redirects to: https://www.postgresql.org/docs/9.1/backup-dump.html
It would be helpful to note that the pg_dump is a shell command and should not be used while inside psql.

**Comment by AnushkaH** [comment]
I'm gssoc 20 participant and I'm a beginner and I'm interested.

**Comment by vegetabill** [comment]
@AnushkaH you should be only looking at issues with the `gssoc20` label per the instructions.

on the [CONTRIBUTING](/CONTRIBUTING.md) instructions you can find a link to all unassigned issues wit that label.

**Comment by vegetabill** [comment]
Thanks for reporting this issue, @lisaau

**Comment by vegetabill** [comment]
## Requirements

in [installing-postgres.md](https://github.com/Techtonica/curriculum/blob/master/databases/installing-postgresql.md):

- Add a new section called [pgAdmin](https://www.pgadmin.org/)
- Add small screenshot of the tool in action
- Add the best directions to install on Mac
- Add general tutorial on pgAdmin
  - Find one that if effective, free, and interactive/hands-on (ideally a video or step-by-step article)
  - go through it and include a link
  - If you find more than one, link the best one and add the others to "Supplemental Materials"
- Add a new section called "Including your database in a codebase" 
  - specific instructions on how to export a database in one SQL file
  - This is so students can submit their DB+testing data along with their projects

**Comment by shreyakapoor08** [comment]
Can i take up this issue

**Comment by Kundan28** [comment]
> Can i take up this issue

It doesn't have gssoc20 label so better to find other issue.

**Comment by vegetabill** [comment]
This was already revised to use postico. Closing
