### ISSUE TITLE
Include Lessons on Dynamic Programming

### ISSUE THREAD

**Issue by HarshCasper** [Techtonica/curriculum#1226]
I believe that we should add an introduction and some lessons where the learners can know about Dynamic Programming and its concepts. As a Girlscript Summer of Code '2020 Participant, I would like to work on these issues and develop a course curriculum where we can learn Dynamic Programming.

**Comment by vegetabill** [comment]
@HarshCasper can you give an example of Dynamic Programming in JavaScript? I've only heard of it in Ruby. Our curriculum is scoped mostly to JS and closely related tools.

**Comment by HarshCasper** [comment]
Sure. Here is a [Repl](https://repl.it/@ErbeusGriffin/InconsequentialPastPatches) that implements a popular problem of finding the shortest path in a Weighted Directed Graph. I plan to implement some popular problems in JS which are solved via Dynamic Programming including an explanation of their respective implementation.

**Comment by vegetabill** [comment]
Sorry my mistake I was confusing that with metaprogramming.

[Dynamic Programming](https://en.wikipedia.org/wiki/Dynamic_programming) looks a bit too advanced for the audience of our curriculum. 

See notes on #1224 why we don't want to expand the CS portions of the course.
