### ISSUE TITLE
Include elective resource list for learning Angular

### ISSUE THREAD

**Issue by HarshCasper** [Techtonica/curriculum#1227]
I believe that we should add an introduction and some lessons where the learners can know about Angular.js and its concepts. As a Girlscript Summer of Code '2020 Participant, I would like to work on these issues and develop a course curriculum where we can learn Angular.

**Comment by vegetabill** [comment]
@HarshCasper 
Angular is a good topic but it might be better to just link in an existing lesson. It takes a **lot of effort** to build an entire lesson from scratch, and would exceed the HARD points of GSSoC. I would suggest we revise this issue to say "find and try out a good free tutorial on Angular" and link it in as an elective.

What do you think?

**Comment by HarshCasper** [comment]
It sounds reasonable @vegetabill 

My proposal is to create a Markdown File which consists of good and free tutorials on Angular including a plan where learners can study well and implement Angular. If it is alright, I would like to start working on it as part of GSSOC.

**Comment by HarshCasper** [comment]
Can you please assign me this task to work on the issue @vegetabill

**Comment by vegetabill** [comment]
@HarshCasper that sounds good! I have created an [Elective Template](https://github.com/Techtonica/curriculum/blob/master/_templates/elective.md] so you can see what the format should be. I'm assigning this to you now.
