### ISSUE TITLE
Rename Eventonica React => Eventonica Part 7 React

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1228]
- Rename `eventonica-react.md` to `eventonica-part7-react.md`. Find and update any internal - links to it.
- Leave the `eventonica-react.md` file in place and make it a link to the new location, kind of a like a wiki redirect page.
- Add it to the [folder readme](https://github.com/Techtonica/curriculum/tree/master/projects/eventonica)

**Comment by abhu-A-J** [comment]
@vegetabill would like to work on this

**Comment by soulhunter10737** [comment]
Please assign me this issue.

**Comment by gauravdas014** [comment]
Please assign me this

**Comment by soulhunter10737** [comment]
@vegetabill I would like to take up this issue, can you please assign me?(gssoc20)

**Comment by huonggiangbui** [comment]
I would like to take up this issue, can you please assign me?

**Comment by ashishnagpal2498** [comment]
Can I take this issue @vegetabill ?

**Comment by Kundan28** [comment]
@soulhunter10737 Now you could work on this issue.

**Comment by soulhunter10737** [comment]
@Kundan28 Thank you! Can you please explain me the second and third point of this issue?

**Comment by soulhunter10737** [comment]
I raised a PR please review it.

**Comment by Adyasha8105** [comment]
@alodahl Can I take this?

**Comment by alodahl** [comment]
@Adyasha8105 please read through these [Contributing Guidelines](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md) if this is your first issue with Techtonica.

**Comment by Kundan28** [comment]
> @Adyasha8105 please read through these [Contributing Guidelines](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md) if this is your first issue with Techtonica.

She had already made a contribution before and that was #1300

**Comment by vegetabill** [comment]
Thanks @Adyasha8105
