### ISSUE TITLE
Rename all numbered JavaScript lessons to include memorable name

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1229]
It's too easy to forget which lesson is which.

In the [JS folder](https://github.com/Techtonica/curriculum/tree/master/javascript)

- javascript-1 => javascript-1-variables (Heading: JavaScript 1 - Variables, Strings, Numbers)
- javascript-2 => javascript-2-arrays-functions 
- javascript-3 => javascript-3-conditionals  (heading: JavaScript 3 - Conditionals, Comparisons, Booleans)
- javascript-4 => javascript-4-loops (heading: JavaScript 4: Loops)
- javascript-5 => javascript-5-switch (heading: JavaScript 5: Switch Statements)
- javascript-9 => javascript-9-async (heading: JavaScript 9: Async, Callbacks, Promises)

Change the heading at the top of the file to match

Update all internal links in the curriculum to point to these new names and to include them in the link text, e.g. the link text should be "JavaScript 1 - **Variables**", not just "JavaScript 1"

**Comment by ishaan2908** [comment]
I would like to work on this issue. Please assign it to me! @vegetabill

**Comment by vegetabill** [comment]
@ishaan2908

Thanks for volunteering to help Techtonica improve its curriculum! I have assigned you to this issue.

Please follow the [contribution instructions](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-0) in additional to any instructions from GSSoC.

### Questions?
- If you have any question about this issue and what contributions are being asked for, reply on this issue. 
- **If you have questions about Git, Pull Requests, GitHub, or the contest itself**, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.
