### ISSUE TITLE
Move all on-boarding lessons into an onboarding folder

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1231]
For the in-person participants, there is a [list on the main README](https://github.com/Techtonica/curriculum#week-1---onboarding--developer-tools) of intro topics.

## "Soft Skills"
These should all be moved  to `/onboarding`

- [x] Welcome, Tips, and Rules 
- [x] Expectations While at Techtonica
- [x] How to Learn
- [x] Professionalism
~- [ ] Roles in Tech~
- [x] How to Pair Program
- [x] Ergonomics 
- [x] Growth Mindset
- [x] Asking Good Questions

## Tooling
These should be moved to `/dev-tools`

- [x] Intro to Command Line Interface 
- [x] Advanced Command Line
- [x] Bash Profile
- [x] Vim
- [x] Operating Systems
- [x] Keyboard Shortcuts
- [x] Local Development with VS Code

Update all internal links that exist to point to the new locations.

**Comment by CipherGirl** [comment]
Can you please assign me this? I'm GSSoC 20 participant.

**Comment by SayanBan** [comment]
@vegetabill Could you kindly assign this to me? I am a GSSoC '20 participant

**Comment by soulhunter10737** [comment]
@vegetabill I would like to take up this issue, can you please assign me?(gssoc20)

**Comment by ayushi0014** [comment]
Wanna work on this issue being a participant of GSSoC '20. Could you assign the same to me?

**Comment by huonggiangbui** [comment]
I would like to take up this issue, can you please assign me? @vegetabill

**Comment by soulhunter10737** [comment]
@vegetabill I would like to take up this issue, can you please assign me?(gssoc20)

**Comment by soulhunter10737** [comment]
@vegetabill I would like to take up this issue, can you please assign me?(gssoc20) i am trying to get assigned , but not got any yet

**Comment by Kundan28** [comment]
@CipherGirl  Now you could start working on this issue.
@SayanBan @soulhunter10737 @ayushi0014 @huonggiangbui Please find some other issue as the issues are assigned on first come first serve basis until the participant is not working on some other issue.

**Comment by CipherGirl** [comment]
@Kundan28 and @vegetabill 
The resources are markdown files under specific folders (such as "welcome-tips-rules/tech-industry-tips.md"). Should I delete those folders while I move those files to the /onboarding and /dev-tools folders.

**Comment by Kundan28** [comment]
> @Kundan28 and @vegetabill
> The resources are markdown files under specific folders (such as "welcome-tips-rules/tech-industry-tips.md"). Should I delete those folders while I move those files to the /onboarding and /dev-tools folders.
> Some of the folders does have other files. So I'm asking about the folders which has only the specific files mentioned to move.

Yeah, moving means adding them to the new place and deleting from the old place.

**Comment by CipherGirl** [comment]
I have created a PR #1263 regarding this issue. Please review.

**Comment by alodahl** [comment]
@vegetabill you have `roles-in-tech` being moved to onboarding here, but you have them being moved to `career` in #1205? Which one is correct?
