### ISSUE TITLE
Provide a reference to the contributing guidelines

### ISSUE THREAD

**Issue by jamesjose03** [Techtonica/curriculum#1234]
As of now, the `README.md` file doesn't include a reference to the contributing guideline which people may miss out.
What I propose is a dedicated section that would help other users in making their very first contribution.

**Comment by jamesjose03** [comment]
@vegetabill I would like to tackle this issue

**Comment by Kundan28** [comment]
@alodahl I think this is a valid issue.

**Comment by vegetabill** [comment]
There is a [section](https://github.com/Techtonica/curriculum#volunteering) already covering this, not to mention CONTRIBUTING.md which is the standard file these instructions would be in for an open-source project

**Comment by Kundan28** [comment]
@vegetabill Isn't this a open source project ? 🤔

**Comment by alodahl** [comment]
@vegetabill I found it a little bit weird that there is repetition in the readme and the contributing file.  Can you tell me your reasons for the two separate locations?
