### ISSUE TITLE
Double-check BEM & md syntax, fix typos & wording in outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1240]
Task: Revise first draft of https://github.com/Techtonica/curriculum/blob/master/css/BEM-style.md.

- Double-check BEM syntax, and fix if necessary
- Correct the markdown syntax if necessary
- fix typos & wording in outline

Once you have finished, make a PR with a comment describing your changes.

**Comment by prangya244** [comment]
As  part of GSSOC 2020 I would like to work on this issue. Could you please assign the same to me?

**Comment by ayushi0014** [comment]
Being a beginner wanna contribute to project through this issue. Could you assign this to me?

**Comment by meghaa105** [comment]
Can you please assign this issue to me?

**Comment by huonggiangbui** [comment]
Can I take this issue @alodahl ?

**Comment by Kundan28** [comment]
@prangya244 Now you could start working on this issue.
@ayushi0014 @meghaa105 @huonggiangbui Please find some other issue as the issues are assigned on first come first serve basis until the participant is not working on some other issue.

**Comment by prangya244** [comment]
Thnks @Kundan28 . I am working on it.

**Comment by Kundan28** [comment]
@prangya244  You only have 5 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Kundan28** [comment]
@prangya244 If we don't get reply by tomorrow then someone else would be assigned to this issue.

**Comment by prangya244** [comment]
@Kundan28 I am not able to find the CSS folder anymore in the upstream master. Is there any recent updates?

**Comment by Kundan28** [comment]
> @Kundan28 I am not able to find the CSS folder anymore in the upstream master. Is there any recent updates?

You could find that inside `web` folder.
