### ISSUE TITLE
Improve mocha-testing lesson

### ISSUE THREAD

**Issue by Tahanima** [Techtonica/curriculum#1241]
https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/mocha-testing.md

Under **Mocha vs. Jasmine** section, there is a sentence saying "So, why might you choose one **other** the other?". The highlighted word "other" in this sentence could be replaced by "over" which sounds more appropriate.

 I am a GSSoC 20 participant and I would like to work in this issue.

## Additional Changes
- Add a note in the "should" section of Chai that you if you like that style, you can use the  [should library](https://www.npmjs.com/package/should) with mocha, as that is a common reason to use it over Jasmine
- Move this lesson to `/electives` folder
  - update its link in the root README after moving
- Include an async example in Chai and Mocha and remove the incorrect [Misconception No. 2](https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/mocha-testing.md#common-mistakes--misconceptions)
- Add a challenge: do the Mocha or Chai projects have their own internal tests? Suggest the student read them and see how they are used

**Comment by samridhijain27** [comment]
I would like to work on this issue

**Comment by Kundan28** [comment]
@alodahl @vegetabill This issue could be made under Beginner level.

**Comment by vegetabill** [comment]
I'm expanding this issue to also include adding a useful section, making it the Easy level.

@Tahanima would you like to work on this? Since you reported it, you should have the first chance to own it.

**Comment by Tahanima** [comment]
@vegetabill, sure. I would like to work on this.

**Comment by Kundan28** [comment]
@Tahanima I've assigned you to this issue, now you could work on this.

**Comment by Tahanima** [comment]
Thank You @Kundan28

**Comment by vegetabill** [comment]
@Tahanima thank for revising the PR. I've merged this and I will now assign you the one you created. Great work!

**Comment by Tahanima** [comment]
Thank You @vegetabill
