### ISSUE TITLE
Add an Elective Lesson on Ionic Mobile App Framework

### ISSUE THREAD

**Issue by HarshCasper** [Techtonica/curriculum#1243]
I believe that we can add an Elective Lesson on Ionic Mobile App Framework in Mobile Development.  As a Girlscript Summer of Code '2020 Participant, I would like to work on these issues and develop an elective lesson where we can learn Ionic.

**Comment by Kundan28** [comment]
@HarshCasper Could you please elaborate what would be the benefit of that lesson ?

**Comment by HarshCasper** [comment]
Ionic is a popular Mobile Development Framework which is powered by the Angular Web Framework, This lesson would be a follow-up for the Angular Lesson and be an elective resource to learn Ionic to build Mobile Apps using standard Web Dev Tools. In many cases, these lessons would be similar to React Native Lesson except for the thing that this would be an elective course. Therefore I believe that we can add an elective lesson on Ionic, which will give a brief exposure on Mobile App frameworks using Web Dev Tools.

**Comment by Kundan28** [comment]
I think this is a good issue, what do you think @alodahl @vegetabill

**Comment by vegetabill** [comment]
No, we'd prefer to improve what is already there rather than add more elective frameworks.

**Comment by Kundan28** [comment]
@HarshCasper Better to find some other issue and work on it once you are done with the issue you are currently assigned.
