### ISSUE TITLE
Create 'apprenticeship-prep' folder

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1250]
At the end of the classroom learning portion of the curriculum, the participants review topics that will help them in the start of their career.

Create a `apprenticeship-prep` folder and move the following lessons there:
- socioeconomic-differences/socioeconomic-differences.md
- financial-literacy/financial-literacy.md
- ethics/ethics.md
- underrepresented-in-tech-resources/underrepresented-in-tech.md
- navigating-new-codebases/navigating-new-codebases.md

Update all existing internal links to this content to point to the new location. If you happen to find an absolute link (http://github) then please replace it with a relative link.

**Comment by HarshCasper** [comment]
I want to take up this issue. Can you please assign me this issue @vegetabill 

I will be highly obliged.

**Comment by atrip10** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by Kundan28** [comment]
@HarshCasper You will be assigned to other issue after you are done with your PR.

**Comment by Kundan28** [comment]
@atrip10 Now you could start working on this issue.

**Comment by Kundan28** [comment]
@atrip10  You only have 5 days left, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Kundan28** [comment]
@atrip10 If we don't get reply from your side by tomorrow then someone else would be assigned to this issue.

**Comment by habeeba-naaz** [comment]
Please assign me this issue...I am interested to do

**Comment by Kundan28** [comment]
> Please assign me this issue if anyone else not working ..I am interested to do

You already have pending PR.
