### ISSUE TITLE
Update elective lessons and migrate all to /electives folder

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1256]
All lesson files listed in the root [README as electives](https://github.com/Techtonica/curriculum#optional--elective-lessons) move those files into a new `/electives` folder.
~SEO: Search Engine Optimization~
- [x] Sass
- [x] Python
~Datetime~
- [x] Data Visualization
- [x] Adding Chai/Mocha Tests to your project
- [x] MongoDB
- [x] Mongoose
- [x] Auth0
- [x] Memoization
- [x] Mobile Development
In addition, add the following files to the elective section in the README and also put them into the /electives folder:

~/agile-development (move the entire folder and all its lessons)~
~/deploying/deploying.md~
- [x] /web-patterns/web-patterns.md
- [x] /databases/database-migrations.md
- [x] /backend/1_intro_to_backend.md
- [x] /optimization/optimization.md

For all moved files, please update all links that exist in the curriculum already to point to their new location. If you any links that are absolute, e.g. use https://github... then convert them to relative links.

**Comment by abhu-A-J** [comment]
@vegetabill can I take it?

**Comment by vegetabill** [comment]
@abhu-A-J you can only work on one issue at a time. Did you already complete #1196 ?

**Comment by abhu-A-J** [comment]
Oops! I didn't realize #1195 was merged today. I was waiting for it and had no issues to work on. So that's the reason claimed this one. Okay, I'll get started on #1195. You can assign this to someone else . Sorry about that. :)

**Comment by FrozenGirl-spd** [comment]
Can you assign the task to me please?

**Comment by Kundan28** [comment]
@FrozenGirl-spd You are assigned to this issue, please start working.

**Comment by Kundan28** [comment]
@FrozenGirl-spd You only have 6 days let, if we don't get any response from your side, the issue will be assigned to someone else.

**Comment by Kundan28** [comment]
@FrozenGirl-spd If we don't get reply from your side within 2 days then someone else would be assigned to this issue.

**Comment by FrozenGirl-spd** [comment]
#1304 I tried to update the elective lessons and migrated all to /electives folder while reviewing readme.md as suggested.

**Comment by Kundan28** [comment]
> #1304 I tried to update the elective lessons and migrated all to /electives folder while reviewing readme.md as suggested.

You have to make the requested changes in the same PR itself, so I'm closing the new one.

**Comment by alodahl** [comment]
@vegetabill you think agile is an elective? Why isn't it as important as git?

**Comment by FrozenGirl-spd** [comment]
@alodahl  I have sent the PR according to the requested and suggested changes. Can you please check into it!! 
#1316

**Comment by alodahl** [comment]
You deleted all the branches... do you still want to work on this or should we give it to someone else?

**Comment by alodahl** [comment]
You are welcome to try another branch, @FrozenGirl-spd , just make sure this is the last one and don't delete it 😉

**Comment by FrozenGirl-spd** [comment]
Thankyou mam

**Comment by alodahl** [comment]
> @vegetabill you think agile is an elective? Why isn't it as important as git?

@vegetabill ?

**Comment by alodahl** [comment]
@vegetabill Question 2:  Is intro to backend an elective now because it's being replaced?  Just making sure backend isn't an elective in general 😛

**Comment by alodahl** [comment]
4/27/2020 Meeting notes:
- Keep Datetime
- SEO could be later once they first deploy to netlify, with a Google Site analyzer exercise.
- Agile lessons need to be way more practical and less theoetical. Make sure it includes MVP and prioritizing techniques.
- Deployment: maybe it needs to be updated or double-checked?

**Comment by alodahl** [comment]
changing this to medium, since we changed the ACs midstream.

**Comment by Kundan28** [comment]
> changing this to medium, since we changed the ACs midstream.

I've made changes in scoresheet accordingly.
