### ISSUE TITLE
Combine static web lessons into new /web folder

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1257]
Create a new folder `/web` and migrate the following lessons to it.

- html/html.md
- `/css/*`
- bootstrap/bootstrap.md
- `/jquery/*`
- /ajax/ajax.md
- /accessibility/accessibility.md

Note: For all moved files, please update all links that exist in the curriculum already to point to their new location. If you any links that are absolute, e.g. use https://github... then convert them to relative links.

**Comment by habeeba-naaz** [comment]
I am gssoc participant...interested to work on it.please assign me

**Comment by Kundan28** [comment]
@habeeba-naaz Now you could start working.

**Comment by habeeba-naaz** [comment]
Thank you for assigning

**Comment by Kundan28** [comment]
And please write `Fixes #issue_number` in the PR comments so that once your PR gets merged the issue will be closed automatically.

**Comment by habeeba-naaz** [comment]
Sure
