### ISSUE TITLE
Find and fix link for Assessment 9 objectives

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1264]
https://github.com/Techtonica/curriculum/blob/master/objectives/9.md

Task: Use search or logic to find the new url for the header link in the outline above. You can use the readme or the other assessment links in the objectives folder for guidance.

Make a PR with the fixed link. If the readme is wrong, fix that too.

**Comment by CipherGirl** [comment]
I would like to work on this

**Comment by abhu-A-J** [comment]
@alodahl may I work on this? I don't have any pending issue on me at the moment??

**Comment by CipherGirl** [comment]
I've raised a PR #1266. Please review.
