### ISSUE TITLE
Add "Why OOP in JS?" section to JS 7 - OOP

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1269]
In the [JS 7 OOP lesson](https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-7-oop.md) it doesn't really cover why one should learn OOP in JS, considering that JS code and libraries tend not to use OOP and instead skew more functional.

Look at the JavaScript section in the readme to be aware of what gets covered before this lesson.

Let's add a section immediately following "Motivation" called "Why learn OOP in JavaScript?". It should cover the following points:
- [ ] While not as popular in JS as some languages, React uses classes for its components (find link showing this)
- [ ] While its OOP style is unique, it shouldn't be considered second-rate and can be used to build good OOP code
- [ ] Participants will need to understand OOP for technical interviews and to learn other languages so it's good to learn it now
- [ ] Please find any blogs or videos explaining the benefits of OOP in JS

## Ensure inclusion of 
- dependency inversion
- Liskov substitution
- [SOLID](https://en.wikipedia.org/wiki/SOLID)

**Comment by habeeba-naaz** [comment]
I want to contribute...please assign me if possible

**Comment by abhu-A-J** [comment]
@vegetabill  I'll like to do these. I don't have any open issues

**Comment by mahakmandlecha** [comment]
please assign me this .

**Comment by KHMohit** [comment]
I am interested in working on this, please assign me

**Comment by Kundan28** [comment]
> I want to contribute...please assign me if possible

Please complete the issue which is already assigned to you then we could assign you to other one.

**Comment by Kundan28** [comment]
@mahakmandlecha You could now start working on this issue. And do keep in mind if you are not able to complete it within 2 weeks, the task will be assigned to someone else.

**Comment by mahakmandlecha** [comment]
okay. I will do that.

**Comment by lindes** [comment]
I don't know that I have too much to say on this at the moment, except that I watched a video recently that drew a comparison (bordering on equivalence) between functional and oop that y'all might find interesting... here's the talk: https://youtu.be/Y7StjYhXvpE

**Comment by alodahl** [comment]
Hi @mahakmandlecha , it has been 3 weeks and we do not see a PR.  Please respond to us about whether you are still working in it or if you need help.  If you are not, we'd like make this available to another volunteer.

**Comment by alodahl** [comment]
Assigning to meghanagottapu

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign this to me as part of GSSOC'20.

**Comment by Kundan28** [comment]
@Rukmini-Meda If this is your first contribution then please go through[ this ](https://bit.ly/2wQxqLy) and fill out the form. And after that you could start contributing to this issue. You could have a look at #1315 for reference and ping us you get stuck anywhere.

**Comment by Rukmini-Meda** [comment]
@Kundan28 This is not my first contribution. But this is the first issue I have taken up in this project. Do I have to fill that form in that case too?

**Comment by Kundan28** [comment]
> @Kundan28 This is not my first contribution. But this is the first issue I have taken up in this project. Do I have to fill that form in that case too?

Yes you have to fill that form. As I was asking about the contribution to this project.

**Comment by alodahl** [comment]
Hi @Rukmini-Meda, will you be able to make a PR for this in the next few days so we have time to review?

**Comment by Rukmini-Meda** [comment]
@alodahl I will make a PR by today. I have a question. Is there any problem if I dont fill the release form since I dont want to give the permission of posting my pictures and other stuff.

**Comment by alodahl** [comment]
All we know about you is your public GitHub profile at the moment, so the most we might do is share a list of contributors. Is that ok with you?  I think pictures generally apply to pictures we take at in-person events. But if you still disagree with signing it, I ask what I should do in those cases.  Go ahead and make your PR though; and thanks for your help!

**Comment by Rukmini-Meda** [comment]
> All we know about you is your public GitHub profile at the moment, so the most we might do is share a list of contributors. Is that ok with you? I think pictures generally apply to pictures we take at in-person events. But if you still disagree with signing it, I ask what I should do in those cases. Go ahead and make your PR though; and thanks for your help!

My contribution will be counted for GSSoC'20 right, even if I dont sign the release form.

**Comment by Kundan28** [comment]
> My contribution will be counted for GSSoC'20 right, even if I dont sign the release form.

Yeah, it will be counted.

**Comment by alodahl** [comment]
Hi @Rukmini-Meda, my director says please fill out the form, and we promise to remove your permissions so that you're not agreeing to the media release.  If there's anywhere in the form where you can be clear about that, write that as a note, too.  We just really need to keep track of how many people are volunteering; sorry that you can't progress through the form without checking that box.

**Comment by alodahl** [comment]
Hi @Rukmini-Meda, submit your PR as soon as possible so we can review it and still have time for changes before the deadline.

**Comment by Rukmini-Meda** [comment]
@alodahl Yes, I am working on it. I will make a PR by noon.

**Comment by Kundan28** [comment]
@Rukmini-Meda Last 5 hours are left in GSSoC20.

**Comment by Rukmini-Meda** [comment]
@Kundan28 I am sorry for being this late. I will make a PR right away.

**Comment by Kundan28** [comment]
> @Kundan28 I am sorry for being this late. I will make a PR right away.

Sure
