### ISSUE TITLE
The irony issue:  Proofread Eslint and Linting outlines

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1279]
Task:

- [ ] Proofread these two files for spelling and markdown:
  - javascript/eslint.md
  - linting/code-linting-eslint.md 
- [ ] Complete @vegetabill's requests made in this review: https://github.com/Techtonica/curriculum/pull/1244/files
- [ ] Change the titles of the two files to be more relevant - ie not exactly the same!

**Comment by Adyasha8105** [comment]
please assign this issue to me @alodahl

**Comment by KHMohit** [comment]
I am interested, please assign me

**Comment by Ashindustry007** [comment]
I am part of GSSOC and interested in this issue. Please, assign this issue to me.

**Comment by Tawishi** [comment]
I would like to work o this issue.

**Comment by Kundan28** [comment]
@Adyasha8105 Please sign up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_Hs‌Fwm0kjNOxtbtg/viewform?c=0&w=1‌ ) and start working on the issue.

**Comment by Kundan28** [comment]
@KHMohit @Ashindustry007 Please have a look to other open issues, as the issues are assigned on first come first serve basis.

**Comment by Kundan28** [comment]
> * linting/code-linting-eslint.md
> *

@alodahl This file don't exist as the stuff of that was moved to `javascript/eslint.md`

**Comment by Adyasha8105** [comment]
This issue solves in the PR #1300
