### ISSUE TITLE
Style Guide link shows #404 ERROR

### ISSUE THREAD

**Issue by Tawishi** [Techtonica/curriculum#1281]
### *The Style Guide link in the below image leads to #404 error.*

![issue#](https://user-images.githubusercontent.com/55306738/76748446-c8d43480-67a0-11ea-92fc-f3538e567ae5.jpg)

![issue1#](https://user-images.githubusercontent.com/55306738/76748568-033dd180-67a1-11ea-89e2-ad8f14928566.jpg)

**Comment by vegetabill** [comment]
@Tawishi thanks for taking the time to capture this error. Can you include a URL where your image came from?

**Comment by Tawishi** [comment]
> @Tawishi thanks for taking the time to capture this error. Can you include a URL where your image came from?

Yes. Here it is.
https://github.com/Techtonica/curriculum/blob/master/_templates/instructions.md

**Comment by alodahl** [comment]
> > @Tawishi thanks for taking the time to capture this error. Can you include a URL where your image came from?
> 
> Yes. Here it is.
> https://github.com/Techtonica/curriculum/blob/master/_templates/instructions.md

The link you provided is broken!

**Comment by alodahl** [comment]
I see - this should be https://github.com/Techtonica/curriculum/tree/master/_templates#instructions

**Comment by vegetabill** [comment]
@Tawishi I meant the page where that link is used, not the 404 link.

By searching the text in your image above, I found the page: [/CONTRIBUTING.md](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-1-gssoc-participants)

It should be updated to point to `_templates/` so it will show the README

**Comment by vegetabill** [comment]
@Tawishi since you are still working on #1189 I will leave this unassigned for 7 days so you can have the opportunity to work on it since you created it. After that I will open it up for anyone to work on it.

**Comment by rukaiya2000** [comment]
I would like to contribute to this.

**Comment by alodahl** [comment]
Hi @rukaiya2000, I will add you. Be sure to follow this contributing guide if this is your first Techtonica issue. https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md

**Comment by thisLinda** [comment]
I would like to work on this issue (or any easy/beginner labeled issue).

**Comment by Kundan28** [comment]
@rukaiya2000 Are you still working on this issue, please reply or someone else would be assigned to this issue.

**Comment by rukaiya2000** [comment]
Please assign this to someone else.

**Comment by Kundan28** [comment]
> Please assign this to someone else.

Sure.

**Comment by Kundan28** [comment]
@thisLinda Do you want to work on this issue ?

**Comment by thisLinda** [comment]
Yes I do!

**Comment by Kundan28** [comment]
Hi @thisLinda , I have added you. Be sure to follow this contributing guide if this is your first Techtonica issue. https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md

**Comment by thisLinda** [comment]
Completed 1281.

Researching this issue I found no links that lead to a 404 error. I checked the page that apparently had the error and all links are active. https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-1-gssoc-participants

New issue.
There is an error on this page with the last hyperlink ('template docs in this folder'). When clicked it leads to the current page. https://github.com/Techtonica/curriculum/tree/master/_templates#instructions

**Comment by Kundan28** [comment]
> Completed 1281.
> 
> Researching this issue I found no links that lead to a 404 error. I checked the page that apparently had the error and all links are active. https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md#step-1-gssoc-participants
> 
> New issue.
> There is an error on this page with the last hyperlink ('template docs in this folder'). When clicked it leads to the current page. https://github.com/Techtonica/curriculum/tree/master/_templates#instructions

@vegetabill

**Comment by Deeksha2501** [comment]
Is this issue still open? 
I would like to work on it.

**Comment by Kundan28** [comment]
> Is this issue still open?
> I would like to work on it.

@thisLinda is already assigned to this issue.

**Comment by thisLinda** [comment]
Kundan I emailed about the issue. There is no longer any issue with respect
to the 404--it seems to have been fixed--but I did find another. I didn't
do a pull request because there is no change to be made.

**Comment by Tawishi** [comment]
> Kundan I emailed about the issue. There is no longer any issue with respect to the 404--it seems to have been fixed--but I did find another. I didn't do a pull request because there is no change to be made.
> […](#)

@Kundan28 this is because I fixed the issue already. https://github.com/Tawishi/curriculum/commit/fbe2566c32890516a08b2b3615d526ca148c2cf8

**Comment by Kundan28** [comment]
> @Kundan28 this is because I fixed the issue already. [Tawishi@fbe2566](https://github.com/Tawishi/curriculum/commit/fbe2566c32890516a08b2b3615d526ca148c2cf8)

But you were not assigned to this issue and you have to create a PR for that instead of directly making the changes in master.

**Comment by Tawishi** [comment]
> @Tawishi since you are still working on #1189 I will leave this unassigned for 7 days so you can have the opportunity to work on it since you created it. After that I will open it up for anyone to work on it.

I did it cause of this comment and sorry, I forgot to create a PR.😔

**Comment by Kundan28** [comment]
> > @Tawishi since you are still working on #1189 I will leave this unassigned for 7 days so you can have the opportunity to work on it since you created it. After that I will open it up for anyone to work on it.
> 
> I did it cause of this comment and sorry, I forgot to create a PR.😔

I could understand but without PR you would not get the points for this.

**Comment by alodahl** [comment]
@Tawishi it looks like you committed to your own forked repo.  You still need to make a PR for this repo.

**Comment by Tawishi** [comment]
> @Tawishi it looks like you committed to your own forked repo. You still need to make a PR for this repo.

I am just figuring out how to squash the commits and remove the unnecessary ones.

**Comment by alodahl** [comment]
Alright.  We'll be in the lookout for a PR soon.

**Comment by thisLinda** [comment]
Following up on my messages of May 1 and May 8 (above), I did identify another issue which is defined in the first message.

I continue to be available to work on any easy/beginner issue if a gssoc20 participant is not able.

**Comment by alodahl** [comment]
@thisLinda  can you elaborate on the existing issue?  I thought you meant it didn't need to be fixed.

**Comment by thisLinda** [comment]
Issue #1281 had been fixed without a pull request as previously discussed. 

I checked all the links on the page and discovered a different issue [https://github.com/Techtonica/curriculum/tree/master/_templates](url). When you click on the very last link (a hyperlink: 'template docs in this folder') on the page it leads to the page it is already on rather than a different page.

> Okay I am ready to get started
Use the template docs in this folder.

**Comment by alodahl** [comment]
Thanks @thisLinda , but that is actually the intended functionality of readmes - to  be presented while you look at a parent folder. If you actually go to the [Readme](https://github.com/Techtonica/curriculum/blob/master/_templates/README.md) and click on that link, it should take you back to the _templates folder.

**Comment by alodahl** [comment]
Hi @Tawishi do you need any help?
