### ISSUE TITLE
Fix links in README.md file

### ISSUE THREAD

**Issue by Tahanima** [Techtonica/curriculum#1282]
https://github.com/Techtonica/curriculum/blob/master/README.md

Some of the links in the README.md file give 404 errors since the paths to the resources are incorrect. For example: **Whiteboarding** link under **Independent Topics**   

I am a GSSoC 20 participant and I would like to work on this issue.

**Comment by kichloo** [comment]
@vegetabill Can I take this issue?

**Comment by vegetabill** [comment]
@Tahanima thanks for opening this. I will look at your other PR and then I can assign this to you (as only one active issue at a time is allowed).

**Comment by kichloo** [comment]
Was it necessary to delete the comment? In most cases, it is seen that issues are given on FCFS basis and if one does not fix the issue, it is given to next one.

**Comment by vegetabill** [comment]
@kichoo as my comment said I reserved for the person who took the time to create it. I do not want others to pile on a bunch of noise comments asking to work on an issue. If you'd like to work on an issue, find one that is tagged as gssoc20 (this one was not).

**Comment by vegetabill** [comment]
@Tahanima I've assigned you this issue. Let me know if you have any questions.

**Comment by rukaiya2000** [comment]
I would like to contribute to this.
