### ISSUE TITLE
Replace code examples in sorting alogrithms with JS

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1284]
Currently [sorting.md](https://github.com/Techtonica/curriculum/blob/master/algorithms/sorting.md) uses Python code examples. We want to replace this with JavaScript.

- In addition there is a style typo near BogoSort

**Comment by goyalmuskan** [comment]
May I work on this issue? @vegetabill

**Comment by Kundan28** [comment]
> May I work on this issue? @vegetabill @Kundan28

Yes, you can start.
