### ISSUE TITLE
Fix broken link in Hash Table Topic Outline

### ISSUE THREAD

**Issue by lisaau** [Techtonica/curriculum#1286]
The last link in the supplemental method section of the [hash table topic](https://github.com/Techtonica/curriculum/blob/master/data-structures/hash-tables.md) (JavaScript implementation of Java's String.hashCode() method) has a broken link.

Also found another article that summarizes hash tables:
https://medium.com/javascript-in-plain-english/algorithm-in-javascript-hash-table-7b0464d2b81b

**Comment by vegetabill** [comment]
Thanks @lisaau

**Comment by Tahanima** [comment]
Hello,
I am a GSSoC20 participant and I want to contribute to this issue.

**Comment by kichloo** [comment]
@vegetabill Can I work on this issue?

**Comment by habeeba-naaz** [comment]
I am interested to contribute...please assign me if possible

**Comment by Kundan28** [comment]
@Tahanima @habeeba-naaz Your PR is not yet merged so I can't assign you to this issue.
@kichloo You are already assigned to other task.

**Comment by gauravdas014** [comment]
Please assign me this issue

**Comment by Kundan28** [comment]
> Please assign me this issue

I aasigned you to issue 1287

**Comment by kichloo** [comment]
@Kundan28 I have submitted by issue. Pl assign it to me now,

**Comment by Kundan28** [comment]
> @Kundan28 I have submitted my issue. Pl assign it to me now,

Another issue will only be assigned after the previous pull request is merged.

**Comment by Aman-Codes** [comment]
@Kundan28 Sir I am a GSSOC participant and I would like to work on it. This would be my first contribution in this project so please assign me this issue.

**Comment by Kundan28** [comment]
@Aman-Codes 

Thanks for volunteering to help Techtonica improve its curriculum! I have assigned you to this issue.

Please follow the contribution instructions in additional to any instructions from GSSoC.

Questions?
If you have any question about this issue and what contributions are being asked for, reply on this issue.
If you have questions about Git, Pull Requests, GitHub, or the contest itself, talk to a mentor (M) in Slack. Questions of that nature posted here will not be answered.
