### ISSUE TITLE
Create full stack app creation checklist

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1287]
Create new cheklist file in [/projects]( https://github.com/Techtonica/curriculum/tree/master/projects) folder.

This should be a detailed guide that lists how to create a PERN stack app from scratch.

- create-react-app UI app
- Express API node app
- Postgres database

A simplified form of it can be found in the [Animal Tracker](https://github.com/Techtonica/curriculum/blob/master/projects/mern-pern-project.md#im-having-trouble-starting) assignment. Please turn this into a full document with code snippets.

## Repository Layout

Include notes about the best way to include a react client and its API in one repo. The simplest way we found in H1-2020 looked like this:

```
├── .gitignore
├── README.md
├── react-client
│   ├── README.md
│   ├── build
│   ├── coverage
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── public
│   └── src
├── index.js // Defines the Express server
├── lib // any modules needed by the Express API server
├── seed-data.sql
└── package.json
```

This works well with Heroku if you add this script to your package.json:

```json
"scripts": {
  "heroku-postbuild": "npm install --prefix react-client && npm run build --prefix react-client"
}
```

And in your Express app in `index.js`

```js
/* FOR HEROKU-DEPLOYMENT */
if (process.env.NODE_ENV === 'production') {
  app.use(express.static('react-client/build'));
  app.get('*', (req, res) => {
    res.sendfile(path.resolve(__dirname, 'react-client', 'build', 'index.html'));
  });
}
```
For a working example, see [Moodify](https://github.com/ari-os310/Moodify)

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by habeeba-naaz** [comment]
I am interested to work...please assign me this if possible

**Comment by Kundan28** [comment]
> I am interested to work...please assign me this if possible

Sorry to say but your PR is not yet merged.

**Comment by habeeba-naaz** [comment]
Yes...but it’s already approved by one reviewer ...so I am free to do this issue..Please try to assign..I am interested to do..this issue..from this issue I can learn a lot,it’s good opportunity for me

**Comment by Kundan28** [comment]
> Yes...but it’s already approved by one reviewer ...so I am free to do this issue..Please try to assign..I am interested to do..this issue..from this issue I can learn a lot,it’s good opportunity for me

At least 2 mentors has to approve it.

**Comment by gauravdas014** [comment]
Please assign me this issue.

**Comment by Kundan28** [comment]
You could now start working on this issue @gauravdas014

**Comment by gauravdas014** [comment]
Thank you! How much time  am I alloted for this?

**Comment by Kundan28** [comment]
Two weeks.

**Comment by gauravdas014** [comment]
Sir, I was assigned the issue 1287 , but I have realized I am not much experienced for that issue, I am not a pro in backend so I will not be able to complete it, please deassign the issue, so that others can work on it. I am really very sorry for that.

**Comment by habeeba-naaz** [comment]
@alodahl specified changes in my previous issue and I did that changes...she told to comment on another issue...she told she’ll merge that Issue ASAP. So please if possible assign me this issue?

**Comment by Kundan28** [comment]
@habeeba-naaz You could start working on this issue.

**Comment by habeeba-naaz** [comment]
Thank you @Kundan28

**Comment by habeeba-naaz** [comment]
Can I take any example to create PERN stack example from scratch? Or only Animal Tracker assignment only?

**Comment by Kundan28** [comment]
> Can I take any example to create PERN stack detailed guide from scratch? Or only Animal Tracker assignment ?

@alodahl @vegetabill

**Comment by habeeba-naaz** [comment]
Once please answer below question:

Can I take any example to create PERN stack detailed guide from scratch? Or only Animal Tracker assignment ? @vegetabill  @alodahl

**Comment by alodahl** [comment]
@habeeba-naaz  I think Bill means that you can use the animal tracker as a starting point. Based on the description, I'm thinking that this should be topic-agnostic, and should simply list what any basic PERN app needs. @vegetabill is that correct?

**Comment by habeeba-naaz** [comment]
I thought to implement a basic PERN stack app example with screen shots..which includes steps to build

**Comment by Kundan28** [comment]
> I thought to implement a basic PERN stack app example with screen shots..which includes steps to build..is it right?

@alodahl

**Comment by alodahl** [comment]
@habeeba-naaz yes, sorry I missed this for so long.  Having steps to build a basic PERN stack app example with screen shots sounds perfect.  For the screenshots, can add them and the directions to a new slideshow from a copy of this template?: https://docs.google.com/presentation/d/1uFlV8eVrPtwjb4wPoUCd7Fk3PNqf1Eoo9mZ-_7D3_GQ/edit#slide=id.p

Please let me know yes or no if you are still willing to work on this issue.

**Comment by habeeba-naaz** [comment]
Sorry...please unassign me...got some other work to do...please assign this to anyone interested

**Comment by lemon-yellow** [comment]
Hi - I am available to work on this issue.

**Comment by alodahl** [comment]
Hi @lemon-yellow, sorry I missed this. Are you still interested?

**Comment by lemon-yellow** [comment]
Sure, please assign this task to me!
