### ISSUE TITLE
Suggestion for  the data structure slideshow.

### ISSUE THREAD

**Issue by cadence09** [Techtonica/curriculum#1290]
I suggest at the beginning of the slideshow to have a video goes through stack, linked list, and queue with a simple code illustration before just jumped in to talk about different types of data structure with a silent video. The concept of each type of data structure is straight forward, but it would give more sense to apprentices to see a video of a simple data structure implementation. And a silent video may deliver information less effective.

https://github.com/Techtonica/curriculum/blob/master/data-structures/intro-to-data-structures.md

**Comment by alodahl** [comment]
Do you think it would help if the Crash course video should go before the slideshow?

**Comment by vegetabill** [comment]
I think a silent video isn't really a useful resource so can we find a replacement with narration?

**Comment by vegetabill** [comment]
@cadence09 can you suggest a replacement your group found?
