### ISSUE TITLE
Add SRE (site reliability engineer) to roles in tech

### ISSUE THREAD

**Issue by jonah-williams** [Techtonica/curriculum#1293]
Could we include SRE or similar operations roles as a career path in week 1's [Roles in Tech](https://github.com/Techtonica/curriculum/blob/master/career/roles-in-tech/roles-in-tech.md) and week 13's [Career Week](https://github.com/Techtonica/curriculum/blob/master/README.md#week-13---career-week)?

**Comment by vegetabill** [comment]
@jonah-williams thanks for capturing this. Sure, especially if you are one and can add the material 😃

**Comment by vegetabill** [comment]
@jonah-williams just curious is this a role an intern could do? Not having done it myself, I'd imagine you'd need a ton of system arch and networking understanding.

**Comment by jonah-williams** [comment]
@vegetabill Like every other role I think it really depends on the organization but yes, I think it's reasonable to consider interns for roles on SRE teams.

Alice Goldfuss has a nice blog post on getting into SRE and what these roles can look like: https://blog.alicegoldfuss.com/how-to-get-into-sre/
