### ISSUE TITLE
Create new lesson on Working & Collaborating Remotely

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1295]
It was already a useful skill but now is vital in these times.

## Requirements
- Use the [lesson template](https://github.com/Techtonica/curriculum/tree/master/_templates) to create a lesson
- The new lesson should be placed in the `/career` folder
- For activities/practice on this, have the participants try out popular free screen sharing software to pair program on some code to see the challenges

**Comment by vegetabill** [comment]
It should be easy to find resources buzzing about on Twitter at the moment. Even if you're not an engineer, you should be able to find general resources and then add a few geared towards pair programming remotely

**Comment by datadaveshin** [comment]
I'll try this one

**Comment by datadaveshin** [comment]
Hi - I'm ready to put in a PR, but appears the repo has been reorganized. Previously, it was to go into the `career/` folder, where should I place the document?

**Comment by vegetabill** [comment]
@datadaveshin thanks for asking. I think `/career` is still the right place. Thanks for checking.

**Comment by datadaveshin** [comment]
Let me know if there are any concerns, editing, etc. to do. Also, I'm not familiar with how these lessons are taught.

**Comment by vegetabill** [comment]
Thanks @datadaveshin !
