### ISSUE TITLE
[tmdb] Part 1: React read-only app

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1297]
_Child task of Epic #1296_

For the current cohort's full-stack assessment, we used this [minimal codebase](https://github.com/Techtonica/full-stack-assessment-h1-2020). Using that as inspiration, please create Part 1 lesson, where the student will use React to make a read-only app with in-memory data.

## Requirements

 In a new lesson file in the `/projects/tmdb` folder called `part-1-readonly-react.md`

### App setup step(s)
- Include start instructions for using [create-react-app](https://github.com/facebook/create-react-app)
- Add a small intro section on reactstrap (and the difference between, say, `<button>` and `<Button>`

### Test Data Step(s)
- Instead of coming from an API & DB call, include the creation of some test data as a hardcoded array in `App.js`
  - stick with `snake_case` for attribute names and just tell them to go with it for now, even though they were used to `camelCase`

### Create components
- Based on the UI in the example app, above, create step-by-step instructions to create the `<MovieList>` and `<Movie>` components (read-only)
- these should be class-based components, not functional

### Optional challenges
- Add optional challenge to the exercise of having a dropdown with different kinds of in-memory sorts for the list
  - by release_date, oldest first
  - by release_date, newest first (default)
  - by title, A-Z
- Add another optional challenge to have a fallback image for movie if there is no poster url included in the data

### Troubleshooting section
- Beginners are often confused when a syntax error breaks rendering of the page
  - Remind them to read errors carefully and commit often when things are working, so they can do a git diff and see what changed
- Suggest installation of the React dev tools browser plugin

**Comment by vegetabill** [comment]
Child task issue of Epic #1296

**Comment by ashishnagpal2498** [comment]
Can I work on this issue ?

**Comment by Kundan28** [comment]
> Can I work on this issue ?

Please wait for the #1333 to get merge, after that you will be assigned to other tasks.

**Comment by pa7ri** [comment]
hi @Kundan28, can I work on this issue?

**Comment by ashishnagpal2498** [comment]
Okay , but I have given the PR for the issue #1333 .

**Comment by Kundan28** [comment]
> Okay , but I have given the PR for the issue #1333 .

Sorry to say but you have to wait for it to get merged.

**Comment by vegetabill** [comment]
wont-fix
