### ISSUE TITLE
Add 3 common technical coding questions to tech-interviewing lesson

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1298]
The challenge example questions in the [technical interviewing lesson](https://github.com/Techtonica/curriculum/blob/master/career/interviewing/technical-interviewing.md#challenge) are not really the kind of questions you'd be asked in a tech interview.

Please replace them with some relatively short technical interview questions. Problems should be language independent.

**Comment by jamesjose03** [comment]
@vegetabill I would like to take up this issue.

**Comment by kichloo** [comment]
@vegetabill I have submitted all my issues. Pl assign this issue!

**Comment by Adyasha8105** [comment]
@vegetabill please assign this issue to me

**Comment by AbhipsaGuru1012** [comment]
@vegetabill I would like to take this issue up.

**Comment by vegetabill** [comment]
@jamesjose03 I have assigned you this issue. Just to confirm, are you part of gssoc20?

Please follow the [Contributor](https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md) instructions and ask any questions here.

**Comment by jamesjose03** [comment]
@vegetabill Yes I am a participant of gssoc20. Thank you for assigning this issue to me.

**Comment by shwhite17** [comment]
assign this issue to me please? @vegetabill
