### ISSUE TITLE
Add ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Aman-Codes** [Techtonica/curriculum#1302]
@alodahl @vegetabill I am a GSSOC participant and I would like to add an issue template folder with bug report, feature request and pull request template
### Bug report
![bug report](https://user-images.githubusercontent.com/54680709/77220483-80cd5d00-6b66-11ea-8685-2751fa20c0c2.PNG)

### Feature Request
![feature request](https://user-images.githubusercontent.com/54680709/77220495-98a4e100-6b66-11ea-8197-e72016d126c0.PNG)

### Pull Request
![pull request](https://user-images.githubusercontent.com/54680709/77220497-9c386800-6b66-11ea-9d0a-72820d72a239.PNG)

**Comment by vegetabill** [comment]
Thanks for the idea but we don't need something like that in our project. But we'd love if you want to contribute to one of our existing issues.
