### ISSUE TITLE
detail-oriented issue:  format & proofread CSS_in_React slides

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1306]
Task: format & proofread these CSS_in_React slides. https://docs.google.com/presentation/d/15SRalCJq0HaZ7O8LIngmDVqxDSU0GBVzOhpF1Q0eQOw/edit?usp=sharing
Request edit access with a note explaining that you are trying to solve this issue.

Related to: #1258 

 - [ ] format the above slideshow to the 2020 Slides Template standards. Make a copy to your own drive to have access to the styles.
- [ ]  also make sure it follows the style rules described here:  #600 

- Other things to notice:
  - [ ] Fix odd capitalizations you find, like "Used" on slide 6. Make sure all slide headers are consistently capitalized. Right now one is all lowercase while another is all upper.
  - [ ] Fix code example indentation
  - [ ] Use consistent image and text positioning and margins.
  - [ ] Make sure proper names are capitalized - ex. `React`, not `react`.
  - [ ] Change sentence structures if they are run-on or hard to read.
  - [ ] Official spelling:  Is Bootstrap capitalized or not?  What is the proper way to format inline CSS?  Inline-CSS?  Research and change if necessary.

 Once you've completed this, make a PR of any typo in this project, and link this issue in the PR to receive GSSoC points.
For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by Adyasha8105** [comment]
I just want to work on this issue @alodahl

**Comment by alodahl** [comment]
@Adyasha8105 would you still like to work on this issue?

**Comment by HeroicHitesh** [comment]
@alodahl Assign this to me if it's still up-for-grab.

**Comment by HeroicHitesh** [comment]
> Also, provide request access I have requested for it.

@alodahl please provide edit access of slides also. I have requested it 2 days ago. And sent a request now again.

**Comment by alodahl** [comment]
Can you send me your gmail address in Slack?  I don't seem to be receiving those requests through google.

**Comment by alodahl** [comment]
@MichelleGlauser Can you please move this into our slides folder so someone can work on this someday?  Not urgent, but no one has access to this one.

**Comment by alodahl** [comment]
This issue is still relevant, and it looks like we do have access to the slides now.

**Comment by HeroicHitesh** [comment]
@alodahl Sorry, for the delayed response. I have resolved this issue and created a PR. Have a look at it and let me know if anything needs to be updated.
