### ISSUE TITLE
[React] Add lesson outline: React Part 2 

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1308]
_This is a child issue of Epic #1301_

For new lessons, use the [lesson v2 template](https://github.com/Techtonica/curriculum/blob/master/_templates/lesson-v2.md) after reviewing the [lesson instructions](https://github.com/Techtonica/curriculum/tree/master/_templates) 

## Prereqs
They have learned about React, JSX, and props.

## Objectives to Cover in this Lesson
- Component state (only cover class-based components, not hooks)
- Compare & contrast props and state
- Why you should not directly mutate state, e.g. `this.state.count++`
  - i.e. how state relates to the re-rendering 
- The code in this lesson should be simple. We should not need `create-react-app`. Codepen or similar is preferred

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue.

**Comment by annu12340** [comment]
Can I work on this issue

**Comment by Kundan28** [comment]
> Can I work on this issue

@ashishnagpal2498 is already assigned to this issue. You could only work on the issue which are not assigned to anyone and you could comment there that you want to work and once you are assigned to that issue you could start working.

**Comment by annu12340** [comment]
ok
