### ISSUE TITLE
Format Techtonica Slideshows

### ISSUE THREAD

**Issue by Kundan28** [Techtonica/curriculum#1318]
This single-contributor task is to ensure all Techtonica-owned slideshows have the same styles and formatting. This a simple task, but may take a while! Some of these are already formatted, but your job is to double-check or make changes.

Check the box next to the slideshow once it is ready.
Message Alina(@alodahl ) the numbers of any slideshows that are locked to editing, and she will unlock them for you.
Here is an example of a slideshow with correct formatting. https://docs.google.com/presentation/d/1ANf64yQ_Nxtul45xofh8cpjWF23UM6c8m8kJQHQyx_Q/edit?usp=sharing
Notice:

Each slide has the Techtonica logo & bar at the bottom
The accepted text colors are black, gray, and custom turquoise
All text is in Lato font
Headers are at size 28 font, while regular text is either 18 or 24(preferred), with the exception of footnotes/side notes

- [x] 1. https://docs.google.com/presentation/d/1USOZJSzwXmSYepjwrE9r9ky_fmQ8VPE7bshjsBoDsZM
- [x] 2. https://docs.google.com/presentation/d/1S3BjcLZNjex2_qiA9MdyJOjWZ_qmJ78STbUeDEyHH_8
- [x] 3. https://docs.google.com/presentation/d/1viDJyLHXVs-VioUEatvWHDZeOCCmPxZNPHzH0C393rg
- [x] 4. https://docs.google.com/presentation/d/1N2eDw84BqmcqvNDjtQfNEF_7PO91z-IHTR44QXt3-oI
- [x] 5. https://docs.google.com/presentation/d/1Dcu1q3W3hZIkk0Wa1mG3KBK75vzY2peFel5WNgNyqN0
- [x] 6. https://docs.google.com/presentation/d/1-TEyN4TTjP9c9WGcThS1jQmVoY4pG-xt9gjbDhJkUTc

**Comment by FrozenGirl-spd** [comment]
Can i work on this?

**Comment by Kundan28** [comment]
> Can i work on this?

Wait for it to get reviewed by project admin. And you have a pending PR.

**Comment by alodahl** [comment]
Yes @FrozenGirl-spd you have your work cut out for you fixing your PR.  Ask about what you are specifically trying to do in #git_github, and you will receive help.

**Comment by Kundan28** [comment]
@kichloo You want to work on this ?

**Comment by kichloo** [comment]
@Kundan28 @alodahl Can I take up this issue?

**Comment by Kundan28** [comment]
> @Kundan28 @alodahl Can I take up this issue?

You could now start working, I've already made the comments in the slide where changes are required but check each and every thing.

**Comment by kichloo** [comment]
@Kundan28 I have some questions:
1. The title/ first page should also be modified?
2. The code snippet is in a different font. Should it be modified too?

**Comment by kichloo** [comment]
https://docs.google.com/presentation/d/1N2eDw84BqmcqvNDjtQfNEF_7PO91z-IHTR44QXt3-oI/edit?disco=AAAAJP0Z0vU
Changing the code to 18/24 would not be feasible and the text is set to 18

**Comment by kichloo** [comment]
1. https://docs.google.com/presentation/d/1USOZJSzwXmSYepjwrE9r9ky_fmQ8VPE7bshjsBoDsZM
  2. https://docs.google.com/presentation/d/1S3BjcLZNjex2_qiA9MdyJOjWZ_qmJ78STbUeDEyHH_8
  3. https://docs.google.com/presentation/d/1viDJyLHXVs-VioUEatvWHDZeOCCmPxZNPHzH0C393rg
  4. https://docs.google.com/presentation/d/1N2eDw84BqmcqvNDjtQfNEF_7PO91z-IHTR44QXt3-oI
  5. https://docs.google.com/presentation/d/1Dcu1q3W3hZIkk0Wa1mG3KBK75vzY2peFel5WNgNyqN0
  6. https://docs.google.com/presentation/d/1-TEyN4TTjP9c9WGcThS1jQmVoY4pG-xt9gjbDhJkUTc

**Comment by kichloo** [comment]
@Kundan28 @alodahl Done

**Comment by Kundan28** [comment]
> https://docs.google.com/presentation/d/1N2eDw84BqmcqvNDjtQfNEF_7PO91z-IHTR44QXt3-oI/edit?disco=AAAAJP0Z0vU
> Changing the code to 18/24 would not be feasible and the text is set to 18

Okay

**Comment by kichloo** [comment]
@alodahl @Kundan28 Pl review the PR
