### ISSUE TITLE
Create short lesson on JS / React /Function modularity + best practices.

### ISSUE THREAD

**Issue by lizandry** [Techtonica/curriculum#1320]
Please make a 30 -60 minute lesson on JS / React modularity. The shorter the better, as long as the most important points are covered.  The basic goal is to demonstrate a few correct ways that React projects are structured, with examples. Maybe an activity can be a scavenger hunt for similar things in differently organized React projects.

Use this template and put your new outline in the javascript/ directory: https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md

- Link our new _import export_ outline as a prereq if it exists by the time you take up this issue. At time of writing, it is in progress. #1221
 
- Be aware that they will be getting [this Navigating New Codebases](https://github.com/Techtonica/curriculum/blob/master/apprenticeship-prep/navigating-new-codebases.md) lesson a few weeks later.  Don't be redundant, but if you feel you need something that is stated there, you may move that point into your new outline, and link a reference to its new spot in the new-codebases outline.

- if you think of some best practices that are relevant, but you feel they would be better in another outline (like Liz's loop example being a quick FYI during a JS basics lesson instead) feel free to change another file. Better yet, put it in that other file and link to it in your new outline as you are listing things to look out for.

- Hands-on exercises & challenges are best.
_____
Original Feedback:

There currently isn't a lesson (or a series of lessons?) that covers the transition between writing most of your code in one or two files, and having a neat, modular codebase. A walkthrough for when it's time to start a new file, as well as how to move a segment of code without losing its functionality, would be an enormous help around or a little after the React-Eventonica project.

Best practices for how professional codebases are typically structured and explicit information about common variables that'd we'll be expected to use in the workplace (ie a for-loop nearly always uses an i, a nested for-loop uses a  j), so we can get an early start, would also be enormously helpful.

**Comment by vegetabill** [comment]
@alodahl I'm not sure what is best to do with this. I wouldn't really know what to include so it feels too open-ended for gssoc. I feel like this may be material that is learned over time with experience, like OOP. Everyone learns require but knowing when and how to split functionality is not only challenging but it has very little consensus other than broad approaches like MVC. Thinking back to the original feedback around this, this was a reaction to encountering multi-file codebases and being lost.

**Comment by alodahl** [comment]
@vegetabill  I've added some clarity to the description, and am making it available for gssoc just in case someone can do it.

**Comment by urbashi123** [comment]
Can I work on this issue? @alodahl

**Comment by urbashi123** [comment]
I have to make a lesson on JS? @alodahl

**Comment by alodahl** [comment]
@urbashi123 yes, a very short one that's just about how react and js projects are commonly structured, so that apprentices are not surprised when they see a new codebase.
