### ISSUE TITLE
Create Advanced JS folder

### ISSUE THREAD

**Issue by annu12340** [Techtonica/curriculum#1328]
I found that many important topics like  Closures, hoisting, destructing, Higher Order Functions, Error Handling, etc are missing in the current curriculum. I would like to include them in a new section called advanced-js

Mentors, can I go ahead with this issue as a part of Gssoc

**Comment by vegetabill** [comment]
Almost all of the those topics are covered, with the possible exception of hoisting. Where did you look to see what was covered?

**Comment by annu12340** [comment]
I was not able to find topics like arrow fn, Template literals, Strict Mode, Object Prototypes, Event Bubbling and Capturing, Inheritance , Scope,  Currying,  Callback Function, OOP in JavaScript, call() , apply() and bind() etc

**Comment by alodahl** [comment]
I'm 100% sure that map filter reduce,  promises and try/catch, scope, OOP are already in the curriculum.  Arrow function is definitely included, although I don't know if it has been explicitly explained.  I never ever ever use call() , apply() and bind(), but if others think these are widely used and important, go ahead. We are explicitly leaving prototypes out, unless Bill thinks its a good advanced topic.

Here is our table of contents just in case it helps you see what we currently cover: https://github.com/Techtonica/curriculum/blob/master/README.md#week-3---javascript-fundamentals

**Comment by annu12340** [comment]
Thanks
