### ISSUE TITLE
A good source for implementing auth0 in React

### ISSUE THREAD

**Issue by cadence09** [Techtonica/curriculum#1329]
I suggest to add this source https://auth0.com/blog/authenticating-your-first-react-app/ to auth0 topic outline (https://github.com/Techtonica/curriculum/blob/master/oauth/o-auth.md). This is easy to follow along and clear as well.

**Comment by vegetabill** [comment]
Awesome thanks @cadence09

**Comment by Tahanima** [comment]
Hello,
I am a GSSoC'20 participant and I would like to work on this issue.

**Comment by saloniankita23** [comment]
Kindly assign me this issue. I would like to work on it.

**Comment by vegetabill** [comment]
@Tahanima I've assigned you. @saloniankita23 issues are assigned first-come-first-served so please find one that someone else hasn't commented on already.

**Comment by vegetabill** [comment]
@cadence09  this has been added. if you further suggestions, please open more issues! 😄

**Comment by Tahanima** [comment]
@Kundan28 can you please check whether the score has been updated in the score sheet for this issue?

**Comment by Kundan28** [comment]
> @Kundan28 can you please check whether the score has been updated in the score sheet for this issue?

I apologies, I've updated it now.
