### ISSUE TITLE
Fix these dead links

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1332]
Task: read through these notes describing the repo’s broken links, and repair or replace them.

react-js/react-hooks.md
15:12-15:93 warning Link to unknown file: version-control/git-version-control/git-version-control.md. Did you mean ../git-version-control/git-version-control.md missing-file remark-validate-links
***NO SUCH LINK anywhere in repo
redux/redux.md
***these LINKS ARE ALL ACTIVE but they are in react-js/react.md file (redux/redux.md no longer exists)

Note: Some  of the security links were fixed in #1397 
 the Activision link is old.
roles-in-tech/security.md
3:1-3:53 warning Link to unknown file: \roles-in-tech\security-locks.jpg missing-file remark-validate-links
***link now in career/roles-in-tech/security.md BAD/INCOMPLETE LINK for .jpg
17:268-17:383 warning Link to https://www.thenetworkpro.net/2010/04/02/why-is-computer-security-important/ is dead no-dead-urls remark-lint
***no such link appears to have been replaced with another, similar link
65:30-65:139 warning Link to https://wanguolin.github.io/assets/cryptography_and_network_security.pdf is dead no-dead-urls remark-lint
***NO SUCH LINK anywhere in repo
140:7-140:78 warning Link to https://www.themuse.com/jobs/eventbrite/security-engineer is dead no-dead-urls remark-lint
***DEAD LINK, now in career/roles-in-tech/security.md
148:78-148:175 warning Link to https://www.cloudflare.com/learning/security/glossary/what-is-penetration-testing/ is dead no-dead-urls remark-lint
***NO SUCH LINK anywhere in repo
196:3-196:48 warning Link to https://twitter.com/Mikab0nita is dead no-dead-urls remark-lint
***DEAD LINK, now in career/roles-in-tech/security.md
199:3-199:58 warning Link to https://live.ncsc.gov.uk/information/about-ncsc is dead no-dead-urls remark-lint
***DEAD LINK, now in career/roles-in-tech/security.md

**Comment by abhu-A-J** [comment]
@alodahl Ma'am May I?

**Comment by shreyakapoor08** [comment]
can I work on it? @alodahl

**Comment by annu12340** [comment]
Can I work on this issue

**Comment by Kundan28** [comment]
@abhu-A-J You could start working on this issue.

**Comment by abhu-A-J** [comment]
> @abhu-A-J You could start working on this issue.

Okay Sure! Thank you!

**Comment by Kundan28** [comment]
@abhu-A-J If I don't get any response from your side within 24 hours then I will unassign you from this issue.

**Comment by abhu-A-J** [comment]
> @abhu-A-J If I don't get any response from your side within 24 hours then I will unassign you from this issue.

Sir, you may assign to someone else. It's a very tedious task and due to my exams I won't be able to give time to it

**Comment by Kundan28** [comment]
> > @abhu-A-J If I don't get any response from your side within 24 hours then I will unassign you from this issue.
> 
> Sir, you may assign to someone else. It's a very tedious task and due to my exams I won't be able to give time to it

Okay, no problem.
Keep coding and I'm pretty sure you would be the top performer of GSSoC20. As your current score is 575, and I think no one is near you.

**Comment by FrozenGirl-spd** [comment]
@Kundan28  Can i work on this?

**Comment by Kundan28** [comment]
> @Kundan28 Can i work on this?

Sorry but your PR is not yet merged. If I get any message from Project Admin I'll assign you.

**Comment by shubkaushik** [comment]
@Kundan28 , is this still an open issue ? if yes can i try it ?

**Comment by Kundan28** [comment]
@shubkaushik  If this is your first contribution to this project then please go through [this ](https://bit.ly/2wQxqLy) and fill out the form. And after that you could start contributing to this issue.

**Comment by alodahl** [comment]
Hi @shubkaushik, will you be able to make a PR for this in the next few days so we have time to review?

**Comment by shubkaushik** [comment]
Sure, @alodahl, working on this, will complete it earliest

**Comment by Kundan28** [comment]
> Sure, @alodahl, working on this, will complete it earliest

Do remember that we only have 6 days left in GSSoC20

**Comment by alodahl** [comment]
Hi @shubkaushik, submit your PR as soon as possible so we can review it and still have time for changes before the deadline.

**Comment by Kundan28** [comment]
@shubkaushik Last 5 hours are left.

**Comment by marcobarrera** [comment]
Is this issue still open? If so, may I work on it?

**Comment by Kundan28** [comment]
@alodahl Could I work on this issue ?

**Comment by alodahl** [comment]
@marcobarrera could you please leave a comment on each of the listed links in the description to help us review.  Were some of them unnecessary to change?  If so, why?

**Comment by alodahl** [comment]
Hi @marcobarrera , are you still working on this? If I don't hear from you, I will make the issue available to other volunteers.

**Comment by marcobarrera** [comment]
Hi, yes I've just been a bit busy, but I will finish this assignment.

**Comment by GazKris** [comment]
I would like to work on this if it's available.

**Comment by CoderCarrot** [comment]
I am happy to work on all remaining dead links in the curriculum, too.

**Comment by alodahl** [comment]
Thank you @CoderCarrot !    Let us know if you have any questions.
