### ISSUE TITLE
Create a folder for ML concepts

### ISSUE THREAD

**Issue by annu12340** [Techtonica/curriculum#1334]
I would like to create a folder on ML concepts that would be focusing on both the theory in ML and its implementation.  I thought of covering all the fundamentals in ML like different types of Machine Learning, Linear and Logistic Regression, different types of cost function, optimization techniques,  Under-fitting & Over-fitting, Regularization, Hyper-parameters, Cross-Validation, basis of CNN etc

**Comment by vegetabill** [comment]
We're not interested in expanding the scope of our curriculum at this time, as we'd prefer to increase the quality and depth of existing topics.
