### ISSUE TITLE
Add mini-lesson on spread operator

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1335]
## Topics to Cover
- [x] varargs in function params
- [x] before and after examples of building new arrays using slice
- [ ] how this relates to following an immutable coding style to always create new objects and never modify arrays in place
- [ ] show adding an item
- [ ] show removing an item
- [ ] Independent practice should include converting some existing code to use spread as well as writing some original code

A good mini-lesson is the one on [destructuring](https://github.com/Techtonica/curriculum/blob/master/javascript/destructuring.md) for an idea of length and format.

- [x] This mini-lesson should also go in the `javascript` folder.

**Comment by urbashi123** [comment]
I want to work on the issue. Can you assign me?

**Comment by alodahl** [comment]
@urbashi123 sure!  Be sure to follow https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md before starting.

**Comment by urbashi123** [comment]
Ya sure. I will follow all the steps.
