### ISSUE TITLE
React Part 4 - Apps

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1337]
_Child task of Epic #1301_

The previous three lessons covered props, state, and component hierarchies. This will build on that to create a TODO list app with an in-memory data store, meaning all data will be lost on full page refresh. But we want to reinforce the existing content before getting into async/ajax.

Use our [Lesson Template v2](https://github.com/Techtonica/curriculum/blob/master/_templates/lesson-v2.md)

## Topics to Cover
- How to use `create-react-app` to create a skeleton app
  - A brief note as to why it's so complex / slow but that it's nice with live-reload etc
- Guided practice should be a TODO list app
- Once you have created the entry form and a way to mark items complete, add additional features as independent practice. This is the perfect time to differentiate the mastered data vs. a temporary array used for the active display
  - filtering completed out
  - different sorts, A-Z, Z-A, `creationDate` ASC or DESC
  - display the creationDate nicely using `moment`, which can cover how to add packages
- Independent practice can also include deploying to Heroku with the CRA build-pack

This lesson should go in the `./react-js/react-part-4-apps.md` and a link added to the main README.md along with the other React lessons.

**Comment by HarshCasper** [comment]
I would like to work on this issue @vegetabill

**Comment by annu12340** [comment]
I would like to work on this issue. Could you assign it to me?

**Comment by Kundan28** [comment]
> I would like to work on this issue @vegetabill

You could now start working, I've assigned you to this issue.

**Comment by darkmatter18** [comment]
@vegetabill @Kundan28 If noone is working on it, please assign me

**Comment by Kundan28** [comment]
> @vegetabill @Kundan28 If noone is working on it, please assign me

As you can see above @HarshCasper is assigned to this issue.

**Comment by HarshCasper** [comment]
@vegetabill @Kundan28 Due to some commitments on other issues, I am not able to resolve this issue. Kindly unassign me with this issue.

**Comment by Kundan28** [comment]
> @vegetabill @Kundan28 Due to some commitments on other issues, I am not able to resolve this issue. Kindly unassign me with this issue.

Sure

**Comment by marcobarrera** [comment]
May I work on this issue?

**Comment by vegetabill** [comment]
Looking at what's done on the Eventonica & React epics, this is the next most important item so starting it now
