### ISSUE TITLE
Improve and update "Deploying to Heroku" outline.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1339]
**Recent curriculum feedback:**
"Deploying is always hard. On this week’s surveys, in response to “What suggestions do you have for improving Techtonica’s apprenticeship program?“: “a clearer/easier to follow demo for deploying apps on Heroku.”

https://github.com/Techtonica/curriculum/blob/master/deploying/deploying.md

## Tasks:
- Update, improve, and make our deploying outline as easy to follow as possible, with as little guesswork or assumptions as possible. 
- Assess existing links and videos, and feel free to replace with better ones. 
- Request edit access for the included Techtonica Deploying slideshow and make the same improvements there. It could be a lot more relevant than it is now - consider skipping info about containers, etc if it's not immediately useful to someone deploying a small simple React App.

**Comment by vegetabill** [comment]
@alodahl thanks for capturing this. It's definitely a need! But I think this is too vague or advanced for gssoc until we break it down further. I can do that this week sometime.

**Comment by vegetabill** [comment]
@alodahl Can I have some more ctx on the feedback/motivation for this? The lesson seems fine to me and accurate (without going through the whole thing, anyway). This is a case where a participant would need to open a very specific improvement idea if some part wasn't working.

**Comment by alodahl** [comment]
@vegetabill sorry for the delay.  I added this issue because Michelle asked me to, but I have no more context than you.  For that reason I made an issue to review it and see what we can do.
