### ISSUE TITLE
Add lesson on HTML forms

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1343]
Use our [v2 lesson template](https://github.com/Techtonica/curriculum/blob/master/_templates/lesson-v2.md)

# Prereqs
- [HTML lesson]()

## Concepts to Cover
- Common form elements
  - text
  - select
  - checkbox
  - date
- validation attributes
- Submit and action (for non-ajax forms)

## Guided Practice
Build a simple form with a few of the validations

## Independent practice
Learn about what happens when a form is submitted. Are there echo/debug servers that can print out what is submitted to the server?

Target location: `/web/html-forms.md`

**Comment by shreyakapoor08** [comment]
can I work on it?

**Comment by Kundan28** [comment]
> can I work on it?

Yeah, I have assigned you to this issue. Now you could start working.

**Comment by Kundan28** [comment]
@shreyakapoor08 You only have 2 days left, if we don't get reply within this period then someone else would be assigned to this issue.

**Comment by shreyakapoor08** [comment]
@Kundan28 Sure, I will update you by tomorrow night

**Comment by Kundan28** [comment]
> @Kundan28 Sure, I will update you by tomorrow night

Thanks!

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign as part of GSSOC'20.

**Comment by Kundan28** [comment]
> I would like to work on this issue. Please assign as part of GSSOC'20.

@shreyakapoor08 is already assigned to this issue, so kindly have a look at the issue which is not assigned to anyone.

**Comment by shreyakapoor08** [comment]
@Kundan28 @vegetabill Do I have to add the lesson in the slide and give the link to it in the md file like it is done in html.md or do the explanation part in the md file only ?

**Comment by Kundan28** [comment]
Nothing is mentioned about the slides above by @vegetabill , so for now do the explanation part in the md file itself until we get any reply from @alodahl or @vegetabill .
@alodahl Could you please guide us on this if we need to create slides or not ?

**Comment by vegetabill** [comment]
Please create the md file as requested. The slides are not part of this issue.

@Kundan28 this issue was assigned 14 days ago. I think it should go to someone else as others have expressed interest while it sits idle. Please reassign it.

**Comment by shreyakapoor08** [comment]
> Please create the md file as requested. The slides are not part of this issue.
> 
> @Kundan28 this issue was assigned 14 days ago. I think it should go to someone else as others have expressed interest while it sits idle. Please reassign it.

I am in the middle of doing it. Will complete it by tomorrow. Sorry for the delay.
I have raised the PR till where i have done

**Comment by Kundan28** [comment]
> @Kundan28 this issue was assigned 14 days ago. I think it should go to someone else as others have expressed interest while it sits idle. Please reassign it.

She is working on this, so do I've assign someone else ?
