### ISSUE TITLE
Review Agile Lessons

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1350]
Agile/ lessons need to be way more practical and less theoretical. Make sure they include MVP and prioritizing techniques.

Write any issues necessary to update the outlines.

**Comment by vegetabill** [comment]
Thanks for creating this @alodahl

**Comment by vegetabill** [comment]
I'm not sure where to go with this. Let's have @timirahj review these lessons and weigh in later.

**Comment by vegetabill** [comment]
Closing as others in the future may have different opinions on the content.
