### ISSUE TITLE
Proofread, clarify, and update Deploying with Heroku outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1351]
Proofread, clarify, and update Deploying with Heroku outline:
https://github.com/Techtonica/curriculum/blob/master/deploying/deploying.md

Please make sure:
- [ ] The language is as clear as possible for someone who is deploying a site to heroku for the first time, and deploying a full-stack app for the first time ever.
- [ ] Make sure all Heroku directions and resources are not out-of-date -- replace them if they are. either way, feel free to replace with better ones.
- [ ] Make sure any updates are also applied to the slideshow linked in the outline. (Request edit access)
- [ ]  It could be a lot more relevant than it is now - consider skipping info about containers, etc if it's not immediately useful to someone deploying a small simple React App.

**Comment by kichloo** [comment]
I want to work on this issue!

**Comment by Kundan28** [comment]
@kichloo Now you could start working on this issue.

**Comment by anirudh-kac** [comment]
I'd like to work on this

**Comment by Kundan28** [comment]
@anirudh-kac Someone else is already assigned to this issue. Please have a look at other one.
