### ISSUE TITLE
Fixing HTML validator errors in index.html

### ISSUE THREAD

**Issue by Castella1313** [Techtonica/curriculum#1355]
Aims to fix HTML validator issues shown in w3c html validator.
screenshot:
![Screenshot 2020-05-07 at 8 23 09 PM](https://user-images.githubusercontent.com/53293156/81309690-d91dd700-90a0-11ea-991e-4a42745079d5.png)

**Comment by Castella1313** [comment]
Is this a valid issue?

**Comment by vegetabill** [comment]
@Castella1313 I don't really understand the above screenshot. Is this file in our repo?

If you're talking about our website, Techtonica.org, it has a separate repo and is not part of GSSOC. Feel free to open the issue in its repo if you want: https://github.com/Techtonica/techtonica.org

**Comment by Castella1313** [comment]
@vegetabill I am just trying to verify the HTML code of index.html in w3c validator.
https://validator.w3.org
