### ISSUE TITLE
Create a venture capitalism topic outline in the roles in tech folder

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#1357]
- [ ] Start with this template:https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md
- [ ] Create a new file in the roles-in-tech folder
- [ ] Use the other files in that folder for references.  The goal is not to learn venture capitalism, but to learn the basics of what it is, what steps one should take to begin a career, and where they can learn more. It take be 30-45 minutes max.
- [ ] Include these resources:
https://backstagecapital.com/cover/books/
https://backstagecapital.com/together/
https://www.amazon.com/Its-About-Damn-Time-Underestimated/dp/0593136411
https://www.indie.vc/faq
https://www.atomico.com/introducing-the-atomico-angel-programme/

**Comment by kichloo** [comment]
Having done the "Workspace" topic, I can do this one!

**Comment by alodahl** [comment]
Hi @kichloo, submit your PR as soon as possible so we can review it and still have time for changes before the deadline.

**Comment by vegetabill** [comment]
@MichelleGlauser what was the motivation driving inclusion of this topic? At first glance, this seems fairly distant from the core and I'd love volunteer hours to go toward deepening the core rather than adding new topics like these.

**Comment by MichelleGlauser** [comment]
@vegetabill We had two participants ask about it and a few supporters offer. Don't worry about making it the top priority.

**Comment by vegetabill** [comment]
@MichelleGlauser can you refer the supporters to this issue then? If there is an actual owner, that would ensure it would have a better chance of getting done.

**Comment by vegetabill** [comment]
Still suggest this be closed as wontfix. It feels more like an optional reading article about "What Series A means" or something. I'm still not sure why this is worth adding and what the audience wanted but maybe the potential owners could speak to that.

**Comment by alodahl** [comment]
@MichelleGlauser do you have strong feelings about this one?  Otherwise, I don't mind closing it.
