### ISSUE TITLE
Revise React Part 2 lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1359]
This issue requires basic markdown and React knowledge.

https://github.com/techtonica/curriculum/blob/master/react-js/react-part-2.md

- [x] on line 81, fix the example from using this.state to this.setState.
- [ ] Correct any grammar mistakes
- [x] Correct any md mistakes
- [x] Correct any code mistakes

**Comment by nandanasreeraj123** [comment]
Can i do it?

**Comment by Kundan28** [comment]
@nandanasreeraj123  If this is your first contribution then please go through [this](https://bit.ly/2wQxqLy) and fill out the form. And after that you could start contributing to this issue.
