### ISSUE TITLE
Fix links in Deploying with Heroku outline

### ISSUE THREAD

**Issue by Kundan28** [Techtonica/curriculum#1363]
Fix links in Deploying with Heroku outline
https://github.com/Techtonica/curriculum/blob/master/deploying/deploying.md

Tasks:

- [x] Change `deploying.md` file name to `deploying-to-heroku.md`
- [x] Remove one video link with the label `Why use Node.js?` from Supplemental Materials in `node-js.md` file.
- [x] Add `A free Heroku account` under prerequisites in `deploying.md` file and it should redirect to `https://signup.heroku.com/dc`.

**Comment by supu2701** [comment]
@alodahl @Kundan28 
May I work on this issue please

**Comment by alodahl** [comment]
Sure @supu2701 !  Be sure to follow these directions before you start if this is your first Techtonica issue: https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md

**Comment by supu2701** [comment]
@alodahl @Kundan28 
There are two video links with label "Why use Node.js?" in node-js.md file: https://github.com/Techtonica/curriculum/blob/master/node-js/node-js.md
which one should I remove.
![node js](https://user-images.githubusercontent.com/58454886/82289756-19475880-99c3-11ea-934e-1e9f3da5c883.JPG)

**Comment by supu2701** [comment]
> @alodahl @Kundan28
> There are two video links with label "Why use Node.js?" in node-js.md file: https://github.com/Techtonica/curriculum/blob/master/node-js/node-js.md
> which one should I remove.
> ![node js](https://user-images.githubusercontent.com/58454886/82289756-19475880-99c3-11ea-934e-1e9f3da5c883.JPG)

@Kundan28 @alodahl 
Please help me out regarding which video link should I remove

**Comment by Kundan28** [comment]
> Please help me out regarding which video link should I remove

It's all up to you. You have to figure out which one is more useful.

**Comment by supu2701** [comment]
@alodahl @Kundan28 
Please review the pull request and merge it if found suitable.
