### ISSUE TITLE
Find suitable HTML form resources for beginners 

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1364]
**Task**:  Find suitable HTML form resources for beginners.

Add a link to each independent practice topic in [this file](https://github.com/Techtonica/curriculum/blob/master/web/html-forms.md) that clearly explains it for beginners.

The result should look like this:

Independent Practice
Spend 15 minutes answering these questions alone or with a partner.  Use the links provided for more info.

What happens when an HTML form is submitted?: [Name of blog or resource](link)
Are there echo/debug servers that can print out what is submitted to the server?: [Name of blog or resource](link)

**Comment by imanishbarnwal** [comment]
Hello, @alodahl I want to work on this issue but can you please explain more about this like where to add the link and which link? Thank You!

**Comment by alodahl** [comment]
The task is to find links suitable for beginners to learn the topic.  The section is at the bottom of this outline: https://github.com/Techtonica/curriculum/blob/master/web/html-forms.md

**Comment by imanishbarnwal** [comment]
> The task is to find resources suitable for beginners to learn the topic. The section is at the bottom of this outline: https://github.com/Techtonica/curriculum/blob/master/web/html-forms.md

Okay, so I need to add some good resources in Supplemental materials for beginners to practice or sharp their learnings right.

**Comment by alodahl** [comment]
No, we need a resource within Independent Practice to address each of these:
What happens when an HTML form is submitted?
and 
Are there echo/debug servers that can print out what is submitted to the server?:

**Comment by imanishbarnwal** [comment]
> No, we need a resource within Independent Practice to address each of these:
> What happens when an HTML form is submitted?
> and
> Are there echo/debug servers that can print out what is submitted to the server?:

Ohh got it. So there I have to put some good resources available on the internet right.

**Comment by alodahl** [comment]
Yes thank you!  Just one or two valuable ones.

**Comment by imanishbarnwal** [comment]
@alodahl I just added few useful resources kindly check them and let me know if it's fine. Thank You!!
