### ISSUE TITLE
find and list any instances of jQuery code or documentation in the project

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1366]
Context:  We are considering teaching vanilla JS instead of jQuery to beginners.

Task:  find and list any instances of jQuery code or documentation in the project with line and file path. If it is the entire file or most of it, don't bother with the lines =)

To receive GSSoC points, make a PR with any single typo or formatting fix and link the issue.  Once we believe the jQuery issue has been resolved, we will merge your PR and make it official.

Related to epic #1296

**Comment by HeroicHitesh** [comment]
@alodahl I am working on it will send a PR soon.

**Comment by Kundan28** [comment]
> @alodahl I am working on it will send a PR soon.

@HeroicHitesh I am glad to see your work. But you have to wait for the mentors or admin to assign you to a particular issue and then you have to start working on that issue. So I think you would keep track of it from next time.

**Comment by HeroicHitesh** [comment]
Actually I am in a hurry to get as many points as I can so, wasn't able to control myself😅 since, I am late in starting this GSSoC's contribution and have limited time remaining.
> So I think you would keep track of it from next time.

I will keep this in mind.😁

**Comment by Kundan28** [comment]
> Actually I am in a hurry to get as many points as I can so, wasn't able to control myself😅 since, I am late in starting this GSSoC's contribution and have limited time remaining.

I like you dedication to score more points. Best of luck for the contribution, you are 1099 behind from the top contributor.

**Comment by HeroicHitesh** [comment]
> I like you dedication to score more points. Best of luck for the contribution, you are 1099 behind from the top contributor.

Where can I see my score of contributions to all the GSSoC projects in which I am contributing?

**Comment by Kundan28** [comment]
> Where can I see my score of contributions to all the GSSoC projects in which I am contributing?

Currently you have to search manually at https://www.gssoc.tech/profile.html by entering username of individuals.
