### ISSUE TITLE
Create a vanilla JS lesson modeled after our jQuery one

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1367]
Task: Create a JavaScript - HTML DOM Methods lesson modeled after our jQuery one.

Do not change the jQuery file; rather:
-  create a new file in web/ called js-dom-methods.md, 
- copy the contents of this [intro to jQuery](https://github.com/Techtonica/curriculum/blob/master/web/jquery.md) outline, 
- and then replace the content with JS DOM methods info instead.  
- Of course, if there are basics you think they should know about JS DOM methods please add them, and if there is nothing that corresponds to a detail about jQuery in vanilla JS, you can just remove that part.

Related to epic #1296

**Comment by Mighty-Geek** [comment]
I would like to work on this issue.

**Comment by alodahl** [comment]
Thanks @Mighty-Geek ! If this is your first Techtonica contribution, be sure to follow these directions and then you can start: https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md

**Comment by vegetabill** [comment]
@Mighty-Geek thanks for the contribution!
