### ISSUE TITLE
complete partial modularity in JS and React lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1375]
Someone got a start on fixing #1320, but it should be one outline, not two, and should simply be about modularizing code, and how a project can be structured differently. It should also be very short and exploratory.

There will likely be be additional content needed, but move anything useful from these two files into a new file with a proper lower-kebab-case name, and then delete these:
/javascript/JavaScript-React-Modularity.md
/javascript/React_JavaScript.md

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md

**Comment by chrisjaure** [comment]
@alodahl I can pick this up. Is it still valuable?

**Comment by Yosolita1978** [comment]
Hi @chrisjaure! yes, you can still help us with this!
