### ISSUE TITLE
Rename master branch to mainline

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1378]
Although it's less obvious, the `master` branch default name is derived from `master/slave` so we want to rename it to not draw on that legacy. For more details, see [Gnome archive](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html).

Let's rename `master` => `mainline`

**Comment by vegetabill** [comment]
@alodahl take a look at this when you have a moment. As soon as the current cohort wraps, it would be a good time to make this change.

**Comment by alodahl** [comment]
@vegetabill I'd love to change the name; we are doing it at work as well.  Would `main` be a good alternative to `mainline`, or has the decision been made?

**Comment by alodahl** [comment]
Here are directions a friend sent to me last month:

You might have heard that GitHub decided to abandon the term master.
 
If you’re interested in changing your default branch naming from master to main, we wanted to share with you the steps to do so:
 
    •    Create a new branch from master and name it main
    •    Replace every reference to master branch in your code for main. Push it to GitHub. 
    •    In GitHub, go to settings -> branches -> and update the default branch 
    •    In CI, replace every reference to master branch for main.  
    •    Trigger your seed job. Pipeline now should be reading from main branch. 
    •    Last but not least - If you have any open PRs, edit them and change the base branch to be main

**Comment by alodahl** [comment]
Complete!  No merging required.
