### ISSUE TITLE
Add activity for simple session management

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1379]
We jump right to oauth which handles everything for you. It would be beneficial to have manual cookie assignment so the apprentices understand that HTTP is stateless and what a _session_ means.

This could probably be incorporated into Eventonica

**Comment by alodahl** [comment]
We could - this is important stuff to know, but I would definitely consider this intermediate, so I am skeptical as to whether it fits into our 6-month curriculum.
