### ISSUE TITLE
Remove unnecessary steps in our relational DB lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1380]
Split from #1202 

The relational DB lesson is far too lengthy. It should introduce some basics, ensure the participant has installed and can successfully use Postgres, and leave the rest of it up to the other lessons, e.g. [SQL Part 1](https://github.com/Techtonica/curriculum/blob/master/databases/sql-1.md)

Edit this file:
[/databases/relational-databases.md](https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md)

### Items to Remove
- [x] Remove `difference of MySQL vs PSQL` article - as we're not going to use MySQL this is a useless article
- [x] remove example companies and replace with an infographic about use of SQL vs NoSQL databases
- [x] SQL dialects
- [x] ORM's
- [x] Modeling data (covered in other topics)
- [x] Remove LucidChart database example and links
- [x] Remove "Users of databases" - it's also a confusing terminology
- [x] Replace "verb" with "operator" for the query actions - "verb" is not standard terminology
- [x] remove LIMIT examples
- [x] remove JOIN - that's a later topic
- [x] remove the second type of INSERT (where column order is named)
- [x] Remove DDL section
- [x] remove "advantages of relational" section
- [x] foreign key constraints
- [x] Remove all of the mistakes / misconceptions

**Comment by iamdhruvsharma** [comment]
I would like to work on this.

**Comment by alodahl** [comment]
Thank you @iamdhruvsharma!  If this is your first time contributing, please complete these steps first, since we're a non-profit that needs to keep track of volunteer work.  https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md. Let us know if you have questions.

**Comment by iamdhruvsharma** [comment]
Thank you for assigning this task.

**Comment by iamdhruvsharma** [comment]
For "Infographic about SQL vs NoSQL databases"I can use any source from the internet?

**Comment by iamdhruvsharma** [comment]
I done with all the things except  **LucidChart database**  and **Infographic** . Please tell me little more about how you want me tackle LucidChart links.

**Comment by alodahl** [comment]
@iamdhruvsharma sorry if the description is not clear, but this issue is about carefully removing unneeded content from the lesson.  You're welcome to submit a PR if the bulleted tasks are done.  Then if you are interested, you can also pick up #1202 , which it sounds like you may have started already.

**Comment by alodahl** [comment]
Ok, after looking at the lesson regarding Lucidcharts, I think we need you to delete any links that include the "lucidchart" url, and then use your judgement to delete/edit the sections that they're in if they no longer make sense.  I think this is because they all discuss DB Models, which we already have a separate lesson for, so bringing it up here is not relevant enough.

**Comment by iamdhruvsharma** [comment]
Thanks for the clarification. While, I was reviewing the file, I found that many times Lucidcharts links were mentioned and the area of discussion was around the database models (covered in different section) so I have removed them strategically. Please have a look and do let me know for any other issues.
