### ISSUE TITLE
Add note that .env only works when loaded by an NPM module

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1382]
The dot env lesson doesn't mention you need to use a NPM module to automatically load a `.env` file.

[dot-env lesson](https://github.com/Techtonica/curriculum/blob/master/command-line/env.md)

**Comment by vegetabill** [comment]
@alodahl believes this might be automatic but when I spent 5minutes trying it, it did not work.

**Comment by alodahl** [comment]
I tried it again without a dotenv package, and it works.  Did you do the whole lesson?  I wrote it so that the first attempt doesnt work, and then provide the solution.

**Comment by vegetabill** [comment]
Ah, I hadn't read the whole thing. I thought there was some magic. Basically, we're just sourcing the file, which has nothing to do with its name `.env` or anything else so I don't think there's any action to take here.
