### ISSUE TITLE
Store corpus of code challenges as part of this repo

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1384]
Currently they are locked up in REPL.it. Should we store some/all of them here?

A few them are available in a subfolder of the [private SEAM repo](https://github.com/Techtonica/techtonica-seam/tree/mainline/code-challenges).

## Pros
- Can ask for improvements to them from volunteers
- Outside readers can use them as a resource
- Most questions are leaked all over so there aren't secret ones anymore
- We can host all of them here, since not all are used in the program

## Cons
- Syncing with repl.it would be annoying...maybe maybe they have an API?
- Are they somewhat secret? Other bootcamps have theirs as secret insider info

**Comment by alodahl** [comment]
1. If apprentices are smart enough to google the answer, more power to them.
2. The challenges are on record in our Google Doc called "Interview Prep (with Coding Challenges)". I can email you the link.
3.  They're not really "secret", but those not enrolled wont get on the mailing list. I can't remember if they are public or not once they're "published".

**Comment by alodahl** [comment]
4.  All of the lettered challenges are mine, and they should be in that doc.  If they aren't that just means I'm behind 😬

**Comment by alodahl** [comment]
5. Can I pretty please have access to the SEAM repo?

**Comment by alodahl** [comment]
6.  The solutions are definitely secret.

**Comment by vegetabill** [comment]
@alodahl I granted you access. The repo link above was actually a 404 not for access reasons but now you also have access 🙂

**Comment by vegetabill** [comment]
Thanks for sharing that doc, @alodahl. Sounds like this ticket should be edited to:

1. problems and test cases should be moved to this repo
1. reference solutions can stay in SEAM private/REPL.it

Does that sound right?

**Comment by alodahl** [comment]
Saving the example solutions sounds great.   

Saving example problems in Techtonica/curriculum seems low-priority, the only advantage being centralization.  I suppose it would give non-enrolled users access as well. But we have a lot more pressing things to do before this can happen. Maybe it can be broken into 2 tickets so the example solutions are backed up first.

**Comment by vegetabill** [comment]
Hmm, sounds like might not be worth doing. If we're sticking with repl.it, and you didn't find the management of the problems in repl.it too onerous, I'd say this should just be closed then. How was the effort in setting them all up for this cohort?

FWIW, [repl.it has GitHub integration](https://blog.repl.it/github) but the ad copy makes it sound like a one-way operation, so not necessarily that helpful for our challenge/classroom format.

**Comment by alodahl** [comment]
Getting all the problems and solutions into the replit took about a year.  Once they are in, though, it takes about an hour to sync them to be published according to the new calendar and add the new apprentices to the mailing list. Correcting existing problems has been pretty easy.

**Comment by vegetabill** [comment]
Sounds good then. Closing for now. We'll stick with repl.it.
