### ISSUE TITLE
Add information about DOM events to DOM lesson

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1386]
In the [JS DOM methods lesson](https://github.com/Techtonica/curriculum/blob/master/web/js-dom-methods.md) there isn't background knowledge about DOM events.

During interviews, participants were asked about events and didn't know much about them outside the context of React.

## Topics to Add
- DOM event basics
- [`.addEventListener` function](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)
- Event bubbling and propagation
- Add practice exercise that has the participant add console logging to see how events propagate

**Comment by Mu-C00L** [comment]
I want to work on this issue.

**Comment by alodahl** [comment]
Thank you @Mu-C00L ! If this is your first time contributing, please complete these steps first, since we're a non-profit that needs to keep track of volunteer work. https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md. Let us know if you have questions.

**Comment by AbhipsaGuru1012** [comment]
@vegetabill @alodahl Hi, can I work on this issue?

**Comment by alodahl** [comment]
Yes please! Let us know if you have questions.

**Comment by AbhipsaGuru1012** [comment]
Okay sure. Thank you!

**Comment by AbhipsaGuru1012** [comment]
@alodahl do you have any preferences where I should add the practice exercise on event propagation?

**Comment by alodahl** [comment]
@AbhipsaGuru1012 You can add it as one of the Guided Practice activities.  Feel free to use existing online tutorials too, as long as its free and cited in the outline.

**Comment by AbhipsaGuru1012** [comment]
@alodahl I have made the pull request. Please review and suggest if any changes have to be made.

**Comment by alodahl** [comment]
Closed by #1395
