### ISSUE TITLE
Update our "Deploying to Heroku" outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1389]
(Created from https://github.com/Techtonica/curriculum/issues/1358)
Things to fix:

Techtonica Slides: 
- [x] Deploying Slide 6, FYI, refers to only PAAS and IAAS, video on slide 7 refers to SAAS, PAAS, and IAAS.
- [x] remove Slide 14 Rackspace video is dead link/null.
- [x] Slide 18 Links are not clickable (because they are in Google docs), copied links active for all except #3 to Digital Ocean which is a 404 error. Replace or remove.

Outline:
- [x] Remove references to Video "The Deploy Node.JS Apps to Heroku" 
- [x] In place of the video, add directions to:
- go to. https://devcenter.heroku.com/ and notes the various languages Heroku supports and 
- click "Get Started" OR they can click on Node.js. Both options will bring them to https://devcenter.heroku.com/articles/getting-started-with-nodejs which is the tutorial.

**Comment by alodahl** [comment]
Fixed #1389 in this commit: https://github.com/Techtonica/curriculum/commit/088ed5d22134af7e5be763813f693147ef18486c

**Comment by thisLinda** [comment]
Since I'm already working on the issue which in turn created this issue I would like to work on it.

**Comment by alodahl** [comment]
Thanks @thisLinda but I finished this yesterday!
