### ISSUE TITLE
[Eventonica] Expand the steps in Express API part

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1425]
The Express backend steps are very brief and could benefit from additional detail. Go through and add more detailed steps and example snippets as you see fit.

The lesson is currently in https://github.com/Techtonica/curriculum/blob/main/projects/eventonica/eventonica-part5-express-backend.md

If you want you can use [expandable section syntax](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) to add snippets.

**Comment by alodahl** [comment]
by "should be changed to part 4.", do you mean parts 5-7 need to be renamed to being parts 4-6?

**Comment by alodahl** [comment]
Then a new testing outline will be number 7?

**Comment by vegetabill** [comment]
@alodahl yes that's right. I tried to revise the desc above to be clearer

**Comment by vegetabill** [comment]
Closing

We are intentionally leaving these instructions without examples as the participants should have already gone through practice, e.g. https://github.com/Techtonica/curriculum/blob/main/projects/minimal-api-project.md
