### ISSUE TITLE
Find new resources to replace these defunct links

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1434]
The unchecked links below are out-of-date.  Find a replacement link that would be a good resource in context.

- [x] algorithms/intro-to-algorithms.md line 34 & 35.
- [ ] git/git-version-control.md line 173.
- [x] react-js\react-part-3-component-hierarchies.md 
  - 94:1-94:66  warning  Link to https://codepen.io/annu12340/pen/WNQGBjy?editors=1010
   - 197:1-197:66  warning  Link to https://codepen.io/annu12340/pen/wvKowmj?editors=1010 is dead                                                                                   no-dead-urls  remark-lint
    - 254:1-254:53  warning  Link to https://codepen.io/annu12340/pen/QWjqrwO is dead  

- [x] web\html.md
      -  75:3-75:96  warning  Link to https://www.girldevelopit.com/materials/inter-html is dead
       ***The material/repo for the link is here: https://github.com/girldevelopit/gdi-featured-html-css-intermediate, but the link itself has not been fixed yet.

- [x] personal-brand\personal-branding.md
     28:67-28:219  warning  Link to https://blocktogether.org/show-blocks/5867111278318bd542293272f75147f8fc5931bea431e7ca16e9242964965d66494a6fb68f3518b82f171bcf0e419ccc

**Comment by CoderCarrot** [comment]
In reference to point 5: I can't find a public block list or block bot that isn't outdated or buggy (from what I can tell without trying them out one by one). Also, Twitter depreciated their import block list functionality. There is a [Chrome extension](https://chrome.google.com/webstore/detail/twitter-block-chain/dkkfampndkdnjffkleokegfnibnnjfah?hl=en) that will block the followers of a Twitter account, so the link could be changed to the [Twitter account for the block list](https://twitter.com/ggautoblocker?lang=en) itself as well as the extension and they can be used together. 
_Also_, Twitter has now come out with a functionality that allows you to [choose who can reply to your public tweets](https://www.forbes.com/sites/johnbbrandon/2020/01/09/twitter-just-announced-a-new-way-to-combat-trolls-but-only-if-they-are-stupid/?sh=1a7664124258). So this could replace the block list or be added on top of the block list (advising them the post such that only the people they follow can reply). 
I could workup a PR for these changes, depending on which you think are appropriate. Just let me know!

**Comment by alodahl** [comment]
Thank you so much for looking into that!  I was wondering if the whole idea was outdated.  Would you mind replacing that part with the one "that allows you to choose who can reply to your public tweets" ?

Shall I assign this issue to you @CoderCarrot ?

**Comment by CoderCarrot** [comment]
Sure! And then if anyone else wants to help, I would welcome it. Haha.

**Comment by alodahl** [comment]
The bad links in react-js\react-part-3-component-hierarchies.md are being fixed in https://github.com/Techtonica/curriculum/pull/1442.

**Comment by CoderCarrot** [comment]
@alodahl I believe 1 and 2 were fixed in a previous PR not attached to this issue. At the very least, there are no longer dead links in those areas, so you might be able to close the issue.

**Comment by alodahl** [comment]
Thanks for double-checking 🎉
