### ISSUE TITLE
build break into DOM manipulation md lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1467]
several of the participants have mentioned that the DOM manipulation lesson is very long, ~and that they believe it would have been better to schedule it before assigning the game project~. Some also suggested splitting it up into two lessons. The other option is to build an explicit break into the middle somewhere.

update: ive completed the “move in curriculum” portion. i will open this up to volunteers unless i get to it sooner.

### Main Goals

- Split the existing DOM manipulation lesson into two separate lessons
- Create an explicit break in the middle of the lesson content

### Acceptance Criteria

- Identify natural breaking points in the current DOM manipulation lesson content
- Create a clear separation between the two lessons
- Ensure continuity of learning objectives across both lessons
- Maintain logical flow of concepts within each lesson
- Update instructor notes and student materials accordingly

**Comment by ChasVanDav** [comment]
May I take this issue? @daaimah123

**Comment by daaimah123** [comment]
@ChasVanDav I have assigned you to the issue and added the acceptance criteria

**Comment by ChasVanDav** [comment]
thank you! :) @daaimah123

**Comment by daaimah123** [comment]
Please audit the following, it looks like this may have been broken up already

https://github.com/Techtonica/curriculum/blob/main/projects/recipe-page/phase-4-DOM-Manipulation.md

https://github.com/Techtonica/curriculum/blob/main/web/js-dom-methods.md

**Comment by ChasVanDav** [comment]
@daaimah123 To echo our conversation over Slack, this issue's pr will be reviewed by @thisIsTheWei on Monday (12/30) and will be ready for your final review!
