### ISSUE TITLE
[Eventonica] Replace Event Recommender with Eventonica

### ISSUE THREAD

**Issue by carbonsoda** [Techtonica/curriculum#1475]
In Eventonica's starter code (in [the folder](https://github.com/Techtonica/curriculum/tree/main/projects/eventonica/starter-code) +[Part 1](https://github.com/Techtonica/curriculum/blob/main/projects/eventonica/eventonica-part1-objects.md#starter-code)) the three main classes are  `Eventonica`, `Event`, and `User`.

In Part 1's starter code description and in all other parts, the text refers to the three main classes as `EventRecommender`, `Event`, and `User`. 

Given the changed description in 2f4affaaedc4819754c9a6cbba22f7129803386e and original files' starter code cf1ba07d97688d25dfbb645129b6857d47db0e06, should all mentions of `EventRecommender` be updated to `Eventonica`?

**Comment by naomiquinones** [comment]
Thanks @carbonsoda, I believe @vegetabill is looking into these updates.

**Comment by vegetabill** [comment]
@carbonsoda I'm not directly looking into this issue quite yet. A PR for a find & replace of these would be appreciated but if not I'll get it queued up soon. Thanks for reporting!
