### ISSUE TITLE
Improve promise example in JS -9 Async Lesson 

### ISSUE THREAD

**Issue by aedward8** [Techtonica/curriculum#1491]
https://github.com/Techtonica/curriculum/blob/main/javascript/javascript-9-async.md

JS Code snippet: https://github.com/Techtonica/curriculum/blame/main/javascript/javascript-9-async.md#L94-L124

I found the second example after 5. in guided practice a bit confusing. It was unclear to me for a while that there are in fact 2 promises in this example . I think it would be helpful to include comments in the example code and a description before or after the example going through what happened. It might also be helpful to see a video walk-though/voice over explaining the code line by line!

**Comment by vegetabill** [comment]
Snippet: https://github.com/Techtonica/curriculum/blame/main/javascript/javascript-9-async.md#L94-L124
