### ISSUE TITLE
Wrong video slide walkthrough -JS - 7 -OOP

### ISSUE THREAD

**Issue by aedward8** [Techtonica/curriculum#1516]
The current Lesson slide video walkthrough is for a previous lesson and not this one.

https://github.com/Techtonica/curriculum/blob/main/javascript/javascript-7-oop.md

**Comment by parbindersingh** [comment]
I can update the slide video walkthrough for you. Can you share the link to the JavaScript VII video ?

**Comment by parbinder** [comment]
I can update the slide video walkthrough for you. Can you share the link to the JavaScript VII video ?

**Comment by alodahl** [comment]
Thank you!  It should be somewhere among these.  Please open first to ensure the video isn't incorrectly titled.  https://drive.google.com/drive/folders/14Ew_wyoIR1bWWBRnetIKnqXt_deDImDU

**Comment by parbinder** [comment]
@alodahl  I checked all videos in the folder you shared. I could not find the video walk though for OOP.

**Comment by alodahl** [comment]
hi @parbinder , im pretty confused, since i played the video under “Materials”, and it seems to be about JS objects. is this not it? what am i missing?

**Comment by parbinder** [comment]
Done. Here's the link to pull request - https://github.com/Techtonica/curriculum/pull/1582

**Comment by alodahl** [comment]
fixed in #1582
