### ISSUE TITLE
Missing screenshot of Terminal Git codings in slides of GitHub

### ISSUE THREAD

**Issue by zzyou** [Techtonica/curriculum#152]
In "Using GitHub for Code Storage", steps of Git codings in Terminal (creating new local repo and push) are not included in the slides. They are only showed in the slides video (mini lesson, slides walkthrough). 
Maybe it's better to include screenshots of these Git codings in Terminal in the original slides too.

**Comment by antislice** [comment]
Needs a link to the slides in question

**Comment by alodahl** [comment]
Added video screenshots of terminal commands in to the slideshow
