### ISSUE TITLE
Intro to React - key warning discussed in lesson not demonstrated by codepen

### ISSUE THREAD

**Issue by aedward8** [Techtonica/curriculum#1524]
_Thanks for reporting an issue with the Techtonica curriculum! Please fill in the following information to help us resolve the problem as soon as we can._

### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/react-js/react-part-1-intro.md

### Type of problem

Common examples:

- Confusing or incomplete explanation
The Guided practice examples states
"If something is modified or updated, React needs to quickly figure out which element changed and where it needs to reflect that change. So, we have to set key attribute on the li of the list.
Eg: <li key={value}>
If the key property is not set, then the browser will give warning in the console."

 
However the codepen currently does not have a key attribute on the li of the list and it runs fine without any warnings in the console.

### Suggestion Solution

Seems like an explanation may be missing

**Comment by vegetabill** [comment]
Good catch. It's because the pen author is using the minified aka production JS bundles of React which do not include any warnings:

`https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.min.js`

These should be updated to dev bundles (and a more recent major version)

**Comment by alodahl** [comment]
will be addressed in #1561 👀
