### ISSUE TITLE
REST API guided practice has incomplete code snippets

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1525]
### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/api/REST-API.md

### Type of problem

As explained in #1517 the example code at a glance appears to be real code, it doesn't do anything. For "Guided Practice" we expect the code to be correct. If something is to be added by the reader, it should be clearly marked with comments , e.g. `// your solution goes here`

### Acceptance Criteria

- the `PUT` code is incomplete and doesn't do anything. Please finish it so it works
- the `DELETE` code is incomplete and doesn't do anything. Please finish it so it works. (And a DELETE endpoint typically just sends 200 and no body, not what it's doing now)
- Remove the warning added in #1517 since this will fix it and make it unnecessary
- Bonus points: While you're at it, please make the code follow Express best practices. It's a bit of a mess at the moment
- Bonus points: Move the lengthy test data into a JSON file (which can just as easily be required)

**Comment by priyaraj7** [comment]
We updated the [REST API doc](https://github.com/Techtonica/curriculum/blob/main/api/REST-API.md). So closing the issue
