### ISSUE TITLE
Update outdated usage of createReactClass in React Part 1 Slides

### ISSUE THREAD

**Issue by aedward8** [Techtonica/curriculum#1526]
### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/react-js/react-part-1-intro.md

### Type of problem

Common examples:

-conflicting material
In the Techtonica slides on slide 12 it says "createReactClass(): this is rarely used; no need to learn this"

However, link 4 in resources "Building your first component in React.js | Pluralsight (video)" Is an 7 min example vide primarily using React.createClass.

**Comment by sheriecarter** [comment]
I have updated the slides to remove "this is rarely used; no need to learn this" and instead added a bullet point that lets them know that this is not used in ES6. I think it would be potentially helpful to still keep the Pluralsight tutorial in the curriculum unless there are already other tutorials in the curriculum which go over the create-react-class module.

**Comment by alodahl** [comment]
I see this is connected to #1557. I looked at the slides just now, and there is still a line that says "this is rarely used; no need to learn this", so I'm confused about what changes were made @sheriecarter .

Does this resolve the issue @aedward8 ?

**Comment by aedward8** [comment]
@alodahl  I think you can resolve this issue as the larger issue of updating the curriculum from class based components to function based components is what #1557 and this issue is about
