### ISSUE TITLE
React slides should not use create-react-app until Part 4

### ISSUE THREAD

**Issue by aedward8** [Techtonica/curriculum#1528]
### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/react-js/react-part-1-intro.md

(https://medium.com/in-the-weeds/learning-react-with-create-react-app-part-1-a12e1833fdc)
Last Updated in  2017
### Type of problem

Common examples:

-outdated download information in medium tutorial that is in the Techtonica slides (slide 16)

The article instructs us to download create react app with. $ npm install -g create-react-app
However when I do this it says that  that global installation of create-react-app is no longer supported and recommends uninstalling globally. The official React docs say to use $npx create-react-app my-app

### Suggested Solution

If we want to continue to use this tutorial will need to put a disclaimer to download with $npx create-react-app my-app before following the tutorial or finding another tutorial resource here to replace it

**Comment by vegetabill** [comment]
@aedward8 React Part 1 and 2 were designed to _not_ require CRA and instead use CodePen or similar to save complexity.

I think the true fix for this ticket is to make sure the slides also reflect this.

**Comment by vegetabill** [comment]
Sorry those slides are really out of whack with the curriculum in many key ways. I think they reflect the very original versions of the material. Created a bigger issue: #1544 

This individual issue should be taken care of with the solution for that.
