### ISSUE TITLE
Proposed Schedule Changes for H2-2021

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1543]
Placeholder for any major schedule adjustments needed for H2-2021

### React
- Where should [functional components / hooks lesson](https://github.com/Techtonica/curriculum/blob/main/react-js/react-hooks.md) go? Elective week?

### Misc

- DOM lesson should come before Game Project, see #1467 

### Open Questions

- Should the participants learn React immediately after learning HTML/CSS or does the interlude to learn backend still make sense?

**Comment by alodahl** [comment]
covered by @SarahCawley @Yosolita1978 and I.
