### ISSUE TITLE
React slide deck has drifted substantially from markdown lessons

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1544]
### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/react-js/react-part-1-intro.md

[Slides Link](https://docs.google.com/presentation/d/1Bswkl7e1kGVav7KFabHrBgXhRi7mlINTbinxnUcGDy8/edit?usp=sharing)

### Type of problem

- Because React Part 1 used to be everything the slides get way ahead of the markdown content, negating the whole point of simplifying and splitting the lessons
- They reference outdated concepts
  - comparing to jQuery which is no longer taught
  - ES6 constructors as "something new" but it's part of the core JS lessons
- They introduce functional components, which was purposefully deferred
- They talk about DB's and MongoDB (?)
- They contain extraneous information 

### Proposed solution

1. Stop maintaining the same information in two places and delete the slide deck after making sure nothing in it needs to be moved to the markdown
1. **Or** basically rewrite the slide deck and create one for each new lesson

**Comment by vegetabill** [comment]
Not having the slide decks under version control is quite a hassle. I know we have a lot of content in the existing decks but maybe we can make a decision for new decks to be in one of those markdown-based formats and part of this repo. Have you thought any about this @SarahCawley ?

**Comment by alodahl** [comment]
i have a fn component set of react outlines in the works, and im debating whether a deck is even necessary. i have so many codepens and videos anyway. will discuss with Sarah.

**Comment by SarahCawley** [comment]
I think in this instance we can get rid of the slide deck. In general they are a nice "here is vaguely what you will be going over" and can help. But for super large topics like all of react, I think a 5 minute video tutorial would be better
