### ISSUE TITLE
[React Part 3] Recreate CodePen link

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1549]
### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/react-js/react-part-3-component-hierarchies.md#from-parent-to-child--use-a-prop

### Type of problem

The very first code pen at the end of "From Parent to Child — Use a prop" is a 404.

### Suggested Solution

Recreate this pen.

Optionally: fork all of these into a Techtonica-owned account

**Comment by alodahl** [comment]
this seems to be fixed. i will be refactoring this lesson in a few weeks anyway, and will test all links.
