### ISSUE TITLE
Double-check that projected times are accurate in topic outlines.  (Multiple assignees encouraged!)

### ISSUE THREAD

**Issue by chulinguy** [Techtonica/curriculum#155]
Choose an available set of **Topic Outlines** found in [this Curriculum Program](https://docs.google.com/spreadsheets/d/1vIr3fiKa_jxzy7qtFsiE5hEJbiTXwc1LYxbfsHOYD6U/edit#gid=0) . 
1.  Ensure time range in Topic Outline markdown file is accurate when all materials and all lesson sections are included (unless labelled "supplemental" or "additional").
2. Ensure the "Estimated time (hours)" cell in the spreadsheet is also accurate.

Check a range of about 10 you'd like to start work on, and check completed when finished will all lessons in that range:
- [x] 1. Professionalism -> Operating Systems  - Started
- [x] Complete
- [x] 2. Asking Good questions -> .gitignore - Started
- [x] Complete
- [x] 3. Using Github for Code Storage -> Building Confidence - Started
- [x] Complete
- [x] 4. UI/UX Design -> Diversity & Inclusion - Started
- [x] Complete
- [x] 5. Design and Build resume/portfolio webpage -> Deploying with Netlify - Started
- [x] Complete
- [x] 6. JS1 -> Testing, TDD - Started
- [x] Complete
- [x] 7. JS7 -> jQuery - Started
- [x] Complete
- [x] 8. AJAX -> Database Migrations - Started
- [x] Complete
- [x] 9. Intro to Scrum -> Memoization - Started
- [x] Complete
- [x] 10. Agile -> Linked List - Started
- [x] Complete
- [x] 11. Hash Table -> Open Source Projects Week - Started
- [x] Complete
~~- [ ] Resume Writing -> Technical Program Manager~~
- [x] 12. Selecting your Project -> Ethics - Started
- [x] Complete

**Comment by Karla-Isabel-Sandoval** [comment]
@chulinguy which lesson plan are you referring to?

**Comment by chulinguy** [comment]
@Karla-Isabel-Sandoval it looks like @MichelleGlauser created individual issues for each lesson.  
I do think it's difficult to estimate the projected time for the lessons without a video walkthrough now.

**Comment by Karla-Isabel-Sandoval** [comment]
@chulinguy we created them together :) so that volunteers know which issues topic outlines need to be either created or completed. Once the Topic Outline is completed, then it will be easier to add a projected time to complete to each one.

**Comment by alodahl** [comment]
Picked up by Georgina

**Comment by alodahl** [comment]
finished!
