### ISSUE TITLE
Fix due dates on Monday.com H2 cohort boards

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1569]
Based on [Week 4](https://techtonica.monday.com/boards/1068887208), which is correct, Fix due dates on Monday.com H2 cohort boards Week 5-24.  Observe national holidays.  Report back if there is a change in which week has a holiday - we may need to rearrange some things.

Ask @alodahl  or @SarahCawley for board access.

Please mark off when due date updates are complete:
- [ ] Week 5
- [ ] Week 6
- [ ] Week 7
- [ ] Week 8
- [ ] Week 9
- [ ] Week 10
- [ ] Week 11
- [ ] Week 12
- [ ] Week 13
- [ ] Week 14
- [ ] Week 15
- [ ] Week 16
- [ ] Week 17
- [ ] Week 18
- [ ] Week 19
- [ ] Week 20
- [ ] Week 21
- [ ] Week 22
- [ ] Week 23
- [ ] Week 24

**Comment by alodahl** [comment]
it sounds like Joy may be picking this up, will confirm this week.

**Comment by SarahCawley** [comment]
Correct, Joy will be  doing this
