### ISSUE TITLE
Add new day leads on Monday.com h2 cohort boards

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1570]
Last cohort, we rotated the task of being the "Day Lead" to each participant alphabetically.  Please get the new list of participants, and replace the copied Day Leads on all the Monday.com h2 cohort boards, Weeks 1-24, with the new names.

Ask @SarahCawley or @Yosolita1978 for the new list.

**Comment by SarahCawley** [comment]
I was thinking for this cohort I would add the names week by week, so if we have someone drop out I don't need to go edit the rest of the schedule. So you don't need to worry about it :)
