### ISSUE TITLE
Convert code challenges tests from jasmine -> jest

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1572]
Our [code challenges repo](https://github.com/Techtonica/code-challenges) is currently using jasmine. We have a lot of very short, simple unit tests.  Please convert our **repo and tests** to run using *jest* instead. Also update our package.json test command to use any new jest command. If you needed to change any commands, directory or file names, please leave a note about it here.

**Comment by ndp** [comment]
It would be nice to remove the `node_modules` from the git repo, but I'm just leaving it for now. I can do that here or as a separate PR on request.

**Comment by ndp** [comment]
The PR is found here: https://github.com/Techtonica/code-challenges/pull/12

**Comment by alodahl** [comment]
removing node mods would be great - that was an oversight.

**Comment by ndp** [comment]
@alodahl you want me to do that in this PR? or a subsequent one?

**Comment by ndp** [comment]
Nevermind... here is a node_modules PR:  https://github.com/Techtonica/code-challenges/pull/13

**Comment by alodahl** [comment]
it sounds like we wont be using the code challenges anymore, or at least this isnt a priority.
