### ISSUE TITLE
Proofread OOP outline, make sure it matches slideshow

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#160]
Please start with this slideshow that was recently edited.
https://docs.google.com/presentation/d/1XKxBZIJ2gLknsyCBFm0jcq5Gk06d9uAyYTSW0QmQA10/edit?usp=sharing

- [x] Proofread [this topic outline](https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-7-oop.md), and make sure it includes any additional info that's in the above slideshow.

* For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

* Other info:
If you're wondering how much background on objects apprentices have, here is only lesson about it they've had (likely the day before):
 https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-6-object-literals.md

**Comment by Karla-Isabel-Sandoval** [comment]
The structure is available and needs to be filled in.
Great item for a first-time contributor.

**Comment by alodahl** [comment]
Issue picked up by George Brassey

**Comment by alodahl** [comment]
Lots of editing to slideshow and outline by me and George Brassey
