### ISSUE TITLE
eventonica-react: update/ proofread Postgres outline to fit with new Express project

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1611]
### eventonica-react: get the cohort started with a Postgres DB for their create-react-app project

Please make any necessary updates/clarifications so that this file’s directions make it easy to add a Postgres DB to our express app: https://github.com/Techtonica/curriculum/blob/main/projects/eventonica-react/eventonica-postgres.md

Note that this would come immediately after https://github.com/Techtonica/curriculum/blob/main/projects/eventonica-react/eventonica-express-backend.md

Add or change the starter code in projects/eventonica-react/starter-code if necessary.

Here's an example Express project for your reference.  This is for contributors, not curriculum users! https://github.com/alodahl/eventonica-api.

See #1608 for more context and a React app example.

**Comment by priyaraj7** [comment]
I updated the eventonica-postgres doc. So closing the issue
