### ISSUE TITLE
Financial Literacy slideshow is editable

### ISSUE THREAD

**Issue by twolfson** [Techtonica/curriculum#1779]
### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/program-prep/financial-literacy.md

### Type of problem

Access control

### Explanation

Hey Techtonica,
I've heard of y'all a while ago but loving to come across your curriculum! And will likely share it with my coworkers!

As a heads up, while I was browsing the various curriculum pages, I noticed that the Financial Literacy presentation seems to be editable by anyone.

https://docs.google.com/presentation/d/150KD2ORxehyoOHHzF_RWj_G6wHOMqgQlTavtOFhkJ4A/edit

![image](https://user-images.githubusercontent.com/902488/202373312-b7af2b40-b4a0-45d3-8cce-a684740d4df1.png)

Most of the presentations have the ideal settings by being view only:

https://docs.google.com/presentation/d/1Vzx0eyKt0jNQq70pnAeDQ5X1qOPdjIzCgujSp6dd_1U/edit

![image](https://user-images.githubusercontent.com/902488/202373696-15020d84-bc28-4bea-acc4-cf7c505af708.png)

### Suggested Solution

- Restrict edit access for linked presentation
- Consider either manual or automated process to mitigate this in the future (e.g. as part of new changes)

**Comment by Yosolita1978** [comment]
Thank you sooo much for catching this and letting us know! We fixed it with this deck, and we're checking all our slides to avoid this situation in other lectures! Thank you!
