### ISSUE TITLE
Complete Financial Literacy topic outline

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#180]
- [x] Make your outline in this file: https://github.com/Techtonica/curriculum/blob/8a8d56c4c6b214ea87b1bb262a06f7dcd9095066/financial-literacy/financial-literacy.md

- [x] Find a video that covers the important points in this lesson for audio learners, and leave the link in the comments or send it to Alina.

Follow these slides: https://drive.google.com/open?id=150KD2ORxehyoOHHzF_RWj_G6wHOMqgQlTavtOFhkJ4A

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
picked up by julie norris
