### ISSUE TITLE
Finish partial Socioeconomic Differences topic outline.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#181]
- [ ] Write a topic outline for Socioeconomic Differences Lesson here:  https://github.com/Techtonica/curriculum/blob/master/socioeconomic-differences/socioeconomic-differences.md
The goal is to guide apprentices through discussion and possibly research on issues about moving from a blue-collar to a white-collar culture.

- Base the outline on these slides: https://docs.google.com/presentation/d/1qSol4y0rqQi7yrjtXZ3J4EL0BQwW6hZUkHIxDRWooHw/edit?usp=sharing

For more detailed volunteering directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by ch-alicehyun** [comment]
Looks like the links above are linked to a duplicate that has been removed.

I believe this is the link: https://github.com/Techtonica/curriculum/blob/master/socioeconomic-differences/socioeconomic-differences.md

**Comment by ANURADHAJHA99** [comment]
I would like to work on this issue.KIndly assign the issue to me.

**Comment by alodahl** [comment]
No problem! I’ll set it aside for you @ANURADHAJHA99

**Comment by alodahl** [comment]
@ANURADHAJHA99, since we are a US Non-profit, please be sure to fill out this form before you start this project: https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

**Comment by ANURADHAJHA99** [comment]
I have already filled the form.Thank you.

**Comment by alodahl** [comment]
Thanks @ANURADHAJHA99 !  You can start working on it, and make your PR on or after March 1 to get your GSSoC19 points!

**Comment by ANURADHAJHA99** [comment]
@alodahl Can you please provide me an example which I can follow?

**Comment by alodahl** [comment]
@ANURADHAJHA99 Here is a good example of an outline that leads research and discussions on a topic: https://github.com/Techtonica/curriculum/blob/master/ethics/ethics.md

The outline template I provided in the issue description should help you, too.

**Comment by ANURADHAJHA99** [comment]
@alodahl  am I suppose to fill the space for examples in the given outline?

**Comment by ANURADHAJHA99** [comment]
I have created a pull request, kindly check it out https://github.com/Techtonica/curriculum/pull/614

**Comment by ANURADHAJHA99** [comment]
@alodahl I have created a pull request, kindly check it out. https://github.com/Techtonica/curriculum/pull/614

**Comment by ANURADHAJHA99** [comment]
@alodahl is there some sort of issue?

**Comment by alodahl** [comment]
@ANURADHAJHA99 please see our comments in PR #614

**Comment by rudri182** [comment]
I would like to contribute to this issue

**Comment by ANURADHAJHA99** [comment]
I have completed the whole document outline myself and it's just there are few issues to resolve,and since I was busy due to exams I failed to do so...but I would do it by tomorrow.

**Comment by alodahl** [comment]
I understand, @ANURADHAJHA99 ! Did I see you had another issue with an earlier due date? Can you work on that one first, please?

**Comment by ANURADHAJHA99** [comment]
kindly review the following commit https://github.com/Techtonica/curriculum/pull/614/commits/cf89658b36dfe8ee8d695f26c0d41434a0193eee.
sure I am working on that one too.
