### ISSUE TITLE
Create Women in Tech Resources topic outline. 

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#183]
- [ ] Complete [this topic outline about Resources for Women in Tech](https://github.com/Techtonica/curriculum/blob/master/women-in-tech-resources/resources-list.md).  See the issue comments for lots of suggestions.
- [ ] [Create the accompanying slideshow here] (https://docs.google.com/presentation/d/1ZdnhhGbwyJcmgPnTn6eeHjdhekUvo0ht70MwC7Ll5zw/edit?usp=sharing) for visual learners.

**Comment by MichelleGlauser** [comment]
We first need to get the slides from Anna Neyzberg (she's putting them into the linked-to slides above).

**Comment by judytuna** [comment]
from volunteer yv: 

WeAllJS (Really friendly community for technical questions. Pretty active group)
https://wealljs.org/

Girl Develop It SF (I couldn't find the Oakland slack channel. Really friendly community)
https://gdisf-slack.herokuapp.com/
https://www.meetup.com/Girl-Develop-It-San-Francisco/
https://www.meetup.com/Girl-Develop-It-oakland/

Other Groups
Group that gets together to help folks on coding stuff (specifically nodeJS).
Node School OAK: https://nodeschool.io/oakland/
Node School SF: https://nodeschool.io/sanfrancisco/

You probably already know about them, but they have a bunch of cool events.
https://www.meetup.com/Women-Who-Code-SF/
https://www.womenwhocode.com/  -> Global listserv has a bunch of events and job opportunities.

You can find some interesting google hosted events here
https://developers.google.com/programs/launchpad/space/

I recommend signing up for this listserv. They're a cool community and advertise event/job opportunities.
https://lesbianswhotech.org/signup/
They have an event coming up: https://www.eventbrite.com/e/lesbians-who-tech-allies-career-fair-career-mentoring-san-francisco-tickets-53865791031

**Comment by judytuna** [comment]
Systers (though it's going through evolving pains right now)

Google's Women Techmakers for conference discounts and community

Codechix (rupa)

Women 2.0 (angie)

Devchix

**Comment by alodahl** [comment]
Picked up for the morning by Tiffany Stuart
