### ISSUE TITLE
Put the readme.md list in order of appearance, make extras list.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#190]
Here's the order of appearance of topics: https://docs.google.com/spreadsheets/d/1V2XwxcJZl94xegLmM7YM4Vk6kBKLnBROKS_Hgb1qZ28/edit?usp=sharing

**Comment by gitsteph** [comment]
Is "extras list" the category in the Google spreadsheet under "Some time..."?
