### ISSUE TITLE
 Incomplete resources for sample solutions to strings code challenges

### ISSUE THREAD

**Issue by Yosolita1978** [Techtonica/curriculum#1938]
### Page where problem found?

(https://github.com/Techtonica/curriculum/blob/main/code-challenges/string.md)

### Type of problem

 Incomplete resources for sample solutions to strings code challenges

### Suggested Solution

_Optional. If you would like to suggest a specific solution, please add it here._

**Comment by mbommakanti98** [comment]
Hello,

I've gone through the issue, and I am willing to work on this. Would love to connect and get started up on.

Thanks,
Maneesh. B

**Comment by archijaiswal** [comment]
Hello,
I am GHC OSD participant. I've filled the the Volunteer Google Form. I would like to work on this issue. Can you please assign me.

Thanks,
Archi

**Comment by tanayaj1998** [comment]
Hello, I am a GHC OSD Participant  I filled the volunteering form I would like to work on this issue. Thanks

**Comment by Yosolita1978** [comment]
Done, for both of you!

**Comment by lyannel** [comment]
Hi there, I'm also a GHC OSD Participant and filled out the volunteer form.
Would like to contribute to this issue as well.
