### ISSUE TITLE
Incomplete resources for Code Challenges for Arrays

### ISSUE THREAD

**Issue by Yosolita1978** [Techtonica/curriculum#1941]
_Thanks for reporting an issue with the Techtonica curriculum! Please fill in the following information to help us resolve the problem as soon as we can._

### Page where problem found?

https://github.com/Techtonica/curriculum/blob/main/code-challenges/arrays.md

### Type of problem

Common examples:

- Incomplete resources for solutions and test cases for problems about Arrays in JS.

**Comment by vazquezea96** [comment]
Hello, I am interested in working on this issue.

**Comment by Yosolita1978** [comment]
Perfect! I invite you to be part of our Triage team. Please accept the invite (you should also see an email) so I can assign you to this issue. Thank you for volunteering!

**Comment by vazquezea96** [comment]
Awesome, thanks for the invite. So, the main goal here is to complete the test cases and solutions for the problem sets.

**Comment by isadominguez314** [comment]
I would like to work on this issue

**Comment by galgalinidhi** [comment]
Hello, I'm interested in working on this

**Comment by YiyunBao99** [comment]
Hello, I'd like to work on this issue.

**Comment by Shikha2410** [comment]
Hello, I'm interested in working on this

**Comment by lyannel** [comment]
Hi there, interested in working on this issue. I've filled out the volunteer form.

**Comment by Shikha2410** [comment]
#2033
