### ISSUE TITLE
Incomplete resources for code challenges using Objects Literals in JS

### ISSUE THREAD

**Issue by Yosolita1978** [Techtonica/curriculum#1944]
_Thanks for reporting an issue with the Techtonica curriculum! Please fill in the following information to help us resolve the problem as soon as we can._

### Page where problem found?

(https://github.com/Techtonica/curriculum/blob/main/code-challenges/Objects.md)

### Type of problem

Common examples:

Incomplete resources for code challenges using Objects Literals in JS

**Comment by akshay-patade** [comment]
Hi Yosolita,

Hope you are doing well. Just wanted to confirm the issue. You need the sample testcases along with the solution for the Objects.md file.

If my understanding is correct, I would like to work on this issue.

Awaiting for your reply.

Regards,
Akshay

**Comment by amandaguan-ag** [comment]
I am GHC OSD participant. I've filled the the Volunteer Google Form. I would like to work on this issue. Can you please assign me.

**Comment by jennifertran1209** [comment]
Hello, I am a GHC OSD participant, if it is possible could you assign this to me too?

**Comment by daaimah123** [comment]
Resolved with PR #1957.
