### ISSUE TITLE
Add a Group Practice Section to the Learning to Learn Lesson

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2062]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

Presently the [Learning to Learn](https://github.com/Techtonica/curriculum/blob/main/onboarding/learning-to-learn.md) lesson that participants revisit during week 1, does not have a clear objective for a _**group**_ practice activity. Please add a section following Independent Practice that details an exercise that they should do with their pairs / buddy. The exercise should be a group discussion of the different learning styles based on the learning style(s) they discovered during their pre-work learning. They should be prepared to share with the cohort during wrap up. Please specify that the group practice activity will be completed during week 1 and not during pre-work.

### Page where problem found?
[Learning to Learn](https://github.com/Techtonica/curriculum/blob/main/onboarding/learning-to-learn.md)

### Type of problem

Common examples:
Adding clarification about a required participant task during week 1.

### Suggested Solution
Add in a group practice section that explicitly states what the group activity is.

**Comment by abbiehuynh** [comment]
Hello, I would like to work on this issue. Please assign this to me.

**Comment by daaimah123** [comment]
@abbiehuynh you have been assigned this issue! 🎊

**Comment by daaimah123** [comment]
@abbiehuynh can you share where you are at with resolving this issue?

**Comment by Lakhwinderr** [comment]
Please assign this task to me and review my PR #2099.

**Comment by daaimah123** [comment]
It looks like this section has already been added [here](https://github.com/Techtonica/curriculum/blob/6386eaef234674097a3420b517bc8c6e19bc7f0e/onboarding/learning-to-learn.md#group-practice), closing the issue.
