### ISSUE TITLE
Add more context about having multiple learning styles to the "Learning to Learn" lesson

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2063]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

The reinforcement that each person is able to have more than one learning style should be carried throughout entirety of the lesson. We received feedback that this would be helpful to reinforce specifically when taking the learning style quiz. Replace the existing learning style quiz with [this Vark Questionnaire](https://vark-learn.com/the-vark-questionnaire/). Following the quizzes provide this [evidence-back article](https://www.educationnext.org/stubborn-myth-learning-styles-state-teacher-license-prep-materials-debunked-theory/) that digs into why singular learning styles are something that's still being taught to teachers as something to incorporate in lesson plans, and share a sentence or two with key takeaways.

### Page where problem found?
[Learning to Learn](https://github.com/Techtonica/curriculum/blob/main/onboarding/learning-to-learn.md)

### Type of problem
Existing quiz highlights a single learning style which is counter-intuitive to the debunked myth the participants learn in this lesson.

### Suggested Solution
Replace the existing quiz with a new one that highlights a person's multiple learning styles, and add an additional resource link with some context.

**Comment by tati-guzman** [comment]
Since no one is assigned, may I claim this issue?

**Comment by daaimah123** [comment]
@tati-guzman you have been assigned this issue! 🎊

**Comment by tati-guzman** [comment]
Pull request ready to merge here: [Learning to Learn Pull Request - 2088](https://github.com/Techtonica/curriculum/pull/2088)

**Comment by daaimah123** [comment]
PR Merged! 🎉
