### ISSUE TITLE
Add real-world context about application of working with frameworks

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2065]
After applying css, participants may find it difficult to pivot into adding in their bootstrap (or another styling framework) into their project. This may cause them to spend extra time fiddling with styling properties. Please add in some context (a couple sentences) about real world application such as: 
- being able to explain in an interview setting about how they were able to adapt a project
- working with a new technology

### Page where problem found?
[Recipe Page: Bootstrap](https://github.com/Techtonica/curriculum/blob/main/projects/recipe-page/phase-3-bootstrap-prompt.md)

### Type of problem
Context missing for why exposure to and adding in bootstrap (or another styling framework) is necessary.

### Suggested Solution
Add in some brief content about why the exposure and adding can be useful for their career path outside of the learning experience.

**Comment by AmaanRS** [comment]
I am willing to do this, assign me the issue please.

**Comment by daaimah123** [comment]
@AmaanRS I am assigning you to this issue.

**Comment by daaimah123** [comment]
Thank you for working on [Update phase-3-bootstrap-prompt.md](https://github.com/Techtonica/curriculum/pull/2077#top)

**Comment by AmaanRS** [comment]
Welcome

**Comment by daaimah123** [comment]
Resolved with #2077
