### ISSUE TITLE
Create a topic outline for participants to experience "Project Collaboration with Multiple Contributors"

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2070]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

During week 10, have the participants design one of their first projects from weeks 1 - 8 as a group of 2-3 people (their weekly trios are ideal for this). The objective is to have multiple people coding in the same repo, on different parts of a project, for a single result. Make clear the project's timeline: planning should take place the first day whereas implementation of branches for tasks assigned (testing amongst contributors and merging in of branches) should happen throughout the week's duration with a complete screen recording of the project in their README.

The participants will be building another full stack app ([Animal Sighting Tracker](https://github.com/Techtonica/curriculum/blob/main/projects/mern-pern-project.md)) at the same time so there should be mention of the following: 
- revisit their [time management slides](https://docs.google.com/presentation/d/1VGlfYtWXQ8TEXsq4Bad0k2WZ-mK02hI3UwVXrfuUpPA/edit?usp=sharing), 
- intentionally breaking down the project before coding, 
- assignment of tasks to people with incremental deadlines, and 
- checking in with their group daily to understand support and progress needs.

### Page where issue should live
Add the lesson [here](https://github.com/Techtonica/curriculum/tree/99e65383fbf19b3dcdb045431a6f9d8d800a1100/practice).

### Type of problem
Exposure to collaboratively building a project with multiple people for a single outcome.

### Suggested Solution
Create a lesson that helps them to recreate an earlier project with 2+ people building various parts of the application in order to collaborate and communicate with several "moving parts" happening at the same time.

### Supplemental Materials to Include
- [Overview of Kanban](https://www.atlassian.com/agile/kanban) - 5 min read, 5:30 min video
- [Overview of Scrum](https://www.atlassian.com/agile/scrum) - 1 min read, 3:30 min video

**Comment by Lakhwinderr** [comment]
I am working on this.

**Comment by Lakhwinderr** [comment]
Please review my PR #2103

**Comment by daaimah123** [comment]
@Lakhwinderr Merged and labeled "hacktoberfest-accepted"

**Comment by Lakhwinderr** [comment]
Thanks @daaimah123
