### ISSUE TITLE
Advise participants against creating a BMI project for its historical negative implication

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2072]
Week 5, participants create a game in React. Please add a note to not select the BMI project from the list of React example projects because of its racist and size-ist negative implications.

### Page where problem found?
[Week 5: Game App](https://github.com/Techtonica/curriculum/blob/2f4047a287685fcbfee9d06e8318996e79c6803e/projects/react-game.md) in [the examples link](https://legacy.reactjs.org/community/examples.html), under "General guidelines for projects."

### Type of problem
Currently the example list contains a suggested application that historically has size-ist and racist negative implications that have negatively impacted or harmed at least one group of the demographics we serve.

### Suggested Solution
In keeping with [Techtonica's Code of Conduct](https://techtonica.org/conduct/), we would like to point this out to our participants and actively request that they not create such a game for the purposes of this learning exercise.

**Comment by AmaanRS** [comment]
I am willing to work on this

**Comment by AmaanRS** [comment]
Done #2078

**Comment by daaimah123** [comment]
Resolved with PR #2080
