### ISSUE TITLE
Remove codesandbox references from React Game Lesson

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2073]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

Please remove references to codesandbox in the lesson and encourage participants to use git version control and GitHub to save their progress as they build up their work.

### Page where problem found?
[Week 5 React Game Lesson](https://github.com/Techtonica/curriculum/blob/main/projects/react-game.md)

### Type of problem
The existing lesson directs participants to begin making their application in codesandbox.

### Suggested Solution
We want participants to work on testing out react in their text editors locally so that they can save their code progress to GitHub as they progress in their assignment.

**Comment by nianokia** [comment]
Could you please assign this issue to me?

**Comment by daaimah123** [comment]
Yes @nianokia, thank you for completing the contributor guidelines! 😀 You are now a contributor to the project 🎉 I have assigned the issue to you.

**Comment by daaimah123** [comment]
@nianokia please reference the closed PR #2081 for inspiration

**Comment by nianokia** [comment]
@daaimah123 I've submitted the pull request with the new changes!

**Comment by daaimah123** [comment]
Thank you for successfully addressing this with #2087; merged
