### ISSUE TITLE
Remove create-react-app references in curriculum

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2074]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

Please indicate where CRA is referenced, that is no longer maintained and what this means to participants. Direct the participants to use React + Vite to spin up their React app template structure. You can reference the existing lesson and language about the transition to CRA with Vite [here](https://github.com/Techtonica/curriculum/blob/main/react-js/react-local-vite.md). 
- Please make specific notes about the testing differences between CRA and React + Vite in the Jest lesson changes. 
- Week 8 game last statement needs an inclusion of why they should not use CRA.

Questions to answer: 
- Will CRA still work if I code with it?
- What hurdles will I encounter if I work with it?
- If I have already started my project in CRA, should I start over using Vite?

### Page where problem found?

All pages resolved

### Type of problem
Create-React-App (CRA) is no longer maintained.

### Suggested Solution
We would like the curriculum to reference working with React & Vite instead.

**Comment by daaimah123** [comment]
✅ Removed from [react-part-5.md](https://github.com/Techtonica/curriculum/commit/46834e8dca89139d9e127e345199437b644ca49a)

**Comment by manojsiddoji** [comment]
is this open ??

**Comment by daaimah123** [comment]
Yes @manojsiddoji, if you would like to be assigned as a contributor, please follow our contributor guidelines: https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md

**Comment by HtcYlmz** [comment]
Can I work with this?

**Comment by manojsiddoji** [comment]
> Yes @manojsiddoji, if you would like to be assigned as a contributor, please follow our contributor guidelines: https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md

i registered as volunteer, now nxt steps

**Comment by daaimah123** [comment]
✅ @manojsiddoji you have successfully been added as a contributor to the project and are now assigned to this tasks. Please communicate in this issue which areas you will remove the create-react-app reference from. 

----

👋🏾 @HtcYlmz if you would like to support this work as a contributor, as this is a large issue, please follow our contributor guidelines: https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md

**Comment by manojsiddoji** [comment]
where is the problem !!

**Comment by daaimah123** [comment]
@manojsiddoji I would be happy to answer more specific questions after you have read the issue description, there is a detail of the problem there.

**Comment by daaimah123** [comment]
✅ Removed from [Deploying](https://github.com/Techtonica/curriculum/blob/2f4047a287685fcbfee9d06e8318996e79c6803e/deploying/deploying.md?plain=1#L48) and [Deploying to Heroku](https://github.com/Techtonica/curriculum/blob/2f4047a287685fcbfee9d06e8318996e79c6803e/deploying/deploying-to-heroku.md?plain=1#L50)
