### ISSUE TITLE
Add more options for link submission of counter-app-exercise in week 5

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2075]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

The existing README for the counter-app week 5 exercise is limiting participants to use a specific platform to submit to submit a link. We want to give them more options. Please edit the README to include additional options such as: replit, their techtonica-assignment folder in GitHub, or even codepen.io.

### Page where problem found?
[README.md for counter-app exercise week 5](https://github.com/Techtonica/curriculum/blob/testing-with-cohort/pair-programming/week-5/react-couter-app/README.md)

### Type of problem
The README is limiting participants to only work with submitting a link from codesandbox in order to execute the assignment. 

### Suggested Solution
We want to give participants more options, as some of codesandbox's features have been paywalled. They are able to submit links from a replit, their techtonica-assignment folder in GitHub, or even codepen.io.

**Comment by neetasawant** [comment]
Hi, is this open?

**Comment by daaimah123** [comment]
Yes, @neetasawant, I will assign you - thank you for completing the contributor guidelines! 😀

**Comment by daaimah123** [comment]
@neetasawant can you share where you at with addressing this issue?

**Comment by daaimah123** [comment]
Yes @manojsiddoji, if you would like to be assigned as a contributor, please follow our contributor guidelines: https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md

**Comment by Lakhwinderr** [comment]
Hi, let me contribute to this.

**Comment by daaimah123** [comment]
@Lakhwinderr, thank you for completing the contributor guidelines! 😀 You are now a contributor to the project 🎉 I have assigned the issue to you and successfully merged in your PR #2097

**Comment by Lakhwinderr** [comment]
@daaimah123 Thankyou for reviewing and merging, Peace✌

**Comment by daaimah123** [comment]
@Lakhwinderr labeled "hacktoberfest-accepted"

**Comment by Lakhwinderr** [comment]
Thank you @daaimah123
