### ISSUE TITLE
Cackend typo!

### ISSUE THREAD

**Issue by ChasVanDav** [Techtonica/curriculum#2084]
_Thanks for reporting an issue with the Techtonica curriculum! Please fill in the following information to help us resolve the problem as soon as we can._

### Page where problem found?

[_e.g. https://github.com/Techtonica/curriculum/blob/main/api/REST-API.md_](https://github.com/Techtonica/curriculum/blob/main/projects/weather-app.md)

### Type of problem

Common examples:

- Typo

### Suggested Solution

The main header has a typo 'Cackend' instead of 'Backend.'
There just needs to be a spelling corrected.

**Comment by daaimah123** [comment]
@ChasVanDav just a heads up, it looks like #2085 addresses this

**Comment by daaimah123** [comment]
PR Merged 🎉
