### ISSUE TITLE
Learning styles expansion

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#2089]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾

To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

### Page where problem found?

(https://github.com/Techtonica/curriculum/blob/main/onboarding/learning-to-learn.md?plain=1)

### Type of problem

- Confusing or incomplete explanation

### Suggested Solution

Make it clear that learning styles can change, people can have multiple learning styles, and knowing which is working for you has been shown to make your learning more effective.

**Comment by daaimah123** [comment]
✅ Addressed in c316ac54bddfde288657491396628f514070bace
