### ISSUE TITLE
Create Project: Store API data in database & render on webpage

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [Techtonica/curriculum#209]
Create Topic Outline + Slide + Video Slides if necessary
This project should take at least 3 days to complete

**Comment by gitsteph** [comment]
Just for clarity, is this to create a sample demo project scoped to roughly 3 days worth of work (to show what can be done in that amount of time), or to create guidelines for a project that folks would go through and do themselves individually/in pairs?
