### ISSUE TITLE
Ensure links to resources are clear about what they are so people know if it's effective for their learning style(s)

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#2090]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾

To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

### Page where problem found?

Every topic outline

### Type of problem

- Links missing information

### Acceptance Criteria

Links to external resources should be clear about what each resource is. For example, "[Growth Mindset](https://www.youtube.com/watch?v=EyIF5VUOJc0)" is less helpful than "[Growth Mindset (video, 6:36)](https://www.youtube.com/watch?v=EyIF5VUOJc0)"

**Comment by mai-repo** [comment]
@mai-repo I would like to be assigned to this issue

**Comment by daaimah123** [comment]
@mai-repo I have assigned this issue to you! 🥳

**Comment by mai-repo** [comment]
I have successfully completed this ticket.
