### ISSUE TITLE
Make our time management slides into a topic outline in the onboarding folder

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#2091]
We need to make a Time Management topic outline in the onboarding folder using our existing [Time Management slides](https://docs.google.com/presentation/d/1VGlfYtWXQ8TEXsq4Bad0k2WZ-mK02hI3UwVXrfuUpPA/edit#slide=id.g1fdef94fa7_0_0)

Acceptance Criteria: 
- Transition [the slide content](https://docs.google.com/presentation/d/1VGlfYtWXQ8TEXsq4Bad0k2WZ-mK02hI3UwVXrfuUpPA/edit#slide=id.g1fdef94fa7_0_0) into a "Time Management" topic outline
- Include the following sections: 
     - Questions to Consider
     - Prerequisites
     - Motivation or Real-World Application
     - Objectives
     - Common Mistakes / Misconceptions
     - Supplemental Materials
- Use [the vitest topic outline](https://github.com/Techtonica/curriculum/blob/main/testing-and-tdd/vitest.md) for formatting guidance
- Please add this work in [the onboarding folder](https://github.com/Techtonica/curriculum/tree/main/onboarding)

**Comment by mai-repo** [comment]
@mai-repo I would like to be added to this issue

**Comment by daaimah123** [comment]
@mai-repo I have assigned you the issue 🎉

**Comment by mai-repo** [comment]
I have successfully completed this ticket.
