### ISSUE TITLE
Make Clear Week 8 (Trivia Quiz App) Project Requirements

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2092]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾

To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

### Page where problem found?
[Week 8 Trivia Game App](https://github.com/Techtonica/curriculum/blob/main/projects/week8GameREADME.md)

### Type of problem
- Missing implementation requirements that can show their comprehension

### Suggested Solution
- Add the following missing implementation requirements: 
  - User can select number of questions
  - User can select question type
  - User can select question difficulty
  - User can select question category

**Comment by Lakhwinderr** [comment]
Hi, let me contribute to this.

**Comment by Lakhwinderr** [comment]
Hi @daaimah123 , please review PR #2098.

**Comment by daaimah123** [comment]
@Lakhwinderr I have assigned you to the issue and reviewed your submitted PR #2098.

**Comment by daaimah123** [comment]
✅ Merged

**Comment by daaimah123** [comment]
@Lakhwinderr labeled "hacktoberfest-accepted"

**Comment by Lakhwinderr** [comment]
Thank you @daaimah123 ♥.
