### ISSUE TITLE
Clarify when to use the template during Week 9 (Eventonica) Project

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2093]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾

To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

### Page where problem found?

[Eventonica](https://github.com/Techtonica/curriculum/blob/main/projects/eventonica-updated/README.md)

### Type of problem
- Some participants will find the template useful, some will not - we should make clear how they can make that decision for themselves by clarifying when and why they should use the template

### Suggested Solution
- Week 8 introduced the cohort to a template that could use to jump start their implementation of their trivia game app, this was good exposure to working with other people's code
- We should clarify this week reasons to use the template and reasons to not use the template. For example: 
  - NO: using the template felt confusing and like they didn't understand how each part fit together
  - NO: they want to develop a deeper understanding of each technology and how they work together
  - YES: it saved time
  - YES: they understand what the starter code was doing and was able to easily extrapolate what didn't serve their application

**Comment by HtcYlmz** [comment]
Can I work on this issue?

**Comment by daaimah123** [comment]
Hi @HtcYlmz, have you completed [our contributor guideline](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md)? Once that is done, I can certainly assign the issue to you 😄

**Comment by daaimah123** [comment]
Added to requirements #1
