### ISSUE TITLE
Create a Topic Outline on Preparing Local Project to Be Production Ready

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2107]
The existing google doc on [Build Your Production Instructions](https://docs.google.com/document/d/1ley6fg1x44w5Env4a8CKOpaPQNqCPkr8wagtiGOhEHI/edit?usp=sharing) needs to be converted into a topic outline

### Page where problem found?
Add topic outline to [the deploying folder](https://github.com/Techtonica/curriculum/tree/main/deploying)

### Type of problem
The deploying folder has set up details for deploying to various platforms, but does not have a formal lesson in the curriculum repo about why and how setting up a production environment is relevant. This lesson has been taught through google docs, we need to officially move this into the curriculum.

### Suggested Solution
- Prerequisites (call out lessons that they should already have gone through in order to understand this topic outline, these will not be explicitly outlined, look through existing curriculum or contact staff)
- Learning Objective
  - What is the difference between prod and deployment?
  - Participants unsure what this means? How to implement?
  - Understand why the server Local vs prod? Real world relation?
- Leverage [this day doc](https://docs.google.com/document/d/1JIhYrbk5LPjGQzxcGRBwvVpGztoh4fgUW4ITHGHqEzs/edit?usp=sharing) for more lesson content
- May be useful to also include the following sections:
   - Questions to Consider
   - Prerequisites
   - Motivation or Real-World Application
   - Objectives
   - Common Mistakes / Misconceptions
   - Supplemental Materials

### Acceptance Criteria
Include the following in the topic outline: 
- Prerequisites
- Learning objective
    - What is the difference between prod and deployment?
    - Participants unsure what this means? How to implement?
    - Understand why the server Local vs prod? Real world relation?
- Technical and set up requirements
- Visual content for walkthrough of how things should look

**Comment by jsnorek** [comment]
Hi I would like to tackle this issue :)

**Comment by daaimah123** [comment]
Congratulations on becoming a contributor! 🎉

I have assigned the issue to you, @jsnorek

**Comment by jsnorek** [comment]
Created a new branch for this issue and working on it now!

**Comment by jsnorek** [comment]
Created PR #2134 and linking reviewers

**Comment by jsnorek** [comment]
Received feedback and implementing changes to PR

**Comment by jsnorek** [comment]
Received approval - waiting for 2 more reviewers

**Comment by jsnorek** [comment]
PR has been reviewed, approved by all reviewers, and merged to main
