### ISSUE TITLE
Adjust the Final Project Curriculum 

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2108]
_Thanks for reporting an issue with the Techtonica curriculum! Please fill in the following information to help us resolve the problem as soon as we can._

### Page where problem found?
- [Final Project Directory](https://github.com/Techtonica/curriculum/tree/main/projects/final-project)

### Type of problem
- The existing requirement for participants creating their [project timeline during prep week](https://github.com/Techtonica/curriculum/blob/main/projects/final-project/planning-your-project.md) does not ask participants to incorporate the milestones laid out for each week's milestones.

### Acceptance Criteria
- Reference work from the incoming issues creating topic outlines that may be relevant to point/link to in your updates (be sure to include comments in this issue and the following about how you have made them related)  
     - reference incoming [render deployment topic outline](https://github.com/Techtonica/curriculum/issues/2106)
     - reference incoming [production topic outline](https://github.com/Techtonica/curriculum/issues/2107)
- [the prep topic outline](https://github.com/Techtonica/curriculum/blob/main/projects/final-project/planning-your-project.md)
     - make clear that participants should be incorporating [each week 1 - 4 milestones](https://github.com/Techtonica/curriculum/tree/main/projects/final-project#week-1-milestones) in their proposed timeline's work
     - ensure any details in [the prep google doc](https://docs.google.com/document/d/1NG41QXIa9C-q4-FMWcQi9g5Ncb3kffU3VwcM7Kw7Rvg/edit?usp=sharing), that are missing in the existing topic outline are added both into [the prep topic outline](https://github.com/Techtonica/curriculum/blob/main/projects/final-project/planning-your-project.md) and [the final project main topic outline prep section](https://github.com/Techtonica/curriculum/tree/main/projects/final-project#project-prep-week-milestones)
- Ensure any week 1 - 4 details in [the "all milestones" google doc](https://docs.google.com/document/d/1CcIJyAf9h9-Tua5TGsoaxwsQxhbW9tc5gHP0I2YMArY/edit?usp=sharing), that are missing in [the existing topic outline](https://github.com/Techtonica/curriculum/tree/main/projects/final-project#week-1-milestones) are added 
- add a section after week 1 - 4 that clarify that ["GitHub repository requirements for code and PR Collaboration"](https://docs.google.com/document/d/1CcIJyAf9h9-Tua5TGsoaxwsQxhbW9tc5gHP0I2YMArY/edit?usp=sharing) are weekly requirements
- Add a pre-requisite section in [the main final project](https://github.com/Techtonica/curriculum/tree/main/projects/final-project) exposing participants to [Final Project Crash Course](https://docs.google.com/presentation/d/1xbJ6KXlMo-9VsY2dU0qSpWdXa4eSwsHYD9aB1usk9R4/edit?usp=sharing)

**Comment by themagicianking** [comment]
Hello! I would like to tackle this issue.

**Comment by daaimah123** [comment]
Congratulations on becoming a contributor! 🎉

I have assigned the issue to you, @themagicianking

**Comment by daaimah123** [comment]
@themagicianking 

- Please change your PR to ready mode
- [Rebase and address branch conflicts](https://github.com/Techtonica/curriculum/pull/2130#discussion_r1888896250)
- [Reference the updated project template in your topic outline](https://github.com/Techtonica/curriculum/pull/2130#pullrequestreview-2506983549)

Please provide an update on the status of this issue, by 8:30am PT tomorrow.

**Comment by themagicianking** [comment]
@daaimah123 I have fixed all requested adjustments, rebased, and changed the description of the PR to reflect that! I'm now ready for review :)
