### ISSUE TITLE
Create compared-testing-frameworks topic outline

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2112]
Week 8, participants are introduced to new testing frameworks and there is no clear comparison of them all and their usecases. 

### Page where problem found?
Add a compared-testing-frameworks topic outline [here](https://github.com/Techtonica/curriculum/tree/main/testing-and-tdd)

### Type of problem
It may not be clear to participants when to use the various testing frameworks.

### Suggested Solution
- Create a topic outline that clarifies the differences between RTL, jest, vite, super test & when to use them. 
- Provide examples
- Answer the following questions
  - What is the difference between unit and integration testing?
  - What makes up a test suite?
- Leverage the information from the chart in [this day doc](https://docs.google.com/document/d/1t__kfUUSOliKp9xZfIQ8zkJYClfC4c69OhKKvzNKY1c/edit?usp=sharing), supertest is not in the chart
- Add a supplemental material section at the end with the following videos: 
  - 🎦 [Intro to Jest: Object & API Testing](https://www.dropbox.com/scl/fi/anmkgxuntp8uvlyduzpic/IntroToJestObject-ApiTesting.mp4?rlkey=smzcsizwb1legmhml4xolc72h&dl=0)
  - 🎦 [Jest Super Test Integration API Request Testing](https://www.dropbox.com/scl/fi/94h7u58t27zj55teusajo/JestSupertestIntegrationApiRequestTesting.mp4?rlkey=bap50gvtjsmxjt0gasczg3d7a&dl=0) with volunteer Cristina Rodriguez (she/her)
- May be useful to include the following sections: 
     - Questions to Consider
     - Prerequisites
     - Motivation or Real-World Application
     - Objectives
     - Common Mistakes / Misconceptions
     - Supplemental Materials
     
### Acceptance Criteria
1. **Create a compared-testing-frameworks topic outline**
The issue suggests creating a topic outline that clarifies the differences between RTL, Jest, Vitest, SuperTest, and when to use them. This outline should provide examples and address specific questions like:
      - What is the difference between unit and integration testing?
      - What makes up a test suite?

2. **Add supplemental material**
Include the following videos in a supplemental materials section:
      - Intro to Jest: Object & API Testing
      - Jest Super Test Integration API Request Testing with Cristina Rodriguez

3. **Leverage existing chart information**
The issue mentions leveraging information from a day doc chart, specifically noting that Supertest is not in this chart. This suggests incorporating Supertest information into the comparison outline.

4. **Provide clear guidance on framework usage**
The ultimate goal is to clarify when to use each testing framework (RTL, Jest, Vitest, SuperTest). This should be clearly outlined in the topic outline.

5. **Address common testing concepts**
Ensure the outline covers fundamental testing concepts like:
      - Unit testing vs Integration testing
      - Test suite composition
      - Mocking and stubbing techniques

6. **Include practical examples**
Provide concrete examples demonstrating how to use each framework in different scenarios.

7. **Ensure compatibility information**
Include any necessary configuration or setup steps required for each testing framework to work properly within the project environment.

**Comment by stmcpeters** [comment]
hey Daamiah! i've completed the instructions to become a curriculum contributor and would love to tackle this issue. can you please assign it to me? thanks 😄

**Comment by daaimah123** [comment]
Congratulations on becoming a contributor! 🎉

I have assigned the issue to you, @stmcpeters

**Comment by stmcpeters** [comment]
hey @daaimah123 can you allow me access to view the day doc with the testing framework chart mentioned in the above issue. thanks!

**Comment by daaimah123** [comment]
@stmcpeters, you have been given access to the document per request. I am noticing your PR is still in draft mode and no additional commits have been pushed up. Is the PR ready for review? If so, change your PR to ready mode, add reviewers and notify the respective parties that the PR is ready for review (via a courtesy message). 

Please provide an update on the status of this issue, by 8:30am PT tomorrow.

**Comment by stmcpeters** [comment]
hey @daaimah123, sorry for the delay! I have finished a draft of the topic outline and explained changes/additions in this [pull request](https://github.com/Techtonica/curriculum/pull/2129) and moved the issue into the 'in review' section of our Kanban board
