### ISSUE TITLE
Audit Projects for Weeks: 7, 8, & 11 (both app 1 and app 2)

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2116]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

------
The purpose of this ticket is to audit, report, and implement needed changes to the curriculum for areas of the existing full time program projects that aren't clear.

This audit should NOT implement a step by step walk through for each project if not already provided, but rather provide clarity about existing instructions and added context about why the project is necessary for learning.

Week 7: [Weather App](https://github.com/Techtonica/curriculum/blob/main/projects/weather-app.md)

Week 8: [Quiz App](https://github.com/Techtonica/curriculum/blob/main/projects/week8GameREADME.md)

Week 11: Two Apps in One Week
- [Contact App](https://github.com/Techtonica/curriculum/blob/main/projects/pern-contact-list-app.md)
- [Weather2](https://github.com/Techtonica/curriculum/blob/main/projects/pern-weather-app.md) -or- [Game2](https://github.com/Techtonica/curriculum/blob/main/projects/pern-game-app.md)

### Acceptance Criteria
- Things need adjustment: Create a PR with your implemented suggested updates making the projects / assignments more clear for full-time participants
- Nothing needs adjustment: Leave comments in this issue detailing what in the existing curriculum you are auditing is working and why

**Comment by daaimah123** [comment]
Thank you for grabbing this ticket! Looking forward to reviewing your work.

**Comment by mai-repo** [comment]
Status Update: I am working on this issue and have finished auditing the Projects for Weeks  7, 8, & 11 (both app 1 and app 2). I will be submitting a PR soon. :)

**Comment by mai-repo** [comment]
Status Update: Created a PR for the issue and the link to it is [here](https://github.com/Techtonica/curriculum/pull/2192).

**Comment by mai-repo** [comment]
This PR has been approved and all the changes are added to the main branch.
