### ISSUE TITLE
Create video for Security Slides

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [Techtonica/curriculum#214]
Create voice walkthrough for [Security Slides](https://drive.google.com/open?id=1mNyxzYGW-6M5yxBfJsxiwb9lcko5sa91thlBPKTodMg ). 

- [ ] Use QuickTime and record your voice, you can walk through each slide, and (optionally) provide more details about security while you read the slides.

**Comment by antislice** [comment]
Optionally, if you don't want to record your voice but you want to add more detail to the slides _for_ the video, add it as speaker notes and leave a comment here about it.

**Comment by alodahl** [comment]
found a security video
