### ISSUE TITLE
Update Twilio API topic outline

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2143]
### Page where problem found?

[Twilio API topic outline](https://github.com/Techtonica/curriculum/blob/8174f71e08d277f2cf1e00666875e2821b843064/api/twilio-api.md?plain=1)

### Type of problem

Some of the referenced technologies in the app are no longer services or features of the Twilio API. 

### Acceptance Criteria
- Remove the Omni (https://www.beomni.com/) reference 
- The topic outline needs to remove obsolete instructions and steps and update the screenshots and instructions where applicable

**Comment by akhilk2802** [comment]
is this issue resolved ? @daaimah123, can i take this ?

**Comment by daaimah123** [comment]
Hi @akhilk2802 can you confirm you’ve completed the contributor guideline steps? Under which name did you complete the volunteer form?

**Comment by akhilk2802** [comment]
Nope i am not sure about the form, can you give me a reference of how to do it ? 

Thanks

**Comment by daaimah123** [comment]
@akhilk2802 please kindly have a look at [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) 😉

**Comment by ChasVanDav** [comment]
May I take this issue? @daaimah123

**Comment by daaimah123** [comment]
@ChasVanDav I have assigned you to the issue and added the acceptance criteria

**Comment by ChasVanDav** [comment]
thank you! :) @daaimah123

**Comment by ChasVanDav** [comment]
@daaimah123  I took a look at Twilio and wanted to confirm if the features/instructions referenced in the api topic outline are deprecated. I think the scope of this issue needs to be examined given the updates to Twilio. I have attached the [api documentation](https://www.twilio.com/docs/usage/api).

**Comment by daaimah123** [comment]
@ChasVanDav can you give a summary of what you’ve found comparative to the acceptance and cite why this is out of scope, thanks.

**Comment by ChasVanDav** [comment]
@daaimah123  The weblink that once directed to Twilio's website, now routes to this github repository instead.
<img width="827" alt="Screenshot 2024-12-27 at 10 07 17 AM" src="https://github.com/user-attachments/assets/56fc8d01-5c0e-4aa6-be92-3c931920209d" />

**Comment by daaimah123** [comment]
This is enough context for staff to make a decision about the content!

**Comment by ChasVanDav** [comment]
That's great! @daaimah123 Please do let me know the next steps when you get back next week! :)
