### ISSUE TITLE
Add newer JS syntax to topic outline

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#2147]
### Page where problem found?
https://github.com/Techtonica/curriculum/blob/main/javascript/newer-JS-features.md

### Type of problem
The lesson is missing some newer features since the last update. 

### Suggested Solution
Add examples and explanations for things such as: 
- [Temporal](https://www.sitepoint.com/new-javascript-ecmascript/#temporal)
  - Modern date and time handling
  - Provides classes like PlainDate, PlainTime, ZonedDateTime
- [Pipe Operator](https://www.sitepoint.com/new-javascript-ecmascript/#pipeoperator)
  - Allows chaining functions in a more readable way
- [Records and Tuples](https://www.sitepoint.com/new-javascript-ecmascript/#recordsandtuples)
  - Immutable data structures similar to objects and arrays
- [RegExp /v flag](https://www.sitepoint.com/new-javascript-ecmascript/#regexpvflag)
  - Improves Unicode support in regular expressions
- [Decorators](https://www.sitepoint.com/new-javascript-ecmascript/#decorators)
  - Allow modifying or augmenting class, method, property, or parameter behavior
- [Symbols as WeakMap keys](https://plainenglish.io/blog/javascript-new-features-for-2023-and-2024)
  - Allows using Symbols as keys in WeakMaps
  - Provides unique identifiers for WeakMap keys
- [findLastIndex() method](https://plainenglish.io/blog/javascript-new-features-for-2023-and-2024)
  - Similar to findIndex(), but returns the index of the last element that satisfies the provided testing function
- [String.prototype.replaceAll()](https://www.sitepoint.com/new-javascript-ecmascript/)
  - Replaces all occurrences of a substring in a string
- [Object.fromEntries() static method](https://www.sitepoint.com/new-javascript-ecmascript/)
  - Converts an iterable of key-value pairs into an object
- [Promise.allSettled() method](https://www.sitepoint.com/new-javascript-ecmascript/)
  - Waits for all promises in an array to either resolve or reject
  
  
### Acceptance Criteria

- Ensure all new features are explained clearly and concisely
- Include relevant code examples for each new feature
- Maintain consistency with the existing lesson structure and style
- Update any related exercises or quizzes if necessary
- Review and update the prerequisites if needed
- Examples of what to include: 
    - Include Temporal API features:
        - Explain PlainDate, PlainTime, and ZonedDateTime classes
        - Provide examples of their usage
    - Add Pipe Operator section:
        - Explain how it allows chaining functions in a more readable way
        - Provide examples of its usage
    - Introduce Records and Tuples:
        - Explain immutable data structures similar to objects and arrays
        - Provide examples of their usage
    - Update RegExp section:
        - Mention the /v flag for improved Unicode support in regular expressions
        - Provide examples of its usage
    - Add Decorators section:
        - Explain how decorators modify or augment class, method, property, or parameter behavior
        - Provide examples of their usage
    - Include Symbols as WeakMap keys:
        - Explain how Symbols can be used as unique identifiers for WeakMap keys
        - Provide examples of their usage
    - Add findLastIndex() method section:
        - Explain that it's similar to findIndex(), but returns the index of the last element
        - Provide examples of its usage
    - Include String.prototype.replaceAll() section:
        - Explain how it replaces all occurrences of a substring in a string
        - Provide examples of its usage
    - Add Object.fromEntries() static method section:
        - Explain how it converts an iterable of key-value pairs into an object
        - Provide examples of its usage
    - Update Promise.allSettled() method section:
        - Explain how it waits for all promises in an array to either resolve or reject
        - Provide examples of its usage

**Comment by jsnorek** [comment]
I'll start on this issue

**Comment by daaimah123** [comment]
@jsnorek I have assigned you to the issue and added the acceptance criteria

**Comment by jsnorek** [comment]
Created a new branch to start on this issue

**Comment by jsnorek** [comment]
Started a PR request #2167 and linking reviewers

**Comment by jsnorek** [comment]
Received feedback on PR and will be implementing changes this week 👍

**Comment by jsnorek** [comment]
Responded to feedback and PR is ready for merge

**Comment by jsnorek** [comment]
PR has been reviewed, approved by all reviewers, and merged to main
