### ISSUE TITLE
Better link names in Supplemental Materials section of Opensource lesson

### ISSUE THREAD

**Issue by MaggieFero** [Techtonica/curriculum#2158]
This issue should not be worked until after PR #2153 has been merged, because that changes the contents of the list this applies to. However, I want to put this little chunk of the revision out of scope for that PR.

### Page where problem found?
https://github.com/Techtonica/curriculum/blob/main/open-source/open-source.md#supplemental-materials-not-listed-above

### Type of problem

Common examples:

Links are inconsistently-named, which makes the list somewhat hard to use

### Suggested Solution

Each link should have a display name that lists who made/maintains the list, the name of the list, and any filters applied by this specific link.

**Comment by ChasVanDav** [comment]
@daaimah123  May I work on this issue?

**Comment by ChasVanDav** [comment]
@daaimah123  for each of the links, we are tasked to:
-have a display name that lists who made/maintains the list, 
-the name of the list, 
-and any filters applied by this specific link.
<img width="1271" alt="Image" src="https://github.com/user-attachments/assets/af7e50c1-6cc9-4d9d-9c05-9f73ee5de4e7" />

the first link re-directs you to contributions home page of github --> https://firstcontributions.github.io/

The link for Up For Grabs is filtered for javascript but there are no available projects at this time.
<img width="1654" alt="Image" src="https://github.com/user-attachments/assets/527dc423-634a-43cc-a19a-59e62c8866b0" />
For the description, should I just have the website name, filter applied, and maintainer(s) username(s)?
<img width="617" alt="Image" src="https://github.com/user-attachments/assets/b45c9e7c-20a6-4f4c-a801-33af361ab46a" />

I would like more clarification on what information is relevant if available, and confirm if I can remove links that are redirected or have no available projects.

**Comment by daaimah123** [comment]
Correct, the ask is “Each link should have a display name that lists who made/maintains the list, the name of the list, and any filters applied by this specific link.”

Some of the filters are specified in the actual link (for example: #project-list)

Do not remove any of the links as their contents (when clicked into such as the up for grabs page) are constantly changing.

**Comment by ChasVanDav** [comment]
Got it! @daaimah123 I will have those changes ready for you asap, latest Monday!

**Comment by ChasVanDav** [comment]
<img width="854" alt="Screenshot 2024-12-29 at 11 30 46 AM" src="https://github.com/user-attachments/assets/00fe4d1f-f3d6-4117-88d2-03fd0c6a81c2" />


@daaimah123 I wasn't sure what information to draw from here to add as a maintainer of the open source project. Please let me know if what I did is what you are looking for. The pr should appear below this comment. I will tag you there as well.
