### ISSUE TITLE
Create Coding Challenges + Video

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [Techtonica/curriculum#218]
Use the [Coding Challenge Template](https://github.com/Techtonica/curriculum/blob/master/coding-challenges/coding-challenges.md)

**Comment by rcoh** [comment]
@Karla-Isabel-Sandoval what topic is this issue for?

**Comment by Karla-Isabel-Sandoval** [comment]
@rcoh it's from the Topic Outline Coding Challenges 127, f in [](https://docs.google.com/spreadsheets/d/1vIr3fiKa_jxzy7qtFsiE5hEJbiTXwc1LYxbfsHOYD6U/edit#gid=0)

**Comment by rcoh** [comment]
Just to clarify, this is a lesson _about_ coding challenges in interviews (how to prepare for them, how to do them, etc.)?
