### ISSUE TITLE
Update MongoDB topic outline.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#275]
Change "Erin" and "Allard" to example names and change "teacher"/"teachers" to "volunteer"/"volunteers."

**Comment by gitsteph** [comment]
☝️ Sorry about all the links there; didn't realize it did it automatically... (I rebased a couple times, since my auto-replace thing had a couple minor issues... all fixed now though)

**Comment by rcoh** [comment]
Awesome! Thanks!
