### ISSUE TITLE
Strengthen "Motivation" sections: multiple assignees encouraged!

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#288]
Edit any unchecked Topic Outline below that has an absent or incomplete Motivation section, and check it off once completed. If you notice it already fulfills the requirements, please check it off as well. One edited topic outline per PR, please, and once it’s merged you will receive ‘beginner’ points for gssoc. 

 Ensure that they have:
- Useful "Motivation" sections, and 
- 2 companies that use that technology, how they use it, and a  link to an example. Ideally, they are well-known companies.
- [Here's an example of a good motivation section.](https://github.com/Techtonica/curriculum/blob/master/css/media-queries.md#motivation)
- Hint:  If you are having trouble brainstorming, try searching for the technology here: https://stackshare.io/

If you're having trouble coming up with something, just google "why is it important to learn about [this topic]", and formulate an answer from the best results.  Please link the companies and any copied text.

If you have a question, please message Alina, or leave a comment and the tag "question" on the issue.

Topic outlines that have incomplete motivation sections:
- [x] https://github.com/Techtonica/curriculum/blob/master/personal-brand/personal-branding.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/professionalism/professionalism.md
- [x] https://github.com/Techtonica/curriculum/blob/master/ergonomics/ergonomics.md
- [x] https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md
- [x] https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/roles-in-tech.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/welcome-tips-rules/tech-industry-tips.md

- [x] https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-advanced.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/command-line/dot-profile.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/operating-systems/operating-systems.md
 
- [ ] https://github.com/Techtonica/curriculum/blob/master/command-line/keyboard-shortcuts.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/asking-good-questions/asking-good-questions.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/vs-code/vscode.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/networking/networking.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/conflict-resolution/conflict-resolution.md
 
- [ ] https://github.com/Techtonica/curriculum/blob/master/requests-and-responses/requests-and-responses.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/requests-and-responses/intro-to-dns-ip.md
 
- [ ] https://github.com/Techtonica/curriculum/blob/master/pair-programming/pair-programming.md
- [x] https://github.com/Techtonica/curriculum/blob/master/html/html.md
- [x] https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/git-version-control/gitignore.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/github-code-storage/github-storage.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/css/css.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/chrome-developer-tools/chrome-developer-tools.md
- [x] https://github.com/Techtonica/curriculum/blob/master/css/media-queries.md
 
- [ ] https://github.com/Techtonica/curriculum/blob/master/ui-ux-design/ui-ux-design.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/bootstrap/bootstrap.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/professionalism/building-confidence.md
 
- [ ] https://github.com/Techtonica/curriculum/blob/master/giving-presentations/giving-presentations.md
  
- [ ] https://github.com/Techtonica/curriculum/blob/master/diversity-inclusion-bias/inclusion.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/accessibility/accessibility.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/seo/seo.md
 

- [x] https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md

- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md
- [x] https://github.com/Techtonica/curriculum/blob/master/interviewing/whiteboarding.md
- [x] https://github.com/Techtonica/curriculum/blob/master/datetime/datetime.md

- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-7-oop.md

- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-8-regex.md
- [x] https://github.com/Techtonica/curriculum/blob/master/debugging/debugging.md

- [x] https://github.com/Techtonica/curriculum/blob/master/api/twilio-api.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-visualization/data-visualization.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/node-js/node-js.md
- [x] https://github.com/Techtonica/curriculum/blob/master/express-js/express.md
- [x] https://github.com/Techtonica/curriculum/blob/master/react-js/react.md

- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/linked-lists.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/searching.md

**Comment by antislice** [comment]
If a non-technical person is working on this and doesn't feel like they can do justice to the example company/screenshot request, just make a note that that step was skipped and it can be a separate task.

**Comment by alodahl** [comment]
This is a potentially big task.  I'm going to break it up into a few people fixing 10 motivations sections until we are out...I'm guessing there are about 50 lessopn outlines total.

**Comment by jonah-williams** [comment]
Is there an example of a motivation section you're currently happy with we can use as a guide for how much content to include?

**Comment by alodahl** [comment]
Hi Jonah, I'll send one over if I find it, but the idea is just to add a sentence or two about a tech company that uses what they are learning, how they use it, and a visual example if it seems relevant.

**Comment by alodahl** [comment]
@jonah-williams 
![image](https://user-images.githubusercontent.com/29131689/51216881-c0e9dd80-18da-11e9-89fe-6c6c01692e37.png)

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl can I work on the Git and version control motivation?

**Comment by alodahl** [comment]
@Rita-Okonkwo Yes!  I've set it aside for you.

**Comment by Rita-Okonkwo** [comment]
Thank you! Can I submit a PR before March 1st or should I wait till then?

**Comment by alodahl** [comment]
@Rita-Okonkwo You should wait until March 1 to get GSSoc19 points.

**Comment by Rita-Okonkwo** [comment]
Okay thanks Alina

**Comment by Jayashree-panda** [comment]
Hello @alodahl can I work on improving the motivation section?

**Comment by alodahl** [comment]
@Jayashree-panda Sure, which one(s) would you like to start with?

**Comment by Jayashree-panda** [comment]
@alodahl Thank you! I would like to improve the motivation section of html.

**Comment by Jayashree-panda** [comment]
@alodahl Hey! Can I work on to improve the motivation section of expressjs.

**Comment by devakisj1** [comment]
@alodahl ma'am i would like to work on the motivation section for ergonomics. Thank you

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl  can I work on improving the motivation section for linked list?

**Comment by vsharma20v** [comment]
@alodahl ma'am I would like to work on the motivation section of CSS

**Comment by vsharma20v** [comment]
@alodahl ma'am I would like to work on 
https://github.com/Techtonica/curriculum/blob/master/debugging/debugging.md

**Comment by alodahl** [comment]
@vsharma20v can you remind me after you finish the roles in tech outline?

**Comment by vsharma20v** [comment]
> @alodahl ma'am I would like to work on
> https://github.com/Techtonica/curriculum/blob/master/debugging/debugging.md

@alodahl ma'am now can I work on this. I already submitted a PR for roles in tech outline

**Comment by raibove** [comment]
@alodahl these topics contains motivation section but company name is not mentioned:
https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md
https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
https://github.com/Techtonica/curriculum/blob/master/command-line/env.md
https://github.com/Techtonica/curriculum/blob/master/ui-ux-design/ui-ux-design.md
https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
https://github.com/Techtonica/curriculum/blob/master/giving-presentations/giving-presentations.md

Is separate PR required for these topics.

**Comment by alodahl** [comment]
> @alodahl these topics contains motivation section but company name is not mentioned:
> https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md
> https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
> https://github.com/Techtonica/curriculum/blob/master/command-line/env.md
> https://github.com/Techtonica/curriculum/blob/master/ui-ux-design/ui-ux-design.md
> https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
> https://github.com/Techtonica/curriculum/blob/master/giving-presentations/giving-presentations.md
> 
> Is separate PR required for these topics.

Yes, they should all have example companies.
