### ISSUE TITLE
[Proposed] Re: Deployment Lesson Plan Modules & Timing

### ISSUE THREAD

**Issue by gitsteph** [Techtonica/curriculum#295]
@MichelleGlauser @Karla-Isabel-Sandoval 

I think `Deployment` could be very well served broken up into multiple parts -- some types of deployment are much easier than others, and there's value (and added excitement) in deploying something simple early (even as early as Week 1) and iteratively updating/seeing/sharing changes live as people learn new concepts and practices.

How I'd design this --
In Week 1, as people get set up with GitHub accounts and work on personal branding, there could be a `Deployment 1` mini-lesson plan that guides through how to get something very simple up on GitHub pages with their CV/resume/etc., and just enough HTML to render text.  That way, as they work on personal branding (linked below), they can iterate on their public page as the other content is completed to add to it.  This would naturally tie in with other lessons as well; as people learn how to use HTML/CSS/Bootstrap/JS/etc., they can continue building their hosted personal page out slowly and see it taking more complex form that they can share/write about... which can both solidify skills learned by encouraging folks to immediately apply it to their own projects and can build confidence.

So that eventually, when a `Deployment 2` mini-lesson plan comes along much later (to teach deploying on Heroku, or AWS, etc.), or when they want to maybe consider architecting a larger project from scratch, there's already some foundation to build upon.

Just a few thoughts

Related Plans:
Current Deployment Lesson Plan: [https://github.com/Techtonica/curriculum/blob/master/deploying/deploying.md](https://github.com/Techtonica/curriculum/blob/master/deploying/deploying.md)
Currently scheduled for: Week 24

Personal Branding Lesson Plan: [https://github.com/Techtonica/curriculum/blob/master/personal-brand/lesson-plan.md](https://github.com/Techtonica/curriculum/blob/master/personal-brand/lesson-plan.md)
Currently scheduled for: Week 1

**Comment by antislice** [comment]
I really like this idea! Also can help with confidence and a "I'm getting something out of this" feeling if there's something to show off early.

**Comment by gitsteph** [comment]
Yeah!!  My sentiments exactly (re: confidence-building).

BTW, still totally down to write this up if it's the right time for it/no one else has taken it on yet!

**Comment by rcoh** [comment]
I might start with Netlify to deploy static sites. It's extremely easy to get started with (easier than GH pages IMO) and is a bit better for when you want to move outside of Github.

For deploying their client/server apps https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0 covers it pretty clearly

**Comment by alodahl** [comment]
deployment 1 and 2 finished by @rcoh 👍
