### ISSUE TITLE
Write "What is tech?" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#30]
The lesson plan should live at [`what-is-tech/what-is-tech.md`](https://github.com/Techtonica/curriculum/blob/master/what-is-tech/what-is-tech.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by lianthompson** [comment]
test

**Comment by alodahl** [comment]
Michelle said this is no longer relevant.
