### ISSUE TITLE
Write "Welcome, tips, and rules" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#31]
The lesson plan should live at [`welcome-tips-rules/welcome-tips-rules.md`](https://github.com/Techtonica/curriculum/blob/master/welcome-tips-rules/welcome-tips-rules.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by alodahl** [comment]
can be found at https://github.com/Techtonica/curriculum/blob/master/welcome-tips-rules/tech-industry-tips.md
