### ISSUE TITLE
Write "Growth Mindset" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#33]
The lesson plan should live at [`growth-mindset/growth-mindset.md`](https://github.com/Techtonica/curriculum/tree/master/growth-mindset).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by alodahl** [comment]
Outline and slideshow requirements met here:

https://github.com/Techtonica/curriculum/blob/master/growth-mindset/YCLA_LessonPlan_v10.pdf
