### ISSUE TITLE
Write "Dev Tools Setup" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#35]
The lesson plan should live at [`dev-tools-setup/dev-tools-setup.md`](https://github.com/Techtonica/curriculum/blob/master/dev-tools-setup/dev-tools-setup.md) and teach students how to set up Sublime Text to write Python and JavaScript.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by alodahl** [comment]
satisfied by VS Code outline here:
https://github.com/Techtonica/curriculum/blob/master/vs-code/vscode.md
