### ISSUE TITLE
Write "Command Line Interface" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#36]
The lesson plan should live at [`command-line/command-line-interface.md`](https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md) and teach students how to

- make directories,
- move around,
- copy files,
- rename files, and
- use `man`.

Acceptance Criteria:
- [ ] The lesson can be covered in 2 hours
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by kristalane** [comment]
appears complete: https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md
