### ISSUE TITLE
Write "Advanced Command Line" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#37]
The lesson plan should live at [`command-line/command-line-advanced.md`](https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-advanced.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by kristalane** [comment]
appears complete: https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-advanced.md
