### ISSUE TITLE
Write HTML and CSS "Basic Attributes" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#38]
The lesson plan should live at [`html-and-css/basic-attributes.md`](https://github.com/Techtonica/curriculum/blob/master/html-and-css/basic-attributes.md).

Students should look at a sample page to figure out what different tags do, tinker, and eventually try their own (C9 or CodePen or W3Schools, JSLint to avoid needing setup. The lesson should cover block vs. inline, specific tags, and things not to use. By the end of the lesson, students should be able to view source on a web page and understand it.

For example, students should be able to
- Use `<h1-6>`, `<p>`, `<a>`, `<img>`, `<ul>/<ol>/<li>`, `<div>`, `<span>`, `<dl>/<dt>/<dd><form>/<fieldset>/<input>` semantically.
- Name classes and ids semantically.
- Use Web Inspector quickly (hint: keyboard shortcuts)."

See

- https://www.girldevelopit.com/materials/html-intro
- http://fellowship.hackbrightacademy.com/materials/lectures/html-combo/
- https://medium.freecodecamp.com/the-practical-guide-to-becoming-a-professional-web-developer-2f255bc25c90#.dylhyrijn

as reference sources.

Acceptance Criteria:
- [ ] The lesson should have a defined time scope (45 minutes? 2 hours? etc.)
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by alodahl** [comment]
satisfied by html & css outlines and accompanying projects
