### ISSUE TITLE
Fix Project 4.5 - node & mySQL

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#383]
https://github.com/Techtonica/curriculum/blob/master/projects/project-four-point-five.md
Replace Inquirer link with http://enzolutions.com/articles/2014/09/08/how-to-create-an-interactive-command-in-node-js/. 
Put starter code into the Techtonica curriculum repo's projects directory and change link.
Etc.

Probably the best way to start this is to just go through the steps and make notes with what was unclear, what didn't work, etc. Someone who's not a Node/MySQL expert will probably actually be best for this as they won't gloss over smaller difficulties.

**Comment by alodahl** [comment]
They will be studying sql and mongo.
