### ISSUE TITLE
Make specs for project plan doc.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#386]
For final projects, make "example-plan.md" for participants to submit as a Google Doc at the end of the first week and include someone's example with everything required during the planning phase and all the things people missed, like putting their names and titles and GitHub links in it, having a separate MVP and pitch with HOW the project does what it does, including the visual design plans, etc. Also include a link to the example project in the "Planning Your Project" outline.

**Comment by antislice** [comment]
I'm sure a volunteer could make a start, but will need to coordinate with Michelle about all the pieces required.
