### ISSUE TITLE
Incorporate a project that uses the Twilio API. 

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#389]

**Comment by antislice** [comment]
If this is something a volunteer is going to work on, should have more details about the expected size of the project, level of mastery assumed, etc.

**Comment by hnarasaki** [comment]
I found a great existing interactive Twilio tutorial (Twilio Quest) that takes users through creating automated text messages (there are also additional projects available through Twilio Quest). I could write an outline explaining what Twilio Quest is and what users can learn/work on through it.

**Comment by hnarasaki** [comment]
Created an outline of various Twilio exercises users can perform through the interactive website Twilio Quest. (Such as sending an automated text message and sending automated text message responses.)
