### ISSUE TITLE
Write HTML and CSS "IDs and Classes" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#39]
The lesson plan should live at [`html-and-css/ids-and-classes.md`](https://github.com/Techtonica/curriculum/blob/master/html-and-css/ids-and-classes.md) and have a similar workflow to the intro to HTML.

Students should understand

- floating and positioning,
- the box model,
- how to style text, and
- how to quickly build a simple layout.

One idea for an "assessment" would be to have the students participate in a build-the-ugliest-website competition.

The following may be used as references:

- https://www.girldevelopit.com/materials/html-intro
- http://fellowship.hackbrightacademy.com/materials/lectures/css/

Acceptance Criteria:
- [ ] The lesson has a defined time scope (45 minutes? 2 hours? etc.)
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/css/lesson-plan.md
