### ISSUE TITLE
Remove extra "Prerequisite" from topic outlines

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#392]
These have "Prerequisites" and "Prerequisite": https://github.com/Techtonica/curriculum/search?q=Prerequisites+Prerequisite&unscoped_q=Prerequisites+Prerequisite

**Comment by kristalane** [comment]
complete (can see when you open master branch of each file), but as of 8/21/18 Github doesn't seem to have indexed all the changes in search results.
