### ISSUE TITLE
create Negotiation lesson outline based on completed slideshow

### ISSUE THREAD

**Issue by kristalane** [Techtonica/curriculum#393]
- Check out [this completed Negotiating slideshow](https://drive.google.com/file/d/1Wfs7So04uwRLC042pX7OlUvzp92OJ8va/view?usp=sharing).

- [x] Save your Negotiating outline [to this file](https://github.com/Techtonica/curriculum/blob/master/interviewing/negotiating.md).
- [x] Make or find a video for the topic, and leave the link in the issue comments.

For FAQ on contributing, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
completed at https://github.com/Techtonica/curriculum/blob/master/interviewing/negotiating.md
