### ISSUE TITLE
create a slideshow for "Intro to Algorithms"  Lesson

### ISSUE THREAD

**Issue by kristalane** [Techtonica/curriculum#395]
- Check out [this completed outline](https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md) and [this introduction to algorithm concepts video](https://youtu.be/CvSOaYi89B4).

- [x] Create a slideshow to present the lesson to visual learners [in this file.](https://docs.google.com/presentation/d/1WlG5OgF0gf9fQYEEgIysNSfNaMiCASBi8RJa25SwMC4/edit?usp=sharing) Ask Alina for the edit link.

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
found linkedin slideshow
