### ISSUE TITLE
complete "object-oriented-programming" topic outline or combine with JS 6 lesson

### ISSUE THREAD

**Issue by kristalane** [Techtonica/curriculum#398]
https://github.com/Techtonica/curriculum/blob/master/object-oriented-programming/object-oriented-programming.md

Needs review to determine if the above md file is a duplicate of another JS lesson or requires more complete information.

looks like road map contains these slides/video: 
- https://drive.google.com/open?id=1N2eDw84BqmcqvNDjtQfNEF_7PO91z-IHTR44QXt3-oI
- https://drive.google.com/file/d/14c7KrecyuHysmXEjzTCFixCVUE3aZMqh/view?usp=sharing
- and this dead link to another lesson: https://github.com/Techtonica/curriculum/blob/master/javascript-6/oop.md

**Comment by alodahl** [comment]
I was able to organize the object-oriented lessons.  The only task left is addressed in issue #160 .
