### ISSUE TITLE
Learn more about how React fits within other frameworks, how it works with the back-end/database. Know how to fetch data from the database.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#400]

**Comment by vegetabill** [comment]
Hi @amychan331 I know this was a long time ago but did you actually add anything for this?

**Comment by amychan331** [comment]
@vegetabill My memory is a bit blurry since it is a while ago, but I looked up my pull request, and I think I closed it because I did #429 , but forgot to tag it. Sorry about the confusion!
