### ISSUE TITLE
Complete Vim topic outline

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#408]
For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

- [x] The partially complete Lesson Outline(needs work):
https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md

- [x] Slides Template(needs work):
https://docs.google.com/presentation/d/1739vUp2HuAh-f2JUIBkMvkozrlXI_HQBXpLEZg8y9as/edit#slide=id.p

- [x] Video Link:
Still needed

**Comment by MichelleGlauser** [comment]
Put it here: https://github.com/Techtonica/curriculum/tree/master/command-line

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md

**Comment by lindes** [comment]
Some work was done last night on the sections up to and including Materials.  Probably more to add to and/or edit in the sections done, and definitely Lesson onward still needs doing.

**Comment by alodahl** [comment]
no slideshow necessary
