### ISSUE TITLE
Make a topic outline based on completed slides on Memoization.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#413]
For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

- [x] Lesson Outline (needs work!):
https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/memoization.md

- Completed Slides:
https://docs.google.com/presentation/d/1BipDMgjZd3u-QsrPNCljH-Wv2l3tYRAUz8LWnxzt4s8/edit#slide=id.p

* Video Link:
https://www.youtube.com/watch?v=P8Xa2BitN3I

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/memoization.md

**Comment by MichelleGlauser** [comment]
Removed memoization.

**Comment by MichelleGlauser** [comment]
Slides here: https://docs.google.com/presentation/d/1BipDMgjZd3u-QsrPNCljH-Wv2l3tYRAUz8LWnxzt4s8/edit?usp=sharing

**Comment by julie-norris** [comment]
completed as a draft.

**Comment by alodahl** [comment]
Fantastic, @julie-norris !  Where is it?  I'm not seeing it at https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/memoization.md

**Comment by julie-norris** [comment]
Sorry -

Can you see it here..
https://github.com/julie-norris/curriculum/commit/9651c4ba4403490893fda945f52ab48b4a6c704f

GitHub challenges me :-/

**Comment by alodahl** [comment]
Hi Julie,

This looks great!  Just be sure to complete the Specific Things to teach
section, and you're ready to make a pull request to the
Techtonica/curriculum master branch!  Let me know if you need anything else.

Alina

**Comment by alodahl** [comment]
Hi Julie, I am organizing the WWC Holiday Party with another director, and will be helping her set up before 6, but the Techtonica volunteer event is still happening!
