### ISSUE TITLE
Find or create video and slides for Request and Responses topic, link in road map.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#415]
https://github.com/Techtonica/curriculum/blob/master/requests-and-responses/requests-and-responses.md

**Comment by tedyoung** [comment]
Need help creating a video/slides?

**Comment by MichelleGlauser** [comment]
@tedyoung: yes, want to review [these slides](https://docs.google.com/presentation/d/1Ny1BZiNO5heJ2Ad-PaakGL4S861W8CfL7LHYFeun7Io/edit?usp=sharing)? Also, we found these videos: https://www.youtube.com/watch?v=AEaKrq3SpW8 , https://www.youtube.com/watch?v=guvsH5OFizE Do you think those are good?
