### ISSUE TITLE
Complete resume/portfolio project directions to incorporate HTML, CSS, and Bootstrap.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#417]
Write a lesson plan that incorporates basic 
- [x] HTML, 
- [x] CSS, 
- [x] Bootstrap 
skills from the first two weeks of lessons into a real portfolio/resume for themselves.

Complete the "project directions", "questions to consider", and "extensions" this file:
https://github.com/Techtonica/curriculum/blob/master/projects/portfolio/portfolio-webpage-1.md

**Comment by alodahl** [comment]
#467
