### ISSUE TITLE
Put code challenges in Techtonica Repl.it classroom, make automatic tests.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#420]

**Comment by MichelleGlauser** [comment]
(The numbers should be the same as those in the road map and in the interview prep doc.)

**Comment by bnak** [comment]
This is finished! FYI some of the challenges don't have tests + code frameworks if they're `Write a class that...` or something similar. 

Repl.it classroom: https://repl.it/teacher/classrooms/89804
