### ISSUE TITLE
Create bash profile slides and video based on completed lesson outline.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#425]
Use [this completed lesson plan as a guide](https://github.com/Techtonica/curriculum/blob/master/command-line/dot-profile.md).

- [x] The slideshow should be saved over the example in [this google slides file](https://docs.google.com/presentation/d/1FeHmZRNz4ZgpGAfDAIHXNitofon3Uy-h13uCcyy2FuE/edit#slide=id.p).
- [x] Make or find a video that meets the outline objectives, and place the link in the "materials" section in the lesson plan markdown file.

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
video: https://youtu.be/vDOVEDl2z84
