### ISSUE TITLE
Find or make video for difficult workplace conversations/situations key objectives.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#427]
- [x] Save the lesson outline [in this file](https://github.com/Techtonica/curriculum/blob/master/professionalism/difficult-workplace-situations.md).

- [x] Find or make a slideshow that explains the learning objectives well for visual learners, and add a link to the "materials" section of the outline. If you are making it, please save the slides to [this file](https://docs.google.com/presentation/d/1m300Szsrmb60CxFlZq0ODqL96tmZcU9s7FDeoYKbc9U/edit?usp=sharing).
 
- [ ] Find or make a video that explains the learning objectives well for audio learners, and add a link to the "materials" section of the outline.

Apprentices will look at the lesson about common workplace issues on their own before forming groups to discuss the situations, and possible strategies.

Some examples are:
-I was assigned this project and 3 different people told me 3 different ways to do it
-I had an idea, and someone else took credit for it
- other common professional situations that will come up in their careers

For more detailed volunteering directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
picked up by julie norris

**Comment by imskr** [comment]
I will work on this.
