### ISSUE TITLE
Write "What is Version Control?" lesson plan

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#43]
The lesson plan should live at [`git-version-control/git-version-control.md`](https://github.com/Techtonica/curriculum/blob/master/version-control/git-version-control/git-version-control.md).

By the end of the lesson, students should understand
- add, commit, status, log
- rm, stash [pop], reset [soft/hard]
- remote [-v/add]
- push [-f], fetch, clone
- checkout [-b], merge, push -u

The following may be used as resources:
- https://www.youtube.com/playlist?list=PL5-da3qGB5IBLMp7LtN8Nc3Efd4hJq0kD
- http://www.thedom.io/journal/2015/8/12/temporary-post-learning-tools
- http://fellowship.hackbrightacademy.com/materials/lectures/git-1/

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
In here: https://github.com/Techtonica/curriculum/blob/master/git-version-control/lesson-plan.md
