### ISSUE TITLE
Yelp Recommender OOP project

### ISSUE THREAD

**Issue by spyapali** [Techtonica/curriculum#435]
--> Build Prototype for Yelp Recommender OOP project 
--> Components include: 
       --> User Class 
       --> Yelp Class 
       --> Restaurant Class 
       --> Tag Class (tag ratings(?)) 
       --> Ratings Class

**Comment by alodahl** [comment]
https://github.com/Techtonica/curriculum/blob/master/object-oriented-programming/restaurant%20recommender/RestaurantRecommender.md
