### ISSUE TITLE
Confidence in the Workplace: Make topic outline & find or make video based on completed slideshow

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#436]
For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

Base your outline and video choice on [this completed slideshow](https://docs.google.com/presentation/d/18XXIRn2AVWje-8sWErKzQyI_XPV_2aexmwTvkaO_ZPw/edit#slide=id.g22d1a3369e_0_101).

- [x] Write a topic outline in this file, replacing the template: https://github.com/Techtonica/curriculum/blob/master/professionalism/building-confidence.md
- [x] Find a video highlighting the same points as the lesson, or record a screen capture of someone explaining the slides. Place your link in the comments below.

**Comment by alodahl** [comment]
Issue Picked up by Natalie Kim

**Comment by natalie-kim** [comment]
Videos:
- Sheryl Sandberg impostor syndrome: https://www.youtube.com/watch?v=DNikR2GQwVg&t=39s
- Positive, Rational Thinking: https://www.youtube.com/watch?v=KjDfnUaFKCE
