### ISSUE TITLE
Write "GitHub" lesson plan

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#44]
The lesson plan should live at [`version-control/github/github.md`](https://github.com/Techtonica/curriculum/blob/master/version-control/github/github.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
Taken care of with https://github.com/Techtonica/curriculum/blob/master/github-code-storage/lesson-plan.md
