### ISSUE TITLE
Write "Collaborating with GitHub" lesson plan

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#45]
The lesson plan should live at [`version-control/git-collaboration/git-collaboration.md`](https://github.com/Techtonica/curriculum/blob/master/version-control/git-collaboration/git-collaboration.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
It's here now: https://github.com/Techtonica/curriculum/blob/master/github-code-storage/lesson-plan.md

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/git-version-control/lesson-plan.md
