### ISSUE TITLE
Write "Giving Presentations" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#46]
The lesson plan should live at [`giving-presentations/giving-presentations.md`](https://github.com/Techtonica/curriculum/blob/master/giving-presentations/giving-presentations.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by kristalane** [comment]
This topic outline seems complete (I may be biased... I wrote it ;) ): https://github.com/Techtonica/curriculum/blob/master/giving-presentations/giving-presentations.md
