### ISSUE TITLE
Make slideshow to accompany completed Scrum lesson outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#463]
- [ ] Save Scrum slideshow [into this file](https://docs.google.com/presentation/d/15PgPWy7qKllWVpmoAuN6J7uwegCAuiHAapf6Bnd9h8o/edit#slide=id.p). (it was copied from the Agile slideshow; please replace it with real examples of scrum methods ie: point system, sprint planning, etc)

- [Here is the completed lesson outline](https://github.com/Techtonica/curriculum/blob/master/agile-development/scrum.md) for you to follow.

-Here are 2 videos that will be included in the lesson: 
- What is Scrum?: https://www.youtube.com/watch?v=TRcReyRYIMg&feature=youtu.be
- Intro to Scrum Methods: https://www.youtube.com/watch?v=XU0llRltyFM

For more detailed volunteering directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by philihp** [comment]
This looks like the slideshow is already in line with the lesson outline

**Comment by alodahl** [comment]
found linkedin slideshow
