### ISSUE TITLE
Complete "Bootstrap" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#47]
The lesson plan should live at [`bootstrap/bootstrap.md`](https://github.com/Techtonica/curriculum/blob/master/bootstrap/bootstrap.md). By the end of the lesson, students should understand what responsive design is and how Bootstrap enables it.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
Just needs better projected time.
