### ISSUE TITLE
Create slideshow and video based on completed Functional Programming outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#488]
- Check out this lesson outline on Functional Programming: https://github.com/Techtonica/curriculum/blob/master/functional-programming/FP.md

 - [x] Create Functional Programming slideshow in [this file](https://docs.google.com/presentation/d/1n55Xbh7cHNmXuyIag5FL3RfzNjsJ3U0IIFEPGLrYahU/edit?usp=sharing) based on the completed lesson outline above. Request permissions or ask Alina for the edit link, then replace the copied slides with Functional Programming info.
 - [x] Create video narration or find an explanatory video and place link in the "materials" section in the completed outline linked above.

For more FAQ about contributing, see: https://github.com/Techtonica/curriculum#volunteering

related to issue #397

**Comment by alodahl** [comment]
picked up by Josh Guffey

**Comment by jguffey** [comment]
👋

**Comment by alodahl** [comment]
🏅 @jguffey
