### ISSUE TITLE
Write "Sass" lesson plan

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#49]
The lesson plan should live at [`sass/sass.md`](https://github.com/Techtonica/curriculum/blob/master/sass/sass.md). The lesson should discuss mix-ins and variables.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
Completed with this commit: https://github.com/Techtonica/curriculum/commit/aedac988590c95c221659418fa051e32997ed9a8#diff-07ecdbd6564d58f76217920741deef83
