### ISSUE TITLE
How to add node backend unit tests: finish slideshow

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#500]
Prerequisites: #961 Done

- [x] ~Finish the backend testing topic outline here:~
https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/integration-testing.md
- [ ] Test steps in the the above outline to proofread for bugs
- [ ] Finish the backend testing slideshow here: https://docs.google.com/presentation/d/1no4BY2e74QoHJlkO7LIOV-qlcqQ2viQbyJlEDyptmeY/edit?usp=sharing.  We need some screenshots of test code and running tests on the CLI!
- [x] ~Find or create a node unit test video, and add the link to the materials section in the topic outline file.~

The topic trio should include:
- [x] ~how to label files~ 
- [x] ~what, if any, packages, and how to include them in test files~
- [x] ~how to run tests and debug in the command line.~
- [x] ~resources for docs and examples~
- [x] ~video~
- [ ] slideshow should include images of all above processes, either from found video, or screenshot. The only exception is if you find a tutorial that already does this very well.

For FAQs on contributing, see https://github.com/Techtonica/curriculum

**Comment by zspencer** [comment]
I took ~15m to read through and poke at the steps. I changed Step 2 slightly to spell out the names more explicitly, use keyword arguments instead of positional arguments (To make names of things more traceable) and add jsdoc-esque syntax for the mocking functions - https://repl.it/repls/WhirlwindTrimHandwritingrecognition.

I don't know how to run the specs tho with repl.it :(. I am unlikely to get more time to poke at this today, but I am happy to work on it (or something similar!) Wednesday when I come in and volunteer!

I want to make sure I'm spending at least ~2 of the volunteer hours with the learners, but happy to spend ~2 focusing on the curriculum.

**Comment by NirmalKumarJoshi** [comment]
Assign me this, I would like to fix it,

**Comment by alodahl** [comment]
@zspencer I would love that!  I will be around tomorrow afternoon.  Would you tell me which repl.it the above link is an update for? BackendTesting-I, II, or III?

**Comment by zspencer** [comment]
@alodahl Yay! Looking forward to it! The repl.it is from the second one, the one where tests are being added to the existing app.

**Comment by zspencer** [comment]
Unfortunately I am ... bad at planning and didn’t realize I would need my laptop to run through this. I _did_ run through the first example in repl.it; and it looks good! 

Updates - 

• I went through backend-i and added comments - https://repl.it/repls/DearLavishPhysics
* I have migrated backend-ii to glitch. You can run the tests by running `npx mocha` From the glitch console. I have also updated the README ever-so-slightly to include instructions.

Some minor notes:
* This feels like a multi-day challenge. Anywhere from 1 to 4 days.
• The example in `backend-i` starts with the API and not the User Interface. Part of me feels like it is more likely to “stick” if we start by building on the pieces of express that they are more “comfortable” (making forms and web pages) and using those forms to submit data to express. Jumping right into Postgres seems huge.
• I would encourage authors to “group” their variables and functions  in the code based upon usage. When we define a variable way before it  is used, even as part of the `require` Blob at the top of the file, it makes it hard to figure out why the variable exists without scrolling. It also makes it easy to extract a module in production contexts

**Comment by alodahl** [comment]
Hey @zspencer, I love this idea! But since the apprentices are going to read this tomorrow, we really just need to smooth out what's there.  After tomorrow, we can totally re-think the lesson if we want, or add a more basic exercise preceeding the replit examples.

Also, did you change the lesson to include you glitch link?

**Comment by zspencer** [comment]
Sadly I cannot edit GitHub. My notes are more for “in the future maybe” but the repl it and glitch links are safe to drop in

**Comment by alodahl** [comment]
@zspencer Sweet, thank you!

**Comment by alodahl** [comment]
@zspencer how do you run the glitch app?

**Comment by zspencer** [comment]
Ahh I should add that to the README! You click the "Show" button with the sunglasses.

**Comment by alodahl** [comment]
@zspencer Sure, look at the note I added next to the glitch link in the outline, and add more detail if you think it will help.

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl is anyone working on this?
cc @manaswinidas @Kundan28

**Comment by alodahl** [comment]
Hi @Rita-Okonkwo remind me after you finish fixing your PR. No one is working on this now.

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl , can I take this up?

**Comment by Rita-Okonkwo** [comment]
cc @saberprashant

**Comment by yati1998** [comment]
Hey, Can I work on this issue @alodahl ?

**Comment by alodahl** [comment]
@yati1998 you still need to fix #778

**Comment by alodahl** [comment]
@Rita-Okonkwo how is this issue going?  Will you be able to finish?

**Comment by alodahl** [comment]
Hi Rita, you have had this issue for the whole month. If I don’t hear from you in the next day or 2, I will make this issue available to other participants.

**Comment by saberprashant** [comment]
Hi @alodahl , @Rita-Okonkwo confirmed that she won't be able to work on this issue now as she is busy with her school, so I think we should assign this issue to someone else now.

**Comment by vegetabill** [comment]
If this does not get done during gssoc20, I'm closing it unfinished

**Comment by Kundan28** [comment]
@vegetabill GSSoC20 has not been yet started...so it would take some time.

**Comment by Kundan28** [comment]
@vegetabill I'm good to mentor this project and I've worked on this project as a mentor in past too. So I request you to please select me as a mentor for this project.

**Comment by vegetabill** [comment]
That whole lesson is under revision. See #1216

This is a moot issue. Closing
