### ISSUE TITLE
Schedule "informational interview reportback roundtable" in February and let apprentices know

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#512]
From [roles-in-tech](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/roles-in-tech.md):
>A month from now, in a roundtable discussion format, share and compare notes from the conversations had during the project portion of this topic.

Let's get this in the roadmap!

**Comment by alodahl** [comment]
![image](https://user-images.githubusercontent.com/29131689/51143276-01762800-1803-11e9-9b43-1f898bbc53bc.png)
