### ISSUE TITLE
Find or make a video for Advanced Command Line topics

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#513]
The [Advanced Command Line topic outline](https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-advanced.md) is not quite finished.  Please help us complete:

- [x] Outline Section: Guided Practice
- [x] Outline Section: Challenge
- [x] Outline Section: Check for Understanding
- [x] Proofread topic outline
- [ ] Find or make video, add link to "materials" section in outline
- [x] Find or make slideshow about lesson, add link to "materials" section in outline

For FAQ on contributing, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
Anule is working on the slideshow

**Comment by Soumya0803** [comment]
@alodahl I would like to work on this issue.
