### ISSUE TITLE
Clarify when code blocks are commands vs. file contents in the .profile lesson

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#515]
https://github.com/Techtonica/curriculum/blob/master/command-line/dot-profile.md 

Apprentices were attempting to run what was meant to be put into a file on the command line

**Comment by alodahl** [comment]
Hi Judy, is this urgent, or just a fix for the future?

**Comment by alodahl** [comment]
If it's urgent, you can put it in the "open-source curriculum to-do" project and I will try to address it asap with volunteers; otherwise just making an issue for it to get done someday is fine.  If it's super urgent, like "today", then let me know in a comment and I'll get on it =)

**Comment by imskr** [comment]
I would like to work on this.
