### ISSUE TITLE
Write "Developer Advocate/ Evangelist" topic outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#519]
The intention is to present Developer Advocate/ Evangelist roles, and steps to take if one is interested in a career in That field.  

- [x] Create a topic outline [here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/developer-advocate.md).

- [ ] make a slideshow version of the topic. You can make a copy of this old Dev Evangelist slideshow and customize: https://docs.google.com/presentation/d/15Ws1i7szpyhzHhLuHa_LTo9uNGrHg4bujcHq0we2fGM/edit?usp=sharing

Acceptance Criteria:
- [x] The lesson can be covered in 30-45 minutes
- [x] There are clear objectives
- [x] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [x] There is a question-based assessment for Check for Understanding

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by yati1998** [comment]
Hello I would like to work in this, Can I?

**Comment by alodahl** [comment]
@yati1998 would you like to take this one once you finish #585 ?

**Comment by yati1998** [comment]
@alodahl yes sure. I have already completed #585 would make PR on 1st March. And would also like to take this.

**Comment by yati1998** [comment]
@alodahl do I in need to makes changes  in developer-advocate.md or in the Slides?
And what changes exactly I need to do?

**Comment by alodahl** [comment]
@yati1998  Both the md file and the slides need to be created from scratch! I have just provided templates.

**Comment by yati1998** [comment]
@alodahl from where will I get the links to the courses required in the description.

**Comment by yati1998** [comment]
And do I need to describe the steps to learn data science from scratch? and the same slideshow will be made?

**Comment by alodahl** [comment]
That is up to you, @yati1998!  Yup, all from scratch with a slideshow version of the lesson.

**Comment by yati1998** [comment]
@alodahl Earlier it was mentioned that we need to make in the field of data science.  Now the statement is changed. What exactly is the field For which we have to make the lessons and slideshow?

**Comment by alodahl** [comment]
Sorry, @yati1998, I realized I had made mistakes in the issue description. It should only be about developer advocacy/evangelism.

**Comment by yati1998** [comment]
@alodahl what kind of lesson will I have to create. Can it be link to different articles. I can't get a complete idea on this issue. It would be great if you can help me briefing this issue.

**Comment by alodahl** [comment]
@yati1998, articles sound good! Have you looked at the topic outline template? It’s pretty descriptive about what is needed.https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/developer-advocate.md

**Comment by yati1998** [comment]
yes I am working on that template. Will soon make a coomit.

**Comment by MichelleGlauser** [comment]
Here are some more resources recommended by Twilio DevRel folks: 
https://medium.com/@codepo8/what-does-a-developer-evangelist-advocate-do-3ad936dff3e4
http://blog.rickyrobinett.com/2015/01/should-i-become-a-developer-evangelist/
http://developer-evangelism.com/
https://talkpython.fm/episodes/show/189/war-stories-of-the-developer-evangelists
http://www.devangel.io/
https://devrelweekly.com/issues

**Comment by yati1998** [comment]
How can I make the slide show version of the lesson. I have seen the one mentioned in the link. Does that contains exactly the same topics and I need to change the  contents? Can you help me out with the sildeshow detail?

**Comment by alodahl** [comment]
You are going to need to make a copy and make your own slideshow based on your topic outline, @yati1998 . Once you’re done, you can transfer the ownership to techtonicaorg@gmail.com.

**Comment by yati1998** [comment]
I have made a PR. Please do mention if any changes are required.

**Comment by yati1998** [comment]
Issue #519  Solved.

**Comment by alodahl** [comment]
@yati1998 Your outline looks great!  How is the slideshow coming?

**Comment by yati1998** [comment]
@alodahl I have sent the link of slideshow in the mail and it is also in the topic outline.
