### ISSUE TITLE
Finish up "Intro to Security" (1 hour of work or less)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#535]
Here is a very short task, but the catch is it needs to be done before March 6!

Someone with security knowledge needs to finish up [this topic outline](https://github.com/Techtonica/curriculum/blob/master/security/web-security.md). The intention is to give apprentices an intro and ways to implement some basic security in their JS/NodeJS projects. Thank you!

- [x] Please define/explain CSRF & XSS.
- [ ] Topic outline needs more clear directions for the independent practice steps 5&6. Just because there are links doesn't mean that the apprentice knows what they are looking for...it's a bit TOO challenging.
- [x] Topic outline needs short check for understanding so students can self-assess security knowledge
- [ ] Topic outline needs 1-3 example companies and their use of tech security under the "motivation" section.

- [Here is the accompanying slideshow.](https://docs.google.com/presentation/d/1mNyxzYGW-6M5yxBfJsxiwb9lcko5sa91thlBPKTodMg/edit?usp=sharing)  Ask for permission if you'd like to change this, too.

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by bobbylcraig** [comment]
Hey @alodahl 👋 Just started looking through these slides and I've got a few suggestions (mostly in providing some further explanations and breaking up massive slides into more approachable bits).

I can also work on the second and third checks––this'll just end up being a really long lesson/deck. Let me know what your thoughts are :)

**Comment by alodahl** [comment]
@bobbylcraig thank you so much!🤩We definitely need that for the slides.  I've changed the permissions for you...let me know if  you need anything else.

**Comment by alodahl** [comment]
Outline picked up by Matt Torbin

**Comment by bobbylcraig** [comment]
FWIW I looked through the outline last night and started to wade through the slideshow last night. The outline looks pretty good AFAIAC. It _is_ an enormous lesson.

Will continue to look through slideshow (hopefully finish) tonight.

**Comment by alodahl** [comment]
@bobbylcraig Do you have a sense for how long it might take for a beginner to work through?

**Comment by bobbylcraig** [comment]
It's hard to tell. It's 15 slides now and still needs broken into more and to have extra content added. Could end at 30 slides. A minute or two spent on a slide?...I guess it adds up?

What's the general range we shoot for in terms of lesson duration?

**Comment by bobbylcraig** [comment]
The Mickey Mouse gif in the presentation gives me life.

**Comment by alodahl** [comment]
@bobbylcraig How's the slideshow coming?

**Comment by bobbylcraig** [comment]
Will finish it up tonight! Sorry! Got stuck in the middle of a move

**Comment by bobbylcraig** [comment]
Hey! It should be updated and ready for re-review? I added a little bit and trimmed some slides––tried to keep it as short as possible though.

**Comment by alodahl** [comment]
@bobbylcraig The slideshow is so much better, thank you!! 🏆

**Comment by Yugandhartripathi** [comment]
I am on it. :+1:

**Comment by Yugandhartripathi** [comment]
@alodahl @manaswinidas please review and let me know if any changes are required.
