### ISSUE TITLE
Finish 'Hash Tables' slides.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#538]
Base the slideshow on [this topic outline](https://github.com/Techtonica/curriculum/blob/master/data-structures/hash-tables.md). We're also including [this video](https://www.youtube.com/watch?v=shs0KM3wKv8).

- [x] Proofread and Finish [this partially complete slideshow](https://docs.google.com/presentation/d/1V9liCnncXJDXZ0CK_MbXfFrWz6cwGucTYdIkHdkJ9_8/edit?usp=sharing) Introducing Hash Tables.
- [x] Proofread and Finish [this mostly complete slideshow](https://docs.google.com/presentation/d/1-zCx1fc5cUP6rklL-CrYzmO8ibcXztsOZxJUv3Fpd-s/edit?usp=sharing) on Implementing Hash Maps.

**Comment by bobbylcraig** [comment]
👋 Interested in helping! Two questions:
1. Was the second "mostly complete slideshow" finished or is it just missing a link?
2. Should we edit the slideshow directly or create a duplicate and then submit a link to the duplicate?

**Comment by alodahl** [comment]
Hi Bobby, I forgot to link the second one!  Neither of them are done.  You are welcome to directly edit; let me know if you don't have access. Thanks for offering to help 😁

**Comment by bobbylcraig** [comment]
👋 Hello again! I read through and updated the presentations. There might be a bit of information overlap, but I figured that's not horrible for review. Second presentation looked mostly complete so minor additions and proofreading 😄 

I double checked and the "Objectives" and "Specific things to teach" from the topic outline should all be covered by those presentations. Let me know if there are any issues! The video looks awesome.

**Comment by alodahl** [comment]
Thank you so much @bobbylcraig ! This is exactly what we needed.🏆

Would you be willing to look at our Queue and Deque issues in the near future?
