### ISSUE TITLE
judy's grab bag (split and sort later)

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#544]
I find myself saying things to apprentices over and over again. I'm trying to write them down and maybe later I'll find a place for them to go in the curriculum.

- [ ] IC vs manager track. IC in this case means individual contributor (not independent contractor). explain engineering ladder for career progression vs manager ladder. link to sarah mei's tweet about "have someone get really good at something for 18 years then do something else"

- [ ] "managing up" lingo for getting what you want out of 1:1s 

- [ ] team structure (tech lead, 6 or 7 engineers, engineering manager, design, product manager. how you might work together. 

- [x] agile vs waterfall

- [ ] lean startup lingo

- [x] hackathons

- [ ] the phrase "product market fit" 

- [ ] sourcetree for visualizing git

- [x] lorem ipsum text, images

- [ ] ask ingrid to add the sentence "bootstrap columns are like counting lego pegs" to the bootstrap lesson

- [ ] challenges for various sessions, like CSS

- [ ] https://github.com/htmlandcssclass/floating_block_layouts 

- [ ] design tools: sketch (plus plugins like stark for accessibility), omnigraffle for flow charts ($ tho) (visio on windows), invision // zeppelin (view only for devs. margin here is 20px)

- [x] whiteboarding; see https://github.com/Techtonica/curriculum/issues/71 

- [ ] start a catch-all doc for questions to ask during interviews, like "can you tell me about how engineers work with your designers" etc

- [ ] [lingo] what people mean when we talk about "resources" (people, as in "we lost resources so we didn't finish the project on time"). "expensive" as in "this is harder or takes more time to do" 

- [ ] pivotal tracker lesson maybe? pointing exercise 

- [ ] trello ... pomello (pomodoro + trello) ... asana ... ALL THE TOOLS 

- [ ] do [women in tech resources](https://github.com/Techtonica/curriculum/blob/master/women-in-tech-resources/resources-list.md) way earlier. also see associated issue https://github.com/Techtonica/curriculum/issues/183 

- [x] -[X] developer evangelist/relations/advocate - would be in career week

- [x] *mac*
- [x] - two fingers to scroll on touchpad
- [x] - pairing a magic mouse: put it in discovery mode by 1. turn it off. 2. hold down the mouse "button" and keep holding while you 3. turn it on (using the tiny switch on the back). then the green light should blink twice repeatedly. https://apple.stackexchange.com/a/181549 
- [x] - rename your magic mouse so you can identify it (and not steal someone else's mouse) 

- [x] *VS Code and editor setup*
- [x] - how to auto indent
- [x] - how to indent multiple lines at a time (highlight several lines, even just partial lines, then press tab to indent the entire code block, or shift+tab to un-indent the entire code block; internal indentation of the block will be preserved. useful for copy and pasting code) 
- [x] - code folding
- [x] - autosave 
- [x] - mention that VS Code preferences are literally a text file full of key-value pairs

- [x] - define key value pair somewhere 

- [x] *CSS*
- [x] - reset.css basics (find a resource online, or even a video) // exercise where you try a simple website with and without a reset.css and observe the differences. i do not expect everyone to begin using a reset.css in their projects immediately; this is really so people learn about the user agent stylesheet. 

- [x] *teaching debugging*
- [x] - i should do more interactive sessions with chrome dev tools 
- [x] - the phrase "pattern matching" and why it's important: use other code snippets to remind yourself of correct syntax
- [x] - when VS Code shows you a red squiggly underline, it's trying to help. pay attention to the message. 
- [x] - if the red squiggly underline is under something that's clearly correct, like `color: red;` in a css file, then first check if it really is correct
- [x] - when you make a change on a file, and then visually when you refresh your page you don't see any changes, run through a quick checklist: 
- [x]   - did you save? this kills me every time (see: add autosave to VS Code lesson if it's not already there)
- [x]   - make a temporary, very obvious change on your html page. i write some text in the top of the body, or a prominent heading. save the file and reload the browser. verify that you see the text. if you don't see the new text, maybe you have the wrong file open, or the file didn't save, or something else very strange is happening. 
- [x] - make a temporary, very obvious change to your css file. i like to add `color: red;` to something extremely obvious like `body` or `h1`. save and reload the browser and verify that the thing you expected to turn red actually turns red. if it doesn't, maybe the CSS file isn't getting loaded properly. or check for syntax errors earlier in your CSS file that may render the rest of your CSS file inoperable. are you missing a semicolon? did you use `=` instead of `:` accidentally? are you missing a quotation mark in a font declaration, so your CSS file thinks there's a really long string somewhere? are your curly braces correctly matched and closed? 

- [x] *bootstrap*
- [x] - containers inside of containers. talk about rows and columns.
- [x] - rows vs "masonry-style" a la pinterest 
- [x] - clarify order of overriding. large overrides small when screen is large. col-xs-12 col-lg-6 for example

- [x] add https://guide.bash.academy/inception/ as beautiful resource (via aaron/kelly)

- [x] add https://github.com/GoogleChrome/lighthouse to chrome dev tools or accessibility. it now comes in chrome. find it under audit

**Comment by judytuna** [comment]
explain CamelCase, kebab-case, and snake_case

**Comment by judytuna** [comment]
explain a11y and i18n

**Comment by judytuna** [comment]
quantified self (maybe first week during ergonomics)

**Comment by alodahl** [comment]
'do women in tech resources way earlier. also see associated issue #183'

Should we just move what we have to the next week or two so apprentices are aware, @judytuna ?

**Comment by judytuna** [comment]
add to computer shortcuts: beginnings of opsec. 
- have a password on your machine 
- set screensaver (or monitor off) with locking if you're idle for a minute 
- never walk away from your computer without having it locked / never leave your computer unattended and open with your work, browsers logged in with email and social media, pictures, private docs 
- maybe mention full-disk encryption but don't require it (maaayyybe) 
- should we cover "find my mac" ? 
- backups -- see message in techtonica slack from volunteer + dropbox free plan

**Comment by judytuna** [comment]
fix repl.it 1/30 - Code Challenge # 24 
- question wording is ambituous: `sequence` is required???
- my suggested fix: remove the word sequence and make it not required
- then make a second challenge that includes the sequence, so the problem is you need to see a 1, 2, 3 together in order

**Comment by judytuna** [comment]
ideas for future code challenges 

annie's team's funny notes about triple-double-letter-words
- first write a function that tells you if a string has two letters repeated, like `book`
- then write a function that tells you how many consecutive repetitions there are. `bookkeeper` has three. so does `tattooee`, the person getting the tattoo. `noonmoon` (which is not a word) has two sets of double letters, but they're not consecutive, so that doesn't count; the input `noonmoon` would return 1 
- then write a function that takes an array of single words and prints out the words that have the most consecutive two-letter-repetitions 

for the `switch` exercises involving setting the alarm
- break it down so that at first, there's only the question of weekend vs weekday 
  - the point of this is to teach an example of *not* using break. use multiple `case 1:` `case 2:` statements without a break for one block of logic 
- then introduce on_vacation and show that you have to nest your if/else or your new nested switch inside both cases

**Comment by judytuna** [comment]
pass by value vs pass by reference, with examples

**Comment by judytuna** [comment]
Check for Understanding worksheets in pods, people are loving it

**Comment by judytuna** [comment]
gravatar API

**Comment by alodahl** [comment]
@judytuna , I know you're swamped, but if you want to break off some of your easy tasks, they're getting snatched up quickly by GirlScript(GSSoc19) folks!

**Comment by judytuna** [comment]
awesome!

**Comment by alodahl** [comment]
Hi Judy, I've made issues out of all the points in your first main description that made sense to me. The rest require more explanation before I know what to ask of a volunteer.  Can you add more details or make them into issues yourself when you get the chance?

**Comment by vegetabill** [comment]
This seems really context-dependent and I have no way to tell which of the above ideas is worth doing. I'm going to link this from the SEAM Handbook as an example of some ideas but I think each SEAM is going to have their own personal backlog, and only promote certain items to public issues, at least that's what I imagine based on a data point of me.

**Comment by alodahl** [comment]
I converted all the ideas that made sense to me a while back, so I agree.
