### ISSUE TITLE
set up git

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#545]
We need a git lesson between the basics of git ( https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control.md ) and GitHub for Collaboration ( https://github.com/Techtonica/curriculum/blob/master/github-collaboration/github-collaboration.md ) that covers: 

GIT ONLY

- understanding how to peek into your git project root's hidden `.git` directory 
- understand the difference between your home directory's `~/.git/config` file and any given git project's own `.git/config`
- setting your computer's global git user name and email (and peeking into `~/.git/config`) https://help.github.com/articles/setting-your-username-in-git/ 

- understanding what branches are, BEFORE doing anything with different branches on github. the `githug` game covers branches. switch between different branches. use https://gist.github.com/joseluisq/1e96c54fa4e1e5647940 (thank you tiffany!) for keeping track of what branch you're on. 

CONNECTING A GIT REPO ON YOUR OWN COMPUTER TO ONE OF YOUR OWN GITHUB REPOS

- `git remote add origin ___`
- `git remote -v` 
- recognizing any remotes you've added in your git project root's `.git/config` file
- setting up an SSH key on your own machine, then adding it to github https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ and some basic understanding of id_rsa vs id_rsa.public

There are such great tutorials online that I think this shouldn't be so much a lesson as a checklist. I want to set people up for success BEFORE doing "GitHub for Collaboration" on the next day.

**Comment by alodahl** [comment]
checklist now in https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control-part2.md and assigned for the end of week 2.
