### ISSUE TITLE
fix repl.it 1/30 - Code Challenge # 24

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#558]
fix repl.it 1/30 - Code Challenge # 24 
- question wording is ambituous: `sequence` is required???
- my suggested fix: remove the word sequence and make it not required
- then make a second challenge that includes the sequence, so the problem is you need to see a 1, 2, 3 together in order

_Originally posted by @judytuna in https://github.com/Techtonica/curriculum/issues/544#issuecomment-459179557_

**Comment by yati1998** [comment]
Hello, I wpuld like to work on this. can I?

**Comment by alodahl** [comment]
@yati1998, that would be great!  Are you part of gssoc?

Since we are a US Non-profit, please be sure to fill out this form before you start this project: https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

**Comment by alodahl** [comment]
@yati1998, here is the problem and the existing code.  Pleased return it in a comment here when it is complete.

Given an array of ints, return True if the sequence of numbers 1, 2, 3 appears in the array somewhere.


array123([1, 1, 2, 3, 1]) → True
array123([1, 1, 2, 4, 1]) → False
array123([1, 1, 2, 1, 2, 3]) → True

**Comment by alodahl** [comment]
hi @yati1998 , how is this issue going?

**Comment by yati1998** [comment]
@alodahl working on this.  Will try to make pr asa soon as possible.

**Comment by yati1998** [comment]
@alodahl  In which file is this code? and where to make the changes. Can you please highliht the file?

**Comment by alodahl** [comment]
It is not in a file, it is just the problem above that we’re using for our code practice challenges. Once you finish fixing the listed problems, I’ll find a way for you to submit a symbolic PR. @yati1998

**Comment by yati1998** [comment]
Q: Given an array of ints, return true if 1, 2, 3 occurs in sequence in the array.
Ans:
tests = {"1":[1,1,2,3,1],"2":[1,1,2,4,1],"3":[1,1,2,1,2,3]}  
def array123(array):
    state1=False
    state2=False
    state3=False
    if len(array) < 3:
        return False

    for (index, item) in enumerate(array):
        if item == 1:
            state1 = True
        elif (item == 2) and state1:
            state2 = True
        elif (item == 3) and state2:
            return True
        else:
            state1 = False
            state2 = False

        if index == len(array) - 1:
            return False

for test in tests:
      print "starting test %s" % test
      print array123(tests[test])

**Comment by yati1998** [comment]
Q: Given an array of ints, return true if 1,2,3 is present in any sequence in the array.
Ans:
tests = {"1":[1,1,2,3,1],"2":[1,1,2,4,1],"3":[1,1,2,1,2,3]}

def array123(array):
    if len(array)<3:
        return False
    
    for i in range(len(array)-2):
        z = array[i:i+3]
        if (1 in z) and (2 in z) and 3 in z:
            return True
        
    return False

for i in range(1,len(tests)+1):
      print "starting test %s" % tests[str(i)]
      print array123(tests[str(i)])

**Comment by yati1998** [comment]
Above are the solution I hope that works. I got the desired output.

**Comment by alodahl** [comment]
@judytuna is this what you were hoping for?

**Comment by yati1998** [comment]
Issue #558 solved.

**Comment by alodahl** [comment]
Thank you, @yati1998 ! My solution for the PR is, fix one typo in the following file, but be sure to include "closes issue #558" in the description, and that this was my idea =)

https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md

**Comment by yati1998** [comment]
@alodahl  I am Sorry I am not able to get which typo you are refeering to. and where should I make the change?

**Comment by judytuna** [comment]
The solution seems to be written in python. We use javascript =) 

I was hoping for more test coverage, like the "not in order" or "not in sequence"

[5, 1, 3, 2, 4] -> false
[1, 5, 2, 3] -> false 

or "1, 2, and 3 not present at all" and "empty array"

to catch tricky edge edge cases and eliminate false positives. Since it's done though, I can just add them later, or shouldnit be another PR? 

Sorry, I've been out sick! Thank you for working on this!

**Comment by yati1998** [comment]
@judytuna how can I make this better?

**Comment by alodahl** [comment]
@judytuna, I was able to adjust the old tests pretty easily actually.  Tell me if this is ok: https://repl.it/teacher/assignments/1773573/edit (admin link only)

@yati1998, I was told that document has a lot of typos.  Pick any one.

**Comment by judytuna** [comment]
Thanks! @yati1998, no further revisions are required =)

The last step (fixing a typo in that unrelated file, but mentioning this PR
as @alodahl instructs) is just to get you credit for it in this repo, since
the code you provided is going into a different service we use with
apprentices to do code challenges.
