### ISSUE TITLE
Ongoing:  Add a suggestion to our Women in Tech Resource List!

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#560]
- Help our apprentices find support and resources by adding a suggestion to [this topic outline about Resources for Women in Tech](https://github.com/Techtonica/curriculum/blob/master/women-in-tech-resources/resources-list.md). 

For FAQs on contributing, see https://github.com/Techtonica/curriculum#volunteering

**Comment by rudri182** [comment]
@alodahl I would like to work on this issue under GSSOC'19

**Comment by alodahl** [comment]
Thank you!  Submit it on March 1 and i will count your PR for GSSoC!

**Comment by thetaniyagupta** [comment]
I would also like to contribute to this issue under GSSOC'19

**Comment by Lakshita7** [comment]
I would like to work on this issue under GGSOC'19

**Comment by alodahl** [comment]
@thetaniyagupta @Lakshita7 👍. Go ahead and make a PR on March 1 😊

**Comment by alodahl** [comment]
@thetaniyagupta @Lakshita7, since we are a US Non-profit, please be sure to fill out this form before you start this project: https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

**Comment by ronika-das** [comment]
would like to contribute to this issue. Do the resources/meetups etc have to be strictly for women/girls only? there are a couple of them open for all

**Comment by alodahl** [comment]
@ronika-das , if you think it's a resource that would help women and non-binary people network, you can add it.

I emailed you an invitation to contribute; once you accept that, you can assign yourself to this issue.

**Comment by devakisj1** [comment]
hello ma'am , i would like to work on this issue too.

**Comment by alodahl** [comment]
@devakisj1 I emailed you an invitation to contribute; once you accept that, you can start working on the issue and I will assign you.

**Comment by Soumya0803** [comment]
@alodahl  Ma'am,I would like to contribute to this issue

**Comment by Manvityagi** [comment]
@alodahl I want to work on it as my first issue? Please guide.

**Comment by himadrinayak** [comment]
@alodahl I would like to work on this issue under GSSOC'19

**Comment by vaishali614** [comment]
@alodahl i would like to work on this issue under gssoc'19

**Comment by vsharma20v** [comment]
@alodahl I would like to add more groups to this.

**Comment by Rita-Okonkwo** [comment]
Finally resumed contributing after so long!!! please can I work on this issue @alodahl

**Comment by imskr** [comment]
Would like to add some resources to the list.
