### ISSUE TITLE
Add "logging out" directions for auth0 lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#562]
- [ ] [This lesson outline](https://github.com/Techtonica/curriculum/blob/master/oauth/o-auth.md) and [this slideshow](https://docs.google.com/presentation/d/18f-1EbjxLXyxuRoXNekpJ_o-pI1uiBzJxFw9ZoaNuVM/edit?usp=sharing) explain how to set up gmail authentication with Auth0 in a project. We just need to add a quick section to the outline and the slideshow about how to add a button/link that will remove the auth token from localStorage and redirect to a public page, effectively "logging out".

**Comment by ANURADHAJHA99** [comment]
kindly assign this issue to me.

**Comment by alodahl** [comment]
Hi @ANURADHAJHA99 how is this task going?

**Comment by ANURADHAJHA99** [comment]
I am working on it. I am very sorry but I was busy due to my exams. I will be punctual from now on.

**Comment by alodahl** [comment]
That’s alright, but please consider exams, etc along with the due date on the issue.

**Comment by ANURADHAJHA99** [comment]
should I continue with the work?

**Comment by ANURADHAJHA99** [comment]
The reference react app that is supposed to be downloaded in order to work, is not working and is showing certain error,I am trying to fix the error and accordingly work on the auth0 authentication.

**Comment by ANURADHAJHA99** [comment]
I have added code snippet related to the logging-out direction in the https://github.com/mmedina3/Auth0-Lesson/pulls.I have also made the PR.
I am working on the document.

**Comment by ANURADHAJHA99** [comment]
Please kindly review my PR https://github.com/Techtonica/curriculum/pull/640. Also kindly give me the write Access to make the addition in the presentation. I am very sorry for being late, however, I will try my best not to repeat the mistakes.

**Comment by ANURADHAJHA99** [comment]
I have added code snippet related to the logging-out direction in the https://github.com/mmedina3/Auth0-Lesson/pulls I have also made the PR.
I am working on the document.
