### ISSUE TITLE
Add supplemental materials to Jasmine Test outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#568]
We found a list of great resources for [this Jasmine/Chai Testing outline](https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/jasmine-testing.md).  If the link isn't already in the outline somewhere, please add it to a "Supplemental Resources" section in the outline. Note: the "Materials" section is NOT the "Supplemental Resources" section.

Thanks for untangling these links:
Resources examples:  "JS testing with Jasmine" by Dr. Perry, (https://automationpanda.com/2018/01/26/javascript-testing-with-jasmine/) A github repo with mocha test included (https://github.com/webdevjourneyWDJ/Todo-API), plus they have a video about how they created the entire Todo app. "A quick and complete guide to Mocha testing" by Glad Chinda ( https://blog.logrocket.com/a-quick-and-complete-guide-to-mocha-testing-d0e0ea09f09d) "JavaScript - Unit Testing using Mocha and Chai" by NC Patro (https://codeburst.io/javascript-unit-testing-using-mocha-and-chai-1d97d9f18e71) and accompanied by this github repo of tests ( https://github.com/npatro/javascript-unit-testing-with-mocha ). A Chai and Mocha blog post. Video:  "Unit Testing in JavaScript and Jasmine | TLDR Jasmine Unit Test Tutorial By: Dylan Israel" (https://www.youtube.com/watch?v=h2eWfvcAOTI) Testing start at 12:00 minutes. See a developer testing with mocha. "Node JS - Authentication - Login/Logout Mocha Testing" by Web Dev Journey (https://youtu.be/2q6

**Comment by Lakshita7** [comment]
Hey @alodahl I would like to contribute to this.
I am generating a pull request for the same

**Comment by Rita-Okonkwo** [comment]
Hi please has this been worked on?
