### ISSUE TITLE
Fix a JS "if/else" exercise to be more clear.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#569]
we got feedback from basically everyone that the Moviegoers problem from the Javascript-3 lesson was confusing. link: https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-3.md

a lot of the confusion lay in understanding the function you're writing is supposed to be able to take any combination of three names out of the five (so that in itself is a 5-choose-3 problem; there are ten possible combinations). it would be awesome to fix up the text in this problem.
- [x] clarify that the function should be able to take all ten combinations
- [x] clarify that we're working with combinations here, not permutations
- [x] clarify that we expect certain answers
- [x] decide what to do about situations where multiple correct answers exist for a single triplet. do you have to return both possibilities in an array? or is it okay for the function to return one of the existing possibilities? example: in M B P, either M alone or M P are possible results.
- [x] perhaps provide an answer key so people can check their work
- [ ] add this link to "additional resources" (it's just from a quick google search; if you have favored mathematical resources use them instead!)  https://getcalc.com/statistics-5choose3.htm

**Comment by ShraddhaAg** [comment]
Hi @alodahl! I would like to work on this issue.Please assign it to me :)

**Comment by saberprashant** [comment]
Hi @ShraddhaAg , I think that you might have already started working on this issue and that's really great. If you need any help or want to discuss it, then feel free to reach me over slack's DM or even here.

**Comment by alodahl** [comment]
@ShraddhaAg , after you accept the emailed invitation to collaborate, i can add you to the issue.

**Comment by yati1998** [comment]
@alodahl  can I also contribute to this issue?

**Comment by alodahl** [comment]
@yati1998 , @ShraddhaAg has picked up this issue.

**Comment by alodahl** [comment]
Hi @ShraddhaAg , how is this issue going for you?

**Comment by ShraddhaAg** [comment]
@alodahl Hi! I believe it's taking me too long to get this done. If someone wants to work on it, they are welcome :)

**Comment by alodahl** [comment]
Thanks for letting us know, @ShraddhaAg  😎

**Comment by yati1998** [comment]
@alodahl  Can I work on this issue now?

**Comment by yati1998** [comment]
@alodahl I am confused about which function is referred to in this problem. And where the changes need to do. Can you please help me with this?

**Comment by yati1998** [comment]
@alodahl there is a confusion in test cases. For example, as mentioned above in the case of  MBP the answer is complicated because If M alone is going Priya will join and then again there will be 2 so B will also join, in that case, P will deny. So the answer will either none or confusing.
What to do in that case?

**Comment by alodahl** [comment]
@yati1998, exactly! We need to change the problem so it is not confusing like this.

**Comment by yati1998** [comment]
So can we change the problem completely and place similar problem... Or need to modify the same problem?

**Comment by alodahl** [comment]
Modify the same problem please

**Comment by yati1998** [comment]
ok sure. I am looking into this.
