### ISSUE TITLE
separate supplemental resources from required materials. (multiple assignees encouraged)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#570]
On one side, some apprentices think that they need to throughly look through every material, and are getting way behind because of it.  On the other, many well-meaning volunteers have thrown the kitchen sink into the "materials" section, when many or even all of them should be considered "supplemental resources" (supplemental meaning additional, extra, not required). 

Look through topic outlines, and change one so that:
- the "slides" are part of the "materials" section
- the "lesson" explicitly directs how to use the mandatory "materials" (ex: "Read through [these slides]() )
- optional materials are under a "supplemental resources" section.
- if you finish, or notice a topic outline looks fine, please check it off on this list or let a Techtonica admin know it's complete.

Topic outlines whose materials sections not been reviewed:
- [x] https://github.com/Techtonica/curriculum/blob/master/professionalism/professionalism.md
- [x] https://github.com/Techtonica/curriculum/blob/master/ergonomics/ergonomics.md

- [x] https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/html/html.md

- [x] https://github.com/Techtonica/curriculum/blob/master/git-version-control/gitignore.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/css/css.md

- [x] https://github.com/Techtonica/curriculum/blob/master/css/media-queries.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/ui-ux-design/ui-ux-design.md
- [x] https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
- [x] https://github.com/Techtonica/curriculum/blob/master/bootstrap/bootstrap.md
- [x] https://github.com/Techtonica/curriculum/blob/master/professionalism/building-confidence.md

- [x] https://github.com/Techtonica/curriculum/blob/master/github-collaboration/github-collaboration.md
- [x] https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md
- [x] https://github.com/Techtonica/curriculum/blob/master/deploying/deploying-1-personal-site.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md

- [x] https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/runtime-complexity.md
- [x] https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/jasmine-testing.md
- [x] https://github.com/Techtonica/curriculum/blob/master/debugging/debugging.md
- [x] https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md
- [x] https://github.com/Techtonica/curriculum/blob/master/react-js/react.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/intro-to-data-structures.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/stack.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/deque.md

- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/searching.md
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/sorting.md

- [x] https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/machine-learning.md

**Comment by tyagipr** [comment]
I would like to work on this issue under GGSoC2019

**Comment by tyagipr** [comment]
I would like to work on this issue under GSSoC 2019

**Comment by alodahl** [comment]
Thank you, @tyagipr, which file will you work on?

**Comment by tyagipr** [comment]
https://github.com/Techtonica/curriculum/blob/master/professionalism/professionalism.md
I started with this one @alodahl

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl can I work on this slide:  https://github.com/Techtonica/curriculum/blob/master/algorithms/sorting.md

**Comment by Manvityagi** [comment]
Hey @alodahl I would like to work on the slides : https://github.com/Techtonica/curriculum/blob/master/deploying/deploying-1-personal-site.md
&
https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md

This outline looks fine to me with supplement material separated : https://github.com/Techtonica/curriculum/blob/master/node-js/node-js.md

**Comment by devRD** [comment]
Hey, I would like to work on this slides : 
https://github.com/Techtonica/curriculum/blob/master/data-structures/stack.md
https://github.com/Techtonica/curriculum/blob/master/html/html.md
https://github.com/Techtonica/curriculum/blob/master/css/css.md

**Comment by alodahl** [comment]
@devRD I reserved them for you 👍🏻

**Comment by devRD** [comment]
@alodahl Ma'am, I will make sure to address them properly next time onwards.

**Comment by ronika-das** [comment]
Hi,I would like to work on these topic outlines:
https://github.com/Techtonica/curriculum/blob/master/ui-ux-design/ui-ux-design.md
https://github.com/Techtonica/curriculum/blob/master/bootstrap/bootstrap.md
https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md

**Comment by alodahl** [comment]
@ronika-das I reserved them for you

**Comment by devRD** [comment]
can I work on more topic outlines?

**Comment by alodahl** [comment]
@devrd of course, please do! Just tell us which ones.

**Comment by vsharma20v** [comment]
@alodahl ma'am I want to work on this
https://github.com/Techtonica/curriculum/blob/master/algorithms/searching.md

This outline looks fine to me with supplement material separated : 
https://github.com/Techtonica/curriculum/blob/master/open-source/open-source.md

cc @Kundan28  @hoduchieu01

**Comment by vsharma20v** [comment]
@alodahl ma'am
This outline looks fine to me with supplement material separated :

https://github.com/Techtonica/curriculum/blob/master/data-structures/queues.md
https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/machine-learning.md
https://github.com/Techtonica/curriculum/blob/master/git-version-control/gitignore.md

**Comment by DeepanshiD** [comment]
Hey! I wish to work on the outlines of the following:
https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
https://github.com/Techtonica/curriculum/blob/master/data-structures/deque.md
https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md

**Comment by saberprashant** [comment]
hi @DeepanshiD , can you please layout in brief, what all you can add in the outlines?

**Comment by alodahl** [comment]
@DeepanshiD go ahead and start.  I'll reserve those for you!

**Comment by Kumaranupam2020** [comment]
hi @alodahl i would like to work on this issue

**Comment by alodahl** [comment]
> hi @alodahl i would like to work on this issue

Great, which ones?

**Comment by Kumaranupam2020** [comment]
I want to work on this..... 

https://github.com/Techtonica/curriculum/blob/master/recursion/recursion.mdps://github.com/Techtonica/curriculum/blob/master/recursion/recursion.md

**Comment by vsharma20v** [comment]
@alodahl ma'am 
This outline looks fine to me with supplement material separated :
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-7-oop.md
https://github.com/Techtonica/curriculum/blob/master/jquery/jquery.md
https://github.com/Techtonica/curriculum/blob/master/express-js/express.md
https://github.com/Techtonica/curriculum/blob/master/mobile-development/mobile-development.md

And I would like to work on this outline
https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/memoization.md
https://github.com/Techtonica/curriculum/blob/master/chrome-developer-tools/chrome-developer-tools.md

cc @Kundan28 @saberprashant @praveenscience

**Comment by alodahl** [comment]
Thank you @vsharma20v! Mentors, can you please check off all the files he mentioned?

**Comment by Kundan28** [comment]
Okay, will check it.

**Comment by Kundan28** [comment]
@alodahl Do they have to open new PR for different materials or they can make changes in single PR only ?
As @vsharma20v has made #790 & #791 . So is it okay to have different PR for same issue ?

**Comment by raibove** [comment]
I would like to work on this issue.
Topic-  https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md

@alodahl  @Kundan28  please assign me these topics

**Comment by alodahl** [comment]
@kundan28 1 file for one PR in this issue. The only time 1 file would need 2 PRs is if the first one was merged and we realized it needed more fixes, but they don’t get more points for the same file.

**Comment by Kundan28** [comment]
> @Kundan28 1 file for one PR in this issue. The only time 1 file would need 2 PRs is if the first one was merged and we realized it needed more fixes, but they don’t get more points for the same file.

As @vsharma20v has made #790 & #791. But now one of them is merged.

**Comment by Kundan28** [comment]
> As @vsharma20v has made #790 & #791. But now one of them is merged.

And the other one is too ready to be merged.

**Comment by alodahl** [comment]
It looks like 790 and 791 are each for a different file, so each should get issue points.

**Comment by Kundan28** [comment]
Yeah, I have mentioned both of the PRs in the scoresheet.
I just want to confirm from you.

**Comment by alodahl** [comment]
> I want to work on this.....
> 
> https://github.com/Techtonica/curriculum/blob/master/recursion/recursion.mdps://github.com/Techtonica/curriculum/blob/master/recursion/recursion.md

Please read the issue description and decide if you would like to work on this issue.  The issue is not about making additions to lessons. Other suggestions are fine, but you will not get issue points.
