### ISSUE TITLE
Change a line about a legacy bootstrap class

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#571]
From an apprentice: "I read col-xs-* have been dropped in Bootstrap 4; make a note in our curriculum about it or change the instructions for it." https://github.com/Techtonica/curriculum/blob/master/projects/recipe-page/phase-3-bootstrap-prompt.md

**Comment by NirmalKumarJoshi** [comment]
I'll work on this.

**Comment by alodahl** [comment]
Please pick up just one issue at a time @nirmalkumarjoshi 😉

**Comment by imskr** [comment]
I would like to work on this!

**Comment by alodahl** [comment]
@imskr great, just accept the emailed invite to collaborate, and you can assign yourself.

**Comment by tyagipr** [comment]
I want to work on this issue @alodahl

**Comment by imskr** [comment]
@tyagipr It's already solved by me. Please look other issues.

**Comment by tyagipr** [comment]
okay @imskr
