### ISSUE TITLE
Review Intro to Git slideshow directions, edit & clarify where necessary.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#572]
We got some feedback that the git slideshow was confusing. Please review the Intro to Git slideshow directions; edit & clarify where necessary so it's straight-forward for absolute beginners. Ask Techtonica staff for an edit link.

https://docs.google.com/presentation/d/1znMOomkIkAkFKIz2e6t5tLpyzObKqOwfd90fsixSiec/edit?usp=sharing

**Comment by NirmalKumarJoshi** [comment]
@alodahl I would like to work on this issue.

**Comment by alodahl** [comment]
@NirmalKumarJoshi , that would be awesome!  Like I mentioned in the other issue, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1) just once before you start picking up Techtonica issues.  I changed the slideshow, and you should have edit access now.  Let me know if you need anything, and feel free to slack me on the ggsoc19 channel; I'm Alina L. (M).

**Comment by Rita-Okonkwo** [comment]
Hi @alodahl can I work on this issue as well?

**Comment by alodahl** [comment]
@Rita-Okonkwo Thanks Rita, but someone is already working on this one (in-progress).  Choose an issue from the TO-DO column here: https://github.com/Techtonica/curriculum/projects/2

**Comment by Rita-Okonkwo** [comment]
Alright thanks alot
