### ISSUE TITLE
Review bash profile topic

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#573]
We got some feedback that the directions for creating shortcuts and aliases in a bash profile was confusing.  Please work through the outline and slideshow pretending to be an apprentice, and clarify/edit as necessary so they are straight-forward for absolute beginners.  Ask Techtonica staff for an edit link if you'd like to change the slides.

- [ ] Clarify/edit outline and slideshow
- [ ] Add explanation of 'nano' tool

https://github.com/Techtonica/curriculum/blob/master/command-line/dot-profile.md

https://docs.google.com/presentation/d/1FeHmZRNz4ZgpGAfDAIHXNitofon3Uy-h13uCcyy2FuE/edit?usp=sharing

**Comment by Rita-Okonkwo** [comment]
Hi Alina, Please can I work on this?

**Comment by Rita-Okonkwo** [comment]
Hi Alina, I just submitted two(2) PRs. One for the git and version control motivation section while the other is for this issue. But I'm unable to edit the slides I dont know why

**Comment by alodahl** [comment]
Please send me the slide links you need to edit and I will unlock them for you

**Comment by Rita-Okonkwo** [comment]
Hi Alina,
This is the link:  https://docs.google.com/presentation/d/1FeHmZRNz4ZgpGAfDAIHXNitofon3Uy-h13uCcyy2FuE/edit?usp=sharing
