### ISSUE TITLE
(consider for the future) One Project that we add to throughout the curriculum

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#576]
Getting feedback. 

What if we started with 1 project and kept adding to it for the rest of the lifetime of the program? 

Example: keep building on the Recipe page, which we've worked on for a while already. 
1. Original recipe page project had us use bootstrap and create a responsive site. 
2. We added a11y and SEO best practices.
3. For OOP, add js code to the project folder that isn't linked to anything yet, but creates users who will eventually rate your single recipe. 
4. Test it with jasmine on the command line (no browser tests yet, because it's not hooked up to any front end yet).
5. For jQuery, add 1 button at a time that does 1 thing. Maybe eventually we want a list of 5 stars, but at the beginning it's just one star button, and if you click it, it increments a star counter by one. Really incremental changes.

That would bring us up to week 5. 

6. Fetch something very simple from an external API and display it. Maybe it could be the github api and it shows the number of commits made in this project or something meta. Or some awesome Twilio thing because that's in the curriculum for week 6.

**Comment by alodahl** [comment]
I think we've acheived this with our Eventonica epic!
