### ISSUE TITLE
Remove or refactor w3schools reference links in curriculum

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#578]
We've gotten feedback that w3schools docs are pretty outdated, and should be replaced with an equivalent reference from MDN. Please replace these links in the Techtonica/curriculum repo. 
Gotcha: Use your judgement about non-reference materials from w3schools, like tutorials.

**Comment by srishtiBajpai** [comment]
would like to work on this.

**Comment by alodahl** [comment]
sounds good, @srishtiBajpai !  Are you part of GSSoc19?

**Comment by Kundan28** [comment]
Yes @alodahl , she is a part of GSSoC19.

**Comment by bharati-s** [comment]
Has the issue been assigned to someone?

**Comment by alodahl** [comment]
@bharati-s yes, someone has taken this one. You can find open issues in the to-do column here: https://github.com/Techtonica/curriculum/projects/2
