### ISSUE TITLE
Write automated tests for one or more of the daily code challenges. (multiple assignees encouraged)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#579]
These daily code challenges still need automated tests so apprentices can check their own JS solutions.  They are listed in order of priority - the first is the most urgent.  the '#' is part of the title, not an issue link. Please send the working test code along with the code challenge title to Techtonica staff, or add them in the comments below. 

I've posted everything we have about the problem here, including code.  If there is no code, you can make up a function name, etc yourself. Checked-off problems are finished, but you can pick up an unchecked one.  Tell Alina which one you're working on to prevent duplicate work.

Here is an example of the type of testing we're looking for:
```
Given a string, return a new string where the first and last chars have been exchanged.

front_back('code') → 'eodc'
front_back('a') → 'a'
front_back('ab') → 'ba'

function front_back(input_string){
  // Add functionality here! 
  return
}

// Test cases below, click run! 
var test_cases = [{
  "test_case_num": 1,
  "input_string": 'code',
  "expected_output": 'eodc',
  },
  {
  "test_case_num": 2,
  "input_string": 'hello world',
  "expected_output": 'dello worlh',
  },
  {
  "test_case_num": 3,
  "input_string": 'ab',
  "expected_output": 'ba',
  },
  {
  "test_case_num": 4,
  "input_string": '',
  "expected_output": '',
  },
  {
  "test_case_num": 5,
  "input_string": 'a',
  "expected_output": 'a',
  },
]


function run_test_case(input_string, expected_output){
  if (front_back(input_string)==expected_output){
    console.log('Test passed!')
  } else {
    console.log('Test failed!');
    console.log(`Input: ${input_string}`);
    console.log(`Output: ${front_back(input_string)}`);
    console.log(`Expected output: ${expected_output}`);
  }
}

test_cases.forEach(function(test_cases) {
    console.log(` ----- Test Case #${test_cases.test_case_num} ----- `);
    run_test_case(test_cases.input_string, test_cases.expected_output);
    console.log('\n');
});
```

- [x] 2/14 - Code Challenge #95
```
STAR WARS API PROBLEM

You are a Logistics Coordinator for the Star Wars rebel forces and are responsible for planning troop deployments. You need a tool to help find starships with enough passenger capacity and pilots to fly them. 
 
Build a CLI tool that takes as its single argument the number of people that need to be transported and outputs a list of candidate pilot and starship names that are each a valid possibility. Assume that any pilot can be a candidate regardless of allegiance. Assume the entire group of passengers must fit in a single starship. You may skip starships with no pilots or with unknown passenger capacity.  Your tool must use the Star Wars API (http://swapi.co) to obtain the necessary data.

You may not use any of the official Star Wars API helper libraries but can use any other libraries you want (http client, rest client, json).

Example usage:

$ ./find-pilots-and-ships 10
Luke Skywalker, Imperial shuttle
Chewbacca, Imperial shuttle
Han Solo, Imperial shuttle
Obi-Wan Kenobi, Trade Federation cruiser
Anakin Skywalker, Trade Federation cruiser
```
- [x] 2/21 - Code Challenge #81
```
Print out the grade-school multiplication table up to 12x12.

Example output:
  1   2   3   4   5   6   7   8   9  10  11  12
  2   4   6   8  10  12  14  16  18  20  22  24
  3   6   9  12  15  18  21  24  27  30  33  36
  4   8  12  16  20  24  28  32  36  40  44  48
  5  10  15  20  25  30  35  40  45  50  55  60
  6  12  18  24  30  36  42  48  54  60  66  72
  7  14  21  28  35  42  49  56  63  70  77  84
  8  16  24  32  40  48  56  64  72  80  88  96
  9  18  27  36  45  54  63  72  81  90  99 108
 10  20  30  40  50  60  70  80  90 100 110 120
 11  22  33  44  55  66  77  88  99 110 121 132
 12  24  36  48  60  72  84  96 108 120 132 144
```
- [x] 3/1 - Code Challenge #83 
```
Write function to print the odd numbers from 1 to 99.
```
- [x] 3/14 - Code Challenge #99
```
Work with the given set of data  to produce a Chart.js object. 

Produce a static HTML file with either a  polar area chart object, or a bar chart with the following data set = {% of fat: 32, % of protein: 36, % of carbohydrates: 24%} 

The following graph should be generated: 

https://www.chartjs.org/docs/latest/charts/polar.html with the labels being % of fat, % of protein and % of carbohydrates respectively. 
```

- [x] 3/25 - Code Challenge #87
```
Implement a queue Class with two stacks with the following two methods: enqueue and dequeue. 

Reference: https://leetcode.com/problems/implement-queue-using-stacks/description/

Ex 1: 
Let q = new Queue(); 
q.enqueue(1) 
q.enqueue(2) 
q.enqueue(3) 
q.dequeue() → 1 
```

- [x] 3/26 - Code Challenge #88
```
Reverse a singly linked list. 

Reference: https://leetcode.com/problems/reverse-linked-list/

Ex 1: 
Input: 1 → 2 → 3 → 4 → 5 ; return value head: <1> 
Output: 5 → 4→ 3 → 2 → 1 : return value head: <5>
```

- [x] 3/28 - Code Challenge #89
```
Find the length of the longest path in a binary tree 

Reference: https://leetcode.com/problems/maximum-depth-of-binary-tree/description/

Ex1: 
Input:  
      / \
     9  20
     /  \
    15   7 
Output: 3 
```

- [x] 2/5 - Code Challenge #5
```
Create an object that stores individual letters in an array and has a function for displaying the letters as a single word.
```

- [x] 2/6 - Code Challenge #3
```
Create a grades object that stores a set of student grades in an object. Provide a function for adding a grade and a function for displaying the student’s grade average.
```
- [x] 2/7 - Code Challenge: String Calculator
```
Implement a calculator's add function.
The calculator is implemented as a function and each calculator operation is implemented as a method on its prototype, ie. Calculator.prototype.add.

Instructions:

Edit Calculator.prototype.add so that it returns the sum of the two numbers. 

Calculator operations are passed in as a single string, with up to two numbers separated by a comma. Example: 1 + 2 would be written as "1,2". 

Assume that the input will not have spaces, and will only ever have two integers. (Do not worry about invalid input for now!)

Example input and output:

"" => 0
"42" => 42
"4,2" => 6
"123,456" => 579

Here's your starter code:

function Calculator() {}

Calculator.prototype.add = function(numbers) {
  let answer = 0;
  // add code here!
  
  return answer;
}

var calculator = new Calculator();
calculator.add("3,2");

**Comment by dpenny** [comment]
multiplication: 
```
const expected =
  "1 2 3 4 5 6 7 8 9 10 11 12\n2 4 6 8 10 12 14 16 18 20 22 24\n3 6 9 12 15 18 21 24 27 30 33 36\n4 8 12 16 20 24 28 32 36 40 44 48\n5 10 15 20 25 30 35 40 45 50 55 60\n6 12 18 24 30 36 42 48 54 60 66 72\n7 14 21 28 35 42 49 56 63 70 77 84\n8 16 24 32 40 48 56 64 72 80 88 96\n9 18 27 36 45 54 63 72 81 90 99 108\n10 20 30 40 50 60 70 80 90 100 110 120\n11 22 33 44 55 66 77 88 99 110 121 132\n12 24 36 48 60 72 84 96 108 120 132 144"


function testMultiplcation() {
  let result = multiplcationTable()
  if (result == expected) {
    console.log("Test passed!")
  } else {
    console.log("Test failed!")
    console.log(`Output: ${result}`)
    console.log(`Expected output: ${expected}`)
  }
}
```

**Comment by dpenny** [comment]
Queue with Stacks:
```
class Queue{
  constructor(){
  }
  // Push element x to the back of queue.
  push(x){
  }
   
  // Removes the element from in front of queue and returns it
  pop(){
  }
  
  // Returns the front element
  peek(){
  }
  
  // Return whether the queue is empty
  empty(){
  }
}


// Tests
function test1(){
  let q = new Queue()
  q.push(1)
  q.push(2)
  let one = q.peek()
  if (one !== 1){
    console.log("Test 1 push failed!")
    console.log(`After push got ${one}, and expected 1`)
  }
  else {
    console.log('Test 1 push passed!')
  }

  let peek = q.peek()
  if (peek !== 1){
    console.log("Test 1 peek failed!")
    console.log(`After one peek got ${peek}, and expected 1`)
  }
  else {
    console.log('Test 1 peek passed!')
  }
    
  let pop = q.pop()
  if (pop !== 1){
    console.log("Test 1 pop failed!")
    console.log(`After one push got ${pop}, and expected 1`)
  }
  else {
    console.log('Test 1 pop passed!')
  }
  let empty = q.empty()
  if (empty){
    console.log("Test 1 empty failed!")
    console.log(`After one push got ${empty}, and expected false`)
  }
  else {
    console.log('Test 1 empty passed!')
  }
}

function test2(){
  let q = new Queue()
  q.push(42)
  let p = q.pop()
  let empty = q.empty()
  if (!empty){
    console.log("Test 2 empty failed!")
    console.log(`After one push got ${empty}, and expected true`)
  }
  else {
    console.log('Test 2 empty passed!')
  }
  
  q.push(14)
  q.push(28)
  q.push(60)
  q.push(78)
  let pop2 = q.pop()
  if (pop2 !== 14){
    console.log("Test 2 pop failed!")
    console.log(`After popping got ${pop2}, and expected 14`)
  }
  else {
    console.log('Test 2 pop passed!')
  }
  
  let pop3 = q.pop()
  if (pop3 !== 28){
    console.log("Test 2 pop failed!")
    console.log(`After another pop got ${pop3}, and expected 28`)
  }
  else {
    console.log('Test 2 pop passed!')
  }
  
  let peek = q.peek()
  if (peek !== 60){
    console.log("Test 2 peek failed!")
    console.log(`After peek got ${peek}, and expected 60`)
  }
  else {
    console.log('Test 2 peek passed!')
  }
}
function testStackQueue() {
  test1()
  console.log('\n\n')
  test2()
  
}
testStackQueue()

```

**Comment by judytuna** [comment]
Consider: moving to another service with a community generating problems and test cases, such a hackerrank. https://www.hackerrank.com/interview/interview-preparation-kit seems promising. I've completed seven so far (you can see my progress under "submissions" at https://www.hackerrank.com/judytuna ) 

Cons to moving: 
- everyone's already done so much work on this!
- and people have put thought into getting these problems! 
- repl.it allows the Techtonica teacher account to see everyone's progress (though we're not grading them) 

Pros to moving to something like hackerrank: 
- takes it off our plates 
- lots of other people are looking at it, so there will be fewer (or no) bugs in the sample code and test cases
- problems should be clear (again because lots of people look at it) 
- community discussing and sharing solutions (visible after you get the tests to pass)
- lots of tests, covering edge cases as well as large sample size
- discussion of big-O notation
- show it off to other engineers

**Comment by tiffanyjstuart** [comment]
@alodahl 
* I think the Code Calculator problem already has automated tests written for it in repl
* I wrote a test for 2/5 challenge. The test gives away the answer so it would be better to include it as an automated test in repl
```
//Create an object called "word" that stores individual letters in an array called "letters" and has a function called "displayWord" for displaying the letters as a single word.

/*
var word = {
  letters : 
  displayWord :
};
*/

function testDisplayWord() {
var  expected = word.letters.join('');
  let result = word.displayWord()
  if (result == expected) {
    console.log("Test passed!")
  } else {
    console.log("Test failed!")
    console.log(`Output: ${result}`)
    console.log(`Expected output: ${expected}`)
  }
}

testDisplayWord();
```

**Comment by yati1998** [comment]
Hey can I work on this issue?

**Comment by alodahl** [comment]
@yati1998 sure, tell me which unchecked problem you'd like to solve and you can start. Please reply with your solution here.

**Comment by yati1998** [comment]
code challenge #3

**Comment by yati1998** [comment]
var grades = {
            gradesList: [],
            add: function(newGrade) {
                this.gradesList.push(newGrade);
                return this;
            },
            
            average: function() {
                var numberOfGrades = this.gradesList.length;
                var sum = this.gradesList.reduce(function(acc, val) {
                    return acc + val;
                });
                return sum / numberOfGrades;
            }
            
        };
        // average the grades
        console.log(grades.add(87).add(93).add(99).add(77).add(91).average());


Code challenge #3 solution. I hope this works. Please do mention if any changes are required. Thank you.

**Comment by yati1998** [comment]
<canvas id="myChart" width="400" height="400"></canvas>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["% of Fats", "% of Proteins", "% of Carbohydrates"],
        datasets: [{
            label: '# of Votes',
            data: [32,36,24],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
               ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

Solution for the Code Challenge #99

**Comment by yati1998** [comment]
<canvas id="myChart" width="400" height="400"></canvas>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
 type: 'poarArea',
 data:{
     labels:["% of fat", "% of protein", "% of carbohydrate"],
     datasets:[{
              backgroundColor: [
                        "#2ecc71",
                        "#3498db",
                          "#95a5a6",
                        ],
                data: [32, 36, 24]
           }]
        }
  });

Here the solution for Code challenge #99.

**Comment by alodahl** [comment]
https://github.com/Techtonica/curriculum/issues/579#issuecomment-470651966

@yati1998, was your grades comment the code I need to test student’s solutions?

**Comment by yati1998** [comment]
@alodahl #579 contains the code which returns the avg and sum of the student grades.  as mention in code challenge #3 . I havent added multiple test case rather it contain one to test wether the code give correct output or not.

**Comment by alodahl** [comment]
Hi @yati1998 , we need code coverage that tests the student's function and returns 
"Test Passed!" 
or 
"Test failed. 
actual output: something
expected output: other thing
"

See contributor's previous solutions for more info.

**Comment by yati1998** [comment]
@alodahl  ohk sure.

**Comment by yati1998** [comment]
@alodahl  Wrote this code for 2/6 code challenge. Hope you wanted this. If there is something wrong Please Notifiy, I will Try to correct it.


function sum(input){
return}
function avg(input)
{
return
}

function run_test_sum(input, expected_output){
if(sum(input)==expected_output){
console.log('Test sum passed');
}
else{
console.log('Test sum Failed');
console.log('Input:${input} ');
console.log(' Output: ${sum(input)} ');
console.log('Expected output: ${expected_output} ');
}
}

function run_test_avg(input, expected_output){
if(avg(input)==expected_output){
console.log('Test avg passed');
}
else{
console.log('Test avg Failed');
console.log('Input:${input} ');
console.log(' Output: ${avg(input)} ');
console.log('Expected output: ${expected_output} ');
}
}

run_test_sum();
run_test_avg();

**Comment by alodahl** [comment]
@yati1998 , this is more what I was looking for, thank you!  However, 2/6 still needs test cases.  Right now when I run it, the tests pass because everything is undefined.

**Comment by yati1998** [comment]
@alodahl  Hope this works. Code Challenge 2/6.

var test_cases=[{
"input":"70,70,40",
"expected_output_sum": "180",
"expected_output_avg":"60", },
{
"input":"90,60,70",
"expected_output_sum": "220",
"expected_output_avg":"73.33", },
{
"input":"60,30,50",
"expected_output_sum": "140",
"expected_output_avg":"46.66", },
{
"input":"30,50,70",
"expected_output_sum": "150",
"expected_output_avg":"50", },]

function sum(input){
return}
function avg(input)
{
return
}

function run_test_sum(input, expected_output_sum){
if(sum(input)==expected_output_sum){
console.log('Test sum passed');
}
else{
console.log('Test sum Failed');
console.log('Input:${input} ');
console.log(' Output: ${sum(input)} ');
console.log('Expected output: ${expected_output_sum} ');
}
}

function run_test_avg(input, expected_output_avg){
if(avg(input)==expected_output_avg){
console.log('Test avg passed');
}
else{
console.log('Test avg Failed');
console.log('Input:${input} ');
console.log(' Output: ${avg(input)} ');
console.log('Expected output: ${expected_output_avg} ');
}
}

test_cases.forEach(function(test_cases) {
     run_test_sum(test_cases.input, test_cases.expected_output_sum);
     run_test_avg(test_cases.input, test_cases.expected_output_avg);
    console.log('\n');
});

**Comment by yati1998** [comment]
@alodahl  am I done with both the codes? or any changes are required?

**Comment by alodahl** [comment]
Thanks, @yati1998 , the 2/6 tests work great. Go ahead fix just one typo in /learning-to-learn/learning-to-learn.md, and make a PR saying you're solving of problem 2/6 in issue #579.

could you please finish the tests for 3/14 before Wednesday so I can use it for the apprentices on 3/14?

**Comment by yati1998** [comment]
@alodahl  I hope this is what you want.
var test_cases=[{
"input":"70",
"expected_output_avg":"57.5", },
{
"input":"90",
"expected_output_avg":"62.5", },
{
"input":"60",
"expected_output_avg":"55", },
{
"input":"30",
"expected_output_avg":"47.5", },]

var array=[ ];

function insert(input){
 array=[40, 50, 70];
array.push(input);
return array;
}

function avg(array){
return}

function run_test_avg(array, expected_output_avg){
if(avg(array)==expected_output_avg){
console.log('Test avg passed');
}
else{
console.log('Test avg Failed');
console.log(' Output: ${avg(array)} ');
console.log('Expected output: ${expected_output_avg} ');
}
}

test_cases.forEach(function(test_cases) {
run_test_avg(insert(test_cases.input), test_cases.expected_output_avg);
console.log('\n');
});

**Comment by yati1998** [comment]
Can you please reference the learning-to-learn.md. I am unable to get that.
And what changes do i need to make in 3/14 code.? it was about to show the graph. and I guess my code commented above is doing that?

**Comment by alodahl** [comment]
-https://github.com/Techtonica/curriculum/issues/579#issuecomment-471414405
This ^ looks better.  Please add a test for adding a new grade to the "grades" array.

- This is a good opportunity to learn how to search for files in your code editor! Look up ways to search for learning-to-learn.md in the curriculum project.

- for 3/14, we dont need to show anything; we need tests that prove that they entered the correct chart.js code.
@yati1998

**Comment by yati1998** [comment]
@alodahl Added test for grades
var grades=[40, 50, 70];

var test_cases=[{
"input":"70",
"expected_grades":"40,50,70,70",
"expected_output_avg":"57.5", },
{
"input":"90",
"expected_grades":"40,50,70,90",
"expected_output_avg":"62.5", },
{
"input":"60",
"expected_grades":"40,50,70,60",
"expected_output_avg":"55", },
{
"input":"30",
"expected_grades":"40,50,70,30",
"expected_output_avg":"47.5", },]


var array=[ ];

function insert(input){
array=[40, 50, 70];
array.push(input);
return array;
}

function avg(array){
return}

function run_test_avg(array, expected_output_avg){
if(avg(array)==expected_output_avg){
console.log('Test avg passed');
}
else{
console.log('Test avg Failed');
console.log(' Output: ${avg(array)} ');
console.log('Expected output: ${expected_output_avg} ');
}
}
function run_test_grades(array,expected_grades){
if(array == expected_grades)
{
console.log('Test grades passed');
}
else{
console.log('Test grades Failed');
console.log(' Output: ${array} ');
console.log('Expected output: ${expected_grades} ');
}
}

test_cases.forEach(function(test_cases) {
run_test_avg(insert(test_cases.input), test_cases.expected_output_avg);
run_test_grades(insert(test_cases.input), test_cases.expected_grades);
console.log('\n');
});

**Comment by yati1998** [comment]
@alodahl code challenge for 3/14
var test_cases=[{
input:"<script> var ctx = document.getElementById("myChart").getContext('2d'); var myChart = new Chart(ctx, { type: 'poarArea', data:{ labels:["% of fat", "% of protein", "% of carbohydrate"], datasets:[{ backgroundColor: [ "#2ecc71", "#3498db", "#95a5a6", ], data: [32, 36, 24] }] } });</script>",
expected_output:" <script> var ctx = document.getElementById("myChart").getContext('2d'); var myChart = new Chart(ctx, { type: 'poarArea', data:{ labels:["% of fat", "% of protein", "% of carbohydrate"], datasets:[{ backgroundColor: [ "#2ecc71", "#3498db", "#95a5a6", ], data: [32, 36, 24] }] } });</script>"},
{
input:"<script> var ctx = document.getElementById("myChart").getContext('2d'); var myChart = new Chart(ctx, { type: 'poarArea', data:{ labels:["% of fat", "% of protein", "% of carbohydrate"], datasets:[{ backgroundColor: [ "#2ecc71", "#3498db", "#95a5a6", ], data: [34, 34, 24] }] } });</script>"
expected_output: "<script> var ctx = document.getElementById("myChart").getContext('2d'); var myChart = new Chart(ctx, { type: 'poarArea', data:{ labels:["% of fat", "% of protein", "% of carbohydrate"], datasets:[{ backgroundColor: [ "#2ecc71", "#3498db", "#95a5a6", ], data: [32, 36, 24] }] } });</script>"},
]


function run_test_case(input, expected_output)
{
if(input==expected_output)
{
console.log('Test  passed');
}
else{
console.log('Test  Failed');
console.log(' Output: ${input} ');
console.log('Expected output: ${expected_output} ');
}
}
test_cases.forEach(function(test_cases) {
run_test_case(test_cases.input, test_cases.expected_output);
console.log('\n');
});
