### ISSUE TITLE
Update location of "Request/Response" related docs

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#58]
It appears the location of the curriculum materials related to requests and responses has changed between [what was originally in the repo](https://github.com/Techtonica/curriculum/tree/master/request-response) and where contributors actually put things.

Acceptance Criteria:
- [ ] Location of Request/Response lesson plans has been consolidated into one directory
- [ ] That directory is properly linked to by the main table of contents

**Comment by MichelleGlauser** [comment]
Should be called "How the Internet Works."

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/requests-and-responses/
