### ISSUE TITLE
Change assessment 8 to have a simple backend requirement for a future project.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#580]
This is the assessment we want to change: https://github.com/Techtonica/curriculum/blob/master/projects/minimal-api-project.md

The goal is to keep it just as simple, but be productive by having them build & test the first user API endpoint for a large project they will build later. There's no need to mention the impending project; it just needs to be a user endpoint they can use later. Please refer to this project they will build the next week:
https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md

So the minimal-api-project needs to be named eventonica or eventonica project, and contain part of the User data model that they will complete later.

**Comment by alodahl** [comment]
Picked up by Jill Berardini

**Comment by NirmalKumarJoshi** [comment]
@alodahl  Please assign me this issue.

**Comment by alodahl** [comment]
@NirmalKumarJoshi thanks for offering, but like I said in another issue, please only pick up one gssoc issue at a time. Once you finish #583 , remind me and you can grab a new issue.
