### ISSUE TITLE
Consider additions to React topic outline: Redux, async/await

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#584]
React
* Redux: https://redux.js.org/introduction/getting-started

Other current js:
* ES6 new features: https://github.com/lukehoban/es6features
* async/await: https://javascript.info/async-await 

Other js tools:
* I don't think we need to throw Flow at them in March, but we could make it an available option for their final projects. Just making a note here that a volunteer suggested it since it goes well with React. https://flow.org/en/docs/install/

**Comment by judytuna** [comment]
Oh shoot, just saw https://github.com/Techtonica/curriculum/issues/65 , especially https://github.com/Techtonica/curriculum/issues/65#issuecomment-426458992 -- sorry, thanks!

**Comment by alodahl** [comment]
No prob! I can  make sure that async and await are emphasized... I thought it was already in the promises lesson.

**Comment by alodahl** [comment]
@judytuna  - async/await video and reference added to https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-9.md 👍🏼

**Comment by alodahl** [comment]
@judy you think the es6 reference should be in the react outline?

**Comment by judytuna** [comment]
Yeah, as supplemental material!

**Comment by alodahl** [comment]
added es6 link to https://github.com/Techtonica/curriculum/blob/master/react-js/react.md
