### ISSUE TITLE
Change Data Structures & Algo Week from 7 days to 4 days

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#585]
The topic outline for the Data Structures and Algorithms Sprint calls for a seven-day schedule. We need to compress it into four days. 

Topic outline: https://github.com/Techtonica/curriculum/blob/master/projects/data-structures-algorithms-sprint.md 

Our roadmap for this cohort, 2019h1: https://bit.ly/19h1roadmap -- see week 11 starting 3/18/2019

Thoughts on how this week was meant to go, @MichelleGlauser @alodahl ?

**Comment by yati1998** [comment]
hello, Can I solve this issue?

**Comment by alodahl** [comment]
@yati1998 Sure, that would be great!  Please change the Topic Outline linked above so that the directions for Day 1 - Day 7 actually fit into just Day 1, 2, 3,  & 4.  Here is the 4 day schedule:
![image](https://user-images.githubusercontent.com/29131689/53129552-b4c9ef00-351c-11e9-96f7-59d6856b274e.png)


Let me know if you have questions!

**Comment by alodahl** [comment]
@yati1998 are you working on this through GSSoC19?

**Comment by yati1998** [comment]
@alodahl yes I am working through GSSoC19

**Comment by yati1998** [comment]
@alodahl  would you mind assigning me this issue?

**Comment by yati1998** [comment]
@alodahl do we need to make changes in the data-structure-algorithms.md ?

**Comment by alodahl** [comment]
@yati1998 Please change this file: https://github.com/Techtonica/curriculum/blob/master/projects/data-structures-algorithms-sprint.md

**Comment by Lakshita7** [comment]
Hello, can I also contribute to this issue?
I am working through GGSOC'19

**Comment by saberprashant** [comment]
Hey @Lakshita7 , we can assign one issue to one person at a time, if the assigned person won't be able to complete the issue within the deadline, then we will assign the same issue to other participants who want to work on it. 
And, we will start the evaluations from 1st March, so if the currently assigned participant won't be able to complete this, we will assign this issue to you. Till then, you can explore other opened issues and grab them asap. And, we are soon going to open more issues with the tag "gssoc19" .
Hope this helps! :)

**Comment by yati1998** [comment]
@alodahl  does any further changes required? or its ohk.
