### ISSUE TITLE
PostgreSQL installation details and debugging

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#591]
Need to flesh out PostgreSQL installation instructions and help.

https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md 

The comments refer to creating a separate outline for installing postgresql. Please make your outline here: 
https://github.com/Techtonica/curriculum/blob/master/databases/installing-postgresql.md

Please use all the issue comments as a guide. They start here:

Consider: remove PostgreSQL from the Relational Databases topic outline. Teach one-to-many and many-to-many concepts in the Relational Databases topic outline, using sqlite3. Create a totally separate topic outline for PostgreSQL. 

<details><summary>Old instructions, deprecated</summary>

# OLD! DO NOT USE

I just decided to have apprentices use the mac installer for the latest version (11) here: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
- linked to from https://www.postgresql.org/download/macosx/ 
- need to instruct apprentices to uncheck "Stack Builder" (and if they don't uncheck it, just cancel it at the end of the installation when the stack builder window comes up)
<img width="662" alt="screen shot 2019-02-20 at 11 06 47 am" src="https://user-images.githubusercontent.com/315395/53119416-4b3de680-3504-11e9-8581-3c245b4fef08.png">

## Problems and solutions

PROBLEM: doubleclicking the installer package did nothing
SOLUTION: restart the computer lol

PROBLEM: createdb command not found
SOLUTION: it wasn't in the path. look in /Library/PostgreSQL/11/bin/ <--this is where 
Thus `/Library/PostgreSQL/11/bin/createdb mydb` will work
TODO solution: add `/Library/PostgreSQL/11/bin/` to her path
why didn't the installer program add this to her path??? how come it worked for some other people?

PROBLEM: `createdb: could not connect to database template1: FATAL: password authentication failed for user "ownuseraccountonmachere"`
??? Why isn't it using the new postgres user to connect?
- We checked for a new PostgreSQL user and yes, it's there 
- got feedback that this is scary! we should let apprentices know in the instructions that the installer will do this for them and have them look at it after the installation is complete (by bringing up spotlight (cmd+space) and checking for a new user named PostgreSQL.
</details>

**Comment by judytuna** [comment]
We are now trying Postgres.app https://postgresapp.com/downloads.html 

It has optional command-line tools. This may be easier and faster. Currently evaluating.

**Comment by rbatta** [comment]
+1 to the postgresapp. You can even run different versions of it at the same time if ever you needed to.

**Comment by alodahl** [comment]
Recommended links:

Put under materials & in the install steps: https://www.postgresql.org/docs/current/tutorial-install.html

Put under Supplemental Resources:  https://gist.github.com/Kartones/dd3ff5ec5ea238d4c546 - list of Postgres commands.

**Comment by alodahl** [comment]
please move on to this "Querying Relational Databases" course on Treehouse, but only do the first three sections. (Do more if you have time). Link: https://teamtreehouse.com/library/querying-relational-databases   <--if you have a San Francisco Public Library account, then you can get a free treehouse account; we all signed up for treehouse accounts before the apprenticeship began!

**Comment by alodahl** [comment]
Judy Tuan (she/her) [3:06 PM]
and for today, the most important video in the "Table Relationships" section is the "Many to Many Relationships" section.

- The "One to Many Relationships" video is good review for what we did on our worksheets yesterday with our microblog concept. "user authors a post" is a one-to-many relationship.
- The "Many to Many" video will help you understand the "user can star a post" relationship I added on the whiteboard. (Star just means like or heart here. Like, "Wacky Whale gave 'ooo chocolate' a star!") It's a totally different relationship between users and posts that is NOT the same or even at all related to the "user authors a post" relationship I just wrote about in the above bullet point. For stars, the user *has many* posts *through* stars.

**Comment by alodahl** [comment]
hi all, I’ve been using this tutorial to familiarize myself with SQL commands https://www.hackerrank.com/domains/sql

**Comment by judytuna** [comment]
May be a good place to practice SQL https://www.sqlteaching.com/

check this website to generate some mock data https://www.generatedata.com/.

**Comment by judytuna** [comment]
my mentor sent this to me, could be helpful for today too..
http://www.postgresqltutorial.com/psql-commands/

**Comment by imskr** [comment]
I would like to work on it.

**Comment by alodahl** [comment]
Sure @imskr , just please make any PR fixes before working on this issue.

**Comment by imskr** [comment]
Sorry @alodahl I didn't get you, PR fixes ?

**Comment by alodahl** [comment]
Nevermind
