### ISSUE TITLE
Add explanation for npm init command with and without the -y flag (read all comments for direction)

### ISSUE THREAD

**Issue by oubawaleh** [Techtonica/curriculum#593]
To pre-populate the  package.JSON with some basic information.

**Comment by judytuna** [comment]
Context: `npm init` without the `-y` flag makes you enter a tiny command-line program that asks you for details for your package.json. We can skip those steps by using `-y`. (Users were getting confused and trying to type `npm install --save express` into the `npm init` prompt!)

Also add some info about what `npm init` is doing (which is just writing up a `package.json` for you)

**Comment by alodahl** [comment]
Which topic outline do you think this would best fit into? @judytuna   @oubawaleh

**Comment by judytuna** [comment]
Perhaps as a note after the "use npm to create a package.json file" section of the node.js lab exercise part 2

https://github.com/Techtonica/curriculum/blob/master/node-js/node-lab-exercise-part-2.md#part-2---use-npm-to-create-a-packagejson-file

**Comment by yati1998** [comment]
@oubawaleh  I would like to work on this? Can I?

**Comment by alodahl** [comment]
@yati1998 Thanks for offering, but you can only work on one issue at a time.

**Comment by pydevsg** [comment]
@alodahl I would like to work on this issue, can I?

**Comment by Soumya0803** [comment]
@alodahl  Can I work on this issue?

**Comment by alodahl** [comment]
Thanks anyway @Soumya0803 , please choose another issue 🙂

**Comment by yati1998** [comment]
Hey, Can I work on this issue?
