### ISSUE TITLE
Augment OOP outline

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#594]
Make the following changes in this outline: 
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-7-oop.md

## Write down a list of terms. 

People can find resources on their own.

## Generate "Check for Understanding" questions for worksheet. 

For discussion in small groups

## Add to Supplemental Resources 

Polymorphism

https://dev.to/jvanbruegge/what-the-heck-is-polymorphism-nmh

nodeschool?

**Comment by alodahl** [comment]
@judytuna, can you explain your nodeschool comment in the description?

**Comment by imskr** [comment]
I would like to work on it!  And tell me about nodeschool?

**Comment by alodahl** [comment]
sure, @imskr .  Hopefully Judy will tell us more about NodeSchool before you finish.

**Comment by vaishali614** [comment]
@alodahl i would like to work on it! can you assign me this issue?
