### ISSUE TITLE
Change MySQL to PostgreSQL

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#595]
Throughout the curriculum, we use different databases. 

This cohort, we're standardizing on using PostgreSQL. 

We need to swap out the mysql connection node module with `pg` in the Eventonica project in these places:

- [ ] Techtonica curriculum: https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md  (most likely finished; just proofread please)
- [ ] Move the Starter code to Techtonica/curriculum from here & translate any mySQL info to PostgreSQL: https://github.com/chulinguy/Eventful-API-test-page 
- [ ] Search the curriculum to ensure everything else is standardized, too.

**Comment by alodahl** [comment]
@judytuna do any commands need to be changed, or just references and links?

**Comment by judytuna** [comment]
Both commands and instructions, and the use of the node module in @chulinguy's Eventful-API-test-page starter project 

We have to do it by Monday when people begin Eventonica. I'm working on swapping out `connection` with `pg`.

**Comment by judytuna** [comment]
I made this broader issue though because we should search through the curriculum and standardize. Several other topic outlines and project directions also use MySQL.

**Comment by ANURADHAJHA99** [comment]
I would like to take this issue. Kindly assign this issue to me and guide me to solve the problem.

**Comment by tyagipr** [comment]
Can i work on this issue @alodahl  under GSSoC 2019

**Comment by alodahl** [comment]
@tyagipr thanks anyway! Please find another issue 😊
