### ISSUE TITLE
Create/link style guide and attach to the "New & Updated Lessons" instructions

### ISSUE THREAD

**Issue by judytuna** [Techtonica/curriculum#596]
For example, https://twitter.com/trewaters/status/1099188644332490752

**Comment by vegetabill** [comment]
This is a good idea. I added an Instructions doc we can add this to if we decide on one. https://github.com/Techtonica/curriculum/blob/master/_templates/instructions.md

**Comment by ayan-biswas0412** [comment]
Hello I can do that

**Comment by vegetabill** [comment]
We already have a mini style guide in this doc so this seems like a wish list. The original tweet isn't even a style guide.

If we want to expand this, we should create a ticket with concrete items:
https://github.com/Techtonica/curriculum/blob/master/_templates/README.md
