### ISSUE TITLE
Eventonica API project: Manually Persist Data in-memory

### ISSUE THREAD

**Issue by daaimah123** [Techtonica/curriculum#607]
## Task:
https://github.com/judytuna/eventonica-api/tree/judy/steps were being worked on. The task is to finish them in your own branch and make them as clear as possible for the [Eventonica project](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md).

"i changed the name to indicate that when you're saving the data in memory, it's not a database =) and we weren't really saving it as JSON, we were saving it as a JavaScript object (and then converting it to JSON)

I've also started working on a reference implementation: https://github.com/Techtonica/eventonica-api

my work in progress branch is: https://github.com/judytuna/eventonica-api/tree/judy/steps"

### Start here:   

——————
These are the steps that we felt might be useful for future cohorts in understanding the walkthrough of the task as well as having the mental bandwidth to grasp what they are working on: 

**Sister Project**
1. New Folder for local made API
2. npm init => creates JSON pkg which is prompted in the terminal
3. npm i express (i can be used in place of install)
4. create an index.js file where routes will be located
5. require express in the index.js file and set up an express server
6. create an instance of express in var app
7. create listener server (w/port number and console a port message)
8. (GET) create route to show server connected w/logged string
9. (GET, single item) create route with id path to show server connected w/logged string
10. (POST) use postman to test route with res.send => request path same as "get" path from step 8
11. (PUT / DELETE) same as steps 9 & 10
12. create JSON with data => [{}]
13. (GET, single item) find out if path id == obj => set to var
14. create if else to show result options for step 13
15. (POST) create new obj 
      > make sure app can access JSON library using app.use() 
      > make sure obj format is the same 
      > values in body req.body."key name" 
      > test in postman by writing new event in body
16. (PUT) find an old event using step 13 logic
17. (PUT) access key in old event or change it
18. (DELETE) find old event (see step 13)
19. (DELETE) find obj index location => put in variable
20. Create database using psql
21. use node-postgres package to connect database to app 
      > using connecting/programmatic pool and client variable info
22. connect database inside of routes using async-await features

**Pay attention to:** 
- npm i --save "npm pkg name" => "--save" keeps pkg saved into project, so that if something happens to file and you need to bring down repo again, you dont have to reinstall the pkg again
- JSON formating => in json file place quotes around keys, in js files no quotes around keys
- arrays are JSON
- no string and json together in same request (i.e. do not try this => res.json("string" + JSONdata) this will confuse the computer)
- body-parser is depreciated
- app.use(express.json()) => allows us to use JSON library for use of PUT / POST bodies

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
@judytuna is this part of the separate REST API topic idea?

**Comment by daaimah123** [comment]
@alodahl  I am reading the comment she left me and i think this was supposed to be a PR, let me know if I should close this and move it to PR

**Comment by daaimah123** [comment]
Nothing to PR this to, keeping here for now 😃

**Comment by judytuna** [comment]
@daaimah123 here is the PR i'll add this information to! https://github.com/Techtonica/curriculum/pull/605

**Comment by judytuna** [comment]
i changed the name to indicate that when you're saving the data in memory, it's not a database =) and we weren't really saving it as JSON, we were saving it as a JavaScript object (and then converting it to JSON)

I've also started working on a reference implementation: https://github.com/Techtonica/eventonica-api 

my work in progress branch is: https://github.com/judytuna/eventonica-api/tree/judy/steps

**Comment by vsharma20v** [comment]
@alodahl ma'am If this Issue is under GSSoC19 can you elaborate what we have to do in this issue. :thought_balloon: 
because its description is a bit confusing :thinking:  and also @daaimah123 @judytuna ma'am comment messages also makes me confused :confused:

**Comment by alodahl** [comment]
This is all the info I have, but the last comment of Judy’s seems especially important.

@daaimah123 can you help? I also don’t understand why this is a PR if there’s no code to review.

**Comment by daaimah123** [comment]
@alodahl going to close the issue

**Comment by alodahl** [comment]
@daaimah123 that’s fine... is there a way we can still help with this?

**Comment by daaimah123** [comment]
I think the steps here: https://github.com/judytuna/eventonica-api/tree/judy/steps

were being worked on, making them as clear as possible for the assignment may be where the help is needed.

**Comment by vsharma20v** [comment]
https://github.com/judytuna/eventonica-api/tree/judy/steps
@daaimah123 @alodahl ma'am Is this project is also under gssoc19?

**Comment by alodahl** [comment]
@vsharma20v if you’re willing to tackle it, then yes.

**Comment by vsharma20v** [comment]
@alodahl ma'am
Actually, my End semester exams are going on.
So I can work on this issue after the 7th of May

**Comment by alodahl** [comment]
Good luck with exams! Let us know when you’re ready.

**Comment by vsharma20v** [comment]
@alodahl @daaimah123 @judytuna ma'am I want to give this issue a try so can u tell me what I need to do in this plz describe it more.

**Comment by alodahl** [comment]
@vsharma20v have you read the comments so far?

**Comment by vegetabill** [comment]
I'm marking this as close to expiring since it's stale and a lot of context has been lost on it. If someone likes this idea they are free to pick it up and begin actively working on it, otherwise it will be closed in ~7 days
