### ISSUE TITLE
Write "API Basics" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#62]
The lesson plan should live at [`APIs/api-basics.md`](https://github.com/Techtonica/curriculum/blob/master/APIs/api-basics.md).

By the end of the lesson, students should be able to read API documentation.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by Karla-Isabel-Sandoval** [comment]
@rcoh

**Comment by rcoh** [comment]
The current lesson plan is pretty good: https://github.com/Techtonica/curriculum/blob/master/api-application-programming-interface/apis-and-json.md
