### ISSUE TITLE
Write "Intro to React" lesson plan

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#63]
The lesson plan should live at [`react/react.md`](https://github.com/Techtonica/curriculum/blob/master/react/react.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by rhythmsection** [comment]
I am not going to do this in the formatting you ultimately want, but hopefully this will be helpful anyway. (Feel free to format as necessary).

**Comment by MichelleGlauser** [comment]
Thank you! Starting with content is great.

**Comment by MichelleGlauser** [comment]
Still needs slides.
