### ISSUE TITLE
Update MongoDB tutorial/instructions

### ISSUE THREAD

**Issue by lalpert** [Techtonica/curriculum#630]
The MongoDB tutorial recommended (https://www.youtube.com/watch?v=4yqu8YF29cU&feature=youtu.be) in the [MongoDB lesson ](https://github.com/Techtonica/curriculum/blob/master/databases/mongo-db.md) suggests making multiple web accounts, including to a site that was since acquired and can't be used anymore (mLab). I think the accounts are only needed to deploy the software at the end of the tutorial. We should either find a different tutorial that's more up to date, or add instructions to the curriculum possibly saying to skip the login + deployment parts of the tutorial.

**Comment by alodahl** [comment]
@lalpert will you work on this, or should I hand it to volunteers?

**Comment by lalpert** [comment]
If a volunteer is up for it that would be great.

**Comment by tyagipr** [comment]
Can i take this issue? @alodahl

**Comment by Yugandhartripathi** [comment]
I would like to work on this.

**Comment by yati1998** [comment]
@alodahl  if this issue isn't solved yet, can I work on this?

**Comment by Yugandhartripathi** [comment]
@alodahl Please reassign this to @yati1998 I am sorry but I couldn't find time got busy with some college and personal assignments
