### ISSUE TITLE
Build new "Security Roles in Tech" outline and slideshow.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#648]
The intention is to present different Software Security roles, and steps to take if one is interested in a career in that field.  Apprentices should walk away knowing more about whether they're a good fit for work in Security, and how to move forward.

- [ ] Finish building this topic outline [here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/security.md).

- [ ] make a slideshow version of the topic here: https://docs.google.com/presentation/d/1DjbfFt-rgQzBBPwVSXL1nGww1ziycJIxiSRmWbS-v40/edit?usp=sharing

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] It is geared towards beginners & junior devs
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)

**Comment by rudri182** [comment]
I would like to contribute to this issue

**Comment by rudri182** [comment]
Sorry for the delay. I was a little bit busy with my internal exams. I have almost completed and will upload it as soon as possible.

**Comment by Kundan28** [comment]
No problem @rudri182
