### ISSUE TITLE
Create "Roles In Tech: Technical Program Manager" topic outline & slides

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#649]
The intention is to present Technical Program Manager roles, and steps to take if one is interested in a career in that field.  Apprentices should walk away knowing more about whether they're a good fit for a future in that work, and how to move forward.

- [ ] Create a topic outline [here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/technical-program-manager.md).

- [ ] make a slideshow version of the topic here: https://docs.google.com/presentation/d/1q_sa93_LGQTZhNHyBnQHJmaO_2wgVD_7Mz7-gAjFZ8U/edit?usp=sharing

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] It is geared towards beginners & junior devs
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)

**Comment by imskr** [comment]
I would like to take this!

**Comment by rudri182** [comment]
I would like to work on this issue

**Comment by imskr** [comment]
@rudri182 It is already assigned to me.
