### ISSUE TITLE
Write React "Redux" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#65]
- [ ] The lesson plan should be saved into [this file](https://github.com/Techtonica/curriculum/blob/master/redux/redux.md).  The template is a copy of the React lesson that will be learned the day before.

- [ ] Save the accompanying slideshow [in this file](https://docs.google.com/presentation/d/1NfpXuU8rUXpPjboH6teMGHPT_hjMumHrGguCGOZX6Oo/edit?usp=sharing).

- [ ] Find or make an intro to redux video and paste the link in the issue comments.

**Comment by alodahl** [comment]
Redux doesnt fit into the curriculum right now.
