### ISSUE TITLE
Create "Roles In Tech:  Sales Engineer" outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#650]
The intention is to present Sales Engineer roles, and steps to take if one is interested in a career in that field.  Apprentices should walk away knowing more about whether they're a good fit for a future in that work, and how to move forward.

- [ ] Create a topic outline [here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/sales-engineering.md).

- You can base the outline on this slideshow. It needs proofreading, and should follow the styling guidelines in [this issue](https://github.com/Techtonica/curriculum/issues/600) : https://docs.google.com/presentation/d/1e_CgRXTbwZRj17F-Usza5xJerOqa0ya6Lt0wcBsQyak/edit?usp=sharing

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] It is geared towards beginners & junior devs
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)

**Comment by devakisj1** [comment]
@alodahl are we supposed to make slides or just create the outline in markdown for this isue

**Comment by alodahl** [comment]
just create the outline, and fix the styling in the slideshow.  @devakisj1

**Comment by devakisj1** [comment]
please assign this issue to me.
