### ISSUE TITLE
Create outline for "Roles in Tech: QA Engineer"

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#651]
The intention is to present Quality Assurance roles, and steps to take if one is interested in a career in that field.  Apprentices should walk away knowing more about whether they're a good fit for a future in that work, and how to move forward.

- [ ] Create a topic outline [here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/qa.md).

- You can base the outline on this slideshow. It needs proofreading, and should follow the styling guidelines in [this issue](https://github.com/Techtonica/curriculum/issues/600) : https://docs.google.com/presentation/d/17PG75lHEEOaoNM6OuAUeoaLa7Hf14tJPiwwdy5I-G-c/edit#slide=id.g22b045fc2c_0_8

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] It is geared towards beginners & junior devs
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)

**Comment by ANURADHAJHA99** [comment]
Please assign the following issue to me.

**Comment by alodahl** [comment]
Please address the requested changes in your PRs first @ANURADHAJHA99

**Comment by yati1998** [comment]
Can you assign me this issue if no one is assigned yet?

**Comment by ANURADHAJHA99** [comment]
@alodahl assign this issue to me.

**Comment by devakisj1** [comment]
please assign me this issue @alodahl

**Comment by alodahl** [comment]
Hi @devakisj1 , are you almost done with this issue?

**Comment by devakisj1** [comment]
Yes ma'am atmost by tomorrow i will submit it. @alodahl
