### ISSUE TITLE
Create a topic outline & slides on "REST APIs"

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#653]
We need a clear lesson on REST API's, with examples in NodeJS. Apprentices should leave with a strong understanding of what REST, CRUD, and what elements a REST API should have.  Proficiency in building one is not strictly necessary, but practice would be excellent if there's time.  The topic should take 1-2 hours to complete.

- [ ] [Create the topic outline here.](https://github.com/Techtonica/curriculum/blob/master/api/REST-API.md)
- [ ] [Create the slideshow version of the topic here.](https://docs.google.com/presentation/d/1ZdnhhGbwyJcmgPnTn6eeHjdhekUvo0ht70MwC7Ll5zw/edit?usp=sharing)   Follow the style guidelines from issue #600 .
- [ ] Find or make a video that illustrates the points you are making about the topic.

Here are some more details - 

Make this a prerequisite: /api/apis-and-json.md

use this as a resource:  https://teamtreehouse.com/library/rest-apis-with-express-refresh

maybe also this https://teamtreehouse.com/library/introduction-to-rest-apis

keep it short (1 hour), with a good reference sheet linked or in the outline.

where we can help a lot is coming up with "check for understanding" questions for people to do in pods and the assessments/projects

**Comment by ANURADHAJHA99** [comment]
Please assign the following issue to me.

**Comment by alodahl** [comment]
Please address the requested changes in your PRs first @ANURADHAJHA99

**Comment by pydevsg** [comment]
I would like to work on this issue after my PR gets merged @alodahl . Can, I?

**Comment by alodahl** [comment]
Please address the requested changes in your PRs first @pydevsg. Once that is approved by 2 mentors, remind me and I'll assign this to you.

**Comment by pydevsg** [comment]
Okay, I will take this issue after solving the PR.

**Comment by yati1998** [comment]
@alodahl  can I work on this issue?

**Comment by pydevsg** [comment]
@alodahl , I am interested and have started working in this issue , could you please assig n me this issue .

**Comment by alodahl** [comment]
@yati1998, will you take this one or the if/then question? If you dont choose this issue I will give it to @pydevsg.

**Comment by yati1998** [comment]
Yes I would like to take this

**Comment by yati1998** [comment]
@alodahl  can you please assign me this issue?
