### ISSUE TITLE
update our Techtonica/curriculum Readme Table of Contents

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#654]
We have added a lot of content, and need help updating our Techtonica/curriculum Readme Table of Contents. https://github.com/Techtonica/curriculum#table-of-contents

Keep the currant format, but add any missing or outdated links in the "outline" column in the Techtonica Roadmap. This includes assessments and tutorial links, and any link in the "outline" column that isn't private access only.
https://docs.google.com/spreadsheets/d/1vIr3fiKa_jxzy7qtFsiE5hEJbiTXwc1LYxbfsHOYD6U/edit#gid=0

- The RoadMap is the source of truth.  If the order is different in the RoadMap, change the README to match.
- Note that the RoadMap is in two pages - The first half is in the 'archive' page, and the second is in the 2019 schedule page.
- No duplicates, please, even if there are duplicates on the Roadmap.
- Fix dead or incorrect links in Readme.
- Contact Alina for any questions about content.

**Comment by yati1998** [comment]
@alodahl  Hey, I want to work on this issue can I?

**Comment by manaswinidas** [comment]
Assigning you this issue @yati1998

**Comment by alodahl** [comment]
@yati1998, focus on your current issues and PRs.  Once those are all approved, remind me and you might be able to pick up this issue.

**Comment by yati1998** [comment]
@alodahl can you assign me this issue now.. I have completed my previous issues.
