### ISSUE TITLE
Add details about git remote to GitHub Collaboration topic

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#655]
## Here is our topic trio on GitHub Collaboration:
- topic outline: https://github.com/Techtonica/curriculum/blob/master/github-collaboration/github-collaboration.md 
- slides:  https://drive.google.com/open?id=1dGsFDog3uUq0XwVMCbYRJucPuzBWTFCawdas2r6fBdA 
- video:  https://drive.google.com/open?id=1nfCGVlLT3so0G8fBX8cvRUZzE4Wt29ZZ

## What We Need:
how to add a new remote, how to check remote options, how to pull from a different remote (git pull <remote name> <branch>) v how to pull from origin (git pull === git pull origin master, or git pull origin <branch>)

Add these ideas to the outline, and in a few new slides in the slideshow.

**Comment by ANURADHAJHA99** [comment]
I would like to work on the following issue.Kindly assign it to me.

**Comment by alodahl** [comment]
Please address the requested changes in your PRs first @ANURADHAJHA99

**Comment by yati1998** [comment]
@alodahl  please can I work on this issue if no one is assigned this yet?
