### ISSUE TITLE
Write "Web Patterns" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#66]
The lesson plan should live at [`web-patterns/web-patterns.md`](https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/web-patterns/web-patterns.md
