### ISSUE TITLE
Add more lessons/ examples of Dynamic Programming 

### ISSUE THREAD

**Issue by tiffanyjstuart** [Techtonica/curriculum#664]
The lesson on memoization (https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/memoization.md) very briefly mentions Dynamic Programming, a potentially confusing topic that is a popular interview interview topic. There don't seem to be any other lessons that cover Dynamic Programming in the curriculum. 

Lesson needs review and additional resources that specifically go into Dynamic Programming.

**Comment by ANURADHAJHA99** [comment]
@tiffanyjstuart please assign this issue to me.

**Comment by Kundan28** [comment]
@ANURADHAJHA99 You can only work on one issue at a time. And I think you have not completed #645 . So I would suggest you to please complete one issue before then you could work with the other one.

**Comment by ANURADHAJHA99** [comment]
@Kundan28 I have completed a clean PR on the following issue and submitted it. I have edited all the issues as recommended to me.

**Comment by Kundan28** [comment]
Oh, okay.
But as I know if your PR is alright then it should be merged instead of closed.
Correct if I'm wrong.

**Comment by ANURADHAJHA99** [comment]
@Kundan28 You are absolutely right. It's just I am waiting for the PR to be reviewed. I have made the PR one hour ago. Also, there is another PR where I was suggested certain changes and I have submitted the changes.

**Comment by ANURADHAJHA99** [comment]
@Kundan28 sorry for the confusion. I myself have closed the wrong PR.

**Comment by Kundan28** [comment]
Okay

**Comment by Kundan28** [comment]
No problem.
You can fix that.

**Comment by ANURADHAJHA99** [comment]
@alodahl kindly assign this issue to me,now that I have fixed all my PR.

**Comment by pydevsg** [comment]
Can I work on this issue @alodahl and could you please assign me this.

**Comment by alodahl** [comment]
@pydevsg this issue is taken.
