### ISSUE TITLE
Create "Roles In Tech: Technical Writer" topic outline & slides

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#671]
The intention is to present Technical Writing roles, and steps to take if one is interested in a career in that field.  Apprentices should walk away knowing more about whether they're a good fit for a future in that work, and how to move forward.

- [ ] Create a topic outline [here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/technical-writing.md).

- [ ] make a slideshow version of the topic here: https://docs.google.com/presentation/d/1p7fa20o7lRyvXuXhsFz8MfHktY5MaqSPSrLdNjocNcE/edit?usp=sharing

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] It is geared towards beginners & junior devs
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)

**Comment by pydevsg** [comment]
I would like to take this issue @alodahl.
Please atleast assign me this one.

**Comment by alodahl** [comment]
@pydevsg, please address your PR review first.

**Comment by ANURADHAJHA99** [comment]
@alodahl I have addressed the problems to my PR. Kindly assign this issue to me.

**Comment by pydevsg** [comment]
Thanks, @alodahl for aasigning me this issue.
