### ISSUE TITLE
Research whether kramdown notation will open a new tab when link is clicked

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#697]
Your task is to see if the following or another solution will open a new tab when a .md link is clicked, rather than the default behavior of loading the linked page in the current window.

If you come up with a different solution, or if you conclude there is no way, please document that with notes here and that will fulfill the issue.  Make a PR as well if you are successful.

If you do succeed, make a PR with a single .md File of your choice that has every link replaced so it opens a new tab.

Other background info from @daaimah123 :
 add “open new tab ” features to the link…they currently open on the same tab moving away from the md when we click them…i found this kramdown line that is compatible with markdown and wanted to see how it would do if added to our md’s.

[link] (url) {:target=“_blank”} <- remove spaces when using format

**Comment by vsharma20v** [comment]
I would like to work on this.

**Comment by vsharma20v** [comment]
@alodahl ma'am if I completed my research then what I need to do as you said: "please document that with notes here".
Do I need to provide the link of resources from where I come to the conclusion?

**Comment by alodahl** [comment]
@vsharma20v can you just tell me what you learned?

**Comment by vsharma20v** [comment]
@alodahl ma'am
There is no way in Github markdown to open a new tab when a link is clicked and the kramdown notation doesn't work even the HTML anchor tag with the target attribute doesn't work in Github markdown. One suggestion from my side is that we can tell the audience to open the link by pressing `Ctrl` + `mouse left click` which will result in the desired behaviour.

Reference: https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link?rq=1

**Comment by alodahl** [comment]
<a href="http://alinalodahl.com/" target="_blank">example</a>

**Comment by alodahl** [comment]
Bummer.  Thanks for trying for us! You can fix a typo in /learning-to-learn/learning-to-learn.md, and make a PR referencing this issue to get your points.
