### ISSUE TITLE
Add section in removing styles from a website to CSS lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#698]
Please add a step-by step section showing learners how to go to a site and remove link or style tags from the elements section in the inspector to demonstrate what a big difference css makes, while also reinforcing that styles are included via these tags. This activity should take the learner 5 minutes or less.

- [x] choose a site that has the styles included simply, so removing just a few style or link tags will quickly change how the site looks

- [x] choose a site that will change dramatically when this is done

- [ ] include this is the lesson or the guided practice section, wherever it makes the most sense. Make sure to describe what sort of html to look for.

- [x] include the directions with a screenshot of the inspector elements code before and after changing it in the css slideshow.

- [x] include a view of the website before and after the change in the slideshow.

Here is our CSS outline: 
https://github.com/Techtonica/curriculum/blob/master/css/css.md
And the slideshow:
https://docs.google.com/presentation/d/1p-IXWxo0NEbZbHQ_Mdoo-A9dlFXqfSPOfW6navfyeTI/mobilepresent?slide=id.p

**Comment by rudri182** [comment]
I would like to contribute

**Comment by alodahl** [comment]
Thanks @rudri182  - once the Security Roles PR is ready, remind me and you can have this if it's still free.

**Comment by pydevsg** [comment]
Can you please assign me this issue @alodahl , I have completed my PR its waiting to be merged from you.

**Comment by rudri182** [comment]
I have pushed changes in the PR . Can you review it and assign me this
issue ?

**Comment by pydevsg** [comment]
Thanks @alodahl for assigning me this issue.

**Comment by pydevsg** [comment]
@alodahl, I have a doubt before doing a PR whether I need to show two different websites or I can just show one website that how CSS can dramatically change the website,
Secondly, can I add screenshot and images in css outline file , which will help the learners easily to understand or this task is to be done in the slideshow only?

**Comment by alodahl** [comment]
@pydevsg, one site is fine. Unless the image is very small, or you can change it into text, please only put images in the slideshow. Then you can refer them to the slideshow in the outline if you think it would be fitting.

**Comment by pydevsg** [comment]
Okay, thanks for the valuable response , @alodahl.

**Comment by pydevsg** [comment]
@alodahl I am unable to add slides to [CSS Slide](https://docs.google.com/presentation/d/1p-IXWxo0NEbZbHQ_Mdoo-A9dlFXqfSPOfW6navfyeTI/edit#slide=id.g2f8dad5731_0_107) as it is in View only mode. I have requested admin to make it available for me to edit, a few days ago but they haven't responded. Please do have a look at it, so that I can resolve this issue asap.

**Comment by alodahl** [comment]
@pydevsg Try it now; it should be editable.

**Comment by pydevsg** [comment]
@alodahl I have added few slides in the [CSS Slide](https://docs.google.com/presentation/d/1p-IXWxo0NEbZbHQ_Mdoo-A9dlFXqfSPOfW6navfyeTI/edit#slide=id.g2f8dad5731_0_107) earlier.
What else do I need to add in the content or is it fine.
I would like to complete this isssue as early as possible,to grab other issues.

**Comment by alodahl** [comment]
I love what youve done so far. Questions/ requests:
1. Have you put any directions for this in the outline?
1. Can you please use Lato fonts and sizes that match the rest of the slideshow?
1. Please include a change caused by removing a style or link tag from the head in devtools.

**Comment by pydevsg** [comment]
Okay, I shall add these features . Thanks for the guidance, @alodahl .

**Comment by pydevsg** [comment]
Done @alodahl , please do have a review 😄

**Comment by pydevsg** [comment]
Please do have a review @alodahl . I have made all the changes.
