### ISSUE TITLE
Test out a tutorial for building a node/express/mongo api 

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#699]
@yati1998 found us a great-looking tutorial for building a quick node/express/mongo api:  
https://medium.freecodecamp.org/building-a-simple-node-js-api-in-under-30-minutes-a07ea9e390d2

Your task is to work through it and ensure that the tutorial actually results in a working API!

This is a great learning opportunity for someone who wants to learn one of these technologies.

Once you have worked through the tutorial, post your impression of it in the notes here, and we will find a way for you to get PR points.

**Comment by yati1998** [comment]
@alodahl  can I work on this?

**Comment by alodahl** [comment]
@yati1998, you already have 2 issues in progress.

**Comment by yati1998** [comment]
@alodahl  I think I am almost done with the other issues. so once that is reviewed can I work on this?

**Comment by yati1998** [comment]
@alodahl I have gone through the tutorial. And it is exactly resulting in the working API.  the tutorial results in performing the CRUD operation. In addition to this tutorial, we can add the steps to install the POSTMAN app and direction to create a mlab account.

**Comment by alodahl** [comment]
Awesome, thanks @yati1998 ! Can you please look at the server-side topics in the readme that come before mongo to double-check that we’re already introducing postman? I think it should already be there.

**Comment by alodahl** [comment]
After you check for postman, fix 1 real typo in learning-to-learn , make a PR, but tag this issue and title your PR about this issue.

**Comment by yati1998** [comment]
Yes,  postman exists. I am simply making a PR than.
