### ISSUE TITLE
Add subtitles to Advanced Command Line video

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#702]
We want to make sure learners have access to subtitles/captioning for the YouTube tutorials they watch.  Please go into the settings of this video and add subtitles:
https://youtu.be/NodKFuUocQY

![image](https://user-images.githubusercontent.com/29131689/54883633-e2100280-4e24-11e9-8fa4-9aac1d023fbe.png)

![image](https://user-images.githubusercontent.com/29131689/54883651-2a2f2500-4e25-11e9-8652-70b37fa3b47d.png)

Make a comment in this issue when you are finished, and we will find a way for you to make a PR.

Note: Our first priority is English, but if this issue is taken and you'd like to add subtitles in an additional language, add a comment below.

**Comment by Kundan28** [comment]
@alodahl Automatic captioning could be used too.

**Comment by alodahl** [comment]
@Kundan28 sounds good to me, as long as the contributor proof-reads it.

**Comment by ANURADHAJHA99** [comment]
@alodahl kindly assign this issue to me.

**Comment by alodahl** [comment]
Please address your PR reviews first, @anuradhajha99

**Comment by Lakshita7** [comment]
@alodahl  I would like to work on this

**Comment by alodahl** [comment]
@Lakshita7 how is this issue going? Will you be able to finish it?

**Comment by Lakshita7** [comment]
@alodahl I have the transcripts ready but I am not getting time to complete it. You may assign this task to someone else if urgent.

**Comment by alodahl** [comment]
@Lakshita7 when do you think you can complete it?

**Comment by Lakshita7** [comment]
@alodahl  Sorry I won't be able to. Please assign this to someone else.

**Comment by vsharma20v** [comment]
@alodahl  ma'am can I work on this issue?

**Comment by vsharma20v** [comment]
@alodahl  ma'am I have submitted the subtitles/captioning for this video and waiting for it to get a review by the youtube till then can I create a PR?

**Comment by Kundan28** [comment]
Yeah, go for it.

**Comment by vsharma20v** [comment]
> Yeah, go for it.
@Kundan28 @alodahl what work I need to do in PR?

**Comment by vsharma20v** [comment]
I have created the PR #772
