### ISSUE TITLE
Modify path and markdown of link

### ISSUE THREAD

**Issue by vsharma20v** [Techtonica/curriculum#706]
The link in the Motivation section of "Women in Tech: Resources List" is not working. Add the correct path to it and also correct its markdown.
@alodahl @Kundan28 @manaswinidas

**Comment by rudri182** [comment]
I would like to work on this issue

**Comment by vsharma20v** [comment]
@rudri182 you can work on this issue once this issue is accepted, labelled and reviewed by @alodahl ma'am.

**Comment by rudri182** [comment]
I have modified the link in the 'motivation' section and now it is working. So please review it. And suggest if there are any changes required.

**Comment by alodahl** [comment]
This is ready for PR 👍

**Comment by rudri182** [comment]
👍

**Comment by alodahl** [comment]
Have you made a PR? I’m not seeing it.

**Comment by rudri182** [comment]
> Have you made a PR? I’m not seeing it.

No, I have only requested it for working on it. I would like to work on it.

**Comment by alodahl** [comment]
You are assigned to this issue... I’m confused.

**Comment by rudri182** [comment]
ok, I will regenerate it if it is not generated

**Comment by rudri182** [comment]
> You are assigned to this issue... I’m confused. All I see is a commit in your own repo, but no PR.

I have generated PR for #706. I have previously worked in this file for _women in tech_. So I pushed the changes in it. Are they visible?

**Comment by alodahl** [comment]
No, you need to make a new PR for each issue.

**Comment by rudri182** [comment]
Ok. But how can I do it? Do I make a new branch? Because in my branch it is showing _Everything up-to-date_

**Comment by Kundan28** [comment]
Yeah, for every different issue you should create a new branch. That would be a good idea to handle different issues.

**Comment by rudri182** [comment]
ok. I will make it. And generate a pull request as soon as possible. Thank you
