### ISSUE TITLE
Find or make video with specific bash commands

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#712]
Please find or make a video demonstrating the following commands, and add it to the “materials” section of https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-advanced.md :

wc , sort, cut, xargs, apropos, awk, sed, wc, pushd, popd

Finding 2 or 3 short videos instead of one is alright, too.

**Comment by vsharma20v** [comment]
Can I take this issue?

**Comment by vsharma20v** [comment]
@alodahl ma'am I created the PR #717  plz review that
