### ISSUE TITLE
Complete outline for Pair Programming/Lab Experience part.

### ISSUE THREAD

**Issue by rudri182** [Techtonica/curriculum#713]
@alodahl In the pair programming section, the outline for lab experience is incomplete. Please review it here
https://github.com/Techtonica/curriculum/blob/master/pair-programming/lab-exercise.md

**Comment by alodahl** [comment]
@rudri thanks for finding this!

**Comment by alodahl** [comment]
@rudri182 is there a link that leads here from a lesson, or did you just notice it was an empty file in /pair-programming?

**Comment by rudri182** [comment]
I just noticed this while I was reading the interesting topic of pair programming and I found it. Up to now, I have not seen any link that leads to this part of any lesson. It is only to let you know that it is incomplete.😊

**Comment by alodahl** [comment]
If nothing is counting on this file, I’m just going to delete it.

**Comment by rudri182** [comment]
Yes, you can. Because right now there is no linking in this section.
