### ISSUE TITLE
Add mention of certification in Security Roles outline & make a slide.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#719]
- [ ] Add a line or 2 of about this certification in our [Security Roles Outline](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/security.md) based on the following advice. Include a link and a few words about the certification.  
- [ ] Add the same advice in a slide [here](https://docs.google.com/presentation/d/1DjbfFt-rgQzBBPwVSXL1nGww1ziycJIxiSRmWbS-v40/edit#slide=id.p), and be sure to format it like the rest of the slides.

Advice:
One of the security engineers I worked with recommends doing the OSCP certification.  He said it gets you the experience you need to get security jobs.

**Comment by vsharma20v** [comment]
@alodahl  ma'am about which certificate, OSCP?

**Comment by vsharma20v** [comment]
I would like to work on this issue, ma'am.

**Comment by vsharma20v** [comment]
I have created the PR #741
