### ISSUE TITLE
Replace MongoDB tutorial link

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#721]
Task:
- [ ] In the independent practice section of our [MongoDB outline](https://github.com/Techtonica/curriculum/blob/master/databases/mongo-db.md), replace the step about a 2-hour video tutorial with a line about working through this tutorial article instead: https://medium.freecodecamp.org/building-a-simple-node-js-api-in-under-30-minutes-a07ea9e390d2

- [ ] The new tutorial calls for using the cloud MongoDB site, mLab. Please add a descriptive link to a tutorial on how to set up mLab.

- [ ] keep the existing 2-hour tutorial video link, but make it clear that they can use it for reference as they follow the new tutorial, but they don’t have to do the video tutorial.

**Comment by alodahl** [comment]
@yati1998 would you like this one?

**Comment by yati1998** [comment]
Yes sure. Do assign me this issue.
