### ISSUE TITLE
Create 'Roles in Tech: Product Manager' outline based on existing slideshow

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#725]
## Task

- [ ] Create [Roles in Tech: Product Manager outline here](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/product-manager.md) based on [this completed slideshow](https://docs.google.com/presentation/d/1BxTU4nugas3Z30kIawpJtLhSBL6b5tF1P-d03Hm_JOI/edit?usp=sharing).

- [x] Be sure the slides follow the formatting guidelines described here: #600

**Comment by raibove** [comment]
Can I work on this issue

**Comment by rudri182** [comment]
I would like to work on this issue

**Comment by alodahl** [comment]
@raibove have you filled out the volunteer form I sent you?

**Comment by raibove** [comment]
Yes
