### ISSUE TITLE
Proofread Command Line outline with correct markdown

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#727]
## Task:
Proofread our [Command Line Topic Outline](https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md), and fix based on the review comments mentioned in #643 . Make sure to use the markdown formatting guidelines found [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet), so it is clear what is code or a command, what the sub-sections are, etc.

**Comment by rudri182** [comment]
I would like to work on this issue.

**Comment by alodahl** [comment]
@rudri182 resolve the conflicts in your PR and fix the link first, please. If you can’t find it, press command + f to search for the word “conflict”.

**Comment by rudri182** [comment]
I fixed the link in the motivation section. What are other conflicts ? I am
not able to figure it out. I checked other links , they all are working for
which it is showing the conflicts other than motivation section. So I am
confused.

**Comment by alodahl** [comment]
Google “resolving merge conflicts in github”

**Comment by rudri182** [comment]
May I now work on this issue? I have successfully completed my issue #724

**Comment by rudri182** [comment]
I have created a PR #732 the file command-line-interface issue #643 .  Please review it.
