### ISSUE TITLE
Add Mac Utilities resource & describe in outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#728]
## Task:

- [x] Find or make an appropriate section in [our keyboard shortcuts lesson](https://github.com/Techtonica/curriculum/blob/master/command-line/keyboard-shortcuts.md) to add this link:
popular Mac utilities: https://www.producthunt.com/ask/7567-what-are-your-must-have-mac-apps-utilities

- [x] Briefly describe the advantages of the first 2 or 3 choices, but emphasize that they are optional.

**Comment by imskr** [comment]
I will work on it.
