### ISSUE TITLE
Make sure Prerequisite sections are correctly linked (1/2)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#730]
## Task:

This is a single-contributor issue, and should all be in one PR.

Check the first half of the outlines in the [ReadMe Table of Contents](https://github.com/Techtonica/curriculum/blob/master/README.md#table-of-contents ) and ensure that the prerequisites are linked correctly. 

 **For example, if you see this:**
### Prerequisites
- Command Line Lesson

**You should change it to this:**

### Prerequisites
- [Command Line Lesson](/command-line/command-line-interface.md)

**Complete the Prerequisite sections in these sections’ outlines:**
- [ ] Onboarding 
- [ ] Programmer Tools
- [ ] Client-side programming

Most of them should already be done, but your job is to track down the last ones.

Exceptions: if the prerequisite is obviously advice rather than a specific lesson, you don’t have to link it. However, since you’ll be exploring our curriculum anyway, use critical thinking to add an unmentioned prerequisite if it seems like it should be there.

**Comment by tiffanyjstuart** [comment]
@alodahl In https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md link should "Expectations While at Techtonica" lesson link to the google doc with the "Apprentices Expectations"?

**Comment by tiffanyjstuart** [comment]
Completed all the Onboarding Prerequisite sections.

**Comment by tiffanyjstuart** [comment]
@alodahl Some of the lessons in the Prerequisite sections are missing from the ReadMe Table of Contents (https://docs.google.com/document/d/1IWny-IXB-XDWW21l3JODwPuh1QOVBFQbii_DjvF0g00/edit?usp=sharing, https://github.com/Techtonica/curriculum/blob/master/conflict-resolution/conflict-resolution.md, https://github.com/Techtonica/curriculum/blob/master/diversity-inclusion-bias/inclusion.md)

**Comment by alodahl** [comment]
@tiffanyjstuart great catch! Would you have time to add them based on the order in the Roadmap, or should I make an issue for that?

**Comment by yati1998** [comment]
@alodahl  can I work on this?

**Comment by tiffanyjstuart** [comment]
@alodahl No need to make an issue, I made a new PR (https://github.com/Techtonica/curriculum/pull/742) adding them to the Roadmap and consolidating my other PRs

**Comment by yati1998** [comment]
@alodahl do I need to add prerequisites to the links in which none is already mentioned?

**Comment by alodahl** [comment]
Only if they seem necessary. Having “none” for prerequisites can be fine.

**Comment by alodahl** [comment]
Hi @yati1998 , thanks for working on this. Since all of the prerequisites you’re fixing are under the same issue, *please* put them all in the same pull request at once and close all the others that you’ve made for this issue.  @Kundan28 @manaswinidas @Shwetha-Acharya @hoduchieu01

**Comment by Kundan28** [comment]
> Hi @yati1998 , thanks for working on this. Since all of the prerequisites you’re fixing are under the same issue, _please_ put them all in the same pull request at once and close all the others that you’ve made for this issue. @Kundan28 @manaswinidas @Shwetha-Acharya @hoduchieu01

@alodahl How to figure out which one to keep or @yati1998 will close all the PR and start a new one ?

**Comment by alodahl** [comment]
@Kundan28 @manaswinidas @Shwetha-Acharya @hoduchieu01 No need to review any of yati’s PRs until she combines them into one... they are all for the same single-contributor issue.

**Comment by Kundan28** [comment]
Okay.
