### ISSUE TITLE
Ensure Prerequisite sections are correctly linked (2/2)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#731]
## Task:
Check the second half of the outlines in the [ReadMe Table of Contents](https://github.com/Techtonica/curriculum/blob/master/README.md#table-of-contents ) and ensure that the prerequisites are linked correctly.  

**For example, if you see this:**
### Prerequisites
- Command Line Lesson

**You should change it to this:**
### Prerequisites
- [Command Line Lesson](/command-line/command-line-interface.md)

**Complete the Prerequisite sections in these sections’ outlines:**
- [ ] Server-side programming
- [ ] Data Structures & Algorithms
- [ ] Career Development

Most of them should already be done, but your job is to track down the last ones.

Exceptions: if the prerequisite is obviously advice rather than a specific lesson, you don’t have to link it. However, since you’ll be exploring our curriculum anyway, use critical thinking to add an unmentioned prerequisite if it seems like it should be there. Message Alina with curriculum content questions.

**Comment by rudri182** [comment]
I would like to work on this issue

**Comment by rudri182** [comment]
While working on this issue, I found that [data models](https://github.com/Techtonica/curriculum/blob/master/databases/data-models.md) is linked twice in the content.
The link of the content is [here](https://github.com/Techtonica/curriculum/blob/master/README.md#server-side-development--agile-programming).

**Comment by rudri182** [comment]
Are JS and JavaScript different? Somewhere it is written as JS and somewhere it is JavaScript. As per my knowledge, they both are the same 😃  but I want to confirm it before I change it and the meaning is changed.

**Comment by rudri182** [comment]
Generated PR #740 for this issue.

**Comment by alodahl** [comment]
@rudri182 You're correct, the'yre the same =)  . JS is just the abbreviation.

**Comment by rudri182** [comment]
Okay☺️

**Comment by rudri182** [comment]
@alodahl the file called [Assessment #10: Advanced Methods](https://github.com/Techtonica/curriculum/blob/master/projects/advanced-methods-assessment-10.md) is not completed in the curriculum under the **project** folder. It is only drafted. So may I generate the issue for it? Or is it okay for now?

**Comment by alodahl** [comment]
@rudri182 thanks for noticing, but it is complete. It’s intended to be a checklist of what the learner should include in their assessment file.

**Comment by saberprashant** [comment]
Hi @alodahl , is this issue still open? I asked this because I can see that you closed #22 (4 days ago).

**Comment by alodahl** [comment]
It is open. The other issue was a duplicate.
