### ISSUE TITLE
Clean up ‘Intro to Git’ slideshow

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#744]
## Task:

Edit and clarify this Git & Github slideshow based on the slide comments. Also use your judgement to clarify or elaborate on parts you think beginners could find confusing. 

Be sure to stick to the existing sizes and styling.

Link to slideshow:
https://docs.google.com/presentation/d/1znMOomkIkAkFKIz2e6t5tLpyzObKqOwfd90fsixSiec/edit?usp=sharing

**Comment by rudri182** [comment]
May I work on this issue ?

**Comment by viditkumar** [comment]
If no one is working, I would like to get this task assigned to me.

**Comment by rudri182** [comment]
It is assigned to me

**Comment by saberprashant** [comment]
Hi @rudri182 , I hope you are working on this, how is it going? If you need any help then let me know and I have added some comments for some changes, so please have a look at them as they will make the tutorial better. Cheers :)

**Comment by Kundan28** [comment]
@alodahl 
Do this slide too have to follow the same  formatting as of other slideshows ?
- Each slide has the Techtonica logo & bar at the bottom
- The accepted text colors are black, gray, and custom turquoise
- All text is in Lato font
- Headers are at size 28 font, while regular text is either 18 or 24(preferred), with the exception of footnotes/side notes

**Comment by rudri182** [comment]
@saberprashant your comments are very helpful and I will change it accordingly. Thanks for noticing these. 🙂

**Comment by rudri182** [comment]
I have made some changes in a slide show as per comments(still working on some slides). Is it necessary to keep all fonts in Lato or it is okay to keep different font for _commands_? Like for `git diff` I have used _consolas_ fonts. I saw that this is used in some starting slides. So I did it for every command. If it is not proper please let me know, I will remove it.

**Comment by Kundan28** [comment]
@rudri182 In most of the slides the font size of regular text is not 18 or 24. So please change them to either 18 or 24.

**Comment by alodahl** [comment]
@rudri182, console font for code is fine. Please stick with sizes 18 and 24, though.

**Comment by alodahl** [comment]
@viditkumar check out out to-do list here for available issues: https://github.com/Techtonica/curriculum/projects/2

**Comment by rudri182** [comment]
What about font size in a grey box?  Because it looks too big if I try to set it 18. May I change it to 18 or not? For everything else, I have made to 18 or 24.

**Comment by Kundan28** [comment]
> What about font size in a grey box? Because it looks too big if I try to set it 18. May I change it to 18 or not? For everything else, I have made to 18 or 24.

I think no need to change that to 18...it's clear and visible in 14 also.

**Comment by saberprashant** [comment]
Yeah

> What about font size in a grey box? Because it looks too big if I try to set it 18. May I change it to 18 or not? For everything else, I have made to 18 or 24.

Yeah @rudri182 , no need to change that, it's fine.

**Comment by Kumaranupam2020** [comment]
https://docs.google.com/presentation/d/1znMOomkIkAkFKIz2e6t5tLpyzObKqOwfd90fsixSiec/edit?usp=sharing
changed some sequence in slide no. 3 for better understanding

**Comment by Kundan28** [comment]
> changed some sequence in slide no. 3 for better understanding

I don't see any change.

**Comment by rudri182** [comment]
I changed this slide as the comment beside the slide that is made by @saberprashant.

**Comment by Kundan28** [comment]
> I changed this slide as the comment beside the slide that is made by @saberprashant.

Nice work @rudri182

**Comment by rudri182** [comment]
I am not so clear about `"git add ."` in slide no. **11**. I googled it out but I am confused. Can anyone please help me to add this in that slide?

**Comment by Kundan28** [comment]
I think no need to show `git add .` as the heading of the slides says Adding A File to Track, which means only adding single files but when we run `git add .` all the files will be added. So no need to add that command.

**Comment by rudri182** [comment]
May I need to add anything more to the slide-show? Or is it complete now?

**Comment by Kundan28** [comment]
@rudri182 Everything seems fine to me.

**Comment by alodahl** [comment]
awesome work!  find a typo anywhere in the repo (even fixing whitespace), make a PR with it, but title and describe **this issue** and not the typo.

**Comment by rudri182** [comment]
Created PR #781
