### ISSUE TITLE
Write SQL topic outline

### ISSUE THREAD

**Issue by vsharma20v** [Techtonica/curriculum#774]
Acceptance Criteria:

 * [ ] The lesson can be covered in 30-45 minutes
 * [ ] There are clear objectives
 * [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
 * [ ] There is a cheatsheet or other handout
 * [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by vsharma20v** [comment]
@alodahl  ma'am plz review this issue and also labelled it.

cc: @Kundan28 @hoduchieu01 @Shwetha-Acharya

**Comment by vsharma20v** [comment]
I want to work on this if this issue is accepted.

**Comment by alodahl** [comment]
Thanks @vsharma20v but it’s already covered: https://github.com/Techtonica/curriculum/blob/master/databases/sql.md

**Comment by vsharma20v** [comment]
@alodahl  Oh I think I missed that outline to see

**Comment by vsharma20v** [comment]
@alodahl then can I close this issue?
