### ISSUE TITLE
Create an exercise about reset.css and browser differences

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#780]
## Task:
Create a file in the css folder and write a short guided exercise on reset.css basics.  It can be from a really good resource online, or even a video, as long as you site it and include the link.  You can also write it yourself. We want an exercise where you try a simple website with and without a reset.css and observe the differences. Be clear you do not expect everyone to begin using a reset.css in their projects immediately; this is really so people learn about the user agent stylesheet, and the benefits of normalizing their styles between browsers before they start customizing styles in their project.
Another great thing to point out would be browser-specific styles, such as -webkit, -moz, etc.

This should be a pretty short exercise, ideally about 30 minutes. Use the outline template found in the _templates folder in our project.

**Comment by vsharma20v** [comment]
@alodahl ma'am can I take this issue?

**Comment by vsharma20v** [comment]
@alodahl ma'am is there any difference between a topic outline and topic guided practice because in the _templates folder I found topic_outline.md file. And if there is any difference between the two mentions above then what are they.
can you elaborate what things I need to do in a guided practice of a topic?

**Comment by alodahl** [comment]
‘Guided practice’ is a section in the outline. A guided exercise is what I’m using to describe the intention of the whole new outline for reset.css.

**Comment by vsharma20v** [comment]
Ok @alodahl ma'am thanks for the clarification
