### ISSUE TITLE
About position of Curriculum Developer [Volunteer]

### ISSUE THREAD

**Issue by ramlaxman** [Techtonica/curriculum#784]
Hi,
This is Mayur Patil.  I am working as Assistant Professor at MITAOE from last 4+ years. 
Kindly let me know guidelines of how to contribute.
Following are my areas of specialization:

- ### Linux 
   - **Open Source**
   - **Linux Philosophy Types**
   - **In-Built and FOSS in Linux**
   - **Shell Scripting**
   - **Advanced Shell Scripting**
   - **Kernel Programming for Beginners**
   - **Overview of Linux API**

- ### Git
  - **Git for Beginners**
  - **Intermediate Git for Geeks**

- ### Cloud Computing
  - **Compute:** Containers, Cache, Virtualization.
  - **Storage:** 
     - Types: Block, File, Object; 
     - File System: Distributed, Parallel, Virtual; 
     - Databases: 
          - Types: In-Memory, Memory Centric;
          - Models: SQL , NoSQL
  - **Network**: Software Defined.

- ### [Python](https://github.com/ramlaxman/Python-Interview-Questions/blob/master/README.md)

- ### JS

**Comment by Kundan28** [comment]
Welcome @ramlaxman 
Please go through the Readme.md (https://github.com/Techtonica/curriculum) to know how to contribute to this project.

**Comment by alodahl** [comment]
Do you think this is something you can help with, @ramlaxman ?

**Comment by ramlaxman** [comment]
@alodahl Definitely. I have worked as Subject Matter Expert for Linux, python, cloud computing for 2 years.
Kindly allocate me issue directly so I should get things start asap.

**Comment by alodahl** [comment]
@ramlaxman   You are welcome to start working on anything in the "To-do" column on our project board: https://github.com/Techtonica/curriculum/projects/2

**Comment by ramlaxman** [comment]
Thanks. I will start asap.
