### ISSUE TITLE
add links to roles-in-security outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#788]
I received a tip about a career in security. Your task is to find the links for the resources and events mentioned, and add them to our roles-in-security.md topic outline in appropriate section(s).

connect with other women security orgs like Women in Security and Privacy, Women Cyberjutsu and other orgs is very helpful. They tend to have free trainings and offer scholarships. Right now you can sign up to get a free scholarship to Def Con.  See if you can connect with their members and find a mentor. That will help you along a lot.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by yati1998** [comment]
@alodahl can I contribute to this? and Is this a part of GSSoc

**Comment by Kundan28** [comment]
@yati1998 I think this issue is not ready yet...as GSSoC19 label and difficulty(Beginner, Easy, Medium or Hard) label is not there yet.

**Comment by alodahl** [comment]
@yati1998 please look for ready issues here: https://github.com/Techtonica/curriculum/projects/2

**Comment by Gustavomagalhaes** [comment]
Hi @alodahl, I would like to contribute on this one!
