### ISSUE TITLE
Add debugging strategies to interviewing guides

### ISSUE THREAD

**Issue by hoserdude** [Techtonica/curriculum#794]
Many companies are including a debugging exercise as part of their interview process. Since debugging is core to your day-to-day work as a developer (and fixing bugs a first set of tasks on the job). Interviewers want to see that the candidates can navigate an issue from the something the candidate has never seen, to identifying the problem, followed by applying a fix and verifying/testing the solution.

This task would be to create a playbook for debugging "other people's code" and some tips on how to demonstrate the ability to get to root cause and a solution within a constrained time frame.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by hoserdude** [comment]
I'm volunteering for this one, having been through this myself.

**Comment by alodahl** [comment]
Hi @hoserdude, that's definitely true.  We already have some  intro lessons on debugging and navigating new codebases, but if you think there is something missing from these, or if you're interested in exploring a more advanced/interview based debugging challenge, a strategy guide and exercises would be very helpful!  

https://github.com/Techtonica/curriculum/blob/master/debugging/debugging.md
https://github.com/Techtonica/curriculum/blob/master/navigating-new-codebases/navigating-new-codebases.md

Here's our template to get you started:  https://github.com/Techtonica/curriculum/blob/master/_templates/topic-outline.md

**Comment by hoserdude** [comment]
Thanks @alodahl - from what I have seen there's some material to be added to help with server-side debugging. It's going to also be helpful to have some real-world scenarios. One company I interviewed with had me identify and fix a bug in an open-source framework. We can choose a few examples like that to demonstrate how you start to how you wrap it up. 

I will take a crack at it.

**Comment by alodahl** [comment]
How is this going, @hoserdude ?

**Comment by alodahl** [comment]
@hoserdude , Is this still something you're interested in doing?

**Comment by alodahl** [comment]
Hi @hoserdude, I'm going to make this available to other volunteers; let me know if you'd like to pick it back up.

**Comment by vegetabill** [comment]
Thanks for opening this @hoserdude . However, since no one has picked it up, I'm going to close it in 2 weeks unless I hear from you.

**Comment by alodahl** [comment]
Hey @vegetabill I've been adding this red tag to issues so I remember which ones I've put a deadline on! You can remove it if it's not helpful.

**Comment by vegetabill** [comment]
@alodahl that's perfect!!!! And the deadline has come and gone so 👋

Anyone who comes across this and wants to add, it feel free to re-open. This is not a judgment of the idea, just that we have no shortage of ideas, but shortage of time.
