### ISSUE TITLE
Add tips to debugging lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#814]
## Task:

Add the following tips to our debugging.md outline.  You should make a General Tips sub-section in Lesson, or add the tip in common misconceptions if it seems like a better spot.  You are welcome to re-word these, too:

  - the phrase "pattern matching" and why it's important: use other code snippets to remind yourself of correct syntax

  - when VS Code shows you a red squiggly underline, it's trying to help. pay attention to the message.

  - if the red squiggly underline is under something that's clearly correct, like color: red; in a css file, then first check if it really is correct

 - when you make a change on a file, and then visually when you refresh your page you don't see any changes, run through a quick checklist:

    - did you save? this kills me every time (see: add autosave to VS Code lesson if it's not already there)

    - make a temporary, very obvious change on your html page. i write some text in the top of the body, or a prominent heading. save the file and reload the browser. verify that you see the text. if you don't see the new text, maybe you have the wrong file open, or the file didn't save, or something else very strange is happening.

    - make a temporary, very obvious change to your css file. i like to add color: red; to something extremely obvious like body or h1. save and reload the browser and verify that the thing you expected to turn red actually turns red. if it doesn't, maybe the CSS file isn't getting loaded properly. or check for syntax errors earlier in your CSS file that may render the rest of your CSS file inoperable. are you missing a semicolon? did you use = instead of : accidentally? are you missing a quotation mark in a font declaration, so your CSS file thinks there's a really long string somewhere? are your curly braces correctly matched and closed?

**Comment by raibove** [comment]
@alodahl can I work on these issue

**Comment by vsharma20v** [comment]
@alodahl ma'am can u assign this issue to me?
