### ISSUE TITLE
Add new concepts to Bootstrap lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#816]
### Task:

Find our outline introducing Bootstrap for the first time, and add explanations of these 3 concepts in the Lesson section.  For any further explanation, ask @judytuna .

  - containers inside of containers. talk about rows and columns.

  - rows vs "masonry-style" a la pinterest

  - clarify order of overriding. large overrides small when screen is large. col-xs-12 col-lg-6 for example

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by raibove** [comment]
Can I work on  this issue

**Comment by raibove** [comment]
@judytuna  @alodahl  I am not able to understand the first point 'containers inside containers'. Shall I explain nested containers in it.

**Comment by alodahl** [comment]
I think that’s right. @judytuna ?

**Comment by raibove** [comment]
@alodahl  nested container are mostly not used, so I can't find its much reference from internet too.
Can I switch to another issue

**Comment by alodahl** [comment]
I think it just means show them how to position containers in other containers. But you may switch to another issue.

**Comment by vegetabill** [comment]
I didn't get any feedback about this and I'm actually advocating for Bootstrap to be bumped until much later in the curriculum. Unless anyone feels strongly about this, I'm putting it on the chopping block.

**Comment by abhinashgiri** [comment]
I'm not able to find the file where the task is to be done. Any help would be appreciated. Thanks.

**Comment by samridhijain27** [comment]
I am interested in working on this issue under Gssoc '20.

**Comment by Kundan28** [comment]
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by vegetabill** [comment]
I'm closing as wontdo
