### ISSUE TITLE
Add mac tips to keyboard shortcuts file

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#818]
Explain these mac tips in a relevant section of keyboard-shortcuts.md:

  - two fingers to scroll on touchpad

  - pairing a magic mouse: put it in discovery mode by 1. turn it off. 2. hold down the mouse "button" and keep holding while you 3. turn it on (using the tiny switch on the back). then the green light should blink twice repeatedly. https://apple.stackexchange.com/a/181549

  - rename your magic mouse so you can identify it (and not steal someone else's mouse)

**Comment by frostborne** [comment]
@alodahl Can I claim this issue? I'm a Gssoc participant. I'm thinking about creating a new section - **'General Tips'** or **'General Accessibility Tips'**  since there is no relevant section where the above tips can be placed.

**Comment by alodahl** [comment]
sure @frostborne, just make sure the tips title specifies they are for Mac.  I dont know if you should say 'accessibility', since that implies screen readers, etc... features that allow people with specific needs to use an app.

**Comment by alodahl** [comment]
reply to my github invitation, and I will add you as the assignee.

**Comment by frostborne** [comment]
@alodahl Thanks, invitation accepted
