### ISSUE TITLE
Research task: find a good place to mention lorem ipsum text, images

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#819]
## Task:
1. Look through the Client-side curriculum in the project ReadMe.md for a good place to mention resources to get lorem ipsum text, images. 
2. Comment in this issue, and let Alina know which file and which section you think this would work well in.
3. Add links for places to find lorem ipsum text/ images, as well as a short explanation of when you would need it during development.
4. Make your PR!

**Comment by vsharma20v** [comment]
@alodahl ma'am can I work take this issue?

**Comment by alodahl** [comment]
To clarify:
Part of the issue’s task is to make the decision of where to put the link.  Once you find it, check with me.  Then you can put the link in, as well as a short description of why we’re adding it - to provide filler text and images for when you’re designing your site, but before you have your content ready.

**Comment by vsharma20v** [comment]
@alodahl ma'am its a bit difficult because no topic outline does justice with the importance of it. I would like to present a new idea for this what about adding a new topic outline "best practices in Client-side Development " and then add about lorem text/images in that and also some more best practices like using small size image for the mobile view of the website.

**Comment by alodahl** [comment]
That sounds like a good idea.  No pressure to add a lot of extra topics, but if you think it would be better on its own, go ahead and start your own file using a template from _templates/ .  😊

**Comment by alodahl** [comment]
How is this issue going? Do you need anything?

**Comment by vsharma20v** [comment]
> How is this issue going? Do you need anything?

I'm working on it but my speed gets slow because I have my last exam tomorrow.
After tomorrow I will be catchup my previous speed. :man_technologist:

**Comment by alodahl** [comment]
Good luck!!!  📝🧠
