### ISSUE TITLE
Add bash resource to first command line lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#820]
## Task:

1. Look through this resource:  https://guide.bash.academy/inception/
2. Find the file command-line-interface.md.
3. Add the resource link to that file in the supplemental materials section, along with the fact that it is a recommended resource, and a short description of what they'll find there.
4. Make your PR!

**Comment by raibove** [comment]
Can I work on this issue once my PR gets merged?

**Comment by raibove** [comment]
The command line lesson is under Programmer tools  - Intro to Command Line Interface Tools [https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md].
I did not found file with name first command line in Client-side section.

The file is also not mentioned in this folder :[https://github.com/Techtonica/curriculum/tree/master/command-line]

**Comment by alodahl** [comment]
Sorry, that's the one - please use command-line-interface.md.
