### ISSUE TITLE
Take a hard look at our sql relational databases outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#824]
We need someone with a good knowledge of relational databases to fix and audit our https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md outline.  Currently, it has good content, but lots of problems:

- [x] Scary Avalanche of materials. It should only have what we require learners to do as part of the lesson. Please look at these and decide what they really need, and move the rest to supplemental materials (See #790 ) . -also, check off this outline in 790 while you’re there, please.
- [x] Probably inaccurate projected time - please fix after you’ve changed everything. Estimate in hours, not days.
- [x] ‘Things to teach’ needs to be a short list of the topics, not the whole dang lesson. That’s what the lesson section is for.
- [x] we have a new outline for how to install postgresql. Link it when the outline tells learners to install postgresql.
- [x] Needs new ‘check for understanding ‘ with questions instead (see #700  ). also, check off this outline in 700 while you’re there, please.
- [x] Needs a supplemental materials section for all links removed from other sections.
- [x] make any other formatting, grammar, or general changes that you think would improve the outline or it’s accompanying slideshow. Ask Alina for access if you’d like to change the slideshow.
- [x] see /_templates/topic-outline.md for more info on how outline sections should be used.

**Comment by yati1998** [comment]
@alodahl Can I work on this issue once I am done with the other issue. I have made changes in the previous one.

**Comment by Kundan28** [comment]
> @alodahl Can I work on this issue once I am done with the other issue. I have made changes in the previous one.

Yeah, you can definitely work on this issue once your all pending PR are merged...

**Comment by yati1998** [comment]
@alodahl  can you please assign me this issue?

**Comment by alodahl** [comment]
@yati1998 after making changes to #821 you are welcome to work on this 😊

**Comment by yati1998** [comment]
@alodahl I have made the required changes.

**Comment by yati1998** [comment]
@alodahl  can you please tell me what I need to do with #790 ? and moreover it is not related to this outline, so do I need to make the change in the material section or will refer to some other?

**Comment by yati1998** [comment]
@alodahl  what do I need to check in #700 ?

**Comment by alodahl** [comment]
Be sure that your file follows the guidelines set in #790 and #700 , since you will be working on all sections here.

**Comment by yati1998** [comment]
@alodahl  please do check my new PR.
