### ISSUE TITLE
Brainstorm practical optimization advice for a React/Node project

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#84]
It's been determined that students should know how to optimize their services for production--for example, compressing images, preloads, etc. However, it's unclear what, exactly, apprentices should learn, but we hope to have a 1 hour lesson on what specific steps to take to optimize a project before deploying.

[This is the high-level lesson on optimization](https://github.com/Techtonica/curriculum/blob/master/optimization/optimization.md) already in the curriculum.

Please contact Alina (@alodahl) or Judy(@judytuna ) if you have some input, or leave it in the comments below.

**Comment by jonah-williams** [comment]
Some options:

Introduce tools for measuring site performance like Google's PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/?url=techtonica.org) and act on some of the recommended improvements.

Introduce performance timing apis. They're available in both browsers and in node (https://nodejs.org/api/perf_hooks.html) and could be a good tool for measuring performance within a section of code. Unfortunately probably not a great fit for measuring React components so there you might want to look at React's tools (https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab or https://calibreapp.com/blog/react-performance-profiling-optimization/).

Alternately maybe it's useful to have a lesson on caching; what assets/paths to cache, how to adjust cache control or vary on headers, what can go wrong (sharing user specific content via a cache, serving old assets from you caches by mistake), or publishing assets to a cdn.

**Comment by mhess** [comment]
I don't have a whole lot to add what Jonah has already put up.  Caching seems like it merits the most discussion, as it's a complex topic that's relevant in all computing, and probably the optimization technique that I've used most throughout my career.  Here are the only other things that come to mind:

- Code splitting and server-side rendering for improved initial load time and also SEO in the case of SSR, (although, the Google crawler does apparently execute JS).  This is something that would potentially be caught by the Google perf tool Jonah links above.

- Push all computationally-intensive work into another thread/process, and try to never use synchronous I/O methods.  All the JS engines I know are single-threaded.

**Comment by judytuna** [comment]
Do we need both files in https://github.com/Techtonica/curriculum/blob/master/optimization/ ? 
1. https://github.com/Techtonica/curriculum/blob/master/optimization/optimization.md 
2. This topic outline contains only the topic outline template: https://github.com/Techtonica/curriculum/blob/master/optimization/optimizing-your-react-node-project.md 

I think it makes sense to have these as two separate topic outlines, `1. optimization` for going over the general concepts and `2. optimizing your react/node project` as a specific checklist for them to execute on their ongoing project. But someone would have to make 2 =)

**Comment by mhess** [comment]
I've been assigned to make 2 :)  Alina and I have been discussing what makes the most sense in terms of things they can actually do to their own project.  @alodahl should we move that discussion to this thread?

For **caching**, one obvious and achievable task seems like giving them a new requirement that the results of old searches need to appear immediately.  Making requests to the eventful API right now takes ~1 sec, which is a delay that they can observe.

The other item that we'd been discussing is **minification**; however, doing this with `create-react-app` is trivial, and is something they should have already done when they deploy their app to Heroku earlier in week 10, and so I'm not quite what else we can have them do around minification...

Another possibility that I'm thinking of is creating a feature/React component that is purposefully slow 
and ask them include an optimized version into their project.  This could be a good opportunity for them to get familiar with react performance tools.  However, it may or may not be an appropriate task for them, and I'm not yet sure how easy it would be to create something like this.  I can do more research this week...

**Comment by alodahl** [comment]
Hi @mhess, Your caching idea seems perfect, especially if you show them how to time the request.

I'm not sure what you mean by :"and is something they should have already done when they deploy their app".  Is minification automatic in create-react-app, or are you referring to something else?

I think that giving them a practice optimization problem would be awesome - it doesn't have to actually be incorporated into their existing projects.  If it is something you're sure they'll run into in real life, it's relevant.  do you agree @judytuna ?

**Comment by alodahl** [comment]
I don't know how I unassigned you or how to reassign you, sorry!

**Comment by mhess** [comment]
@alodahl no worries! :) Sorry I wasn't more clear.  So, minification is not automatic, but is kinda required since the webpack dev server that runs when they're doing development will not be available in the production environment when it gets deployed to Heroku.  Fortunately, the build process itself is trivial; however, there are at least a couple of different strategies for building/deploying.  They will have to either build their assets and commit them to the repo OR add a script that does the building on the heroku environment.  I'm not a huge fan of committing build artifacts to the repo, and feel like the latter is the best practice.

**Comment by alodahl** [comment]
@mhess That sounds great!  How long do you think it would take you to add a caching exercise and a build-script exercise to the outline?  The apprentices will get to the Optimizing your "React/Node Project" topic on March 13.  Also, if it feels like a lot, would you be willing to work with Jonah?

**Comment by alodahl** [comment]
@mhess ,  how is this going?  Do you think the exercises could be ready for apprentices to follow by March 12?

**Comment by mhess** [comment]
@alodahl my sincere apologies for the delay--I got a little buried this week.

I've got a rough draft of the outline up in #646.

Not exactly sure where the apprentices are with their React Eventonica projects.  I was assuming that the project would following the [original structure](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md), but now I see that in the lesson [outline](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-react.md) for 3/6 that keyword search is not a feature anymore.  I have component/repo with that functionality in it that we could provide for them add the caching to, but maybe we want to keep them working within the scope of the current feature set?

In addition to caching and minification, I included a section about React optimization, and using React Dev tools.  The new profiler is pretty great, but maybe that's too much material to cover?

**Comment by alodahl** [comment]
@judytuna , is keyword search not a feature of eventonica-react?

@mhess , thank you so much for working on this!  I'm estimating that what you have would take them 30 minutes, so if the rest of your ideas would take 45 minutes or less, I say go for it.

**Comment by alodahl** [comment]
@mhess, do you think this outline will be ready for tomorrow? We were hoping to have the apprentices work on React/Node Optimization then.

**Comment by mhess** [comment]
@alodahl Met with my apprentice mentee on Friday, and it looks like the keyword search is no longer a feature.  However, I've written a component and a little mini-API node app that provides search functionality in this [gist](https://gist.github.com/mhess/2a9213d209c4ea464ab305f7bec56300).  We could have them just pop the component into their apps and do the cache optimization on that...

When you say 45min for the React optimization, are we talking just instruction time or instruction + the time required for them to actually work on that optimization?  If they're going to be lectured about React optimization, I feel like the lecture itself could take around 30-45 min...

**Comment by alodahl** [comment]
@mhess yes, lecture can be 30-45 min and practice can be 30-45 min.

**Comment by mhess** [comment]
@alodahl Just finished the lesson outline!  Please feel free to make edits!
