### ISSUE TITLE
Strengthen "Motivation" sections: Part 3c

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#854]
This issue is intended for a single contributor.  Most or all of the Topic Outlines below have an absent or incomplete ### Motivation section.

### Ensure that they all have:
- Useful "Motivation" sections, and 
- 2 companies that use that technology, how they use it, and a  link to an example. Ideally, they are well-known companies.
- [Here's an example of a good motivation section.](https://github.com/Techtonica/curriculum/blob/master/css/media-queries.md#motivation)
- Hint:  If you are having trouble brainstorming, try searching for the technology here: https://stackshare.io/

#### If you're having trouble coming up with something,
 just google "why is it important to learn about [this topic]", and formulate an answer from the best results.  Please link the companies and any copied text.

#### If the file already has a great looking motivation section, 
you can leave it alone, but let us know in your PR.

#### If you have a question, 
please message Alina, or leave a comment on the issue.

### Make sure these topic outlines have complete motivation sections:
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-6-object-literals.md
- [x] https://github.com/Techtonica/curriculum/blob/master/runtime-complexity/runtime-complexity.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/basic-js-practice.md
 
For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by frostborne** [comment]
@alodahl  Can I work on this issue?

**Comment by frostborne** [comment]
@alodahl I won't be able to work on this till 7th June, will that be okay?

**Comment by alodahl** [comment]
That's fine!  Thank you for continuing to help, it makes a difference 💫

**Comment by alodahl** [comment]
Hi @frostborne , how is this issue going?

**Comment by alodahl** [comment]
Hi @frostborne , should I make this issue available for other volunteers?  I haven't heard from you in a while.

**Comment by eaquin1** [comment]
@alodahl, I would like to work on this, if possible!
