### ISSUE TITLE
Write "Object-Oriented Programming" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#87]
The lesson plan should live at [`OOP/OOP.md`](https://github.com/Techtonica/curriculum/blob/master/OOP/OOP.md) and discuss SOLID.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
Moved to here: https://github.com/Techtonica/curriculum/blob/master/object-oriented-programming/object-oriented-programming.md

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/89b8de9c8b28b6c64973ac5348d298a0775ddae8/javascript-8/javascript-8.md
