### ISSUE TITLE
Add example solutions to challenges in repl.it classroom

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#879]
Only admins can access our account to check this, so Mentors please approve once the PR is in the scoresheet.

**Comment by alodahl** [comment]
Sorry to keep you hanging on this one... I’m waiting to hear what the program manager wants for the assessments.

**Comment by imskr** [comment]
Its ok no problem.

**Comment by alodahl** [comment]
I have another task for when you have time though - could you add "example solutions" to the 2019h2 challenges instead?  You can just look at the submissions for them from 2019h1 and pick the best ones.

**Comment by imskr** [comment]
Yeah I will do it.

**Comment by alodahl** [comment]
Hi @imskr , how is this going?

**Comment by imskr** [comment]
Sorry for delay.. It will be done tomorrow!
