### ISSUE TITLE
Write "Data Structures" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#88]
The lesson plan should live in the [`data-structures` directory](https://github.com/Techtonica/curriculum/tree/master/data-structures).

It should cover

- hash tables
- linked lists
- stacks
- queues
- trees
- tries
- graphs
- vectors
- heaps

Acceptance Criteria:
- [ ] The lesson can be covered in 2 days
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a cheatsheet or other handout
- [ ] There is an assessment

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by MichelleGlauser** [comment]
Here's the start: https://github.com/Techtonica/curriculum/blob/master/data-structures/what-is-a-data-structure.md

**Comment by MichelleGlauser** [comment]
https://github.com/Techtonica/curriculum/blob/master/data-structures/intro-to-data-structures.md
