### ISSUE TITLE
Add coding event sections, specify event locations and times

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#881]
We have some great resources in https://github.com/Techtonica/curriculum/blob/master/women-in-tech-resources/resources-list.md, but we need to clean up some hackathon info.

- [ ] in the India part of the outline, someone has made some great sections like Hackathons, Competitions, Open-Source, etc. Please look through the links in General/SF Bay Area and make sections like this too. One still needs to be made for general/sf. one example that needs to be moved is Hacktoberfest.

- [ ] look into Hackathons, Competitions, Open-Source,and any other event-based links, and make sure the location and general date or time of year is next to the event. for example:
  - Hacktoberfest (remote, the whole month of October)
  - GirlScript Summer of Code (India, March April and May)

- [ ] If there are more than a few remote hackathons, make them their own sections, 
### Remote Hackathons 
and 
### Local Hackathons
If Location doesn't matter at all, and it's not specifically an American or Indian community, put the remote section in General/SF Bay Area. If they're still intended to be an Indian community,  keep it in the India section. 

- [ ] Organize all event links by start date! January -> December

**Comment by pydevsg** [comment]
I am taking this issue @alodahl .

**Comment by imskr** [comment]
Can i work on this ?

**Comment by alodahl** [comment]
Hi Shubham, are you still working on this or should I move it back to To-do?

**Comment by imskr** [comment]
Sorry didn't manage to solve this!  Please move it to To-Do.
