### ISSUE TITLE
Add any missing full lesson outlines from roadmap spreadsheet to root README

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#882]
We have added a lot of content, and need help updating our Techtonica/curriculum Readme Table of Contents. https://github.com/Techtonica/curriculum#table-of-contents

Keep the current format, but add any missing or outdated links in the "outline" column in the Techtonica Roadmap to our ReadMe. This includes assessments and tutorial links, and any link in the "outline" column that isn't private access only.
https://docs.google.com/spreadsheets/d/1sGJpzOfaZJW8OedBBf5eHOBppivAoc8Ug4tEmxG8IZ8/edit?usp=sharing

- The RoadMap is the source of truth.  If the order is different in the RoadMap, change the README to match.
- No duplicates, please, even if there are duplicates on the Roadmap.
- add missing full lesson outline files (no homework, no external links, no worksheets, no code challenges)
- Fix dead or incorrect links in Readme.
- Contact @alodahl  or @vegetabill for any questions about content.

**Comment by vegetabill** [comment]
@alodahl is this still relevant? I think it may be somewhat hopeless to have the Roadmap and README always in sync. How many external folks use the curriculum?

**Comment by alodahl** [comment]
I wouldn't stress about it always being in sync, but as the curriculum evolves, I think it would be good to sync up the lesson order with the roadmap every cohort or so, and/or keep the ReadMe in mind as we add or deprecate content. This would benefit anyone outside the program using it.  I don't think there are more than a few people in that category right now, but I understood from Michelle's description of a "free online curriculum" that it should be accessible for anyone. If the ReadMe is very different from the Roadmap, that would not be true.

**Comment by Kundan28** [comment]
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by abhu-A-J** [comment]
@Kundan28 I'll like to work on this

**Comment by Kundan28** [comment]
@abhu-A-J Now you could start working on this issue.

**Comment by vegetabill** [comment]
@alodahl I've assigned this to you while it's revising so @abhu-A-J is open to be assigned other work. Re-assign it to him when it's ready please

**Comment by Kundan28** [comment]
@abhu-A-J Comment on other issue on which you want to work.
