### ISSUE TITLE
Add "Specific Things to Teach" list to Agile outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#899]
## Task:
Add a "Specific Things to Teach" list to our [Intro to Agile outline](/agile-development/intro-to-agile.md). It should just be a bulleted list summary of what they will learn in the lesson.  See other outlines for examples.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by pydevsg** [comment]
Please do merge as the time is very less,
