### ISSUE TITLE
Fix question typos in 2 outlines

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#911]
Fix the typos pointed out in this PR:
https://github.com/Techtonica/curriculum/pull/909

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by zhang1pr** [comment]
Has this been fixed already?

**Comment by alodahl** [comment]
@zhang1pr it is fixed, thank you for pointing this out.  feel free to pick up another issue here: https://github.com/Techtonica/curriculum/projects/2
