### ISSUE TITLE
Restyle "Confidence" slideshow using proper format

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#912]
https://docs.google.com/presentation/d/18XXIRn2AVWje-8sWErKzQyI_XPV_2aexmwTvkaO_ZPw/edit?usp=sharing_eip&ts=5ca2ae72

- 'copy' above slideshow to techtonicaorg@gmail.com 's google drive
- format it to match the [2020 Slides Template](https://docs.google.com/presentation/d/1uFlV8eVrPtwjb4wPoUCd7Fk3PNqf1Eoo9mZ-_7D3_GQ/edit#slide=id.p)
- replace all Confidence topic slideshow links in Roadmap and Outline with new slideshow.
[Roadmap](https://docs.google.com/spreadsheets/d/1vIr3fiKa_jxzy7qtFsiE5hEJbiTXwc1LYxbfsHOYD6U/edit?usp=sharing) | [Outline](https://github.com/Techtonica/curriculum/blob/master/professionalism/building-confidence.md)

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by karentobo** [comment]
I'm on it!

**Comment by alodahl** [comment]
if you cloned it, its a different URL. Thanks for your help!
@lalpert is it useful to change the current RoadMap, or is there a new one?

**Comment by lalpert** [comment]
@alodahl I've been working on a new roadmap for 2020, if you send me the new slideshow and what lesson it is, I can update in the new roadmap.

**Comment by vegetabill** [comment]
The endorsed way to do this styling is to have a master template just like the official Google templates. Without it, maintaining this styling seems a little impractical. 

I'm bumping this out of the project for now until I can discuss further with Michelle.

**Comment by alodahl** [comment]
@vegetabill I don't think that would be difficult...can't we just turn a good-looking one into the "official template"?  At best, it would be filled with super clear directions too, like "this is the title" "this is the image description.  Be sure that the image yada yada yada...."

**Comment by vegetabill** [comment]
@alodahl I haven't ever turned an existing slideshow into a template but I think it's not as friendly as it could be but from the generic title I didn't know the scope of this. I've split off what I'm talking about as a separate issue #1174, especially if this is the last one before finishing

**Comment by vegetabill** [comment]
Almost done with a proper Google slides template so will update soon

**Comment by alodahl** [comment]
hi @vegetabill can we get going on this one yet?

**Comment by vegetabill** [comment]
Sorry for the delay. Added template link in main body

**Comment by alodahl** [comment]
mind if I make this GSSoC?

**Comment by pa7ri** [comment]
hi :) if still available, I would like to work on it

**Comment by alodahl** [comment]
Assigning to @karenjoycelowe just until I get validation that techtonicaorg@gmail.com owns the slideshow.  Then lets make a ticket to add the link to the Roadmap and outline: https://docs.google.com/presentation/d/1vcrBfmQK4QCYd1-MAxe5eYPY2EQiD4VBpAsotwk0NV8/edit?usp=sharing

@vegetabill , can you tell if we own this?

**Comment by vegetabill** [comment]
@alodahl I couldn't tell as I don't have access to that account and the Google UI didn't seem to indicate owner anywhere. You can always make a copy yourself if you want to be sure it's the right owner.
