### ISSUE TITLE
Elaborate on Chrome Dev Tools Common Misconceptions

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#915]
Task: Elaborate on the [Chrome Dev Tools](https://github.com/Techtonica/curriculum/blob/master/chrome-developer-tools/chrome-developer-tools.md) Common Misconceptions section based on this linked review:

https://github.com/Techtonica/curriculum/pull/913#pullrequestreview-256351791

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by kristin-smith** [comment]
Can I work on this?
