### ISSUE TITLE
transfer mentor glitch proj to a techtonica glitch account

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#918]
Note: Blocked until we decide whether to deprecate the backend testing outline in favor of new outlines. If we deprecate that file, this issue will be moot.
---------------
transfer linked glitch to a techtonica glitch account:
https://glitch.com/edit/#!/zee-techtonica-backend-testing-ii?path=index.js:37:0

Ask Michelle or TaLea if a Techtonica account already exists.

If not, make a new one, and send the new credentials to @vegetabill  and Michelle.

After transferring, ensure that the backend-testing outline contains the correct updated link.

Ensure that the RoadMap  contains the correct updated link, if applicable.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by vegetabill** [comment]
@alodahl  Was this what we used before REPL.it? Is this still relevant?

**Comment by alodahl** [comment]
@bill, no, these were part of the guided practice in the "Testing your NodeJS Backend" outline(s).  Has repl.it added the ability to run a server file on their web app?  We used glitch because, at the time of writing, repl.it could not do that.

**Comment by Kundan28** [comment]
@vegetabill @alodahl Could this be worked under GSSoC20 ?

**Comment by alodahl** [comment]
@Kundan28 We're not sure yet.

@vegetabill is this lesson going to be deprecated by new backend lessons?

**Comment by alodahl** [comment]
Blocked until we decide whether to deprecate the backend testing outline in favor of new outlines. If we deprecate that file, this issue will be moot.
