### ISSUE TITLE
copy whiteboarding gists from alodahl to techtonica owned location, replace raw gist links.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#919]
https://github.com/Techtonica/curriculum/blob/master/interviewing/week-3-whiteboard-challenges.md

Create a new google doc for each linked gist in this outline. Be sure to use an account ending in gmail.com so it is easy to transfer ownership later.

Replace links in outline with new google doc urls.

Ensure google docs are visible to those that have the link, but view only.

Transfer ownership of the docs to techtonicaorg@gmail.com.

**Comment by vvscode** [comment]
@alodahl  is there any reasons to keep code in gists? Why just not place those examples in the repo, next to markdown file?

**Comment by alodahl** [comment]
It’s supposed to be a bit of a secret until the interview, but I suppose it would be fine to just keep it in the repo.

**Comment by vegetabill** [comment]
Longer term, I want to move these to a private repo so I'm closing this TODO as "Won't Do"

**Comment by alodahl** [comment]
as long as we don't forget about this task
