### ISSUE TITLE
Finish "Mobile Development" lesson outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#92]
- [x] A Intro to Mobile Development slideshow should be made in [this partially completed file](https://docs.google.com/presentation/d/1aaTRvbQf3jouzDCLCPFEazB3zAnNjtnw_Hgc-M6bB_I/edit?usp=sharing). Ask Alina for the edit link.

- [x] The accompanying  lesson plan should live at [`mobile-development/mobile-development.md`](https://github.com/Techtonica/curriculum/blob/master/mobile-development/mobile-development.md).

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by alodahl** [comment]
picked up by Josh Guffey

**Comment by tonyd256** [comment]
Added a bunch of informational slides. I think it should be pretty good to go.
