### ISSUE TITLE
Write "DevOps" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#93]
We need a topic outline that describes the work of a devOps engineer, and what steps an apprentice should take to pursue a devOps career. It should take 45-60 minutes to cover the topic. The lesson plan should live at https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/dev-ops.md

**Comment by pydevsg** [comment]
I would like to work on this issue.

**Comment by alodahl** [comment]
@pydevsg once you finish #593 , remind me and you can have this one next.

**Comment by pydevsg** [comment]
I shall complete my task and would love to work on this issue. Thanks for assigning #593 to me ,Mam.

**Comment by imskr** [comment]
If nobody is assigned. Can I work on this?

**Comment by pydevsg** [comment]
I am working on this @imskr . You can check for solving other issues.

**Comment by imskr** [comment]
OK @pydevsg
