### ISSUE TITLE
Web design patterns lecture slides have video without permissions

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#934]
Either figure out who should adjust permissions and get them to do it or replace the video? https://docs.google.com/presentation/d/1nkaj3LCyy61AqHvp7yMd6-yg_0fos2NP8MrLwmX8G0U/edit?usp=sharing

**Comment by alodahl** [comment]
I replaced it.  Let me know if someone finds a cooler site we should use instead.
