### ISSUE TITLE
Proofread "Security" roles topic outline, and edit if necessary.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#94]
- [x] Someone with security knowledge needs to proofread [this lesson plan](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/security.md) for accuracy & relevancy. The intention is to give apprentices a better idea of the security roles during career week.  It should take 45-60 minutes to cover the topic. Thank you!

- [Here is the accompanying slideshow.](https://docs.google.com/presentation/d/1mNyxzYGW-6M5yxBfJsxiwb9lcko5sa91thlBPKTodMg/edit?usp=sharing)  Ask for permission if you'd like to change this, too.

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by falun** [comment]
Can we get a read-only copy of the slides? It seems to have gotten dropped from the above comment

**Comment by alodahl** [comment]
Thanks for noticing, @falun.  I included the link 👍🏼

**Comment by imskr** [comment]
Can i work on this?
