### ISSUE TITLE
Updates Needed in Javascript 7 - Object-Oriented Programming

### ISSUE THREAD

**Issue by Reginatam429** [Techtonica/curriculum#945]
The code here was misleading based on the information given above and below it. The audiobook class should extend the book class: "class AudioBook extends Book". The paragraph above the example should also clarify that the audiobook class is a subclass of book.

```
class Book {
  ...
  
  calculateDueDate(borrowedDate) {
    return borrowedDate.setDate(borrowedDate.getDate() + 21);  // 21 days is 3 weeks
  }
}

class AudioBook {
  ...
  
  calculateDueDate(borrowedDate) {
    return borrowedDate.setDate(borrowedDate.getDate() + 14);  // 14 days is 2 weeks
  }
}
```

In addition, the tutorial link sends me to the H1 roadmap instead of a tutorial: "Go through this tutorial". 

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by bobbylcraig** [comment]
Hey @Reginatam429, I'll update this in two separate PRs. Looks like [here](https://docs.google.com/spreadsheets/d/1vIr3fiKa_jxzy7qtFsiE5hEJbiTXwc1LYxbfsHOYD6U/edit#gid=0&range=C124) they're probably referencing [this tutorial](https://www.google.com/url?q=https://www.learn-js.org/en/Object_Oriented_JavaScript&sa=D&ust=1565062459700000&usg=AFQjCNGC3NJJ4Ts86bdfpXn_nbUyjC5V7w).

I can adjust the wording and code above as well.

**Comment by bobbylcraig** [comment]
I've added two patches to the issues. I am concerned that the "Book" and "AudioBook" example isn't very clear (mostly because I'm not entirely sure this is an example that would play out in reality in this inheritance model...). If possible, I will try to remember to go back and update this with a more clear inheritance relationship. That's a big rewrite though.

**Comment by alodahl** [comment]
Hi @bobbylcraig and @Reginatam429 , thanks for pointing this out and for the fixes.  Should we make another issue about a rewrite?

**Comment by bobbylcraig** [comment]
@alodahl Depends how pressing of issues y'all make into issues? If you can add a low priority to it, that might be best :)

**Comment by alodahl** [comment]
Yes, that’s fine @bobbylcraig, none of them are more pressing than this on the board. Would you mind making an issue since you know what’s missing?

**Comment by bobbylcraig** [comment]
@alodahl Will do!

**Comment by yagosansz** [comment]
Hi,
Is this issue still available? I would like to work on it!

**Comment by alodahl** [comment]
Sure thing, @yagosansz .
@lalpert , is this one of the files that has moved?

**Comment by lalpert** [comment]
@alodahl @yagosansz This file has not moved, but I did make significant changes to it recently.

**Comment by yagosansz** [comment]
@lalpert Are there any improvements or changes to be done? If so, would mind elaborating a bit more on it, please. =)
Thanks!

**Comment by lalpert** [comment]
@yagosansz sorry for the delayed reply. No more improvements needed that I know of. I just created this issue also related to OOP if you'd be interested in doing it: https://github.com/Techtonica/curriculum/issues/1075
