### ISSUE TITLE
Come up with LinkedIn topic outline

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#948]
Make your outline here: https://github.com/Techtonica/curriculum/blob/master/professionalism/LinkedIn.md

Include https://www.photofeeler.com

I’m thinking this should be in the first week or so of the program, since having a LinkedIn page is in the welcome tips.  However, at the end of the program we have a resume writing outline, which also mentions LinkedIn. Please look at it too, at least to avoid redundancy - and linking your new outline in it might be a good idea: https://github.com/Techtonica/curriculum/blob/master/resume-writing/resume-writing.md
Once you finish, change the language in the resume one to ‘update your LinkedIn’ instead of making one.

**Comment by alodahl** [comment]
Isabel Rasmussen is working on this.
