### ISSUE TITLE
Add links to Test Automation University into Testing Lesson

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#951]
https://testautomationu.applitools.com/

@rbatta said this one might be most useful: https://testautomationu.applitools.com/web-element-locator-strategies/

**Comment by vegetabill** [comment]
Target: https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/enzyme-testing.md

**Comment by abhinashgiri** [comment]
I want to contribute to this with your permission. May I, please?

**Comment by habeeba-naaz** [comment]
I am gssoc20 participant...I am interested in doing this...please assign me if possible?

**Comment by vvijayalakshmi21** [comment]
Hi, Please could you assign this to me?
I would like to start my GSSoC'20 journey with this contribution

**Comment by alodahl** [comment]
@abhinashgiri I believe you asked first! Would you please fill this form out for us before you start? https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

**Comment by abhinashgiri** [comment]
I need to add https://testautomationu.applitools.com/
 link to this file https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/enzyme-testing.md 
 finding any suitable place in the document. Am I correct. Please, make me understand this issue clearly. Thanks.

**Comment by vegetabill** [comment]
@abhinashgiri yes I believe that's correct
