### ISSUE TITLE
Replace deprecated 'connect' function in API project with updated version

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#958]
Recent curriculum feedback: Connection function in [Eventonica](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md) is deprecated.

Replace connection function found in the linked file above with a current working version. This may require a change to the [starter code](https://github.com/Techtonica/curriculum/tree/master/projects/Eventful-API-test-page), the [project directions](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md), or both.  After you've tested that it runs correctly, make a pull request with the updated file.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by shubha-rajan** [comment]
@alodahl I'm going to start working on this one if that's ok, unless you want to save this issue for first-time Hacktoberfest contributors.

**Comment by alodahl** [comment]
Please go ahead! 😁
