### ISSUE TITLE
Write "Machine Learning" topic outline.

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#96]
The lesson plan should live at [`machine-learning.md`](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/machine-learning.md). You may want to use https://medium.com/@ageitgey/machine-learning-is-fun-80ea3ec3c471#.ycej28f2t as a resource.

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a slides version of the lesson for visual learners [that lives here](https://docs.google.com/presentation/d/1bjU2En4KHo1gx085-NQISuyHuPSSnYhVYBOMz9pr050/edit?usp=sharing).
- [ ] There is a list of self-assessment questions under 'check for understanding'

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by jyotsnaj06** [comment]
@alodahl is there someone taking this on?

**Comment by alodahl** [comment]
@jyotsnaj06 No, would you like to work on it? 😊

**Comment by jyotsnaj06** [comment]
Yes!

**Comment by imskr** [comment]
Is this going on ? @jyotsnaj06 Do you need any help ?

**Comment by pydevsg** [comment]
I would like to work on this issue if no one is actively working on the same.

**Comment by alodahl** [comment]
@pydevsg , Jyotsna is working on it here in California. Please focus on your Technical Writer issue 😊

**Comment by alodahl** [comment]
Hi @jyotsnaj06 , will you be able to finish this by next week? Could you use some help?

**Comment by vsharma20v** [comment]
@alodahl ma'am can I try this issue?

**Comment by alodahl** [comment]
@vsharma20v could you do me a favor and work on this before your other issue?  The deadline is real for this one!

**Comment by alodahl** [comment]
oh nevermind, you already made a PR!

**Comment by vsharma20v** [comment]
@alodahl ma'am I submitted the PR #718  plz review that
