### ISSUE TITLE
Replace outdated Express.js YouTube video

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#960]
Curriculum feedback: "The Express.js YouTube video is outdated."

There are youtube 3 videos at the end the [Express outline](https://github.com/Techtonica/curriculum/blob/master/express-js/express.md); find out which one they believe to be outdated by asking them on our slack #tech-help channel, or by looking through them yourself.

Replace with a video link that is more appropriate.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by dougfabris** [comment]
Hello @alodahl this project has a great purpose. I would like to start helping with this first issue. Can I work on that?

**Comment by alodahl** [comment]
@dougfabris that would be awesome, thank you! Since we are a non-profit, could you fill the form out before you get started?
https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1

After that, go ahead and assign yourself to this issue and you can get started!

**Comment by dougfabris** [comment]
@alodahl you're very welcome. I'll fill the form right now and start to see how can I help in the project.

**Comment by dougfabris** [comment]
@alodahl I can't find the slack channel link. Can you send to me? Maybe it can be enhanced in documentation too.

**Comment by alodahl** [comment]
Have you filled out the form?  Generally you will receive a link a few days after submitting it. In the mean time, you can wait or look into the videos yourself. I can also try to find out from the apprentices.

**Comment by dougfabris** [comment]
@alodahl I already filled out the form! Ok, I'll wait for the link. If you check with the apprentices I'll be grateful.

**Comment by alodahl** [comment]
Sure!  I just sent them a message - I'll let you know if I hear anything.

**Comment by dougfabris** [comment]
@alodahl Did you get some feedback about the videos? I'm not received the invite of slack :(

**Comment by alodahl** [comment]
@dougfabris  I asked them and they don't remember 😣 Sorry Doug. Is one of them obviously older than the others? If not, you'll just have to judge for yourself.

**Comment by dougfabris** [comment]
@alodahl Ok, I'll check by myself. I got it
