### ISSUE TITLE
Audit our outline objectives v the end-of-week assessments

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#962]
https://github.com/Techtonica/curriculum/tree/master/assessment-objectives

Ensure each Roadmap week's objectives in all the outlines match the following assessment's objectives. The roadmap "assessment" column should say which assessment the outline's objectives should appear in.  The "grader guide"  should have a complete list of the objectives from all the outlines that we need to assess.

Relay any mismatches or missing objectives to Alina and TaLea in the slack curriculum channel, or here in the comments.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by anihm136** [comment]
I'd like to take this up.

**Comment by alodahl** [comment]
@anihm136 here is the roadmap mentioned in the description.  We will be basing the 2020 cohorts calendar on this one, so we want to make sure the end-of-week assessments contain the right material. Thank you!

**Comment by anihm136** [comment]
@alodahl There does not seem to be a section on writing documentation in the week 3 assessment. There is only a section on writing good comments, while both are mentioned in the grader's guide.

**Comment by alodahl** [comment]
Thank you! This is exactly the info we need.

**Comment by anihm136** [comment]
@alodahl The links to the assignments in the week 6 grader's guide are broken

**Comment by anihm136** [comment]
The week 7 grader's guide has a small typo in the MarkDown syntax (first checkbox under "Data Visualization" section)

**Comment by anihm136** [comment]
I have finished reading through the material. Everything else seems to be in order. However, I did not have access to some assignments.

**Comment by alodahl** [comment]
Thank you @anihm136! For the contribution, would you mind fixing the little typo in the week 7 graders guide, and make sure that it’s not also wrong in the original data viz lesson?

**Comment by alodahl** [comment]
When you say you don’t have access to things, do you just mean the Week 6 links?
