### ISSUE TITLE
Add React hooks / pure functions topic to our React lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#965]
**Task:**
Add a short react hooks / pure functions topic to our react lesson. Feel free to cite a free outside resource.

Create your outline here: https://github.com/Techtonica/curriculum/blob/master/react-js/react-hooks.md

Best case scenario, you include some kind of quick sandbox example where they can test for themselves how it works.

Be sure to include:
- which React versions apply, 
- compare and contrast to 'extends React.Component' and constructors
- point out any gotchas.  I personally found out that you can't mock a state change in enzyme when the component is written using hooks.

* Also, please alert us to any outdated links or info you may come across as you look at our lesson outline.
https://github.com/Techtonica/curriculum/blob/master/react-js/react.md

**Comment by Windrushfarer** [comment]
React hooks shouldn't be pure functions, because hooks can contain  things like `useEffect`, that cause side effects :)
May be it'll be better to split pure functions lesson and hooks lesson? I cab help you with both of them.

**Comment by alodahl** [comment]
That would be awesome, @windrushfarer!! I was referring to the fact that you use hooks so you can write your components as pure functions.

**Comment by alodahl** [comment]
How long do you think you would need?

**Comment by Windrushfarer** [comment]
@alodahl I think writing short lesson could take may be one day, but I can't understand where I should put this material?

**Comment by alodahl** [comment]
I’ll make a file for you in the React folder.

**Comment by alodahl** [comment]
https://github.com/Techtonica/curriculum/blob/master/react-js/react-hooks.md
You can put it here 😊

**Comment by Windrushfarer** [comment]
Thanks for creating file!

**Comment by alodahl** [comment]
How is this going, @Windrushfarer ?  Will it be in in time for Hacktoberfest?

**Comment by dpenny** [comment]
Is help still needed on this @alodahl ? Would be down to help if so!

**Comment by alodahl** [comment]
Hi Danielle, as I haven’t heard from the other volunteer in 2 months, it’s yours! Thanks for the help 😄

**Comment by alodahl** [comment]
Hi @dpenny , I know you picked up other issues as well... are you still able to work on this?

**Comment by alodahl** [comment]
@gsong if I don’t hear from dpenny, would you like to take this?

**Comment by gsong** [comment]
@alodahl Realistically I probably won't have time to work on this. I'm more than happy to assist and review. I also have some code sandboxes which could serve as starting points.

**Comment by dpenny** [comment]
What's the timeline on this? I should be able to do it next week if
that works for you

**Comment by alodahl** [comment]
We'd need it by 2/24, @dpenny

**Comment by vegetabill** [comment]
@dpenny thanks for volunteering to work on this. Our average PR back-and-forth takes a few weeks so would it be feasible for you to commit to creating a first draft by Monday 3 February?

**Comment by dpenny** [comment]
@vegetabill is end of this week ok?

**Comment by vegetabill** [comment]
@dpenny yes that would be great!!

**Comment by dpenny** [comment]
PR here! https://github.com/Techtonica/curriculum/pull/1186

**Comment by alodahl** [comment]
#1186 was merged
