### ISSUE TITLE
Create Mongoose exercises outline to follow MongoDB lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#966]
Check out our [MongoDB outline](https://github.com/Techtonica/curriculum/blob/master/databases/mongo-db.md).  Create a new outline using our [template](https://raw.githubusercontent.com/Techtonica/curriculum/master/_templates/topic-outline.md).  Based on what they learned in the MongoDB lesson, explain how to use Mongoose as an ORM. 
Create a lesson that:
- links or explains what an ORM is, and names some other ORMs that they might hear about.
- explains how the ORM connects the project to a Mongo DB.
-  includes guided interactive practice
- takes 30-90 minutes for a beginner to complete

**Comment by abhu-A-J** [comment]
@alodahl can I contribute towards this? I  would love to be a part of this program through my small contribution.

**Comment by abhu-A-J** [comment]
@alodahl thanks. I'm working on it. Will let you know when I'm done with it.
