### ISSUE TITLE
Proofread 2 Event project outlines

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#968]
Reword two Event project outlines according to the comments found [here](https://github.com/Techtonica/curriculum/pull/949) , as well as any other typos you might find.

**Comment by imskr** [comment]
I would like to work on this.

**Comment by alodahl** [comment]
Thanks @imskr!

**Comment by imskr** [comment]
Should I proofread both event files in javascript directory ?

**Comment by alodahl** [comment]
Yes please, the javascript/event-recommender.md & javascript/event-recommender-part2.md. General proofreading, plus the comments I made in the link provided in the “changes” tab.

**Comment by imskr** [comment]
@alodahl Thank you, I will do it
