### ISSUE TITLE
OAuth Guided Practice is incomplete

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/curriculum#969]
From @ngriffin23: "Creating a log out button is incomplete and they also mention to add some code into an Auth.js file but that file is not provided when you download the sample folder."

Resolve this problem in our auth0 outline here:https://github.com/Techtonica/curriculum/blob/master/oauth/o-auth.md

**Comment by lemon-yellow** [comment]
I can take a look at this one!

**Comment by lemon-yellow** [comment]
@alodahl - the sample React app from Auth0 comes with a functioning Logout button - was that not the case in the past? 

Here is the code for the Logout button - https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/components/NavBar.js#L85-L91

And the logout logic is not in the sample code anymore, it is imported from Auth0's library here- https://github.com/auth0/auth0-spa-js

Does it make sense to have lesson cover another task instead?
