### ISSUE TITLE
Add cheatsheet links to lesson materials

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#970]
HTML:
https://www.codecademy.com/learn/learn-html/modules/learn-html-elements/reference

**Comment by anihm136** [comment]
HI. I'd like to work on this. Can you elaborate on what exactly is required here?

**Comment by alodahl** [comment]
@anihm136 thank for offering to work on this!  Believe it or not, someone already submitted a PR for this one.  Please take a look at our [Readme contributing directions](https://github.com/Techtonica/curriculum#volunteering) and then feel free to pick up another issue [here](https://github.com/Techtonica/curriculum/projects/2)!
