### ISSUE TITLE
Add 'Roles in Agile' section to Agile Outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#976]
The topic 'Roles in Agile' does not appear in our Intro to Agile or our Agile Scrum outlines.

## Task:
Please look at both of our outlines, and add a section on 'Roles in Agile' to the one where you believe it fits best.

Be sure to update Projected Time, Objectives, and Things to Teach in the outline you've added to.

https://github.com/Techtonica/curriculum/blob/master/agile-development/intro-to-agile.md
https://github.com/Techtonica/curriculum/blob/master/agile-development/scrum.md

**Comment by sophi-li** [comment]
Sent a PR under the scrum section!
