### ISSUE TITLE
Write "Data Science" topic outline based on completed slides

### ISSUE THREAD

**Issue by k4y3ff** [Techtonica/curriculum#98]
Please write a topic outline based on this completed slideshow: https://docs.google.com/presentation/d/1eK4zQsleLwe0pG0Ze_QJ00G-0KR59tJp5pTV36lDZZY/edit?usp=sharing

The intention is to present Data Science roles, and steps to take if one is interested in a career in Data Science/Engineering.  The topic outline should live at [`roles-in-tech/data-science.md`](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/data-science.md).

Acceptance Criteria:
- [ ] The lesson can be covered in 30-45 minutes
- [ ] There are clear objectives
- [ ] There is a short exercise to illustrate data science concepts
- [ ] The activity helps different kinds of learners (e.g. spatial, auditory, verbal, kinesthetic)
- [ ] There is a list of self-assessment questions under 'check for understanding'

Note that [self and peer assessments are preferable to grades](https://www.mindsetkit.org/topics/assessments-growth-mindset-math/using-self-peer-feedback-assessments-learning).

**Comment by alodahl** [comment]
Picked up by Jyotsna Jayaraman

**Comment by alodahl** [comment]
Shubham Kumar, who's started contributing from India, created a list of resources for Data Science that you can draw from: https://github.com/frontbench-open-source/Data-Science-Free
