### ISSUE TITLE
Strengthen Motivation Sections - Part 3b

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#986]
This issue is intended for a single contributor.  Most or all of the Topic Outlines below have an absent or incomplete ### Motivation section.

### Ensure that they all have:
- Useful "Motivation" sections, and 
- 2 companies that use that technology, how they use it, and a  link to an example. Ideally, they are well-known companies.
- [Here's an example of a good motivation section.](https://github.com/Techtonica/curriculum/blob/master/css/media-queries.md#motivation)
- Hint:  If you are having trouble brainstorming, try searching for the technology here: https://stackshare.io/

#### If you're having trouble coming up with something,
 just google "why is it important to learn about [this topic]", and formulate an answer from the best results.  Please link the companies and any copied text.

#### If the file already has a great looking motivation section, 
you can leave it alone, but let us know in your PR.

#### If you have a question, 
please message Alina, or leave a comment on the issue.

### Make sure these topic outlines have complete motivation sections:
- [ ] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-3.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-4.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-5.md
 
For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by JeffOgah** [comment]
I'll work on this

**Comment by JeffOgah** [comment]
@alodahl How do I specify a company using these particular Javascript lessons? It's a bit more difficult to measure than the media queries which is easily visible

**Comment by alodahl** [comment]
Maybe look at what topics they’re learning, and think of a famous web app that uses it so they have a concrete example? I know, it’s hard to narrow down!

**Comment by JeffOgah** [comment]
Okay, I'll try to get that done

**Comment by vegetabill** [comment]
I'm going to close this as "Won't do" -- since the entire curriculum covers JS, I think it's not necessary to go into detail in each lesson. If we have more specific improvement suggestions, let's open another issue.
