### ISSUE TITLE
Add agile v waterfall section to Agile outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#987]
## Task:
Make some important fixes to our Agile Topic.

- [Agile Topic Outline](https://github.com/Techtonica/curriculum/blob/master/agile-development/intro-to-agile.md)
- [Agile Topic Slideshow](https://docs.google.com/presentation/d/1SdCigo6K4aW8p-SZRA0vdI6w628pwhjzf-oX8UKIhS8/edit?usp=sharing) (DM Alina for edit permissions)

- [ ] Add and 'agile vs waterfall' description in our agile lesson. It is mentioned but not explained well.  Please add a slide about it in the slideshow too.  Ideally it would be a chart or diagram outlining the differences.

Thanks for your help!

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by shriaas2898** [comment]
I would like to pick up the issue

**Comment by alodahl** [comment]
Hi @shriaas2898 , this issue is actually in progress, but please check out other easy issues [here](https://github.com/Techtonica/curriculum/projects) 😊
