### ISSUE TITLE
Add table of contents to our Agile topic outline and slides 

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#997]
## Task:
Make an important fix to our Agile Topic.

- [Agile Topic Outline](https://github.com/Techtonica/curriculum/blob/master/agile-development/intro-to-agile.md)
- [Agile Topic Slideshow](https://docs.google.com/presentation/d/1SdCigo6K4aW8p-SZRA0vdI6w628pwhjzf-oX8UKIhS8/edit?usp=sharing) (DM Alina for edit permissions)

- [ ]  Add bullet points for the basic topic covered in the lesson under the "Specific things to teach" header, which is now empty. Do the same as an intro slide in the slideshow.

Thanks for your help!

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by monika** [comment]
Hi! Can I tackle this for ya?

**Comment by monika** [comment]
It looks like the Specific Things to Teach heading exists twice in the Agile Topic Outline, and the first one has a table of contents set up: https://github.com/Techtonica/curriculum/blob/master/agile-development/intro-to-agile.md#specific-things-to-teach

Would you like that first instance of "Specific Things to Teach" moved below the "Materials" section?

**Comment by alodahl** [comment]
Hi @monika, 
Good catch ... could you just remove the heading that's on its own?

As for the section that does exist, but I'm not convinced it actually covers all the points in this long lesson.  Could you make sure that it covers all the topics?

**Comment by monika** [comment]
PR #1038 is up for review with these changes!
