### ISSUE TITLE
Gather and add descriptive titles to outline materials links

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#998]
## Task:
Make an important fix to our Agile Topic.

- [Agile Topic Outline](https://github.com/Techtonica/curriculum/blob/master/agile-development/intro-to-agile.md)
- [Agile Topic Slideshow](https://docs.google.com/presentation/d/1SdCigo6K4aW8p-SZRA0vdI6w628pwhjzf-oX8UKIhS8/edit?usp=sharing) (DM Alina for edit permissions)

- [ ] Create a header right before Lesson called ### Materials. Add bullet points with links and quick descriptions of the links. Links should include the Agile Topic Slideshow, and any required material in the outline. If it is not required, it should be under the header 'Supplemental Materials' on the bottom of the outline (which can have sub-categories if you like).  (See #790  for more details . -also, check off this outline in 790 while you’re there, please.)
- [ ] Make sure all links should really be required. We value our students' time. If no, add them to supplemental materials.  Either way, make sure they *all* have a quick description of what students will find at the linked resource, and how much time they can expect to spend on it.  It should fit into the Projected Time.

Thanks for your help!

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by shriaas2898** [comment]
Hey! I can work on this issue.
It just requires changing links in the material section from external links to that on slide right?

**Comment by alodahl** [comment]
No....
Put all required materials, including the slideshow link, in a new section called ###Materials.

If they are not required and do not show up as part of the lesson, the link should be moved to a *section at the end of the outline* called ###Supplemental Materials.

**Comment by alodahl** [comment]
links labeled ✅
